import type { LanguageCode } from "@/lib/translations";

export type CatalogueText = {
 signIn:string; allCountries:string; live:string; available:string; comingSoon:string;
 assistantDevelopment:string; openAssistant:string; searchRoutes:(n:number,country?:string)=>string;
 noRoutes:(q:string,country?:string)=>string; visaRoutes:(country:string)=>string;
 exploreUK:string; checkedUK:string; exploreCountry:(country:string)=>string;
 checkedCountry:(authority:string)=>string; official:string; officialAuthority:string;
};
const T:Record<LanguageCode,CatalogueText>={
 en:{signIn:"Sign In",allCountries:"All countries",live:"Live",available:"Available",comingSoon:"Coming soon",assistantDevelopment:"Assistant in development",openAssistant:"Open assistant",searchRoutes:(n,c)=>`Search ${n}${c?` ${c}`:""} routes...`,noRoutes:(q,c)=>`No ${c?`${c} `:""}routes match “${q}”.`,visaRoutes:c=>`${c} visa routes`,exploreUK:"Explore UK immigration routes by category. Innovator Founder has a full Visa Assistant today; other routes are visible now and will gain dedicated preparation assistants as they launch.",checkedUK:"Route catalogue checked against GOV.UK on 17 September 2026. Always verify current requirements on GOV.UK before applying.",exploreCountry:c=>`Explore the main visa, immigration and residence routes for ${c}. The route catalogue is open for browsing while dedicated Visa Assistant tools remain locked until launch.`,checkedCountry:a=>`Catalogue reviewed against ${a} sources. Immigration programmes change; always verify current requirements with the official authority before applying.`,official:"GOV.UK",officialAuthority:"Check the official immigration authority"},
 de:{signIn:"Anmelden",allCountries:"Alle Länder",live:"Live",available:"Verfügbar",comingSoon:"Demnächst",assistantDevelopment:"Assistent in Entwicklung",openAssistant:"Assistent öffnen",searchRoutes:(n,c)=>`${n}${c?` ${c}`:""} Routen durchsuchen...`,noRoutes:(q,c)=>`Keine ${c?`${c}-`:""}Routen entsprechen „${q}“.`,visaRoutes:c=>`Visumrouten für ${c}`,exploreUK:"Entdecken Sie die britischen Einwanderungsrouten nach Kategorie. Für Innovator Founder ist bereits ein vollständiger Visa Assistant verfügbar; weitere Routen erhalten eigene Vorbereitungstools.",checkedUK:"Der Routenkatalog wurde am 17. September 2026 mit GOV.UK abgeglichen. Prüfen Sie aktuelle Anforderungen vor der Antragstellung immer auf GOV.UK.",exploreCountry:c=>`Entdecken Sie die wichtigsten Visa-, Einwanderungs- und Aufenthaltsrouten für ${c}. Der Routenkatalog kann bereits durchsucht werden; spezielle Visa-Assistant-Tools folgen schrittweise.`,checkedCountry:a=>`Der Katalog wurde anhand der Quellen von ${a} geprüft. Einwanderungsprogramme können sich ändern; prüfen Sie aktuelle Anforderungen immer bei der zuständigen Behörde.`,official:"GOV.UK",officialAuthority:"Offizielle Einwanderungsbehörde prüfen"},
 es:{signIn:"Iniciar sesión",allCountries:"Todos los países",live:"Activo",available:"Disponible",comingSoon:"Próximamente",assistantDevelopment:"Asistente en desarrollo",openAssistant:"Abrir asistente",searchRoutes:(n,c)=>`Buscar entre ${n} rutas${c?` de ${c}`:""}...`,noRoutes:(q,c)=>`Ninguna ruta${c?` de ${c}`:""} coincide con «${q}».`,visaRoutes:c=>`Rutas de visado de ${c}`,exploreUK:"Explora las rutas de inmigración del Reino Unido por categoría. Innovator Founder ya cuenta con un Visa Assistant completo; las demás rutas recibirán asistentes específicos.",checkedUK:"Catálogo contrastado con GOV.UK el 17 de septiembre de 2026. Verifica siempre los requisitos actuales en GOV.UK antes de solicitar.",exploreCountry:c=>`Explora las principales rutas de visado, inmigración y residencia de ${c}. El catálogo está disponible mientras se preparan los asistentes específicos.`,checkedCountry:a=>`Catálogo revisado con fuentes de ${a}. Los programas pueden cambiar; verifica siempre los requisitos actuales con la autoridad oficial.`,official:"GOV.UK",officialAuthority:"Consultar la autoridad oficial de inmigración"},
 fr:{signIn:"Se connecter",allCountries:"Tous les pays",live:"Disponible",available:"Disponible",comingSoon:"Bientôt",assistantDevelopment:"Assistant en développement",openAssistant:"Ouvrir l’assistant",searchRoutes:(n,c)=>`Rechercher parmi ${n} routes${c?` pour ${c}`:""}...`,noRoutes:(q,c)=>`Aucune route${c?` pour ${c}`:""} ne correspond à « ${q} ».`,visaRoutes:c=>`Voies de visa pour ${c}`,exploreUK:"Explorez les voies d’immigration britanniques par catégorie. Innovator Founder dispose déjà d’un Visa Assistant complet; les autres voies recevront leurs propres assistants.",checkedUK:"Catalogue vérifié avec GOV.UK le 17 septembre 2026. Vérifiez toujours les exigences actuelles sur GOV.UK avant de déposer une demande.",exploreCountry:c=>`Explorez les principales voies de visa, d’immigration et de séjour pour ${c}. Le catalogue est accessible pendant le déploiement des assistants dédiés.`,checkedCountry:a=>`Catalogue vérifié à partir des sources de ${a}. Les programmes peuvent changer; vérifiez toujours les exigences auprès de l’autorité officielle.`,official:"GOV.UK",officialAuthority:"Consulter l’autorité officielle d’immigration"},
 pt:{signIn:"Entrar",allCountries:"Todos os países",live:"Ativo",available:"Disponível",comingSoon:"Em breve",assistantDevelopment:"Assistente em desenvolvimento",openAssistant:"Abrir assistente",searchRoutes:(n,c)=>`Pesquisar ${n} rotas${c?` de ${c}`:""}...`,noRoutes:(q,c)=>`Nenhuma rota${c?` de ${c}`:""} corresponde a “${q}”.`,visaRoutes:c=>`Rotas de visto de ${c}`,exploreUK:"Explore as rotas de imigração do Reino Unido por categoria. O Innovator Founder já tem um Visa Assistant completo; as outras rotas receberão assistentes dedicados.",checkedUK:"Catálogo verificado com o GOV.UK em 17 de setembro de 2026. Confirme sempre os requisitos atuais no GOV.UK antes de solicitar.",exploreCountry:c=>`Explore as principais rotas de visto, imigração e residência de ${c}. O catálogo está disponível enquanto os assistentes dedicados são lançados.`,checkedCountry:a=>`Catálogo revisto com fontes de ${a}. Os programas podem mudar; confirme sempre os requisitos junto da autoridade oficial.`,official:"GOV.UK",officialAuthority:"Consultar autoridade oficial de imigração"},
 zh:{signIn:"登录",allCountries:"所有国家",live:"已上线",available:"可用",comingSoon:"即将推出",assistantDevelopment:"助手开发中",openAssistant:"打开助手",searchRoutes:(n,c)=>`搜索 ${n} 条${c?` ${c}`:""}路线...`,noRoutes:(q,c)=>`没有${c?` ${c}`:""}路线匹配“${q}”。`,visaRoutes:c=>`${c}签证路线`,exploreUK:"按类别浏览英国移民路线。Innovator Founder 已提供完整的 Visa Assistant，其他路线的专用准备助手将陆续上线。",checkedUK:"路线目录已于2026年9月17日与 GOV.UK 核对。申请前请始终在 GOV.UK 核实最新要求。",exploreCountry:c=>`浏览${c}的主要签证、移民和居留路线。路线目录现已开放，专用 Visa Assistant 工具将陆续推出。`,checkedCountry:a=>`目录已根据 ${a} 的资料审核。移民项目可能变化，请始终向官方机构核实最新要求。`,official:"GOV.UK",officialAuthority:"查看官方移民机构"},
 ja:{signIn:"サインイン",allCountries:"すべての国",live:"公開中",available:"利用可能",comingSoon:"近日公開",assistantDevelopment:"アシスタント開発中",openAssistant:"アシスタントを開く",searchRoutes:(n,c)=>`${n}件の${c?`${c}の`:""}ルートを検索...`,noRoutes:(q,c)=>`「${q}」に一致する${c?`${c}の`:""}ルートはありません。`,visaRoutes:c=>`${c}のビザルート`,exploreUK:"英国の移民ルートをカテゴリー別に確認できます。Innovator Founder には完全な Visa Assistant があり、その他のルートにも専用アシスタントが順次追加されます。",checkedUK:"ルート一覧は2026年9月17日に GOV.UK と照合済みです。申請前に必ず GOV.UK で最新要件を確認してください。",exploreCountry:c=>`${c}の主なビザ・移民・在留ルートを確認できます。専用 Visa Assistant の公開に先立ち、ルート一覧を閲覧できます。`,checkedCountry:a=>`一覧は ${a} の情報源に基づき確認済みです。制度は変更されるため、必ず公式機関で最新要件を確認してください。`,official:"GOV.UK",officialAuthority:"公式移民機関を確認"},
 ar:{signIn:"تسجيل الدخول",allCountries:"جميع الدول",live:"متاح",available:"متاح",comingSoon:"قريباً",assistantDevelopment:"المساعد قيد التطوير",openAssistant:"فتح المساعد",searchRoutes:(n,c)=>`ابحث في ${n} مساراً${c?` لـ ${c}`:""}...`,noRoutes:(q,c)=>`لا توجد مسارات${c?` لـ ${c}`:""} تطابق «${q}».`,visaRoutes:c=>`مسارات تأشيرات ${c}`,exploreUK:"استكشف مسارات الهجرة إلى المملكة المتحدة حسب الفئة. يتوفر الآن مساعد كامل لمسار Innovator Founder، وستُضاف مساعدين مخصصين للمسارات الأخرى.",checkedUK:"تمت مراجعة دليل المسارات مقابل GOV.UK في 17 سبتمبر 2026. تحقق دائماً من المتطلبات الحالية على GOV.UK قبل التقديم.",exploreCountry:c=>`استكشف أهم مسارات التأشيرات والهجرة والإقامة في ${c}. الدليل متاح للتصفح بينما يتم إطلاق المساعدين المخصصين.`,checkedCountry:a=>`تمت مراجعة الدليل بالاستناد إلى مصادر ${a}. قد تتغير برامج الهجرة؛ تحقق دائماً من المتطلبات لدى الجهة الرسمية.`,official:"GOV.UK",officialAuthority:"التحقق من جهة الهجرة الرسمية"}
};
export const getCatalogueText=(language:LanguageCode)=>T[language]||T.en;
