// Generated by scripts/generate-ui-string-allowlist.cjs. Do not edit manually.
// The build step replaces this placeholder with the current UI source-string set.
const UI_STRINGS = new Set<string>();

export function isKnownUiString(value: string): boolean {
  return UI_STRINGS.has(value.trim());
}

export const GENERATED_UI_STRING_COUNT = 0;
