import { Card } from "@/components/ui/card"; import { Checkbox } from "@/components/ui/checkbox"; import { Button } from "@/components/ui/button"; import { AuthHeader } from "@/components/AuthHeader"; import { ToolNavigation } from "@/components/ToolNavigation"; import { useState } from "react"; import { AlertTriangle, CheckCircle2, AlertCircle, Download } from "lucide-react";
const ITEMS = [
  {id:"1",name:"Business Criteria (50 points)",cat:"Core",pen:"Critical",guide:"Your business meets the 50-point threshold for innovation, viability, and scalability",action:"Submit endorser assessment and business plan"},
  {id:"2",name:"English Requirement (10 points)",cat:"Language",pen:"Critical",guide:"Proof of B2 level English (GCSE, A-Level, IELTS 7.0, or UK degree)",action:"Get IELTS or equivalent language test"},
  {id:"3",name:"Financial Requirement (10 points)",cat:"Financial",pen:"Critical",guide:"£1,270 available for 28 consecutive days",action:"Provide bank statements showing funds"},
  {id:"4",name:"Personal Savings Verification",cat:"Financial",pen:"High",guide:"Mandatory £1,270 for 28 days minimum before application",action:"Gather last 28 days of bank statements"},
  {id:"5",name:"Dependent Financial Support",cat:"Financial",pen:"High",guide:"Partner £285, first child £315, additional children £200 each",action:"Calculate total if applicable"},
  {id:"6",name:"Visa Fee Payment Ready",cat:"Admin",pen:"High",guide:"£1,274-£1,590 application fee + £1,000 endorsement + £500/meeting",action:"Ensure funds available for all fees"},
  {id:"7",name:"Endorser Identified",cat:"Endorsement",pen:"Critical",guide:"Endorsing body approved by UKVI",action:"Contact and engage with endorser"},
  {id:"8",name:"Evidence Pack Complete",cat:"Documents",pen:"Critical",guide:"All supporting documents compiled and organized",action:"Create evidence folder with index"}
];
export default function AppReqChecker() {
  const [checks, setChecks] = useState<any>({}); const [expanded, setExpanded] = useState<any>({});
  const done = Object.values(checks).filter(Boolean).length; const score = Math.round((done/8)*100);
  return <><AuthHeader /><div className="min-h-screen bg-gradient-to-br from-background via-accent/5 to-primary/5 p-6"><ToolNavigation /><h1 className="text-4xl font-bold mb-2">App Req Checker</h1><p className="text-muted-foreground mb-6">70-point scoring system validation</p><div className="grid md:grid-cols-4 gap-4 mb-6"><Card className="p-4"><p className="text-xs">Score</p><p className="text-3xl font-bold mt-2">{score}%</p></Card><Card className="p-4"><p className="text-xs">Items</p><p className="text-3xl font-bold mt-2">{done}/8</p></Card><Card className="p-4"><p className="text-xs">Status</p><p className={`text-lg font-bold mt-2 ${score>=80?"text-green-600":score>=60?"text-yellow-600":"text-blue-600"}`}>{score>=80?"✓ Ready":score>=60?"⚠ Nearly":"✗ WIP"}</p></Card><Card className={`p-4 ${score>=80?"bg-green-50":"bg-blue-50"}`}><p className="text-xs">Critical</p><p className="text-2xl font-bold mt-2">{ITEMS.filter(i=>checks[i.id]&&i.pen==="Critical").length}/3</p></Card></div><Card className="p-4 mb-4"><div className="flex justify-between mb-2"><span>Progress</span><span>{score}%</span></div><div className="w-full bg-gray-200 h-3 rounded-full"><div style={{width:`${score}%`}} className="bg-primary h-3 rounded-full"/></div></Card><div className="space-y-2">{ITEMS.map(i=><Card key={i.id} className={`p-3 border-l-4 cursor-pointer ${i.pen==="Critical"?"border-l-red-500 bg-red-50":"border-l-blue-500 bg-blue-50"}`} onClick={()=>setExpanded({...expanded,[i.id]:!expanded[i.id]})}><div className="flex gap-3"><Checkbox checked={checks[i.id]||false} onCheckedChange={()=>setChecks({...checks,[i.id]:!checks[i.id]})} onClick={e=>e.stopPropagation()}/><div className="flex-1"><p className="font-semibold text-sm">{i.name}</p><p className="text-xs text-muted-foreground">{i.cat} • {i.pen}</p></div></div>{expanded[i.id]&&<Card className="mt-2 p-2 bg-white text-xs"><p className="font-semibold mb-1">Info: {i.guide}</p><p className="text-blue-600">Action: {i.action}</p></Card>}</Card>)}</div><Button className="w-full mt-4 gap-2 bg-primary"><Download className="w-4 h-4"/>Export Checklist</Button></div></>;
}
