// Comprehensive Question Bank for AI Conversational Interview System
// 475+ questions across Innovation, Viability, Scalability, and Compliance

export interface Question {
  id: string;
  text: string;
  category: string;
  subcategory: string;
  difficulty: 'basic' | 'intermediate' | 'advanced';
  points: number;
  followUpQuestions?: string[];
  tips?: string[];
}

// NOVA - Innovation Specialist Questions (120 questions)
export const novaQuestions: Question[] = [
  // Business Foundation (20 questions)
  { id: 'nova-1', text: "Let's start with your business name. What's the official name of your venture?", category: 'foundation', subcategory: 'identity', difficulty: 'basic', points: 10 },
  { id: 'nova-2', text: "Which industry does your business operate in? Be as specific as possible.", category: 'foundation', subcategory: 'industry', difficulty: 'basic', points: 10 },
  { id: 'nova-3', text: "When was your business founded or when do you plan to launch?", category: 'foundation', subcategory: 'timeline', difficulty: 'basic', points: 10 },
  { id: 'nova-4', text: "Where is your business headquartered or where will it be based in the UK?", category: 'foundation', subcategory: 'location', difficulty: 'basic', points: 10 },
  { id: 'nova-5', text: "What's your company's legal structure (Ltd, LLP, etc.)?", category: 'foundation', subcategory: 'legal', difficulty: 'basic', points: 10 },
  { id: 'nova-6', text: "Describe your business in one sentence - your elevator pitch.", category: 'foundation', subcategory: 'pitch', difficulty: 'basic', points: 15 },
  { id: 'nova-7', text: "What inspired you to start this particular business?", category: 'foundation', subcategory: 'motivation', difficulty: 'basic', points: 10 },
  { id: 'nova-8', text: "Who are your co-founders, if any, and what are their backgrounds?", category: 'foundation', subcategory: 'team', difficulty: 'basic', points: 15 },
  { id: 'nova-9', text: "What's your personal role in the business?", category: 'foundation', subcategory: 'role', difficulty: 'basic', points: 10 },
  { id: 'nova-10', text: "How much time do you dedicate to this venture weekly?", category: 'foundation', subcategory: 'commitment', difficulty: 'basic', points: 10 },
  { id: 'nova-11', text: "What's your business registration number, if already registered?", category: 'foundation', subcategory: 'registration', difficulty: 'basic', points: 5 },
  { id: 'nova-12', text: "Do you have a company website? What's the URL?", category: 'foundation', subcategory: 'presence', difficulty: 'basic', points: 10 },
  { id: 'nova-13', text: "What social media presence does your business have?", category: 'foundation', subcategory: 'presence', difficulty: 'basic', points: 10 },
  { id: 'nova-14', text: "Have you received any press coverage or media mentions?", category: 'foundation', subcategory: 'visibility', difficulty: 'intermediate', points: 20 },
  { id: 'nova-15', text: "What awards or recognition has your business received?", category: 'foundation', subcategory: 'recognition', difficulty: 'intermediate', points: 25 },
  { id: 'nova-16', text: "Are you part of any accelerator or incubator programs?", category: 'foundation', subcategory: 'support', difficulty: 'intermediate', points: 20 },
  { id: 'nova-17', text: "What professional networks or associations are you a member of?", category: 'foundation', subcategory: 'network', difficulty: 'basic', points: 10 },
  { id: 'nova-18', text: "Describe your current office or workspace setup.", category: 'foundation', subcategory: 'operations', difficulty: 'basic', points: 10 },
  { id: 'nova-19', text: "What's the current stage of your business (idea, MVP, growth, scale)?", category: 'foundation', subcategory: 'stage', difficulty: 'basic', points: 15 },
  { id: 'nova-20', text: "How would you describe your company culture and values?", category: 'foundation', subcategory: 'culture', difficulty: 'intermediate', points: 15 },

  // Problem & Solution (25 questions)
  { id: 'nova-21', text: "What specific problem does your business solve? Describe the pain point in detail.", category: 'problem', subcategory: 'identification', difficulty: 'intermediate', points: 25 },
  { id: 'nova-22', text: "How did you discover or identify this problem?", category: 'problem', subcategory: 'discovery', difficulty: 'intermediate', points: 20 },
  { id: 'nova-23', text: "Who experiences this problem most acutely? Describe your target customer.", category: 'problem', subcategory: 'target', difficulty: 'intermediate', points: 20 },
  { id: 'nova-24', text: "How are people currently solving this problem without your solution?", category: 'problem', subcategory: 'alternatives', difficulty: 'intermediate', points: 20 },
  { id: 'nova-25', text: "What are the limitations of current solutions in the market?", category: 'problem', subcategory: 'gaps', difficulty: 'intermediate', points: 25 },
  { id: 'nova-26', text: "Quantify the impact of this problem - time lost, money wasted, etc.", category: 'problem', subcategory: 'impact', difficulty: 'advanced', points: 30 },
  { id: 'nova-27', text: "Why hasn't this problem been solved effectively before?", category: 'problem', subcategory: 'barriers', difficulty: 'advanced', points: 30 },
  { id: 'nova-28', text: "What makes your solution truly innovative? How is it different from existing solutions?", category: 'solution', subcategory: 'differentiation', difficulty: 'advanced', points: 35 },
  { id: 'nova-29', text: "Describe your product or service in detail - what does it actually do?", category: 'solution', subcategory: 'description', difficulty: 'intermediate', points: 25 },
  { id: 'nova-30', text: "What's your unique value proposition in one sentence?", category: 'solution', subcategory: 'uvp', difficulty: 'intermediate', points: 25 },
  { id: 'nova-31', text: "How does your solution address the root cause of the problem?", category: 'solution', subcategory: 'approach', difficulty: 'advanced', points: 30 },
  { id: 'nova-32', text: "What measurable benefits does your solution provide to customers?", category: 'solution', subcategory: 'benefits', difficulty: 'intermediate', points: 25 },
  { id: 'nova-33', text: "How quickly can customers see results from using your solution?", category: 'solution', subcategory: 'timeline', difficulty: 'intermediate', points: 20 },
  { id: 'nova-34', text: "What's the learning curve for new users of your product/service?", category: 'solution', subcategory: 'usability', difficulty: 'intermediate', points: 20 },
  { id: 'nova-35', text: "How do you onboard new customers to your solution?", category: 'solution', subcategory: 'onboarding', difficulty: 'intermediate', points: 20 },
  { id: 'nova-36', text: "What customer support do you provide?", category: 'solution', subcategory: 'support', difficulty: 'basic', points: 15 },
  { id: 'nova-37', text: "How do you gather and incorporate customer feedback?", category: 'solution', subcategory: 'feedback', difficulty: 'intermediate', points: 20 },
  { id: 'nova-38', text: "What's your product roadmap for the next 12 months?", category: 'solution', subcategory: 'roadmap', difficulty: 'intermediate', points: 25 },
  { id: 'nova-39', text: "How do you prioritize new features and improvements?", category: 'solution', subcategory: 'prioritization', difficulty: 'intermediate', points: 20 },
  { id: 'nova-40', text: "What integrations does your solution offer with other tools?", category: 'solution', subcategory: 'integrations', difficulty: 'intermediate', points: 20 },
  { id: 'nova-41', text: "How does your solution scale as customers grow?", category: 'solution', subcategory: 'scalability', difficulty: 'advanced', points: 30 },
  { id: 'nova-42', text: "What's your solution's uptime guarantee or SLA?", category: 'solution', subcategory: 'reliability', difficulty: 'intermediate', points: 20 },
  { id: 'nova-43', text: "How do you handle data backup and disaster recovery?", category: 'solution', subcategory: 'security', difficulty: 'intermediate', points: 20 },
  { id: 'nova-44', text: "What accessibility features does your solution include?", category: 'solution', subcategory: 'accessibility', difficulty: 'intermediate', points: 20 },
  { id: 'nova-45', text: "How does your solution contribute to sustainability or social impact?", category: 'solution', subcategory: 'impact', difficulty: 'advanced', points: 25 },

  // Technology & Innovation (30 questions)
  { id: 'nova-46', text: "Describe your current product development status. What have you built so far?", category: 'technology', subcategory: 'development', difficulty: 'intermediate', points: 25 },
  { id: 'nova-47', text: "What technology stack powers your innovation? Include frameworks, languages, and tools.", category: 'technology', subcategory: 'stack', difficulty: 'intermediate', points: 25 },
  { id: 'nova-48', text: "Do you have any intellectual property - patents pending, filed, or defensive publications?", category: 'technology', subcategory: 'ip', difficulty: 'advanced', points: 35 },
  { id: 'nova-49', text: "How does your data architecture support your innovation claims?", category: 'technology', subcategory: 'data', difficulty: 'advanced', points: 30 },
  { id: 'nova-50', text: "What AI or machine learning methodologies do you employ, if any?", category: 'technology', subcategory: 'ai', difficulty: 'advanced', points: 35 },
  { id: 'nova-51', text: "How have you designed your system for regulatory compliance from day one?", category: 'technology', subcategory: 'compliance', difficulty: 'advanced', points: 30 },
  { id: 'nova-52', text: "What's your approach to cybersecurity and data protection?", category: 'technology', subcategory: 'security', difficulty: 'advanced', points: 30 },
  { id: 'nova-53', text: "How do you handle software versioning and deployment?", category: 'technology', subcategory: 'deployment', difficulty: 'intermediate', points: 20 },
  { id: 'nova-54', text: "What testing methodologies do you use (unit, integration, E2E)?", category: 'technology', subcategory: 'testing', difficulty: 'intermediate', points: 20 },
  { id: 'nova-55', text: "How do you monitor system performance and identify issues?", category: 'technology', subcategory: 'monitoring', difficulty: 'intermediate', points: 20 },
  { id: 'nova-56', text: "What cloud infrastructure do you use and why?", category: 'technology', subcategory: 'infrastructure', difficulty: 'intermediate', points: 20 },
  { id: 'nova-57', text: "How do you handle peak traffic and scaling challenges?", category: 'technology', subcategory: 'scaling', difficulty: 'advanced', points: 25 },
  { id: 'nova-58', text: "What's your approach to mobile development (native, hybrid, PWA)?", category: 'technology', subcategory: 'mobile', difficulty: 'intermediate', points: 20 },
  { id: 'nova-59', text: "How do you ensure cross-browser and cross-device compatibility?", category: 'technology', subcategory: 'compatibility', difficulty: 'intermediate', points: 15 },
  { id: 'nova-60', text: "What APIs do you provide or consume?", category: 'technology', subcategory: 'apis', difficulty: 'intermediate', points: 20 },
  { id: 'nova-61', text: "How do you handle API rate limiting and quotas?", category: 'technology', subcategory: 'apis', difficulty: 'intermediate', points: 15 },
  { id: 'nova-62', text: "What's your approach to database design and optimization?", category: 'technology', subcategory: 'database', difficulty: 'advanced', points: 25 },
  { id: 'nova-63', text: "How do you handle data migration and schema changes?", category: 'technology', subcategory: 'database', difficulty: 'intermediate', points: 20 },
  { id: 'nova-64', text: "What caching strategies do you employ?", category: 'technology', subcategory: 'performance', difficulty: 'intermediate', points: 20 },
  { id: 'nova-65', text: "How do you handle internationalization and localization?", category: 'technology', subcategory: 'i18n', difficulty: 'intermediate', points: 20 },
  { id: 'nova-66', text: "What development tools and IDEs does your team use?", category: 'technology', subcategory: 'tools', difficulty: 'basic', points: 10 },
  { id: 'nova-67', text: "How do you manage technical debt?", category: 'technology', subcategory: 'maintenance', difficulty: 'advanced', points: 25 },
  { id: 'nova-68', text: "What's your code review process?", category: 'technology', subcategory: 'quality', difficulty: 'intermediate', points: 20 },
  { id: 'nova-69', text: "How do you document your codebase and APIs?", category: 'technology', subcategory: 'documentation', difficulty: 'intermediate', points: 15 },
  { id: 'nova-70', text: "What's your disaster recovery plan?", category: 'technology', subcategory: 'resilience', difficulty: 'advanced', points: 25 },
  { id: 'nova-71', text: "How do you handle user authentication and authorization?", category: 'technology', subcategory: 'security', difficulty: 'intermediate', points: 20 },
  { id: 'nova-72', text: "What encryption methods do you use for data at rest and in transit?", category: 'technology', subcategory: 'security', difficulty: 'advanced', points: 25 },
  { id: 'nova-73', text: "How do you comply with GDPR and data privacy regulations?", category: 'technology', subcategory: 'compliance', difficulty: 'advanced', points: 30 },
  { id: 'nova-74', text: "What's your approach to continuous integration and deployment (CI/CD)?", category: 'technology', subcategory: 'devops', difficulty: 'intermediate', points: 20 },
  { id: 'nova-75', text: "How do you handle feature flags and gradual rollouts?", category: 'technology', subcategory: 'deployment', difficulty: 'intermediate', points: 20 },

  // Innovation Evidence (25 questions)
  { id: 'nova-76', text: "What research and development activities have you conducted?", category: 'innovation', subcategory: 'r&d', difficulty: 'advanced', points: 30 },
  { id: 'nova-77', text: "Have you collaborated with any universities or research institutions?", category: 'innovation', subcategory: 'collaboration', difficulty: 'advanced', points: 35 },
  { id: 'nova-78', text: "What technical papers or publications relate to your innovation?", category: 'innovation', subcategory: 'research', difficulty: 'advanced', points: 30 },
  { id: 'nova-79', text: "How does your innovation advance the state of the art in your field?", category: 'innovation', subcategory: 'advancement', difficulty: 'advanced', points: 35 },
  { id: 'nova-80', text: "What technical challenges did you overcome in development?", category: 'innovation', subcategory: 'challenges', difficulty: 'advanced', points: 30 },
  { id: 'nova-81', text: "How do you stay ahead of technological trends in your industry?", category: 'innovation', subcategory: 'trends', difficulty: 'intermediate', points: 20 },
  { id: 'nova-82', text: "What proprietary algorithms or methods have you developed?", category: 'innovation', subcategory: 'proprietary', difficulty: 'advanced', points: 35 },
  { id: 'nova-83', text: "How do you protect your trade secrets and know-how?", category: 'innovation', subcategory: 'protection', difficulty: 'advanced', points: 25 },
  { id: 'nova-84', text: "What innovative business models are you employing?", category: 'innovation', subcategory: 'business-model', difficulty: 'advanced', points: 30 },
  { id: 'nova-85', text: "How does your innovation create barriers to entry for competitors?", category: 'innovation', subcategory: 'moat', difficulty: 'advanced', points: 35 },
  { id: 'nova-86', text: "What's unique about your approach to customer acquisition?", category: 'innovation', subcategory: 'acquisition', difficulty: 'intermediate', points: 25 },
  { id: 'nova-87', text: "How do you innovate in your pricing or monetization strategy?", category: 'innovation', subcategory: 'monetization', difficulty: 'intermediate', points: 25 },
  { id: 'nova-88', text: "What innovative partnerships have you formed?", category: 'innovation', subcategory: 'partnerships', difficulty: 'intermediate', points: 25 },
  { id: 'nova-89', text: "How do you use data to drive innovation and decision-making?", category: 'innovation', subcategory: 'data-driven', difficulty: 'advanced', points: 30 },
  { id: 'nova-90', text: "What patents or patent applications do you have?", category: 'innovation', subcategory: 'patents', difficulty: 'advanced', points: 40 },
  { id: 'nova-91', text: "How do you foster a culture of innovation in your team?", category: 'innovation', subcategory: 'culture', difficulty: 'intermediate', points: 20 },
  { id: 'nova-92', text: "What percentage of revenue do you reinvest in R&D?", category: 'innovation', subcategory: 'investment', difficulty: 'advanced', points: 25 },
  { id: 'nova-93', text: "How do you validate new ideas before full development?", category: 'innovation', subcategory: 'validation', difficulty: 'intermediate', points: 20 },
  { id: 'nova-94', text: "What failed experiments have taught you valuable lessons?", category: 'innovation', subcategory: 'learning', difficulty: 'intermediate', points: 20 },
  { id: 'nova-95', text: "How do you incorporate customer insights into your innovation process?", category: 'innovation', subcategory: 'customer', difficulty: 'intermediate', points: 25 },
  { id: 'nova-96', text: "What emerging technologies are you exploring for future development?", category: 'innovation', subcategory: 'future', difficulty: 'advanced', points: 25 },
  { id: 'nova-97', text: "How does your innovation align with UK government priorities?", category: 'innovation', subcategory: 'alignment', difficulty: 'advanced', points: 30 },
  { id: 'nova-98', text: "What industry standards or certifications does your innovation meet?", category: 'innovation', subcategory: 'standards', difficulty: 'intermediate', points: 25 },
  { id: 'nova-99', text: "How do you measure and track innovation output?", category: 'innovation', subcategory: 'metrics', difficulty: 'intermediate', points: 20 },
  { id: 'nova-100', text: "What makes your team uniquely qualified to deliver this innovation?", category: 'innovation', subcategory: 'team', difficulty: 'advanced', points: 30 },

  // Market Understanding (20 questions)
  { id: 'nova-101', text: "What's the size of your total addressable market (TAM)?", category: 'market', subcategory: 'size', difficulty: 'intermediate', points: 25 },
  { id: 'nova-102', text: "What's your serviceable addressable market (SAM)?", category: 'market', subcategory: 'size', difficulty: 'intermediate', points: 25 },
  { id: 'nova-103', text: "What's your serviceable obtainable market (SOM)?", category: 'market', subcategory: 'size', difficulty: 'intermediate', points: 25 },
  { id: 'nova-104', text: "What market trends support the growth of your business?", category: 'market', subcategory: 'trends', difficulty: 'intermediate', points: 25 },
  { id: 'nova-105', text: "Who are your direct competitors and what are their strengths?", category: 'market', subcategory: 'competition', difficulty: 'intermediate', points: 25 },
  { id: 'nova-106', text: "Who are your indirect competitors?", category: 'market', subcategory: 'competition', difficulty: 'intermediate', points: 20 },
  { id: 'nova-107', text: "What's your competitive advantage that's sustainable over 5+ years?", category: 'market', subcategory: 'advantage', difficulty: 'advanced', points: 35 },
  { id: 'nova-108', text: "How do customers currently discover solutions like yours?", category: 'market', subcategory: 'discovery', difficulty: 'intermediate', points: 20 },
  { id: 'nova-109', text: "What's the typical buying process for your target customers?", category: 'market', subcategory: 'buying', difficulty: 'intermediate', points: 20 },
  { id: 'nova-110', text: "Who are the decision-makers in your target organizations?", category: 'market', subcategory: 'stakeholders', difficulty: 'intermediate', points: 20 },
  { id: 'nova-111', text: "What regulatory changes might affect your market?", category: 'market', subcategory: 'regulation', difficulty: 'advanced', points: 25 },
  { id: 'nova-112', text: "How might economic conditions impact demand for your solution?", category: 'market', subcategory: 'economy', difficulty: 'intermediate', points: 20 },
  { id: 'nova-113', text: "What technological changes could disrupt your market?", category: 'market', subcategory: 'disruption', difficulty: 'advanced', points: 25 },
  { id: 'nova-114', text: "How fragmented or consolidated is your market?", category: 'market', subcategory: 'structure', difficulty: 'intermediate', points: 20 },
  { id: 'nova-115', text: "What barriers to entry exist in your market?", category: 'market', subcategory: 'barriers', difficulty: 'intermediate', points: 20 },
  { id: 'nova-116', text: "How price-sensitive are customers in your market?", category: 'market', subcategory: 'pricing', difficulty: 'intermediate', points: 20 },
  { id: 'nova-117', text: "What's the typical customer lifetime in your market?", category: 'market', subcategory: 'retention', difficulty: 'intermediate', points: 20 },
  { id: 'nova-118', text: "How seasonal is demand in your market?", category: 'market', subcategory: 'demand', difficulty: 'basic', points: 15 },
  { id: 'nova-119', text: "What geographic markets are most attractive for your solution?", category: 'market', subcategory: 'geography', difficulty: 'intermediate', points: 20 },
  { id: 'nova-120', text: "How has COVID-19 changed your market dynamics?", category: 'market', subcategory: 'changes', difficulty: 'intermediate', points: 20 },
];

// STERLING - Financial Analyst Questions (120 questions)
export const sterlingQuestions: Question[] = [
  // Current Financial Position (25 questions)
  { id: 'sterling-1', text: "What's your current funding situation? How much capital do you have?", category: 'funding', subcategory: 'current', difficulty: 'basic', points: 15 },
  { id: 'sterling-2', text: "Walk me through your revenue model. How does your business make money?", category: 'revenue', subcategory: 'model', difficulty: 'intermediate', points: 25 },
  { id: 'sterling-3', text: "What are your 36-month financial projections? Break it down by year.", category: 'projections', subcategory: '36-month', difficulty: 'advanced', points: 35 },
  { id: 'sterling-4', text: "What's your customer acquisition cost (CAC)?", category: 'metrics', subcategory: 'cac', difficulty: 'intermediate', points: 25 },
  { id: 'sterling-5', text: "What's your customer lifetime value (LTV)?", category: 'metrics', subcategory: 'ltv', difficulty: 'intermediate', points: 25 },
  { id: 'sterling-6', text: "What's the LTV:CAC ratio and payback period?", category: 'metrics', subcategory: 'ratio', difficulty: 'advanced', points: 30 },
  { id: 'sterling-7', text: "Detail all your funding sources - personal, grants, investors - with amounts.", category: 'funding', subcategory: 'sources', difficulty: 'intermediate', points: 25 },
  { id: 'sterling-8', text: "Break down all your costs: development, regulatory, operations, marketing.", category: 'costs', subcategory: 'breakdown', difficulty: 'intermediate', points: 25 },
  { id: 'sterling-9', text: "What's your monthly burn rate?", category: 'costs', subcategory: 'burn', difficulty: 'intermediate', points: 20 },
  { id: 'sterling-10', text: "How many months of runway do you have?", category: 'funding', subcategory: 'runway', difficulty: 'intermediate', points: 20 },
  { id: 'sterling-11', text: "What's your current monthly recurring revenue (MRR)?", category: 'revenue', subcategory: 'mrr', difficulty: 'intermediate', points: 25 },
  { id: 'sterling-12', text: "What's your annual recurring revenue (ARR)?", category: 'revenue', subcategory: 'arr', difficulty: 'intermediate', points: 25 },
  { id: 'sterling-13', text: "What's your gross margin percentage?", category: 'margins', subcategory: 'gross', difficulty: 'intermediate', points: 25 },
  { id: 'sterling-14', text: "What's your net margin target?", category: 'margins', subcategory: 'net', difficulty: 'intermediate', points: 20 },
  { id: 'sterling-15', text: "What's your average revenue per user (ARPU)?", category: 'revenue', subcategory: 'arpu', difficulty: 'intermediate', points: 20 },
  { id: 'sterling-16', text: "What's your revenue growth rate month-over-month?", category: 'growth', subcategory: 'mom', difficulty: 'intermediate', points: 25 },
  { id: 'sterling-17', text: "What percentage of revenue comes from your top 10 customers?", category: 'revenue', subcategory: 'concentration', difficulty: 'intermediate', points: 20 },
  { id: 'sterling-18', text: "What's your churn rate?", category: 'metrics', subcategory: 'churn', difficulty: 'intermediate', points: 25 },
  { id: 'sterling-19', text: "What's your net revenue retention rate?", category: 'metrics', subcategory: 'nrr', difficulty: 'advanced', points: 30 },
  { id: 'sterling-20', text: "How do you track and report financial metrics?", category: 'operations', subcategory: 'reporting', difficulty: 'basic', points: 15 },
  { id: 'sterling-21', text: "What accounting software do you use?", category: 'operations', subcategory: 'tools', difficulty: 'basic', points: 10 },
  { id: 'sterling-22', text: "Do you have an accountant or CFO?", category: 'team', subcategory: 'finance', difficulty: 'basic', points: 15 },
  { id: 'sterling-23', text: "Have you had a financial audit?", category: 'compliance', subcategory: 'audit', difficulty: 'intermediate', points: 20 },
  { id: 'sterling-24', text: "What's your cash conversion cycle?", category: 'metrics', subcategory: 'cash', difficulty: 'advanced', points: 25 },
  { id: 'sterling-25', text: "How do you manage working capital?", category: 'operations', subcategory: 'working-capital', difficulty: 'advanced', points: 25 },

  // Pricing Strategy (20 questions)
  { id: 'sterling-26', text: "What's your pricing model (subscription, one-time, freemium, etc.)?", category: 'pricing', subcategory: 'model', difficulty: 'intermediate', points: 20 },
  { id: 'sterling-27', text: "How did you determine your pricing?", category: 'pricing', subcategory: 'strategy', difficulty: 'intermediate', points: 25 },
  { id: 'sterling-28', text: "What's your pricing compared to competitors?", category: 'pricing', subcategory: 'competitive', difficulty: 'intermediate', points: 20 },
  { id: 'sterling-29', text: "Do you offer different pricing tiers? Describe them.", category: 'pricing', subcategory: 'tiers', difficulty: 'intermediate', points: 20 },
  { id: 'sterling-30', text: "What discounts do you offer and when?", category: 'pricing', subcategory: 'discounts', difficulty: 'basic', points: 15 },
  { id: 'sterling-31', text: "Do you offer free trials? What's the conversion rate?", category: 'pricing', subcategory: 'trials', difficulty: 'intermediate', points: 20 },
  { id: 'sterling-32', text: "What's your average contract value?", category: 'pricing', subcategory: 'acv', difficulty: 'intermediate', points: 20 },
  { id: 'sterling-33', text: "What payment methods do you accept?", category: 'pricing', subcategory: 'payments', difficulty: 'basic', points: 10 },
  { id: 'sterling-34', text: "What's your billing cycle (monthly, annual, etc.)?", category: 'pricing', subcategory: 'billing', difficulty: 'basic', points: 10 },
  { id: 'sterling-35', text: "How do you handle failed payments and collections?", category: 'pricing', subcategory: 'collections', difficulty: 'intermediate', points: 15 },
  { id: 'sterling-36', text: "What's your refund policy?", category: 'pricing', subcategory: 'refunds', difficulty: 'basic', points: 10 },
  { id: 'sterling-37', text: "How price-sensitive are your customers?", category: 'pricing', subcategory: 'sensitivity', difficulty: 'intermediate', points: 20 },
  { id: 'sterling-38', text: "Have you tested different price points? What did you learn?", category: 'pricing', subcategory: 'testing', difficulty: 'intermediate', points: 25 },
  { id: 'sterling-39', text: "What's your price elasticity?", category: 'pricing', subcategory: 'elasticity', difficulty: 'advanced', points: 25 },
  { id: 'sterling-40', text: "How often do you adjust pricing?", category: 'pricing', subcategory: 'adjustments', difficulty: 'intermediate', points: 15 },
  { id: 'sterling-41', text: "What's your approach to enterprise pricing?", category: 'pricing', subcategory: 'enterprise', difficulty: 'intermediate', points: 20 },
  { id: 'sterling-42', text: "Do you have usage-based pricing components?", category: 'pricing', subcategory: 'usage', difficulty: 'intermediate', points: 20 },
  { id: 'sterling-43', text: "How do you price for different markets or regions?", category: 'pricing', subcategory: 'regional', difficulty: 'advanced', points: 25 },
  { id: 'sterling-44', text: "What's your approach to partner or reseller pricing?", category: 'pricing', subcategory: 'partners', difficulty: 'intermediate', points: 20 },
  { id: 'sterling-45', text: "How does your pricing support your growth strategy?", category: 'pricing', subcategory: 'strategy', difficulty: 'advanced', points: 25 },

  // Funding & Investment (25 questions)
  { id: 'sterling-46', text: "Have you raised external funding? From whom and how much?", category: 'funding', subcategory: 'history', difficulty: 'intermediate', points: 20 },
  { id: 'sterling-47', text: "What's your current valuation?", category: 'funding', subcategory: 'valuation', difficulty: 'advanced', points: 30 },
  { id: 'sterling-48', text: "What percentage of equity have you given away?", category: 'funding', subcategory: 'equity', difficulty: 'intermediate', points: 20 },
  { id: 'sterling-49', text: "Are you currently raising? What round and target amount?", category: 'funding', subcategory: 'current', difficulty: 'intermediate', points: 25 },
  { id: 'sterling-50', text: "What will you use the funding for? Be specific.", category: 'funding', subcategory: 'use', difficulty: 'intermediate', points: 25 },
  { id: 'sterling-51', text: "What milestones will the funding help you achieve?", category: 'funding', subcategory: 'milestones', difficulty: 'intermediate', points: 25 },
  { id: 'sterling-52', text: "What government grants have you applied for or received?", category: 'funding', subcategory: 'grants', difficulty: 'intermediate', points: 25 },
  { id: 'sterling-53', text: "Have you applied for R&D tax credits?", category: 'funding', subcategory: 'tax', difficulty: 'intermediate', points: 20 },
  { id: 'sterling-54', text: "What's your cap table structure?", category: 'funding', subcategory: 'captable', difficulty: 'advanced', points: 25 },
  { id: 'sterling-55', text: "Do you have any convertible notes or SAFEs outstanding?", category: 'funding', subcategory: 'instruments', difficulty: 'advanced', points: 25 },
  { id: 'sterling-56', text: "What are your investor expectations for returns?", category: 'funding', subcategory: 'expectations', difficulty: 'advanced', points: 25 },
  { id: 'sterling-57', text: "What's your planned exit strategy?", category: 'funding', subcategory: 'exit', difficulty: 'advanced', points: 30 },
  { id: 'sterling-58', text: "Who are your current investors and what value do they add?", category: 'funding', subcategory: 'investors', difficulty: 'intermediate', points: 20 },
  { id: 'sterling-59', text: "Have you received any debt financing?", category: 'funding', subcategory: 'debt', difficulty: 'intermediate', points: 15 },
  { id: 'sterling-60', text: "What's your debt-to-equity ratio?", category: 'funding', subcategory: 'ratio', difficulty: 'advanced', points: 20 },
  { id: 'sterling-61', text: "Have you bootstrapped? For how long?", category: 'funding', subcategory: 'bootstrap', difficulty: 'basic', points: 15 },
  { id: 'sterling-62', text: "What personal investment have founders made?", category: 'funding', subcategory: 'personal', difficulty: 'intermediate', points: 20 },
  { id: 'sterling-63', text: "What's your minimum viable raise?", category: 'funding', subcategory: 'minimum', difficulty: 'intermediate', points: 20 },
  { id: 'sterling-64', text: "What investor terms are you offering?", category: 'funding', subcategory: 'terms', difficulty: 'advanced', points: 25 },
  { id: 'sterling-65', text: "How do you plan to achieve profitability?", category: 'funding', subcategory: 'profitability', difficulty: 'advanced', points: 30 },
  { id: 'sterling-66', text: "What's your path to break-even?", category: 'funding', subcategory: 'breakeven', difficulty: 'advanced', points: 30 },
  { id: 'sterling-67', text: "Have you had any down rounds or bridge financing?", category: 'funding', subcategory: 'history', difficulty: 'advanced', points: 20 },
  { id: 'sterling-68', text: "What due diligence materials do you have ready?", category: 'funding', subcategory: 'materials', difficulty: 'intermediate', points: 20 },
  { id: 'sterling-69', text: "Who handles investor relations?", category: 'funding', subcategory: 'relations', difficulty: 'basic', points: 15 },
  { id: 'sterling-70', text: "What investor updates do you send and how often?", category: 'funding', subcategory: 'updates', difficulty: 'intermediate', points: 15 },

  // Market Validation (25 questions)
  { id: 'sterling-71', text: "Do you have letters of intent or pre-orders from customers?", category: 'validation', subcategory: 'loi', difficulty: 'advanced', points: 35 },
  { id: 'sterling-72', text: "What market validation have you conducted? Share findings.", category: 'validation', subcategory: 'research', difficulty: 'intermediate', points: 25 },
  { id: 'sterling-73', text: "How many customer interviews have you conducted?", category: 'validation', subcategory: 'interviews', difficulty: 'intermediate', points: 20 },
  { id: 'sterling-74', text: "What did customers say they would pay for your solution?", category: 'validation', subcategory: 'willingness', difficulty: 'intermediate', points: 25 },
  { id: 'sterling-75', text: "What pilot programs have you run? What were the results?", category: 'validation', subcategory: 'pilots', difficulty: 'advanced', points: 30 },
  { id: 'sterling-76', text: "How many beta users have you had?", category: 'validation', subcategory: 'beta', difficulty: 'intermediate', points: 20 },
  { id: 'sterling-77', text: "What's your Net Promoter Score (NPS)?", category: 'validation', subcategory: 'nps', difficulty: 'intermediate', points: 25 },
  { id: 'sterling-78', text: "What customer testimonials or case studies do you have?", category: 'validation', subcategory: 'testimonials', difficulty: 'intermediate', points: 25 },
  { id: 'sterling-79', text: "What partnerships have you secured?", category: 'validation', subcategory: 'partnerships', difficulty: 'intermediate', points: 25 },
  { id: 'sterling-80', text: "What distribution agreements do you have?", category: 'validation', subcategory: 'distribution', difficulty: 'advanced', points: 25 },
  { id: 'sterling-81', text: "Have any enterprise customers committed?", category: 'validation', subcategory: 'enterprise', difficulty: 'advanced', points: 30 },
  { id: 'sterling-82', text: "What's your sales pipeline value?", category: 'validation', subcategory: 'pipeline', difficulty: 'intermediate', points: 25 },
  { id: 'sterling-83', text: "What's your average sales cycle length?", category: 'validation', subcategory: 'cycle', difficulty: 'intermediate', points: 20 },
  { id: 'sterling-84', text: "What's your lead-to-customer conversion rate?", category: 'validation', subcategory: 'conversion', difficulty: 'intermediate', points: 25 },
  { id: 'sterling-85', text: "How many active paying customers do you have?", category: 'validation', subcategory: 'customers', difficulty: 'basic', points: 20 },
  { id: 'sterling-86', text: "What's your customer retention rate?", category: 'validation', subcategory: 'retention', difficulty: 'intermediate', points: 25 },
  { id: 'sterling-87', text: "How have customers discovered your product?", category: 'validation', subcategory: 'acquisition', difficulty: 'intermediate', points: 20 },
  { id: 'sterling-88', text: "What's your most effective customer acquisition channel?", category: 'validation', subcategory: 'channels', difficulty: 'intermediate', points: 25 },
  { id: 'sterling-89', text: "What's your cost per lead by channel?", category: 'validation', subcategory: 'cpl', difficulty: 'advanced', points: 25 },
  { id: 'sterling-90', text: "What percentage of new customers come from referrals?", category: 'validation', subcategory: 'referrals', difficulty: 'intermediate', points: 20 },
  { id: 'sterling-91', text: "What upselling or cross-selling success have you had?", category: 'validation', subcategory: 'expansion', difficulty: 'intermediate', points: 25 },
  { id: 'sterling-92', text: "How do you segment your customers?", category: 'validation', subcategory: 'segmentation', difficulty: 'intermediate', points: 20 },
  { id: 'sterling-93', text: "Which customer segment is most profitable?", category: 'validation', subcategory: 'profitability', difficulty: 'advanced', points: 25 },
  { id: 'sterling-94', text: "What's your ideal customer profile (ICP)?", category: 'validation', subcategory: 'icp', difficulty: 'intermediate', points: 20 },
  { id: 'sterling-95', text: "How do you measure product-market fit?", category: 'validation', subcategory: 'pmf', difficulty: 'advanced', points: 30 },

  // Financial Projections & Planning (25 questions)
  { id: 'sterling-96', text: "What are your revenue projections for Year 1?", category: 'projections', subcategory: 'year1', difficulty: 'intermediate', points: 25 },
  { id: 'sterling-97', text: "What are your revenue projections for Year 2?", category: 'projections', subcategory: 'year2', difficulty: 'intermediate', points: 25 },
  { id: 'sterling-98', text: "What are your revenue projections for Year 3?", category: 'projections', subcategory: 'year3', difficulty: 'intermediate', points: 25 },
  { id: 'sterling-99', text: "What assumptions underpin your financial projections?", category: 'projections', subcategory: 'assumptions', difficulty: 'advanced', points: 30 },
  { id: 'sterling-100', text: "What's your best-case scenario projection?", category: 'projections', subcategory: 'best', difficulty: 'intermediate', points: 20 },
  { id: 'sterling-101', text: "What's your worst-case scenario projection?", category: 'projections', subcategory: 'worst', difficulty: 'intermediate', points: 20 },
  { id: 'sterling-102', text: "What's your most likely scenario projection?", category: 'projections', subcategory: 'likely', difficulty: 'intermediate', points: 25 },
  { id: 'sterling-103', text: "How many customers do you need to break even?", category: 'projections', subcategory: 'breakeven', difficulty: 'advanced', points: 25 },
  { id: 'sterling-104', text: "What's your projected headcount growth?", category: 'projections', subcategory: 'headcount', difficulty: 'intermediate', points: 20 },
  { id: 'sterling-105', text: "What are your projected operating expenses?", category: 'projections', subcategory: 'opex', difficulty: 'intermediate', points: 20 },
  { id: 'sterling-106', text: "What capital expenditures are planned?", category: 'projections', subcategory: 'capex', difficulty: 'intermediate', points: 20 },
  { id: 'sterling-107', text: "What's your projected cash flow statement?", category: 'projections', subcategory: 'cashflow', difficulty: 'advanced', points: 30 },
  { id: 'sterling-108', text: "What sensitivity analysis have you done?", category: 'projections', subcategory: 'sensitivity', difficulty: 'advanced', points: 30 },
  { id: 'sterling-109', text: "What key metrics are you tracking to validate projections?", category: 'projections', subcategory: 'metrics', difficulty: 'intermediate', points: 25 },
  { id: 'sterling-110', text: "How often do you update your financial model?", category: 'projections', subcategory: 'updates', difficulty: 'basic', points: 15 },
  { id: 'sterling-111', text: "What's your contingency plan if projections aren't met?", category: 'projections', subcategory: 'contingency', difficulty: 'advanced', points: 30 },
  { id: 'sterling-112', text: "What efficiency gains are built into your projections?", category: 'projections', subcategory: 'efficiency', difficulty: 'intermediate', points: 20 },
  { id: 'sterling-113', text: "How do your projections compare to industry benchmarks?", category: 'projections', subcategory: 'benchmarks', difficulty: 'advanced', points: 25 },
  { id: 'sterling-114', text: "What's your projected market share in Year 3?", category: 'projections', subcategory: 'marketshare', difficulty: 'advanced', points: 25 },
  { id: 'sterling-115', text: "When do you project reaching profitability?", category: 'projections', subcategory: 'profitability', difficulty: 'advanced', points: 30 },
  { id: 'sterling-116', text: "What's your projected EBITDA margin at scale?", category: 'projections', subcategory: 'ebitda', difficulty: 'advanced', points: 25 },
  { id: 'sterling-117', text: "How do seasonal factors affect your projections?", category: 'projections', subcategory: 'seasonal', difficulty: 'intermediate', points: 20 },
  { id: 'sterling-118', text: "What economic assumptions underpin your projections?", category: 'projections', subcategory: 'economic', difficulty: 'advanced', points: 25 },
  { id: 'sterling-119', text: "How have your projections evolved over time?", category: 'projections', subcategory: 'evolution', difficulty: 'intermediate', points: 20 },
  { id: 'sterling-120', text: "What external validation of your projections do you have?", category: 'projections', subcategory: 'validation', difficulty: 'advanced', points: 30 },
];

// ATLAS - Growth Strategist Questions (120 questions)
export const atlasQuestions: Question[] = [
  // Job Creation & UK Impact (30 questions)
  { id: 'atlas-1', text: "How many jobs do you plan to create in the UK over the next 3 years?", category: 'jobs', subcategory: 'total', difficulty: 'intermediate', points: 25 },
  { id: 'atlas-2', text: "Detail your hiring plan - specific roles, salaries, and hiring milestones.", category: 'jobs', subcategory: 'plan', difficulty: 'advanced', points: 30 },
  { id: 'atlas-3', text: "Which specific UK regions will you target for your business?", category: 'location', subcategory: 'regions', difficulty: 'intermediate', points: 20 },
  { id: 'atlas-4', text: "What's your expansion strategy beyond the initial market?", category: 'growth', subcategory: 'expansion', difficulty: 'advanced', points: 30 },
  { id: 'atlas-5', text: "Do you have international expansion plans? Which markets and timeline?", category: 'growth', subcategory: 'international', difficulty: 'advanced', points: 30 },
  { id: 'atlas-6', text: "How will your business benefit the UK economy?", category: 'impact', subcategory: 'economy', difficulty: 'advanced', points: 30 },
  { id: 'atlas-7', text: "What tax revenue will you generate for the UK?", category: 'impact', subcategory: 'tax', difficulty: 'advanced', points: 25 },
  { id: 'atlas-8', text: "Will you be exporting products or services? To which markets?", category: 'impact', subcategory: 'exports', difficulty: 'intermediate', points: 25 },
  { id: 'atlas-9', text: "How will you contribute to the UK's innovation ecosystem?", category: 'impact', subcategory: 'innovation', difficulty: 'advanced', points: 30 },
  { id: 'atlas-10', text: "What partnerships with UK universities are planned?", category: 'impact', subcategory: 'education', difficulty: 'intermediate', points: 25 },
  { id: 'atlas-11', text: "How will you support local suppliers and businesses?", category: 'impact', subcategory: 'suppliers', difficulty: 'intermediate', points: 20 },
  { id: 'atlas-12', text: "What skills training will you provide to employees?", category: 'jobs', subcategory: 'training', difficulty: 'intermediate', points: 20 },
  { id: 'atlas-13', text: "What apprenticeship or graduate programs will you offer?", category: 'jobs', subcategory: 'programs', difficulty: 'intermediate', points: 25 },
  { id: 'atlas-14', text: "How diverse will your workforce be?", category: 'jobs', subcategory: 'diversity', difficulty: 'intermediate', points: 20 },
  { id: 'atlas-15', text: "What's your remote work policy?", category: 'jobs', subcategory: 'remote', difficulty: 'basic', points: 15 },
  { id: 'atlas-16', text: "What employee benefits will you offer?", category: 'jobs', subcategory: 'benefits', difficulty: 'intermediate', points: 20 },
  { id: 'atlas-17', text: "What's your planned payroll in Year 1?", category: 'jobs', subcategory: 'payroll', difficulty: 'intermediate', points: 20 },
  { id: 'atlas-18', text: "What's your planned payroll in Year 3?", category: 'jobs', subcategory: 'payroll', difficulty: 'intermediate', points: 20 },
  { id: 'atlas-19', text: "How will you attract top talent to your company?", category: 'jobs', subcategory: 'attraction', difficulty: 'intermediate', points: 20 },
  { id: 'atlas-20', text: "What employee retention strategies will you implement?", category: 'jobs', subcategory: 'retention', difficulty: 'intermediate', points: 20 },
  { id: 'atlas-21', text: "Will you offer equity or profit-sharing to employees?", category: 'jobs', subcategory: 'equity', difficulty: 'intermediate', points: 20 },
  { id: 'atlas-22', text: "What office space plans do you have in the UK?", category: 'location', subcategory: 'office', difficulty: 'basic', points: 15 },
  { id: 'atlas-23', text: "Will you be based in any enterprise zones or development areas?", category: 'location', subcategory: 'zones', difficulty: 'intermediate', points: 20 },
  { id: 'atlas-24', text: "How will you engage with local communities?", category: 'impact', subcategory: 'community', difficulty: 'intermediate', points: 20 },
  { id: 'atlas-25', text: "What CSR initiatives will you undertake?", category: 'impact', subcategory: 'csr', difficulty: 'intermediate', points: 20 },
  { id: 'atlas-26', text: "Will you sponsor or support any UK charities or causes?", category: 'impact', subcategory: 'charity', difficulty: 'basic', points: 15 },
  { id: 'atlas-27', text: "What environmental commitments will your business make?", category: 'impact', subcategory: 'environment', difficulty: 'intermediate', points: 20 },
  { id: 'atlas-28', text: "Are you targeting B Corp certification or similar?", category: 'impact', subcategory: 'certification', difficulty: 'intermediate', points: 20 },
  { id: 'atlas-29', text: "How will you measure and report social impact?", category: 'impact', subcategory: 'reporting', difficulty: 'intermediate', points: 20 },
  { id: 'atlas-30', text: "What's your net zero carbon strategy?", category: 'impact', subcategory: 'carbon', difficulty: 'advanced', points: 25 },

  // Growth Strategy (30 questions)
  { id: 'atlas-31', text: "Describe your 5-year vision for this business.", category: 'vision', subcategory: 'long-term', difficulty: 'advanced', points: 30 },
  { id: 'atlas-32', text: "Who are your main competitors? List at least 5 with strengths and weaknesses.", category: 'competition', subcategory: 'analysis', difficulty: 'intermediate', points: 25 },
  { id: 'atlas-33', text: "What's your measurable competitive advantage?", category: 'competition', subcategory: 'advantage', difficulty: 'advanced', points: 30 },
  { id: 'atlas-34', text: "What's your total addressable market (TAM)?", category: 'market', subcategory: 'tam', difficulty: 'intermediate', points: 25 },
  { id: 'atlas-35', text: "What's your serviceable obtainable market (SOM)?", category: 'market', subcategory: 'som', difficulty: 'intermediate', points: 25 },
  { id: 'atlas-36', text: "What market share do you aim to capture in Year 3?", category: 'market', subcategory: 'share', difficulty: 'intermediate', points: 25 },
  { id: 'atlas-37', text: "What are your key growth metrics?", category: 'growth', subcategory: 'metrics', difficulty: 'intermediate', points: 20 },
  { id: 'atlas-38', text: "What growth targets have you set for the next 12 months?", category: 'growth', subcategory: 'targets', difficulty: 'intermediate', points: 25 },
  { id: 'atlas-39', text: "What's your customer acquisition strategy?", category: 'growth', subcategory: 'acquisition', difficulty: 'intermediate', points: 25 },
  { id: 'atlas-40', text: "What marketing channels will you use?", category: 'growth', subcategory: 'marketing', difficulty: 'intermediate', points: 20 },
  { id: 'atlas-41', text: "What's your content marketing strategy?", category: 'growth', subcategory: 'content', difficulty: 'intermediate', points: 20 },
  { id: 'atlas-42', text: "What's your SEO and SEM approach?", category: 'growth', subcategory: 'seo', difficulty: 'intermediate', points: 20 },
  { id: 'atlas-43', text: "What's your social media marketing strategy?", category: 'growth', subcategory: 'social', difficulty: 'intermediate', points: 20 },
  { id: 'atlas-44', text: "Will you use paid advertising? What platforms and budgets?", category: 'growth', subcategory: 'advertising', difficulty: 'intermediate', points: 20 },
  { id: 'atlas-45', text: "What's your referral or affiliate program strategy?", category: 'growth', subcategory: 'referral', difficulty: 'intermediate', points: 20 },
  { id: 'atlas-46', text: "How will you build brand awareness?", category: 'growth', subcategory: 'brand', difficulty: 'intermediate', points: 20 },
  { id: 'atlas-47', text: "What PR strategy will you implement?", category: 'growth', subcategory: 'pr', difficulty: 'intermediate', points: 20 },
  { id: 'atlas-48', text: "Will you attend trade shows or conferences? Which ones?", category: 'growth', subcategory: 'events', difficulty: 'basic', points: 15 },
  { id: 'atlas-49', text: "What strategic partnerships are you pursuing?", category: 'growth', subcategory: 'partnerships', difficulty: 'advanced', points: 30 },
  { id: 'atlas-50', text: "What distribution channels will you use?", category: 'growth', subcategory: 'distribution', difficulty: 'intermediate', points: 25 },
  { id: 'atlas-51', text: "What's your sales strategy (direct, channel, self-serve)?", category: 'growth', subcategory: 'sales', difficulty: 'intermediate', points: 25 },
  { id: 'atlas-52', text: "How will you structure your sales team?", category: 'growth', subcategory: 'team', difficulty: 'intermediate', points: 20 },
  { id: 'atlas-53', text: "What sales tools and CRM will you use?", category: 'growth', subcategory: 'tools', difficulty: 'basic', points: 15 },
  { id: 'atlas-54', text: "What's your sales process from lead to close?", category: 'growth', subcategory: 'process', difficulty: 'intermediate', points: 20 },
  { id: 'atlas-55', text: "How will you expand into new customer segments?", category: 'growth', subcategory: 'segments', difficulty: 'advanced', points: 25 },
  { id: 'atlas-56', text: "What product line extensions are planned?", category: 'growth', subcategory: 'products', difficulty: 'intermediate', points: 25 },
  { id: 'atlas-57', text: "How will you expand geographically?", category: 'growth', subcategory: 'geography', difficulty: 'advanced', points: 30 },
  { id: 'atlas-58', text: "Are acquisitions part of your growth strategy?", category: 'growth', subcategory: 'acquisitions', difficulty: 'advanced', points: 25 },
  { id: 'atlas-59', text: "How will you defend against new entrants?", category: 'growth', subcategory: 'defense', difficulty: 'advanced', points: 30 },
  { id: 'atlas-60', text: "What's your strategy for enterprise customers?", category: 'growth', subcategory: 'enterprise', difficulty: 'advanced', points: 30 },

  // Scalability (30 questions)
  { id: 'atlas-61', text: "How will your technology scale with 10x more users?", category: 'scale', subcategory: 'technology', difficulty: 'advanced', points: 30 },
  { id: 'atlas-62', text: "How will your operations scale with growth?", category: 'scale', subcategory: 'operations', difficulty: 'advanced', points: 30 },
  { id: 'atlas-63', text: "What automation will enable scalability?", category: 'scale', subcategory: 'automation', difficulty: 'advanced', points: 30 },
  { id: 'atlas-64', text: "How will you maintain quality as you scale?", category: 'scale', subcategory: 'quality', difficulty: 'advanced', points: 25 },
  { id: 'atlas-65', text: "What processes will you need to document and systemize?", category: 'scale', subcategory: 'processes', difficulty: 'intermediate', points: 20 },
  { id: 'atlas-66', text: "How will customer support scale?", category: 'scale', subcategory: 'support', difficulty: 'intermediate', points: 25 },
  { id: 'atlas-67', text: "What bottlenecks might limit your growth?", category: 'scale', subcategory: 'bottlenecks', difficulty: 'advanced', points: 30 },
  { id: 'atlas-68', text: "How will you manage cash flow during rapid growth?", category: 'scale', subcategory: 'cashflow', difficulty: 'advanced', points: 30 },
  { id: 'atlas-69', text: "What unit economics improvements are needed at scale?", category: 'scale', subcategory: 'economics', difficulty: 'advanced', points: 30 },
  { id: 'atlas-70', text: "How will your organizational structure evolve?", category: 'scale', subcategory: 'organization', difficulty: 'advanced', points: 25 },
  { id: 'atlas-71', text: "What management layers will you add?", category: 'scale', subcategory: 'management', difficulty: 'intermediate', points: 20 },
  { id: 'atlas-72', text: "How will company culture be maintained during growth?", category: 'scale', subcategory: 'culture', difficulty: 'intermediate', points: 25 },
  { id: 'atlas-73', text: "What key hires will enable scale?", category: 'scale', subcategory: 'hiring', difficulty: 'advanced', points: 25 },
  { id: 'atlas-74', text: "How will you onboard employees quickly at scale?", category: 'scale', subcategory: 'onboarding', difficulty: 'intermediate', points: 20 },
  { id: 'atlas-75', text: "What performance management systems will you implement?", category: 'scale', subcategory: 'performance', difficulty: 'intermediate', points: 20 },
  { id: 'atlas-76', text: "How will decision-making work at scale?", category: 'scale', subcategory: 'decisions', difficulty: 'advanced', points: 25 },
  { id: 'atlas-77', text: "What governance structures will you need?", category: 'scale', subcategory: 'governance', difficulty: 'advanced', points: 25 },
  { id: 'atlas-78', text: "How will you maintain innovation while scaling?", category: 'scale', subcategory: 'innovation', difficulty: 'advanced', points: 30 },
  { id: 'atlas-79', text: "What supplier relationships will enable scale?", category: 'scale', subcategory: 'suppliers', difficulty: 'intermediate', points: 20 },
  { id: 'atlas-80', text: "How will you manage inventory or capacity at scale?", category: 'scale', subcategory: 'capacity', difficulty: 'advanced', points: 25 },
  { id: 'atlas-81', text: "What data infrastructure improvements are needed?", category: 'scale', subcategory: 'data', difficulty: 'advanced', points: 25 },
  { id: 'atlas-82', text: "How will reporting and analytics scale?", category: 'scale', subcategory: 'analytics', difficulty: 'intermediate', points: 20 },
  { id: 'atlas-83', text: "What compliance challenges come with scale?", category: 'scale', subcategory: 'compliance', difficulty: 'advanced', points: 25 },
  { id: 'atlas-84', text: "How will international expansion affect operations?", category: 'scale', subcategory: 'international', difficulty: 'advanced', points: 30 },
  { id: 'atlas-85', text: "What currency or payment complexities come with scale?", category: 'scale', subcategory: 'payments', difficulty: 'advanced', points: 25 },
  { id: 'atlas-86', text: "How will customer onboarding scale?", category: 'scale', subcategory: 'customers', difficulty: 'intermediate', points: 25 },
  { id: 'atlas-87', text: "What self-service capabilities will enable scale?", category: 'scale', subcategory: 'self-service', difficulty: 'intermediate', points: 25 },
  { id: 'atlas-88', text: "How will documentation and knowledge base scale?", category: 'scale', subcategory: 'documentation', difficulty: 'intermediate', points: 20 },
  { id: 'atlas-89', text: "What partner ecosystem will support scale?", category: 'scale', subcategory: 'partners', difficulty: 'advanced', points: 25 },
  { id: 'atlas-90', text: "How will you handle increased legal and contract complexity?", category: 'scale', subcategory: 'legal', difficulty: 'advanced', points: 25 },

  // Vision & Long-term (30 questions)
  { id: 'atlas-91', text: "Where do you see your company in 10 years?", category: 'vision', subcategory: '10-year', difficulty: 'advanced', points: 30 },
  { id: 'atlas-92', text: "What's your ultimate mission for this company?", category: 'vision', subcategory: 'mission', difficulty: 'intermediate', points: 25 },
  { id: 'atlas-93', text: "What impact do you want to have on your industry?", category: 'vision', subcategory: 'impact', difficulty: 'advanced', points: 30 },
  { id: 'atlas-94', text: "How might your business model evolve?", category: 'vision', subcategory: 'evolution', difficulty: 'advanced', points: 25 },
  { id: 'atlas-95', text: "What new markets could you enter long-term?", category: 'vision', subcategory: 'markets', difficulty: 'advanced', points: 25 },
  { id: 'atlas-96', text: "What adjacent products or services might you offer?", category: 'vision', subcategory: 'products', difficulty: 'intermediate', points: 25 },
  { id: 'atlas-97', text: "How might technology trends change your business?", category: 'vision', subcategory: 'technology', difficulty: 'advanced', points: 25 },
  { id: 'atlas-98', text: "What platforms could your business become?", category: 'vision', subcategory: 'platform', difficulty: 'advanced', points: 30 },
  { id: 'atlas-99', text: "How might vertical integration benefit your business?", category: 'vision', subcategory: 'integration', difficulty: 'advanced', points: 25 },
  { id: 'atlas-100', text: "What's the most ambitious outcome you can imagine?", category: 'vision', subcategory: 'ambition', difficulty: 'advanced', points: 30 },
  { id: 'atlas-101', text: "What legacy do you want to leave?", category: 'vision', subcategory: 'legacy', difficulty: 'intermediate', points: 25 },
  { id: 'atlas-102', text: "How will you stay relevant in a changing market?", category: 'vision', subcategory: 'relevance', difficulty: 'advanced', points: 30 },
  { id: 'atlas-103', text: "What strategic pivots might you consider?", category: 'vision', subcategory: 'pivots', difficulty: 'advanced', points: 25 },
  { id: 'atlas-104', text: "How will you build lasting customer relationships?", category: 'vision', subcategory: 'relationships', difficulty: 'intermediate', points: 25 },
  { id: 'atlas-105', text: "What ecosystem will you build around your product?", category: 'vision', subcategory: 'ecosystem', difficulty: 'advanced', points: 30 },
  { id: 'atlas-106', text: "How will AI and automation shape your future?", category: 'vision', subcategory: 'ai', difficulty: 'advanced', points: 30 },
  { id: 'atlas-107', text: "What network effects can you create?", category: 'vision', subcategory: 'network', difficulty: 'advanced', points: 35 },
  { id: 'atlas-108', text: "How will you create switching costs?", category: 'vision', subcategory: 'switching', difficulty: 'advanced', points: 30 },
  { id: 'atlas-109', text: "What data assets will you accumulate?", category: 'vision', subcategory: 'data', difficulty: 'advanced', points: 30 },
  { id: 'atlas-110', text: "How might regulatory changes create opportunities?", category: 'vision', subcategory: 'regulation', difficulty: 'advanced', points: 25 },
  { id: 'atlas-111', text: "What industry consolidation might affect you?", category: 'vision', subcategory: 'consolidation', difficulty: 'advanced', points: 25 },
  { id: 'atlas-112', text: "Could your company go public? When?", category: 'vision', subcategory: 'ipo', difficulty: 'advanced', points: 30 },
  { id: 'atlas-113', text: "What types of companies might acquire you?", category: 'vision', subcategory: 'acquisition', difficulty: 'advanced', points: 25 },
  { id: 'atlas-114', text: "How will you create generational value?", category: 'vision', subcategory: 'value', difficulty: 'advanced', points: 30 },
  { id: 'atlas-115', text: "What's your founder succession plan?", category: 'vision', subcategory: 'succession', difficulty: 'advanced', points: 25 },
  { id: 'atlas-116', text: "How will the company operate without you?", category: 'vision', subcategory: 'independence', difficulty: 'advanced', points: 30 },
  { id: 'atlas-117', text: "What values will guide long-term decisions?", category: 'vision', subcategory: 'values', difficulty: 'intermediate', points: 25 },
  { id: 'atlas-118', text: "How will you balance growth with sustainability?", category: 'vision', subcategory: 'sustainability', difficulty: 'advanced', points: 30 },
  { id: 'atlas-119', text: "What would make you consider selling the company?", category: 'vision', subcategory: 'exit', difficulty: 'advanced', points: 25 },
  { id: 'atlas-120', text: "What's your personal long-term commitment to this business?", category: 'vision', subcategory: 'commitment', difficulty: 'intermediate', points: 25 },
];

// SAGE - Compliance Expert Questions (115 questions)
export const sageQuestions: Question[] = [
  // Endorsing Body Strategy (25 questions)
  { id: 'sage-1', text: "Which endorsing body are you targeting? (Envestors, UKES, Innovator International, GEP)", category: 'endorsement', subcategory: 'target', difficulty: 'basic', points: 15 },
  { id: 'sage-2', text: "What's your strategy for the 6 required contact points with your endorser?", category: 'endorsement', subcategory: 'strategy', difficulty: 'advanced', points: 35 },
  { id: 'sage-3', text: "Have you already made contact with any endorsing body?", category: 'endorsement', subcategory: 'contact', difficulty: 'intermediate', points: 25 },
  { id: 'sage-4', text: "Why have you chosen this particular endorsing body?", category: 'endorsement', subcategory: 'rationale', difficulty: 'intermediate', points: 20 },
  { id: 'sage-5', text: "What are the specific criteria of your chosen endorsing body?", category: 'endorsement', subcategory: 'criteria', difficulty: 'intermediate', points: 25 },
  { id: 'sage-6', text: "How does your business align with your endorser's focus areas?", category: 'endorsement', subcategory: 'alignment', difficulty: 'advanced', points: 30 },
  { id: 'sage-7', text: "What evidence will you present to demonstrate innovation?", category: 'endorsement', subcategory: 'evidence', difficulty: 'advanced', points: 30 },
  { id: 'sage-8', text: "What evidence will you present to demonstrate viability?", category: 'endorsement', subcategory: 'evidence', difficulty: 'advanced', points: 30 },
  { id: 'sage-9', text: "What evidence will you present to demonstrate scalability?", category: 'endorsement', subcategory: 'evidence', difficulty: 'advanced', points: 30 },
  { id: 'sage-10', text: "What supporting documents have you prepared?", category: 'endorsement', subcategory: 'documents', difficulty: 'intermediate', points: 25 },
  { id: 'sage-11', text: "Who will be your references for the endorsement application?", category: 'endorsement', subcategory: 'references', difficulty: 'intermediate', points: 20 },
  { id: 'sage-12', text: "Have you attended any endorser information sessions?", category: 'endorsement', subcategory: 'preparation', difficulty: 'basic', points: 15 },
  { id: 'sage-13', text: "What's your timeline for the endorsement application?", category: 'endorsement', subcategory: 'timeline', difficulty: 'intermediate', points: 20 },
  { id: 'sage-14', text: "Do you have a backup endorsing body if your first choice declines?", category: 'endorsement', subcategory: 'backup', difficulty: 'intermediate', points: 20 },
  { id: 'sage-15', text: "How will you demonstrate commitment to the UK?", category: 'endorsement', subcategory: 'commitment', difficulty: 'advanced', points: 30 },
  { id: 'sage-16', text: "What unique value does your business bring to the UK?", category: 'endorsement', subcategory: 'value', difficulty: 'advanced', points: 30 },
  { id: 'sage-17', text: "How will you maintain ongoing contact with your endorser?", category: 'endorsement', subcategory: 'ongoing', difficulty: 'intermediate', points: 25 },
  { id: 'sage-18', text: "What milestones will you report to your endorser?", category: 'endorsement', subcategory: 'milestones', difficulty: 'intermediate', points: 25 },
  { id: 'sage-19', text: "Are you aware of any recent changes to endorser requirements?", category: 'endorsement', subcategory: 'updates', difficulty: 'intermediate', points: 20 },
  { id: 'sage-20', text: "What feedback have you received from initial endorser discussions?", category: 'endorsement', subcategory: 'feedback', difficulty: 'advanced', points: 25 },
  { id: 'sage-21', text: "How will you address any weaknesses in your endorsement application?", category: 'endorsement', subcategory: 'weaknesses', difficulty: 'advanced', points: 30 },
  { id: 'sage-22', text: "What makes your application stand out from other applicants?", category: 'endorsement', subcategory: 'differentiation', difficulty: 'advanced', points: 30 },
  { id: 'sage-23', text: "Have you spoken to others who have been endorsed?", category: 'endorsement', subcategory: 'network', difficulty: 'intermediate', points: 20 },
  { id: 'sage-24', text: "What's your pitch deck for the endorsing body?", category: 'endorsement', subcategory: 'pitch', difficulty: 'advanced', points: 30 },
  { id: 'sage-25', text: "How will you handle endorser interviews or panels?", category: 'endorsement', subcategory: 'interview', difficulty: 'advanced', points: 30 },

  // Regulatory Compliance (25 questions)
  { id: 'sage-26', text: "List all regulatory requirements for your business - certifications, compliance standards.", category: 'regulatory', subcategory: 'requirements', difficulty: 'advanced', points: 30 },
  { id: 'sage-27', text: "What's your timeline for achieving each compliance requirement?", category: 'regulatory', subcategory: 'timeline', difficulty: 'advanced', points: 30 },
  { id: 'sage-28', text: "What budget have you allocated for regulatory compliance?", category: 'regulatory', subcategory: 'budget', difficulty: 'intermediate', points: 25 },
  { id: 'sage-29', text: "What industry-specific regulations apply to your business?", category: 'regulatory', subcategory: 'industry', difficulty: 'advanced', points: 30 },
  { id: 'sage-30', text: "How will you ensure GDPR compliance?", category: 'regulatory', subcategory: 'gdpr', difficulty: 'advanced', points: 30 },
  { id: 'sage-31', text: "What data protection measures have you implemented?", category: 'regulatory', subcategory: 'data', difficulty: 'advanced', points: 30 },
  { id: 'sage-32', text: "Do you need any specific licenses to operate?", category: 'regulatory', subcategory: 'licenses', difficulty: 'intermediate', points: 25 },
  { id: 'sage-33', text: "What insurance policies do you have or need?", category: 'regulatory', subcategory: 'insurance', difficulty: 'intermediate', points: 25 },
  { id: 'sage-34', text: "How will you handle international data transfers?", category: 'regulatory', subcategory: 'transfers', difficulty: 'advanced', points: 30 },
  { id: 'sage-35', text: "What health and safety regulations apply?", category: 'regulatory', subcategory: 'safety', difficulty: 'intermediate', points: 20 },
  { id: 'sage-36', text: "What environmental regulations must you comply with?", category: 'regulatory', subcategory: 'environmental', difficulty: 'intermediate', points: 25 },
  { id: 'sage-37', text: "Do you need FCA authorization or registration?", category: 'regulatory', subcategory: 'fca', difficulty: 'advanced', points: 30 },
  { id: 'sage-38', text: "What consumer protection regulations apply?", category: 'regulatory', subcategory: 'consumer', difficulty: 'intermediate', points: 25 },
  { id: 'sage-39', text: "How will you ensure accessibility compliance?", category: 'regulatory', subcategory: 'accessibility', difficulty: 'intermediate', points: 20 },
  { id: 'sage-40', text: "What employment law requirements will you follow?", category: 'regulatory', subcategory: 'employment', difficulty: 'intermediate', points: 25 },
  { id: 'sage-41', text: "How will you handle intellectual property disputes?", category: 'regulatory', subcategory: 'ip', difficulty: 'advanced', points: 30 },
  { id: 'sage-42', text: "What terms of service and privacy policy do you have?", category: 'regulatory', subcategory: 'legal', difficulty: 'intermediate', points: 25 },
  { id: 'sage-43', text: "How do you ensure advertising compliance?", category: 'regulatory', subcategory: 'advertising', difficulty: 'intermediate', points: 20 },
  { id: 'sage-44', text: "What anti-money laundering measures do you have?", category: 'regulatory', subcategory: 'aml', difficulty: 'advanced', points: 30 },
  { id: 'sage-45', text: "How will you handle sanctions and export controls?", category: 'regulatory', subcategory: 'sanctions', difficulty: 'advanced', points: 30 },
  { id: 'sage-46', text: "What tax compliance measures are in place?", category: 'regulatory', subcategory: 'tax', difficulty: 'advanced', points: 30 },
  { id: 'sage-47', text: "How will you ensure VAT compliance?", category: 'regulatory', subcategory: 'vat', difficulty: 'intermediate', points: 25 },
  { id: 'sage-48', text: "What corporate governance structures do you have?", category: 'regulatory', subcategory: 'governance', difficulty: 'advanced', points: 25 },
  { id: 'sage-49', text: "How do you manage regulatory change?", category: 'regulatory', subcategory: 'change', difficulty: 'advanced', points: 30 },
  { id: 'sage-50', text: "What compliance monitoring do you conduct?", category: 'regulatory', subcategory: 'monitoring', difficulty: 'intermediate', points: 25 },

  // Traction & Evidence (25 questions)
  { id: 'sage-51', text: "Do you have existing customers or beta testers? Describe them.", category: 'traction', subcategory: 'customers', difficulty: 'intermediate', points: 25 },
  { id: 'sage-52', text: "What traction evidence can you provide - metrics, pilot results, revenue?", category: 'traction', subcategory: 'evidence', difficulty: 'advanced', points: 35 },
  { id: 'sage-53', text: "What measurable results have you achieved?", category: 'traction', subcategory: 'results', difficulty: 'advanced', points: 30 },
  { id: 'sage-54', text: "What growth trends can you demonstrate?", category: 'traction', subcategory: 'growth', difficulty: 'intermediate', points: 25 },
  { id: 'sage-55', text: "What customer success stories can you share?", category: 'traction', subcategory: 'success', difficulty: 'intermediate', points: 25 },
  { id: 'sage-56', text: "What media coverage have you received?", category: 'traction', subcategory: 'media', difficulty: 'intermediate', points: 20 },
  { id: 'sage-57', text: "What awards or recognition have you earned?", category: 'traction', subcategory: 'awards', difficulty: 'intermediate', points: 25 },
  { id: 'sage-58', text: "What partnerships have you formed?", category: 'traction', subcategory: 'partnerships', difficulty: 'intermediate', points: 25 },
  { id: 'sage-59', text: "What funding have you raised?", category: 'traction', subcategory: 'funding', difficulty: 'intermediate', points: 25 },
  { id: 'sage-60', text: "What user engagement metrics can you show?", category: 'traction', subcategory: 'engagement', difficulty: 'intermediate', points: 25 },
  { id: 'sage-61', text: "What retention or repeat purchase data do you have?", category: 'traction', subcategory: 'retention', difficulty: 'intermediate', points: 25 },
  { id: 'sage-62', text: "What referral or word-of-mouth evidence exists?", category: 'traction', subcategory: 'referrals', difficulty: 'intermediate', points: 20 },
  { id: 'sage-63', text: "What waitlist or early interest do you have?", category: 'traction', subcategory: 'waitlist', difficulty: 'intermediate', points: 20 },
  { id: 'sage-64', text: "What intellectual property have you secured?", category: 'traction', subcategory: 'ip', difficulty: 'advanced', points: 30 },
  { id: 'sage-65', text: "What product development milestones have you hit?", category: 'traction', subcategory: 'milestones', difficulty: 'intermediate', points: 25 },
  { id: 'sage-66', text: "What team growth have you achieved?", category: 'traction', subcategory: 'team', difficulty: 'intermediate', points: 20 },
  { id: 'sage-67', text: "What market validation studies have you conducted?", category: 'traction', subcategory: 'validation', difficulty: 'advanced', points: 30 },
  { id: 'sage-68', text: "What industry expert endorsements do you have?", category: 'traction', subcategory: 'endorsements', difficulty: 'advanced', points: 30 },
  { id: 'sage-69', text: "What social proof can you demonstrate?", category: 'traction', subcategory: 'social', difficulty: 'intermediate', points: 20 },
  { id: 'sage-70', text: "What thought leadership have you established?", category: 'traction', subcategory: 'thought', difficulty: 'intermediate', points: 25 },
  { id: 'sage-71', text: "What speaking engagements or publications do you have?", category: 'traction', subcategory: 'speaking', difficulty: 'intermediate', points: 20 },
  { id: 'sage-72', text: "What pilot programs have you completed?", category: 'traction', subcategory: 'pilots', difficulty: 'advanced', points: 30 },
  { id: 'sage-73', text: "What letters of intent or commitments do you have?", category: 'traction', subcategory: 'commitments', difficulty: 'advanced', points: 35 },
  { id: 'sage-74', text: "What third-party validation have you received?", category: 'traction', subcategory: 'validation', difficulty: 'advanced', points: 30 },
  { id: 'sage-75', text: "How do your metrics compare to industry benchmarks?", category: 'traction', subcategory: 'benchmarks', difficulty: 'advanced', points: 30 },

  // Founder Background (25 questions)
  { id: 'sage-76', text: "What professional certifications or accreditations do you hold?", category: 'background', subcategory: 'certifications', difficulty: 'intermediate', points: 25 },
  { id: 'sage-77', text: "Describe your relevant work history that qualifies you for this venture.", category: 'background', subcategory: 'experience', difficulty: 'advanced', points: 30 },
  { id: 'sage-78', text: "What measurable achievements from previous roles demonstrate your capability?", category: 'background', subcategory: 'achievements', difficulty: 'advanced', points: 30 },
  { id: 'sage-79', text: "What's your educational background?", category: 'background', subcategory: 'education', difficulty: 'basic', points: 15 },
  { id: 'sage-80', text: "What specialized training have you completed?", category: 'background', subcategory: 'training', difficulty: 'intermediate', points: 20 },
  { id: 'sage-81', text: "Have you started businesses before? What happened?", category: 'background', subcategory: 'entrepreneurship', difficulty: 'intermediate', points: 25 },
  { id: 'sage-82', text: "What leadership roles have you held?", category: 'background', subcategory: 'leadership', difficulty: 'intermediate', points: 20 },
  { id: 'sage-83', text: "What industry expertise do you bring?", category: 'background', subcategory: 'expertise', difficulty: 'intermediate', points: 25 },
  { id: 'sage-84', text: "What technical skills do you possess?", category: 'background', subcategory: 'technical', difficulty: 'intermediate', points: 20 },
  { id: 'sage-85', text: "What business skills do you bring?", category: 'background', subcategory: 'business', difficulty: 'intermediate', points: 20 },
  { id: 'sage-86', text: "What's your professional network like?", category: 'background', subcategory: 'network', difficulty: 'intermediate', points: 20 },
  { id: 'sage-87', text: "Who are your mentors or advisors?", category: 'background', subcategory: 'mentors', difficulty: 'intermediate', points: 20 },
  { id: 'sage-88', text: "What boards or advisory roles do you hold?", category: 'background', subcategory: 'boards', difficulty: 'intermediate', points: 20 },
  { id: 'sage-89', text: "What professional associations are you a member of?", category: 'background', subcategory: 'associations', difficulty: 'basic', points: 15 },
  { id: 'sage-90', text: "What publications or patents are in your name?", category: 'background', subcategory: 'publications', difficulty: 'advanced', points: 30 },
  { id: 'sage-91', text: "What awards have you personally received?", category: 'background', subcategory: 'awards', difficulty: 'intermediate', points: 20 },
  { id: 'sage-92', text: "What languages do you speak?", category: 'background', subcategory: 'languages', difficulty: 'basic', points: 10 },
  { id: 'sage-93', text: "What countries have you worked in?", category: 'background', subcategory: 'international', difficulty: 'intermediate', points: 20 },
  { id: 'sage-94', text: "How do your co-founders complement your skills?", category: 'background', subcategory: 'team', difficulty: 'intermediate', points: 25 },
  { id: 'sage-95', text: "What's your commitment to staying in the UK?", category: 'background', subcategory: 'commitment', difficulty: 'advanced', points: 30 },
  { id: 'sage-96', text: "What ties do you have to the UK?", category: 'background', subcategory: 'ties', difficulty: 'intermediate', points: 25 },
  { id: 'sage-97', text: "What's your personal financial investment in this venture?", category: 'background', subcategory: 'investment', difficulty: 'intermediate', points: 25 },
  { id: 'sage-98', text: "How do you balance this venture with other commitments?", category: 'background', subcategory: 'dedication', difficulty: 'intermediate', points: 20 },
  { id: 'sage-99', text: "What's your long-term residency intention?", category: 'background', subcategory: 'residency', difficulty: 'advanced', points: 25 },
  { id: 'sage-100', text: "What drives your passion for this business?", category: 'background', subcategory: 'motivation', difficulty: 'intermediate', points: 20 },

  // Visa Requirements (15 questions)
  { id: 'sage-101', text: "Do you meet the English language requirement?", category: 'visa', subcategory: 'english', difficulty: 'basic', points: 15 },
  { id: 'sage-102', text: "Do you have proof of £1,270 maintenance funds?", category: 'visa', subcategory: 'maintenance', difficulty: 'basic', points: 15 },
  { id: 'sage-103', text: "What's your TB test status if required?", category: 'visa', subcategory: 'health', difficulty: 'basic', points: 10 },
  { id: 'sage-104', text: "Do you have a clean criminal record?", category: 'visa', subcategory: 'character', difficulty: 'basic', points: 15 },
  { id: 'sage-105', text: "What's your current immigration status?", category: 'visa', subcategory: 'status', difficulty: 'basic', points: 15 },
  { id: 'sage-106', text: "Have you previously been refused a UK visa?", category: 'visa', subcategory: 'history', difficulty: 'basic', points: 15 },
  { id: 'sage-107', text: "Are you switching from another visa category?", category: 'visa', subcategory: 'switching', difficulty: 'intermediate', points: 20 },
  { id: 'sage-108', text: "Are you applying as a new applicant or extending?", category: 'visa', subcategory: 'application', difficulty: 'basic', points: 10 },
  { id: 'sage-109', text: "When do you plan to apply for the visa?", category: 'visa', subcategory: 'timeline', difficulty: 'basic', points: 10 },
  { id: 'sage-110', text: "Have you engaged an immigration lawyer?", category: 'visa', subcategory: 'legal', difficulty: 'intermediate', points: 20 },
  { id: 'sage-111', text: "What's your understanding of the visa conditions?", category: 'visa', subcategory: 'conditions', difficulty: 'intermediate', points: 25 },
  { id: 'sage-112', text: "Are you planning to bring dependents?", category: 'visa', subcategory: 'dependents', difficulty: 'basic', points: 15 },
  { id: 'sage-113', text: "What's your settlement or ILR timeline?", category: 'visa', subcategory: 'settlement', difficulty: 'advanced', points: 25 },
  { id: 'sage-114', text: "How will you document your business activities for visa renewal?", category: 'visa', subcategory: 'documentation', difficulty: 'advanced', points: 30 },
  { id: 'sage-115', text: "What contingency plans do you have if the visa is delayed or refused?", category: 'visa', subcategory: 'contingency', difficulty: 'advanced', points: 30 },
];

// Export all questions
export const allQuestions = {
  nova: novaQuestions,
  sterling: sterlingQuestions,
  atlas: atlasQuestions,
  sage: sageQuestions,
};

// Get question by agent and index
export function getQuestion(agent: string, index: number): Question | null {
  const questions = allQuestions[agent as keyof typeof allQuestions];
  if (!questions || index < 0 || index >= questions.length) {
    return null;
  }
  return questions[index];
}

// Get random question by agent
export function getRandomQuestion(agent: string, excludeIds: string[] = []): Question | null {
  const questions = allQuestions[agent as keyof typeof allQuestions];
  if (!questions) return null;
  
  const available = questions.filter(q => !excludeIds.includes(q.id));
  if (available.length === 0) return null;
  
  return available[Math.floor(Math.random() * available.length)];
}

// Get total question count
export function getTotalQuestionCount(): number {
  return novaQuestions.length + sterlingQuestions.length + atlasQuestions.length + sageQuestions.length;
}
