/**
 * FULLY AUTOMATED BLOG PIPELINE
 *
 * This module runs the complete end-to-end blog pipeline without any human
 * intervention. It schedules itself internally using Node.js timers — no
 * external cron service required.
 *
 * PIPELINE PER POST:
 *   1. Qwen generates article
 *   2. Quad-AI verification (Gemini + OpenAI + Claude + Qwen)
 *   3. If composite ≥95 and no floor violation → auto-publish immediately
 *   4. If fails → auto-fix (Qwen reads all flags, surgically corrects)
 *   5. Re-verify → if passes → auto-publish
 *   6. If still fails → repeat fix+verify up to MAX_FIX_ATTEMPTS times
 *   7. If still failing after all attempts → leave in human_review queue
 *
 * SCHEDULE:
 *   - Generate 3 posts at 07:00 GMT
 *   - Generate 3 posts at 12:00 GMT
 *   - Generate 3 posts at 20:00 GMT
 *   - Drain human review queue at :30 past every even hour (00:30, 02:30, …)
 *
 * STATUS TRACKING:
 *   Fix attempt count is stored inside verificationDetails JSON so no schema
 *   change is required.
 */

import { db } from "./db.js";
import { blogPosts } from "../shared/schema.js";
import { eq, and, lte } from "drizzle-orm";
import { generateBlogPost } from "./blogGenerator.js";
import { verifyBlogPost, computeContentHash } from "./blogMultiVerifier.js";
import { autoFixBlogPost } from "./blogAutoFixer.js";

// ─── Config ──────────────────────────────────────────────────────────────────

const MAX_FIX_ATTEMPTS = 3;          // Max auto-fix rounds before giving up on a post
const MAX_DRAIN_ATTEMPTS = 2;        // Max attempts per drain cycle on stuck review-queue posts
const POSTS_PER_RUN = 3;            // Posts generated per scheduled run
const INTER_POST_DELAY_MS = 3000;   // Delay between posts to avoid rate limits
const INTER_FIX_DELAY_MS = 2000;    // Delay between fix iterations

// ─── Types ────────────────────────────────────────────────────────────────────

type BlogPostRow = typeof blogPosts.$inferSelect;

// ─── Core: generate one post with automatic fix loop ─────────────────────────

async function generateWithAutoFix(): Promise<{ title: string; status: string; compositeScore: number }> {
  console.log("[Pipeline] Generating new blog post…");

  // Step 1: Generate
  const raw = await generateBlogPost();

  // Step 2: Verify
  let verification = await verifyBlogPost(raw.title, raw.content);
  let content = raw.content;
  let attempt = 0;

  // Step 3: Fix loop
  while (!verification.passed && attempt < MAX_FIX_ATTEMPTS) {
    attempt++;
    console.log(
      `[Pipeline] Post "${raw.title.substring(0, 50)}" failed gate (composite: ${verification.compositeScore}). ` +
      `Fix attempt ${attempt}/${MAX_FIX_ATTEMPTS}…`
    );

    // Collect all flags from the last verification
    const details = verification.verificationDetails as any;
    const allFlags = [
      ...(details?.geminiFlags ?? []),
      ...(details?.openaiFlags ?? []),
      ...(details?.claudeFlags ?? []),
      ...(details?.qwenFlags ?? []),
    ];

    await new Promise(r => setTimeout(r, INTER_FIX_DELAY_MS));
    const fixResult = await autoFixBlogPost(raw.title, content, allFlags);
    content = fixResult.fixedContent;
    verification = fixResult.verificationResult;
  }

  // Step 4: Build final status
  const status = verification.passed ? "published" : "human_review";
  const contentHash = computeContentHash(content);

  console.log(
    `[Pipeline] "${raw.title.substring(0, 50)}" → ${status.toUpperCase()} ` +
    `(composite: ${verification.compositeScore}, fixes applied: ${attempt})`
  );

  // Step 5: Insert into database
  const verificationDetails = {
    ...(verification.verificationDetails as object ?? {}),
    autoFixAttempts: attempt,
  };

  const slug = raw.slug + (Math.random().toString(36).substring(2, 6));

  await db.insert(blogPosts).values({
    title: raw.title,
    slug,
    excerpt: raw.excerpt,
    content,
    category: raw.category,
    tags: raw.tags,
    metaTitle: raw.metaTitle,
    metaDescription: raw.metaDescription,
    metaKeywords: raw.metaKeywords,
    readingTime: raw.readingTime,
    author: raw.author,
    authorBio: raw.authorBio,
    featuredImage: (raw as any).featuredImage ?? null,
    isPublished: verification.passed,
    postStatus: status,
    isFeatured: false,
    publishedAt: verification.passed ? new Date() : null,
    isAutoGenerated: true,
    generatedAt: new Date(),
    aiVerificationScore: verification.compositeScore,
    geminiScore: verification.geminiScore,
    openaiScore: verification.openaiScore,
    claudeScore: verification.claudeScore,
    qwenScore: verification.qwenScore,
    verificationStatus: verification.passed ? "verified" : "flagged",
    verificationDetails,
    verifiedAt: new Date(),
    verificationExpiresAt: new Date(Date.now() + 90 * 24 * 60 * 60 * 1000),
    humanReviewRequired: !verification.passed,
    contradictionFlags: verification.allFlags?.length ?? 0,
    contentHash,
  });

  return { title: raw.title, status, compositeScore: verification.compositeScore };
}

// ─── Core: drain human review queue ──────────────────────────────────────────

async function drainHumanReviewQueue(): Promise<void> {
  console.log("[Pipeline] Draining human review queue…");

  // Fetch posts stuck in human review that haven't exceeded max drain attempts
  const queue = await db
    .select()
    .from(blogPosts)
    .where(
      and(
        eq(blogPosts.humanReviewRequired, true),
        eq(blogPosts.isPublished, false),
      )
    )
    .limit(10);

  if (queue.length === 0) {
    console.log("[Pipeline] Human review queue is empty — nothing to drain.");
    return;
  }

  console.log(`[Pipeline] Found ${queue.length} post(s) in human review queue.`);

  for (const post of queue) {
    try {
      // Read current attempt count from stored details
      const details = (post.verificationDetails ?? {}) as any;
      const drainAttempts = details.drainAttempts ?? 0;

      if (drainAttempts >= MAX_DRAIN_ATTEMPTS) {
        console.log(
          `[Pipeline] Skipping "${post.title?.substring(0, 50)}" — already attempted ${drainAttempts} drain fix(es). Needs human review.`
        );
        continue;
      }

      console.log(
        `[Pipeline] Auto-fixing review-queue post: "${post.title?.substring(0, 50)}" (drain attempt ${drainAttempts + 1})`
      );

      // Collect all flags from stored verification details
      const allFlags = [
        ...(details.geminiFlags ?? []),
        ...(details.openaiFlags ?? []),
        ...(details.claudeFlags ?? []),
        ...(details.qwenFlags ?? []),
      ];

      let content = post.content ?? "";
      let verification = await verifyBlogPost(post.title ?? "", content);

      // Run fix loop up to MAX_FIX_ATTEMPTS for this drain cycle
      let fixRound = 0;
      while (!verification.passed && fixRound < MAX_FIX_ATTEMPTS) {
        fixRound++;
        const currentFlags = [
          ...((verification.verificationDetails as any)?.geminiFlags ?? []),
          ...((verification.verificationDetails as any)?.openaiFlags ?? []),
          ...((verification.verificationDetails as any)?.claudeFlags ?? []),
          ...((verification.verificationDetails as any)?.qwenFlags ?? []),
        ];
        await new Promise(r => setTimeout(r, INTER_FIX_DELAY_MS));
        const fixResult = await autoFixBlogPost(post.title ?? "", content, currentFlags.length > 0 ? currentFlags : allFlags);
        content = fixResult.fixedContent;
        verification = fixResult.verificationResult;
      }

      const passed = verification.passed;
      const newDetails = {
        ...(verification.verificationDetails as object ?? {}),
        drainAttempts: drainAttempts + 1,
        autoFixAttempts: ((details.autoFixAttempts ?? 0) + fixRound),
      };

      await db
        .update(blogPosts)
        .set({
          content,
          isPublished: passed,
          postStatus: passed ? "published" : "human_review",
          humanReviewRequired: !passed,
          publishedAt: passed ? new Date() : null,
          aiVerificationScore: verification.compositeScore,
          geminiScore: verification.geminiScore,
          openaiScore: verification.openaiScore,
          claudeScore: verification.claudeScore,
          qwenScore: verification.qwenScore,
          verificationStatus: passed ? "verified" : "flagged",
          verificationDetails: newDetails,
          verifiedAt: new Date(),
          verificationExpiresAt: new Date(Date.now() + 90 * 24 * 60 * 60 * 1000),
          contentHash: computeContentHash(content),
        })
        .where(eq(blogPosts.id, post.id));

      console.log(
        `[Pipeline] Queue drain result for "${post.title?.substring(0, 50)}": ` +
        `${passed ? "AUTO-PUBLISHED" : "still in review"} (composite: ${verification.compositeScore})`
      );

      await new Promise(r => setTimeout(r, INTER_POST_DELAY_MS));
    } catch (err) {
      console.error(`[Pipeline] Failed to drain post "${post.title?.substring(0, 50)}":`, err);
    }
  }
}

// ─── Scheduled run: generate N posts with fix loops ──────────────────────────

async function scheduledGenerationRun(): Promise<void> {
  console.log(`[Pipeline] Scheduled generation run — generating ${POSTS_PER_RUN} posts…`);
  const results: Array<{ title: string; status: string; compositeScore: number }> = [];

  for (let i = 0; i < POSTS_PER_RUN; i++) {
    try {
      const result = await generateWithAutoFix();
      results.push(result);
    } catch (err) {
      console.error(`[Pipeline] Post ${i + 1}/${POSTS_PER_RUN} failed completely:`, err);
    }
    if (i < POSTS_PER_RUN - 1) {
      await new Promise(r => setTimeout(r, INTER_POST_DELAY_MS));
    }
  }

  const published = results.filter(r => r.status === "published").length;
  const inReview = results.filter(r => r.status === "human_review").length;
  console.log(
    `[Pipeline] Generation run complete — ` +
    `${published} auto-published, ${inReview} in human review, ${POSTS_PER_RUN - results.length} failed.`
  );
}

// ─── Scheduler: compute ms until next target time (GMT) ──────────────────────

function msUntilNextGMT(hour: number, minute: number = 0): number {
  const now = new Date();
  const target = new Date(now);
  target.setUTCHours(hour, minute, 0, 0);
  if (target <= now) target.setUTCDate(target.getUTCDate() + 1);
  return target.getTime() - now.getTime();
}

function scheduleDaily(
  label: string,
  gmtHour: number,
  gmtMinute: number,
  fn: () => Promise<void>
): void {
  const scheduleNext = () => {
    const delay = msUntilNextGMT(gmtHour, gmtMinute);
    const nextRun = new Date(Date.now() + delay);
    console.log(
      `[Pipeline] "${label}" next run in ${Math.round(delay / 60000)} min ` +
      `(${nextRun.toUTCString()})`
    );
    setTimeout(async () => {
      try {
        await fn();
      } catch (err) {
        console.error(`[Pipeline] "${label}" run failed:`, err);
      } finally {
        scheduleNext(); // Always reschedule
      }
    }, delay);
  };
  scheduleNext();
}

// ─── Start: wire up all schedules ─────────────────────────────────────────────

export function startBlogPipeline(): void {
  console.log("[Pipeline] Automated blog pipeline starting…");

  // Generation runs: 07:00, 12:00, 20:00 GMT
  scheduleDaily("generate-07:00", 7,  0, scheduledGenerationRun);
  scheduleDaily("generate-12:00", 12, 0, scheduledGenerationRun);
  scheduleDaily("generate-20:00", 20, 0, scheduledGenerationRun);

  // Human review queue drain: every 2 hours at :30 past (00:30, 02:30, …)
  const drainHours = [0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22];
  for (const h of drainHours) {
    scheduleDaily(`drain-${String(h).padStart(2, "0")}:30`, h, 30, drainHumanReviewQueue);
  }

  console.log(
    "[Pipeline] Schedules set: generate at 07:00, 12:00, 20:00 GMT | " +
    "drain queue every 2 hours."
  );
}
