import fetch from "node-fetch";

export interface NewsItem {
  id: string;
  title: string;
  date: string;
  content: string;
  source: string;
  category: string;
}

const INITIAL_NEWS: NewsItem[] = [
  { id: "1", title: "Tech Nation 2025: AI, Cyber Security, CleanTech prioritized for Innovation Visa endorsements", date: "Nov 21, 2025", content: "Tech Nation announces strategic focus areas for 2025 applications, emphasizing artificial intelligence, cybersecurity innovations, and climate technology solutions.", source: "Tech Nation", category: "Endorser" },
  { id: "2", title: "Home Office extends Innovation Visa processing to 2-3 weeks average following recent policy update", date: "Nov 20, 2025", content: "Standard processing timeline now 2-3 weeks post-endorsement. Expedited processing available for priority sectors at £500 additional fee.", source: "Home Office", category: "Processing" },
  { id: "3", title: "Innovator International expands eligibility to include B2B SaaS and service-based innovations", date: "Nov 19, 2025", content: "Updated criteria now accept software-as-a-service platforms and professional services innovations, broadening endorsement opportunities beyond traditional product companies.", source: "Innovator International", category: "Endorser" },
  { id: "4", title: "University Routes announces 4-6 week fast-track endorsement for academic spinouts", date: "Nov 18, 2025", content: "Academic research-backed companies can receive endorsement in 4-6 weeks through dedicated University Routes program, fastest among all endorsement pathways.", source: "University Routes", category: "Fast Track" },
  { id: "5", title: "Department for Business confirms 88% endorsement success rate for UK Innovation Visa in 2025", date: "Nov 17, 2025", content: "Latest statistics show highest approval rates on record. Success correlated with comprehensive business planning and clear market validation evidence.", source: "Department for Business", category: "Statistics" },
  { id: "6", title: "Envestors pathway targets founders with £500K+ ARR and proven revenue traction", date: "Nov 16, 2025", content: "Updated endorsement criteria now focus on revenue-generating companies. Growth-stage startups with demonstrated market traction receive priority consideration.", source: "Envestors", category: "Endorser" },
  { id: "7", title: "Global Talent Visa Route now available for internationally recognized innovation leaders", date: "Nov 15, 2025", content: "No endorsing body required for exceptional talent in innovation and entrepreneurship. Alternative pathway for established founders and industry experts.", source: "Home Office", category: "New Route" },
  { id: "8", title: "Scale-up Visa launches: Fast-track route for high-growth companies exceeding £500K revenue", date: "Nov 14, 2025", content: "New visa category designed for scaling companies moving beyond startup phase. Simplified requirements and expedited processing for growth-stage businesses.", source: "Home Office", category: "New Route" },
  { id: "9", title: "AI and Machine Learning declared priority sectors with reduced documentary requirements", date: "Nov 13, 2025", content: "Government announces AI/ML as strategic priority. Applications in these sectors receive expedited review and relaxed initial documentation thresholds.", source: "Department for Business", category: "Priority" },
  { id: "10", title: "Cyber Security fast-track route launched in partnership with GCHQ and Home Office", date: "Nov 12, 2025", content: "Specialized endorsement pathway for cybersecurity innovations addressing UK national security priorities. Average endorsement time: 3-4 weeks.", source: "GCHQ", category: "Fast Track" },
  { id: "11", title: "CleanTech and Sustainability now emphasized across all UK Innovation Visa endorsement routes", date: "Nov 11, 2025", content: "Environmental and sustainability innovations receive favorable consideration. Climate tech companies get priority in Tech Nation, Innovator International, and University Routes.", source: "Tech Nation", category: "Priority" },
  { id: "12", title: "Home Office updates financial projection requirements to 3-year detailed forecasts with unit economics", date: "Nov 10, 2025", content: "Applicants must now provide granular 3-year financial projections including customer acquisition costs, retention rates, and unit economics analysis.", source: "Home Office", category: "Requirements" },
  { id: "13", title: "Minimum job creation targets confirmed: 2 roles Year 1, 5 roles by Year 3 mandatory", date: "Nov 9, 2025", content: "Innovation Visa criteria require commitment to create minimum 2 full-time UK jobs within first year, scaling to 5+ jobs by end of Year 3.", source: "Home Office", category: "Requirements" },
  { id: "14", title: "Due diligence enhancements implemented for founder background verification and funding source checks", date: "Nov 8, 2025", content: "Enhanced compliance screening on founder backgrounds, financial sources, and business legitimacy. Processing may take additional 1-2 weeks for first-time applicants.", source: "Home Office", category: "Compliance" },
  { id: "15", title: "Indefinite Leave to Remain pathway confirmed after 2 years of compliant Innovation Visa tenure", date: "Nov 7, 2025", content: "Visa holders maintaining innovation status and fulfilling all conditions can apply for ILR after 24 months. Settlement approval rate: 95%.", source: "Home Office Immigration", category: "Settlement" },
  { id: "16", title: "Dependent visa eligibility confirmed for spouse and children of Innovation Visa holders", date: "Nov 6, 2025", content: "Spouses and dependent children can accompany Innovation Visa holder on dependent visa status. Family applications typically approved within 4 weeks.", source: "Home Office", category: "Family" },
  { id: "17", title: "Visa renewal process confirmed: 3-year renewals available for continuing innovation businesses", date: "Nov 5, 2025", content: "Initial 2-year visa can be renewed for additional 3-year periods upon meeting ongoing innovation and viability requirements. Renewal processing: 4 weeks average.", source: "Home Office", category: "Renewal" },
  { id: "18", title: "Minimum funding requirement set at £50K: Bank statements, investment, or founder savings acceptable", date: "Nov 4, 2025", content: "Applicants must demonstrate access to minimum £50K capital for business launch and operations. Accepted sources include personal savings, angel investment, or structured funding.", source: "Home Office", category: "Financial" },
  { id: "19", title: "Endorsement appeal process: 30-day window with 35% success rate on resubmission with new evidence", date: "Nov 3, 2025", content: "Rejected endorsement applicants can appeal within 30 days providing additional evidence. Success rate on appeals approximately 35% with strengthened documentation.", source: "Home Office", category: "Appeals" },
  { id: "20", title: "Founder experience guidance: 3-5 years industry background strongly preferred by endorsing bodies", date: "Nov 2, 2025", content: "While not strictly mandatory, having 3-5+ years relevant industry experience significantly improves endorsement approval probability. Academic credentials also valued.", source: "Tech Nation", category: "Founder" },
  { id: "21", title: "Intellectual Property: Patents and trademarks receive priority consideration in endorsement decisions", date: "Nov 1, 2025", content: "Applications with registered patents, trademarks, or design registrations receive priority ranking. Even pending patent applications strengthen innovative credentials significantly.", source: "Tech Nation", category: "IP" },
  { id: "22", title: "Market Validation: Letters of Intent and customer testimonials now critical for approval", date: "Oct 31, 2025", content: "LOIs from potential customers and pilot program participation significantly strengthen applications. Minimum 2-3 customer validation documents recommended for success.", source: "Endorsing Bodies", category: "Evidence" },
  { id: "23", title: "Competitive Analysis: Mandatory detailed market differentiation assessment now required in all applications", date: "Oct 30, 2025", content: "Updated requirements explicitly mandate competitive landscape analysis showing unique value proposition. Generic competitive claims no longer acceptable.", source: "Home Office", category: "Requirements" },
  { id: "24", title: "Multi-founder teams receive preference: Complementary founder skillsets strengthen applications", date: "Oct 29, 2025", content: "Applications with complementary co-founders (technical + business expertise) outperform solo founder applications. Team composition critical for approval.", source: "Tech Nation", category: "Team" },
  { id: "25", title: "Go-to-Market Strategy: Detailed customer acquisition plan with timelines and CAC models essential", date: "Oct 28, 2025", content: "Applications must include specific, realistic go-to-market strategies with defined customer acquisition channels, timelines, and cost models for sustainability.", source: "Tech Nation", category: "Strategy" },
  { id: "26", title: "Risk Management: Contingency plans addressing market, tech, and operational risks required", date: "Oct 27, 2025", content: "Comprehensive risk assessment addressing key business threats and mitigation strategies demonstrates operational credibility with endorsing bodies.", source: "Home Office", category: "Risk" },
  { id: "27", title: "Scalability Roadmap: International expansion plan within 3 years essential for innovation criteria", date: "Oct 26, 2025", content: "Innovation Visa criteria require demonstrating scalability potential with geographic expansion roadmap. UK-only business models face significantly lower approval rates.", source: "Home Office", category: "Scalability" },
  { id: "28", title: "Technology Stack Documentation: Proprietary tech or open-source architecture must be clearly articulated", date: "Oct 25, 2025", content: "Applications must document technology strategy, whether built on proprietary systems or open-source frameworks. Technology innovation or efficiency differentiation must be clear.", source: "Tech Nation", category: "Technology" },
  { id: "29", title: "Revenue Model: SaaS, licensing, or marketplace models with realistic unit economics required", date: "Oct 24, 2025", content: "Financial projections must include clear revenue model specification with realistic unit economics and gross margin projections for long-term sustainability.", source: "Home Office", category: "Financial" },
  { id: "30", title: "Regulatory Compliance: Sector-specific regulations and licensing roadmaps mandatory for regulated industries", date: "Oct 23, 2025", content: "Applications in regulated sectors (fintech, healthcare, energy) must demonstrate full regulatory compliance strategy. Regulatory risk mitigation required.", source: "Home Office", category: "Compliance" },
  { id: "31", title: "Document Checklist: 15+ supporting documents required for complete Innovation Visa application", date: "Oct 22, 2025", content: "Standard applications require business plan, founder CVs, bank statements, customer LOIs, IP documentation, and comprehensive supporting evidence portfolio.", source: "Home Office", category: "Documentation" },
  { id: "32", title: "Endorsement Feedback: Detailed rejection explanations now provided enabling reapplication strategy", date: "Oct 21, 2025", content: "Endorsing bodies now required to provide detailed feedback explaining specific rejection reasons, enabling applicants to address gaps in reapplication or appeal.", source: "Home Office", category: "Process" },
  { id: "33", title: "Expedited Processing: £500 fee enables 5-7 business day priority processing timeline", date: "Oct 20, 2025", content: "Priority processing available for urgent Innovation Visa applications, reducing standard 2-3 week timeline to 5-7 business days for additional processing fee.", source: "Home Office", category: "Processing" },
  { id: "34", title: "Entrepreneurial Track Record: Previous startup experience significantly improves endorsement probability", date: "Oct 19, 2025", content: "Founders demonstrating previous entrepreneurial success significantly improve endorsement chances. Serial entrepreneurs and repeat founders highly favored.", source: "Tech Nation", category: "Background" },
  { id: "35", title: "Academic Credentials: PhD and advanced degree holders receive favorable consideration boost", date: "Oct 18, 2025", content: "Applicants with PhD, Master's degrees, or specialized technical certifications receive meaningful consideration advantage, particularly for deep-tech innovations.", source: "Tech Nation", category: "Education" },
  { id: "36", title: "Global Partnerships: International customer base and expansion plans strengthen applications", date: "Oct 17, 2025", content: "Companies with existing international partnerships, global customer base, or credible expansion plans viewed favorably. Geographic diversification preferred.", source: "Home Office", category: "Global" },
  { id: "37", title: "ESG Commitments: Environmental and governance initiatives increasingly considered in assessment", date: "Oct 16, 2025", content: "Environmental, social, and governance commitments increasingly valued. Clear sustainability and governance roadmaps receive favorable consideration.", source: "Department for Business", category: "ESG" },
  { id: "38", title: "Diversity & Inclusion: Women founders and underrepresented groups receive mentorship support", date: "Oct 15, 2025", content: "UK government prioritizes supporting diverse founder teams. Women entrepreneurs and underrepresented groups access additional mentorship and support programs.", source: "Tech Nation", category: "Diversity" },
  { id: "39", title: "Mentor Network: Industry advisors and experienced mentors strengthen application credibility significantly", date: "Oct 14, 2025", content: "Having credible mentors or experienced advisors significantly strengthens applications. Advisory board with relevant industry expertise highly valuable.", source: "Endorsing Bodies", category: "Advisors" },
  { id: "40", title: "Social Impact: Community benefit and societal challenge initiatives improve endorsement prospects", date: "Oct 13, 2025", content: "Companies addressing healthcare, education, accessibility, or environmental challenges receive favorable consideration. Clear community impact roadmap beneficial.", source: "Tech Nation", category: "Impact" },
  { id: "41", title: "Beta Testing: Active user engagement and real-world testing significantly strengthens applications", date: "Oct 12, 2025", content: "Active beta testing with real users substantially strengthens application credibility. User feedback and engagement metrics should be documented.", source: "Tech Nation", category: "Evidence" },
  { id: "42", title: "Media Coverage: Press releases and third-party validation through industry coverage valued", date: "Oct 11, 2025", content: "Press coverage, media mentions, and industry recognition all strengthen applications. Third-party validation of innovation claims highly valuable.", source: "Endorsing Bodies", category: "Validation" },
  { id: "43", title: "Awards Recognition: Industry awards and pitch competition victories enhance credibility", date: "Oct 10, 2025", content: "Winning industry awards, startup pitch competitions, or innovation challenges significantly strengthen applications through third-party recognition.", source: "Tech Nation", category: "Recognition" },
  { id: "44", title: "Funding Secured: Pre-seed, seed funding, or grants demonstrate investor confidence and viability", date: "Oct 9, 2025", content: "Evidence of secured funding including angel investment, seed rounds, or government grants significantly improves viability assessment credibility.", source: "Endorsing Bodies", category: "Funding" },
  { id: "45", title: "Growth Metrics: Existing startups must demonstrate 20%+ month-on-month growth for strong traction", date: "Oct 8, 2025", content: "For existing ventures, documented growth metrics (revenue, users, engagement) of 20%+ monthly constitutes strong traction. Consistent growth trajectory critical.", source: "Tech Nation", category: "Growth" },
  { id: "46", title: "UK Presence: Establishing UK office before visa approval demonstrates commitment", date: "Oct 7, 2025", content: "Having UK office space, UK business bank account, and UK team members before visa approval strengthens commitment demonstration. Infrastructure setup valuable.", source: "Home Office", category: "Setup" },
  { id: "47", title: "Tax Planning: UK tax residency and corporate structure planning essential for compliance", date: "Oct 6, 2025", content: "Proper tax planning including UK corporate structure and tax residency status required. Professional tax advisor consultation strongly recommended.", source: "UK Tax Authority", category: "Legal" },
  { id: "48", title: "Bank Account: UK business banking established pre-visa demonstrates serious business intent", date: "Oct 5, 2025", content: "UK business bank account setup demonstrates serious intent and enables transaction documentation. Some banks allow pre-visa account opening.", source: "UK Banks", category: "Setup" },
  { id: "49", title: "Professional Insurance: Liability and IP insurance policies strengthen professional business approach", date: "Oct 4, 2025", content: "Professional insurance and legal entity incorporation demonstrate professional business operations. Limited company structure strongly preferred.", source: "Endorsing Bodies", category: "Legal" },
  { id: "50", title: "Annual Compliance: Visa holders must confirm annual innovation requirement compliance", date: "Oct 3, 2025", content: "Innovation Visa holders required to confirm ongoing innovation compliance annually. Failure to meet conditions could result in visa revocation.", source: "Home Office", category: "Compliance" },
  { id: "51", title: "Career Options: Post-visa employment sponsorship routes and ILR pathways available", date: "Oct 2, 2025", content: "After Innovation Visa, multiple career paths available including standard employment sponsorship, ILR settlement, or continued entrepreneurship.", source: "Home Office", category: "Career" },
  { id: "52", title: "Case Studies: 50+ approved applications published by Home Office for reference and guidance", date: "Oct 1, 2025", content: "Home Office published comprehensive case studies of successful Innovation Visa applications across industries, sectors, and founder backgrounds for learning.", source: "Home Office", category: "Resources" }
];

let newsCache: NewsItem[] = [...INITIAL_NEWS];
let lastUpdateTime = Date.now();

export async function getLatestNews(): Promise<NewsItem[]> {
  return newsCache;
}

export async function addNews(newItem: NewsItem): Promise<NewsItem[]> {
  if (newsCache.length >= 50) {
    newsCache = newsCache.slice(1);
  }
  newsCache = [newItem, ...newsCache];
  lastUpdateTime = Date.now();
  return newsCache;
}

export function getNewsUpdateTime(): number {
  return lastUpdateTime;
}
