const translations: Record<string, Record<string, string>> = {
  es: {
    "Long-term & Business Residence":"Residencia de larga duración y negocios",
    "Golden Visa":"Visa Dorada",
    "Long-term residence for qualifying investors, entrepreneurs, exceptional talent, scientists, students and other eligible categories.":"Residencia de larga duración para inversores, emprendedores, talentos excepcionales, científicos, estudiantes y otras categorías elegibles.",
    "Green Visa – skilled worker":"Visa Verde – trabajador cualificado",
    "Five-year self-sponsored residence for qualifying skilled workers.":"Residencia de cinco años con autopatrocinio para trabajadores cualificados que cumplan los requisitos.",
    "Green Visa – freelancer / self-employed":"Visa Verde – freelance / trabajador por cuenta propia",
    "Five-year self-sponsored residence for eligible freelancers and self-employed people.":"Residencia de cinco años con autopatrocinio para freelancers y trabajadores por cuenta propia elegibles.",
    "Green Visa – investor / business partner":"Visa Verde – inversor / socio empresarial",
    "Residence for qualifying investors and business partners.":"Residencia para inversores y socios empresariales que cumplan los requisitos.",
    "Investor / partner residence":"Residencia para inversor / socio",
    "Business-owner and investor residence options under applicable emirate/federal rules.":"Opciones de residencia para propietarios de empresas e inversores conforme a las normas aplicables del emirato o federales.",
    "Blue Visa":"Visa Azul",
    "Long-term residence for qualifying environmental contributors.":"Residencia de larga duración para personas que contribuyan al medioambiente y cumplan los requisitos.",
    "Work & Remote":"Trabajo y trabajo remoto",
    "Standard Work Visa":"Visa de trabajo estándar",
    "Employer-sponsored government or private-sector employment.":"Empleo en el sector público o privado patrocinado por un empleador.",
    "Domestic Worker Visa":"Visa de trabajador doméstico",
    "Residence and work for eligible domestic workers.":"Residencia y trabajo para trabajadores domésticos elegibles.",
    "Virtual Work Residence Visa":"Visa de Residencia para Trabajo Virtual",
    "Live in the UAE while working remotely for an overseas organisation.":"Residir en los EAU mientras se trabaja de forma remota para una organización extranjera.",
    "Jobseeker Visit Visa":"Visa de visita para búsqueda de empleo",
    "Visit to explore employment opportunities.":"Visita para explorar oportunidades de empleo.",
    "Visit Visa to Explore Business Opportunities":"Visa de visita para explorar oportunidades de negocio",
    "Visit to explore investment or business opportunities.":"Visita para explorar oportunidades de inversión o negocio.",
    "Study & Family":"Estudios y familia",
    "Student Visa":"Visa de estudiante",
    "Residence for study under parent or accredited institution sponsorship.":"Residencia para estudios bajo patrocinio de un progenitor o institución acreditada.",
    "Family Residence Visa":"Visa de residencia familiar",
    "Residence for qualifying family members of residents.":"Residencia para familiares elegibles de residentes.",
    "Residence for families of university students":"Residencia para familias de estudiantes universitarios",
    "Qualifying family residence connected to a student.":"Residencia familiar vinculada a un estudiante que cumpla los requisitos.",
    "Retirement Residence":"Residencia de jubilación",
    "Residence for eligible retirees.":"Residencia para jubilados elegibles.",
    "Visit & Transit":"Visita y tránsito",
    "Tourist Visa":"Visa de turista",
    "Tourism visit permission.":"Permiso de visita por turismo.",
    "Visit Visa":"Visa de visita",
    "Family, friends and other eligible visit purposes.":"Visitas a familiares, amigos y otros fines de visita elegibles.",
    "Transit Visa":"Visa de tránsito",
    "Transit permission, including applicable 48/96-hour arrangements.":"Permiso de tránsito, incluidos los regímenes aplicables de 48/96 horas.",
    "Medical Visa / Patient Entry Permit":"Visa médica / permiso de entrada para pacientes",
    "Entry for qualifying medical treatment.":"Entrada para recibir tratamiento médico que cumpla los requisitos.",
    "Multiple-entry visit options":"Opciones de visita de entradas múltiples",
    "Longer or repeated visit permissions where eligibility rules are met.":"Permisos para visitas más largas o repetidas cuando se cumplen las normas de elegibilidad."
  },
  fr: {
    "Long-term & Business Residence":"Résidence de longue durée et affaires",
    "Golden Visa":"Visa doré",
    "Long-term residence for qualifying investors, entrepreneurs, exceptional talent, scientists, students and other eligible categories.":"Résidence de longue durée pour investisseurs, entrepreneurs, talents exceptionnels, scientifiques, étudiants et autres catégories admissibles.",
    "Green Visa – skilled worker":"Visa vert – travailleur qualifié",
    "Five-year self-sponsored residence for qualifying skilled workers.":"Résidence de cinq ans avec auto-parrainage pour travailleurs qualifiés admissibles.",
    "Green Visa – freelancer / self-employed":"Visa vert – freelance / indépendant",
    "Five-year self-sponsored residence for eligible freelancers and self-employed people.":"Résidence de cinq ans avec auto-parrainage pour freelances et indépendants admissibles.",
    "Green Visa – investor / business partner":"Visa vert – investisseur / associé d’entreprise",
    "Residence for qualifying investors and business partners.":"Résidence pour investisseurs et associés d’entreprise admissibles.",
    "Investor / partner residence":"Résidence investisseur / associé",
    "Business-owner and investor residence options under applicable emirate/federal rules.":"Options de résidence pour propriétaires d’entreprise et investisseurs selon les règles applicables de l’émirat ou fédérales.",
    "Blue Visa":"Visa bleu",
    "Long-term residence for qualifying environmental contributors.":"Résidence de longue durée pour les personnes contribuant à l’environnement et répondant aux critères.",
    "Work & Remote":"Travail et télétravail",
    "Standard Work Visa":"Visa de travail standard",
    "Employer-sponsored government or private-sector employment.":"Emploi dans le secteur public ou privé parrainé par un employeur.",
    "Domestic Worker Visa":"Visa de travailleur domestique",
    "Residence and work for eligible domestic workers.":"Résidence et travail pour travailleurs domestiques admissibles.",
    "Virtual Work Residence Visa":"Visa de résidence pour travail virtuel",
    "Live in the UAE while working remotely for an overseas organisation.":"Résider aux EAU tout en travaillant à distance pour une organisation à l’étranger.",
    "Jobseeker Visit Visa":"Visa de visite pour recherche d’emploi",
    "Visit to explore employment opportunities.":"Visite destinée à explorer des possibilités d’emploi.",
    "Visit Visa to Explore Business Opportunities":"Visa de visite pour explorer des opportunités d’affaires",
    "Visit to explore investment or business opportunities.":"Visite pour explorer des possibilités d’investissement ou d’affaires.",
    "Study & Family":"Études et famille",
    "Student Visa":"Visa étudiant",
    "Residence for study under parent or accredited institution sponsorship.":"Résidence pour études sous parrainage d’un parent ou d’un établissement agréé.",
    "Family Residence Visa":"Visa de résidence familiale",
    "Residence for qualifying family members of residents.":"Résidence pour les membres de famille admissibles de résidents.",
    "Residence for families of university students":"Résidence pour les familles d’étudiants universitaires",
    "Qualifying family residence connected to a student.":"Résidence familiale admissible liée à un étudiant.",
    "Retirement Residence":"Résidence de retraite",
    "Residence for eligible retirees.":"Résidence pour retraités admissibles.",
    "Visit & Transit":"Visite et transit",
    "Tourist Visa":"Visa touristique",
    "Tourism visit permission.":"Autorisation de visite touristique.",
    "Visit Visa":"Visa de visite",
    "Family, friends and other eligible visit purposes.":"Visites à la famille, aux amis et autres motifs de visite admissibles.",
    "Transit Visa":"Visa de transit",
    "Transit permission, including applicable 48/96-hour arrangements.":"Autorisation de transit, y compris les dispositifs applicables de 48/96 heures.",
    "Medical Visa / Patient Entry Permit":"Visa médical / permis d’entrée pour patient",
    "Entry for qualifying medical treatment.":"Entrée pour un traitement médical admissible.",
    "Multiple-entry visit options":"Options de visite à entrées multiples",
    "Longer or repeated visit permissions where eligibility rules are met.":"Autorisations pour des visites plus longues ou répétées lorsque les critères sont remplis."
  },
  de: {
    "Long-term & Business Residence":"Langfristiger Aufenthalt und Geschäftsaufenthalt",
    "Golden Visa":"Golden Visa",
    "Long-term residence for qualifying investors, entrepreneurs, exceptional talent, scientists, students and other eligible categories.":"Langfristiger Aufenthalt für berechtigte Investoren, Unternehmer, außergewöhnliche Talente, Wissenschaftler, Studierende und weitere berechtigte Kategorien.",
    "Green Visa – skilled worker":"Green Visa – Fachkraft",
    "Five-year self-sponsored residence for qualifying skilled workers.":"Fünfjähriger eigenständig gesponserter Aufenthalt für berechtigte Fachkräfte.",
    "Green Visa – freelancer / self-employed":"Green Visa – Freelancer / Selbstständige",
    "Five-year self-sponsored residence for eligible freelancers and self-employed people.":"Fünfjähriger eigenständig gesponserter Aufenthalt für berechtigte Freelancer und Selbstständige.",
    "Green Visa – investor / business partner":"Green Visa – Investor / Geschäftspartner",
    "Residence for qualifying investors and business partners.":"Aufenthalt für berechtigte Investoren und Geschäftspartner.",
    "Investor / partner residence":"Aufenthalt für Investoren / Partner",
    "Business-owner and investor residence options under applicable emirate/federal rules.":"Aufenthaltsmöglichkeiten für Unternehmensinhaber und Investoren nach den geltenden emiratischen bzw. bundesweiten Regeln.",
    "Blue Visa":"Blue Visa",
    "Long-term residence for qualifying environmental contributors.":"Langfristiger Aufenthalt für berechtigte Personen mit bedeutendem Umweltbeitrag.",
    "Work & Remote":"Arbeit und Remote-Arbeit",
    "Standard Work Visa":"Standard-Arbeitsvisum",
    "Employer-sponsored government or private-sector employment.":"Arbeitgebergesponserte Beschäftigung im öffentlichen oder privaten Sektor.",
    "Domestic Worker Visa":"Visum für Hausangestellte",
    "Residence and work for eligible domestic workers.":"Aufenthalt und Arbeit für berechtigte Hausangestellte.",
    "Virtual Work Residence Visa":"Aufenthaltsvisum für virtuelle Arbeit",
    "Live in the UAE while working remotely for an overseas organisation.":"In den VAE leben und gleichzeitig remote für eine ausländische Organisation arbeiten.",
    "Jobseeker Visit Visa":"Besuchsvisum zur Arbeitssuche",
    "Visit to explore employment opportunities.":"Besuch zur Erkundung von Beschäftigungsmöglichkeiten.",
    "Visit Visa to Explore Business Opportunities":"Besuchsvisum zur Erkundung von Geschäftsmöglichkeiten",
    "Visit to explore investment or business opportunities.":"Besuch zur Erkundung von Investitions- oder Geschäftsmöglichkeiten.",
    "Study & Family":"Studium und Familie",
    "Student Visa":"Studentenvisum",
    "Residence for study under parent or accredited institution sponsorship.":"Aufenthalt zum Studium unter Sponsoring eines Elternteils oder einer akkreditierten Einrichtung.",
    "Family Residence Visa":"Familienaufenthaltsvisum",
    "Residence for qualifying family members of residents.":"Aufenthalt für berechtigte Familienangehörige von Einwohnern.",
    "Residence for families of university students":"Aufenthalt für Familien von Universitätsstudierenden",
    "Qualifying family residence connected to a student.":"Berechtigter Familienaufenthalt in Verbindung mit einem Studierenden.",
    "Retirement Residence":"Aufenthalt im Ruhestand",
    "Residence for eligible retirees.":"Aufenthalt für berechtigte Ruheständler.",
    "Visit & Transit":"Besuch und Transit",
    "Tourist Visa":"Touristenvisum",
    "Tourism visit permission.":"Besuchserlaubnis für touristische Zwecke.",
    "Visit Visa":"Besuchsvisum",
    "Family, friends and other eligible visit purposes.":"Familien-, Freundesbesuche und andere berechtigte Besuchszwecke.",
    "Transit Visa":"Transitvisum",
    "Transit permission, including applicable 48/96-hour arrangements.":"Transitgenehmigung einschließlich anwendbarer 48-/96-Stunden-Regelungen.",
    "Medical Visa / Patient Entry Permit":"Medizinvisum / Einreisegenehmigung für Patienten",
    "Entry for qualifying medical treatment.":"Einreise für berechtigte medizinische Behandlung.",
    "Multiple-entry visit options":"Besuchsoptionen mit mehrfacher Einreise",
    "Longer or repeated visit permissions where eligibility rules are met.":"Erlaubnisse für längere oder wiederholte Besuche, wenn die Voraussetzungen erfüllt sind."
  },
  zh: {
    "Long-term & Business Residence":"长期与商业居留",
    "Golden Visa":"黄金签证",
    "Long-term residence for qualifying investors, entrepreneurs, exceptional talent, scientists, students and other eligible categories.":"面向符合条件的投资者、企业家、杰出人才、科学家、学生及其他合资格类别的长期居留。",
    "Green Visa – skilled worker":"绿色签证 – 技能工人",
    "Five-year self-sponsored residence for qualifying skilled workers.":"面向符合条件技能工人的五年自主担保居留。",
    "Green Visa – freelancer / self-employed":"绿色签证 – 自由职业者 / 自雇人士",
    "Five-year self-sponsored residence for eligible freelancers and self-employed people.":"面向符合条件自由职业者和自雇人士的五年自主担保居留。",
    "Green Visa – investor / business partner":"绿色签证 – 投资者 / 商业伙伴",
    "Residence for qualifying investors and business partners.":"面向符合条件投资者和商业伙伴的居留。",
    "Investor / partner residence":"投资者 / 合伙人居留",
    "Business-owner and investor residence options under applicable emirate/federal rules.":"依据适用酋长国或联邦规则提供的企业主及投资者居留选择。",
    "Blue Visa":"蓝色签证",
    "Long-term residence for qualifying environmental contributors.":"面向符合条件环境贡献者的长期居留。",
    "Work & Remote":"工作与远程工作",
    "Standard Work Visa":"标准工作签证",
    "Employer-sponsored government or private-sector employment.":"由雇主担保的政府或私营部门就业。",
    "Domestic Worker Visa":"家政工人签证",
    "Residence and work for eligible domestic workers.":"面向符合条件家政工人的居留和工作许可。",
    "Virtual Work Residence Visa":"虚拟工作居留签证",
    "Live in the UAE while working remotely for an overseas organisation.":"居住在阿联酋，同时远程为境外机构工作。",
    "Jobseeker Visit Visa":"求职访问签证",
    "Visit to explore employment opportunities.":"用于探索就业机会的访问。",
    "Visit Visa to Explore Business Opportunities":"探索商业机会访问签证",
    "Visit to explore investment or business opportunities.":"用于探索投资或商业机会的访问。",
    "Study & Family":"学习与家庭",
    "Student Visa":"学生签证",
    "Residence for study under parent or accredited institution sponsorship.":"在父母或获认可教育机构担保下用于学习的居留。",
    "Family Residence Visa":"家庭居留签证",
    "Residence for qualifying family members of residents.":"面向符合条件居民家庭成员的居留。",
    "Residence for families of university students":"大学生家庭居留",
    "Qualifying family residence connected to a student.":"与学生身份相关、符合条件的家庭居留。",
    "Retirement Residence":"退休居留",
    "Residence for eligible retirees.":"面向符合条件退休人士的居留。",
    "Visit & Transit":"访问与过境",
    "Tourist Visa":"旅游签证",
    "Tourism visit permission.":"用于旅游访问的许可。",
    "Visit Visa":"访问签证",
    "Family, friends and other eligible visit purposes.":"探访家人、朋友及其他符合条件的访问目的。",
    "Transit Visa":"过境签证",
    "Transit permission, including applicable 48/96-hour arrangements.":"过境许可，包括适用的 48/96 小时安排。",
    "Medical Visa / Patient Entry Permit":"医疗签证 / 患者入境许可",
    "Entry for qualifying medical treatment.":"因符合条件的医疗治疗而入境。",
    "Multiple-entry visit options":"多次入境访问选项",
    "Longer or repeated visit permissions where eligibility rules are met.":"在符合资格规则时可获得更长期或多次访问许可。"
  },
  ar: {
    "Long-term & Business Residence":"الإقامة طويلة الأجل وإقامة الأعمال",
    "Golden Visa":"التأشيرة الذهبية",
    "Long-term residence for qualifying investors, entrepreneurs, exceptional talent, scientists, students and other eligible categories.":"إقامة طويلة الأجل للمستثمرين ورواد الأعمال وأصحاب المواهب الاستثنائية والعلماء والطلاب والفئات الأخرى المستوفية للشروط.",
    "Green Visa – skilled worker":"التأشيرة الخضراء – عامل ماهر",
    "Five-year self-sponsored residence for qualifying skilled workers.":"إقامة لمدة خمس سنوات بكفالة ذاتية للعمال المهرة المستوفين للشروط.",
    "Green Visa – freelancer / self-employed":"التأشيرة الخضراء – مستقل / عامل لحسابه الخاص",
    "Five-year self-sponsored residence for eligible freelancers and self-employed people.":"إقامة لمدة خمس سنوات بكفالة ذاتية للمستقلين والعاملين لحسابهم الخاص المؤهلين.",
    "Green Visa – investor / business partner":"التأشيرة الخضراء – مستثمر / شريك تجاري",
    "Residence for qualifying investors and business partners.":"إقامة للمستثمرين والشركاء التجاريين المستوفين للشروط.",
    "Investor / partner residence":"إقامة المستثمر / الشريك",
    "Business-owner and investor residence options under applicable emirate/federal rules.":"خيارات إقامة لأصحاب الأعمال والمستثمرين وفق القواعد المحلية أو الاتحادية المطبقة.",
    "Blue Visa":"التأشيرة الزرقاء",
    "Long-term residence for qualifying environmental contributors.":"إقامة طويلة الأجل للمساهمين في المجال البيئي المستوفين للشروط.",
    "Work & Remote":"العمل والعمل عن بعد",
    "Standard Work Visa":"تأشيرة العمل القياسية",
    "Employer-sponsored government or private-sector employment.":"عمل في القطاع الحكومي أو الخاص برعاية صاحب عمل.",
    "Domestic Worker Visa":"تأشيرة العامل المنزلي",
    "Residence and work for eligible domestic workers.":"إقامة وعمل للعمال المنزليين المؤهلين.",
    "Virtual Work Residence Visa":"تأشيرة إقامة للعمل الافتراضي",
    "Live in the UAE while working remotely for an overseas organisation.":"الإقامة في الإمارات أثناء العمل عن بعد لدى جهة خارج الدولة.",
    "Jobseeker Visit Visa":"تأشيرة زيارة للباحث عن عمل",
    "Visit to explore employment opportunities.":"زيارة لاستكشاف فرص العمل.",
    "Visit Visa to Explore Business Opportunities":"تأشيرة زيارة لاستكشاف فرص الأعمال",
    "Visit to explore investment or business opportunities.":"زيارة لاستكشاف فرص الاستثمار أو الأعمال.",
    "Study & Family":"الدراسة والأسرة",
    "Student Visa":"تأشيرة الطالب",
    "Residence for study under parent or accredited institution sponsorship.":"إقامة للدراسة بكفالة أحد الوالدين أو مؤسسة معتمدة.",
    "Family Residence Visa":"تأشيرة إقامة الأسرة",
    "Residence for qualifying family members of residents.":"إقامة لأفراد أسرة المقيمين المستوفين للشروط.",
    "Residence for families of university students":"إقامة لأسر طلاب الجامعات",
    "Qualifying family residence connected to a student.":"إقامة أسرية مستوفية للشروط مرتبطة بطالب.",
    "Retirement Residence":"إقامة التقاعد",
    "Residence for eligible retirees.":"إقامة للمتقاعدين المؤهلين.",
    "Visit & Transit":"الزيارة والعبور",
    "Tourist Visa":"تأشيرة سياحية",
    "Tourism visit permission.":"إذن زيارة لأغراض السياحة.",
    "Visit Visa":"تأشيرة زيارة",
    "Family, friends and other eligible visit purposes.":"زيارة الأسرة والأصدقاء وأغراض زيارة أخرى مؤهلة.",
    "Transit Visa":"تأشيرة عبور",
    "Transit permission, including applicable 48/96-hour arrangements.":"إذن عبور، بما في ذلك ترتيبات 48/96 ساعة المطبقة.",
    "Medical Visa / Patient Entry Permit":"تأشيرة طبية / تصريح دخول مريض",
    "Entry for qualifying medical treatment.":"دخول لتلقي علاج طبي مستوفٍ للشروط.",
    "Multiple-entry visit options":"خيارات زيارة متعددة الدخول",
    "Longer or repeated visit permissions where eligibility rules are met.":"تصاريح لزيارات أطول أو متكررة عند استيفاء قواعد الأهلية."
  },
  pt: {
    "Long-term & Business Residence":"Residência de longa duração e negócios",
    "Golden Visa":"Visto Dourado",
    "Long-term residence for qualifying investors, entrepreneurs, exceptional talent, scientists, students and other eligible categories.":"Residência de longa duração para investidores, empreendedores, talentos excecionais, cientistas, estudantes e outras categorias elegíveis.",
    "Green Visa – skilled worker":"Visto Verde – trabalhador qualificado",
    "Five-year self-sponsored residence for qualifying skilled workers.":"Residência de cinco anos com autopatrocínio para trabalhadores qualificados elegíveis.",
    "Green Visa – freelancer / self-employed":"Visto Verde – freelancer / trabalhador independente",
    "Five-year self-sponsored residence for eligible freelancers and self-employed people.":"Residência de cinco anos com autopatrocínio para freelancers e trabalhadores independentes elegíveis.",
    "Green Visa – investor / business partner":"Visto Verde – investidor / parceiro de negócios",
    "Residence for qualifying investors and business partners.":"Residência para investidores e parceiros de negócios elegíveis.",
    "Investor / partner residence":"Residência para investidor / parceiro",
    "Business-owner and investor residence options under applicable emirate/federal rules.":"Opções de residência para proprietários de empresas e investidores segundo as regras aplicáveis do emirado ou federais.",
    "Blue Visa":"Visto Azul",
    "Long-term residence for qualifying environmental contributors.":"Residência de longa duração para pessoas com contributos ambientais elegíveis.",
    "Work & Remote":"Trabalho e trabalho remoto",
    "Standard Work Visa":"Visto de trabalho padrão",
    "Employer-sponsored government or private-sector employment.":"Emprego no setor público ou privado patrocinado por empregador.",
    "Domestic Worker Visa":"Visto de trabalhador doméstico",
    "Residence and work for eligible domestic workers.":"Residência e trabalho para trabalhadores domésticos elegíveis.",
    "Virtual Work Residence Visa":"Visto de residência para trabalho virtual",
    "Live in the UAE while working remotely for an overseas organisation.":"Viver nos EAU enquanto trabalha remotamente para uma organização no estrangeiro.",
    "Jobseeker Visit Visa":"Visto de visita para procura de emprego",
    "Visit to explore employment opportunities.":"Visita para explorar oportunidades de emprego.",
    "Visit Visa to Explore Business Opportunities":"Visto de visita para explorar oportunidades de negócio",
    "Visit to explore investment or business opportunities.":"Visita para explorar oportunidades de investimento ou negócio.",
    "Study & Family":"Estudo e família",
    "Student Visa":"Visto de estudante",
    "Residence for study under parent or accredited institution sponsorship.":"Residência para estudo sob patrocínio de um progenitor ou instituição acreditada.",
    "Family Residence Visa":"Visto de residência familiar",
    "Residence for qualifying family members of residents.":"Residência para familiares elegíveis de residentes.",
    "Residence for families of university students":"Residência para famílias de estudantes universitários",
    "Qualifying family residence connected to a student.":"Residência familiar elegível associada a um estudante.",
    "Retirement Residence":"Residência de reforma",
    "Residence for eligible retirees.":"Residência para reformados elegíveis.",
    "Visit & Transit":"Visita e trânsito",
    "Tourist Visa":"Visto de turista",
    "Tourism visit permission.":"Autorização de visita para turismo.",
    "Visit Visa":"Visto de visita",
    "Family, friends and other eligible visit purposes.":"Visitas a família, amigos e outros fins de visita elegíveis.",
    "Transit Visa":"Visto de trânsito",
    "Transit permission, including applicable 48/96-hour arrangements.":"Autorização de trânsito, incluindo regimes aplicáveis de 48/96 horas.",
    "Medical Visa / Patient Entry Permit":"Visto médico / autorização de entrada para paciente",
    "Entry for qualifying medical treatment.":"Entrada para tratamento médico elegível.",
    "Multiple-entry visit options":"Opções de visita de múltiplas entradas",
    "Longer or repeated visit permissions where eligibility rules are met.":"Autorizações para visitas mais longas ou repetidas quando as regras de elegibilidade são cumpridas."
  },
  ja: {
    "Long-term & Business Residence":"長期・ビジネス居住",
    "Golden Visa":"ゴールデン・ビザ",
    "Long-term residence for qualifying investors, entrepreneurs, exceptional talent, scientists, students and other eligible categories.":"要件を満たす投資家、起業家、卓越した人材、科学者、学生、その他対象カテゴリー向けの長期居住。",
    "Green Visa – skilled worker":"グリーン・ビザ – 技能労働者",
    "Five-year self-sponsored residence for qualifying skilled workers.":"要件を満たす技能労働者向けの5年間の自己スポンサー居住。",
    "Green Visa – freelancer / self-employed":"グリーン・ビザ – フリーランサー / 自営業",
    "Five-year self-sponsored residence for eligible freelancers and self-employed people.":"要件を満たすフリーランサー・自営業者向けの5年間の自己スポンサー居住。",
    "Green Visa – investor / business partner":"グリーン・ビザ – 投資家 / ビジネスパートナー",
    "Residence for qualifying investors and business partners.":"要件を満たす投資家・ビジネスパートナー向けの居住。",
    "Investor / partner residence":"投資家 / パートナー居住",
    "Business-owner and investor residence options under applicable emirate/federal rules.":"適用される首長国または連邦規則に基づく事業主・投資家向けの居住選択肢。",
    "Blue Visa":"ブルー・ビザ",
    "Long-term residence for qualifying environmental contributors.":"要件を満たす環境分野への貢献者向けの長期居住。",
    "Work & Remote":"就労・リモートワーク",
    "Standard Work Visa":"標準就労ビザ",
    "Employer-sponsored government or private-sector employment.":"雇用主スポンサーによる政府機関または民間部門での雇用。",
    "Domestic Worker Visa":"家事労働者ビザ",
    "Residence and work for eligible domestic workers.":"要件を満たす家事労働者向けの居住・就労。",
    "Virtual Work Residence Visa":"バーチャルワーク居住ビザ",
    "Live in the UAE while working remotely for an overseas organisation.":"海外の組織でリモート勤務しながらUAEに居住するための制度。",
    "Jobseeker Visit Visa":"求職者訪問ビザ",
    "Visit to explore employment opportunities.":"雇用機会を探すための訪問。",
    "Visit Visa to Explore Business Opportunities":"ビジネス機会探索訪問ビザ",
    "Visit to explore investment or business opportunities.":"投資・ビジネス機会を探すための訪問。",
    "Study & Family":"留学・家族",
    "Student Visa":"学生ビザ",
    "Residence for study under parent or accredited institution sponsorship.":"親または認定教育機関のスポンサーによる就学居住。",
    "Family Residence Visa":"家族居住ビザ",
    "Residence for qualifying family members of residents.":"居住者の要件を満たす家族向けの居住。",
    "Residence for families of university students":"大学生の家族向け居住",
    "Qualifying family residence connected to a student.":"学生に関連する要件を満たす家族居住。",
    "Retirement Residence":"退職者居住",
    "Residence for eligible retirees.":"要件を満たす退職者向けの居住。",
    "Visit & Transit":"訪問・乗り継ぎ",
    "Tourist Visa":"観光ビザ",
    "Tourism visit permission.":"観光目的の訪問許可。",
    "Visit Visa":"訪問ビザ",
    "Family, friends and other eligible visit purposes.":"家族・友人訪問など、要件を満たす訪問目的。",
    "Transit Visa":"通過ビザ",
    "Transit permission, including applicable 48/96-hour arrangements.":"適用される48/96時間制度を含む通過許可。",
    "Medical Visa / Patient Entry Permit":"医療ビザ / 患者入国許可",
    "Entry for qualifying medical treatment.":"要件を満たす医療を受けるための入国。",
    "Multiple-entry visit options":"複数回入国の訪問オプション",
    "Longer or repeated visit permissions where eligibility rules are met.":"資格条件を満たす場合の長期または反復訪問許可。"
  }
};
export default translations;
