const translations: Record<string, Record<string, string>> = {
  es: {
    "Skilled & Employer Work":"Trabajo cualificado y patrocinado por empleador",
    "Skills in Demand (subclass 482)":"Skills in Demand (subclase 482)",
    "Employer-sponsored temporary skilled work.":"Trabajo cualificado temporal patrocinado por un empleador.",
    "Employer Nomination Scheme (186)":"Programa de Nominación por Empleador (186)",
    "Employer-sponsored permanent residence.":"Residencia permanente patrocinada por un empleador.",
    "Skilled Independent (189)":"Trabajador Cualificado Independiente (189)",
    "Points-tested independent skilled migration.":"Migración cualificada independiente evaluada mediante puntos.",
    "Skilled Nominated (190)":"Trabajador Cualificado Nominado (190)",
    "State or territory nominated skilled migration.":"Migración cualificada nominada por un estado o territorio.",
    "Skilled Work Regional (491)":"Trabajo Cualificado Regional (491)",
    "Regional provisional skilled migration.":"Migración cualificada provisional para zonas regionales.",
    "Skilled Employer Sponsored Regional (494)":"Trabajador Cualificado Regional Patrocinado por Empleador (494)",
    "Regional employer sponsorship.":"Patrocinio de empleador en una zona regional.",
    "Permanent Residence Skilled Regional (191)":"Residencia Permanente Cualificada Regional (191)",
    "Permanent residence for eligible regional provisional visa holders.":"Residencia permanente para titulares elegibles de visas regionales provisionales.",
    "Temporary Work Short Stay Specialist (400)":"Trabajo Temporal de Especialista de Corta Duración (400)",
    "Short-term highly specialised work.":"Trabajo altamente especializado de corta duración.",
    "Temporary Activity (408)":"Actividad Temporal (408)",
    "Specified temporary activities.":"Actividades temporales específicas.",
    "International Relations (403)":"Relaciones Internacionales (403)",
    "Work connected to international arrangements.":"Trabajo relacionado con acuerdos internacionales.",
    "National Innovation (858)":"Innovación Nacional (858)",
    "Invitation-based permanent visa for exceptional achievement.":"Visa permanente por invitación para personas con logros excepcionales.",
    "Study & Training":"Estudios y formación",
    "Student (500)":"Estudiante (500)",
    "Full-time study with an eligible provider.":"Estudios a tiempo completo con una institución elegible.",
    "Student Guardian (590)":"Tutor de Estudiante (590)",
    "Guardian for an eligible international student.":"Tutor de un estudiante internacional elegible.",
    "Training (407)":"Formación (407)",
    "Occupational training and professional development.":"Formación ocupacional y desarrollo profesional.",
    "Family":"Familia",
    "Partner visas (820/801, 309/100)":"Visas de pareja (820/801, 309/100)",
    "Partner migration onshore or offshore.":"Migración de pareja dentro o fuera de Australia.",
    "Prospective Marriage (300)":"Matrimonio Futuro (300)",
    "Fiancé(e) pathway.":"Vía para prometido/a.",
    "Parent visas":"Visas para padres",
    "Parent migration categories, including contributory routes.":"Categorías de migración para padres, incluidas las vías contributivas.",
    "Child visas":"Visas para hijos",
    "Eligible dependent, adoption and orphan-relative child categories.":"Categorías para hijos dependientes, adoptados y familiares huérfanos elegibles.",
    "Other family visas":"Otras visas familiares",
    "Remaining relative and carer family categories.":"Otras categorías familiares para parientes y cuidadores.",
    "Visit & Working Holiday":"Visita y Working Holiday",
    "Visitor (600)":"Visitante (600)",
    "Tourism, family and eligible business visitor activity.":"Turismo, visitas familiares y actividades empresariales permitidas para visitantes.",
    "Electronic Travel Authority (601)":"Autorización Electrónica de Viaje (601)",
    "ETA for eligible passport holders.":"ETA para titulares de pasaportes elegibles.",
    "eVisitor (651)":"eVisitor (651)",
    "Visitor permission for eligible passport holders.":"Permiso de visitante para titulares de pasaportes elegibles.",
    "Working Holiday (417)":"Working Holiday (417)",
    "Work and holiday for eligible young adults.":"Trabajo y vacaciones para jóvenes adultos elegibles.",
    "Work and Holiday (462)":"Work and Holiday (462)",
    "Work and holiday for eligible partner-country citizens.":"Trabajo y vacaciones para ciudadanos elegibles de países participantes.",
    "Transit (771)":"Tránsito (771)",
    "Transit through Australia.":"Tránsito por Australia.",
    "Medical Treatment (602)":"Tratamiento Médico (602)",
    "Travel for medical treatment or support.":"Viaje para recibir tratamiento médico o prestar apoyo.",
    "Business, Residence & Humanitarian":"Negocios, residencia y protección humanitaria",
    "Business Innovation and Investment Permanent (888)":"Innovación Empresarial e Inversión Permanente (888)",
    "Permanent stage for eligible legacy business/investment holders.":"Etapa permanente para titulares elegibles de categorías anteriores de negocios/inversión.",
    "Resident Return (155/157)":"Retorno de Residente (155/157)",
    "Travel facility for eligible permanent residents.":"Facilidad de viaje para residentes permanentes elegibles.",
    "Refugee and Humanitarian visas":"Visas de refugiado y humanitarias",
    "Offshore and onshore humanitarian/protection categories.":"Categorías humanitarias y de protección dentro y fuera de Australia.",
    "Bridging visas":"Visas puente",
    "Temporary lawful status while immigration matters are resolved.":"Estatus legal temporal mientras se resuelven asuntos migratorios."
  },
  fr: {
    "Skilled & Employer Work":"Emploi qualifié et parrainé par un employeur",
    "Skills in Demand (subclass 482)":"Skills in Demand (sous-classe 482)",
    "Employer-sponsored temporary skilled work.":"Emploi qualifié temporaire parrainé par un employeur.",
    "Employer Nomination Scheme (186)":"Employer Nomination Scheme (186)",
    "Employer-sponsored permanent residence.":"Résidence permanente parrainée par un employeur.",
    "Skilled Independent (189)":"Travailleur qualifié indépendant (189)",
    "Points-tested independent skilled migration.":"Migration qualifiée indépendante évaluée selon un système de points.",
    "Skilled Nominated (190)":"Travailleur qualifié désigné (190)",
    "State or territory nominated skilled migration.":"Migration qualifiée sur désignation d’un État ou territoire.",
    "Skilled Work Regional (491)":"Travail qualifié régional (491)",
    "Regional provisional skilled migration.":"Migration qualifiée provisoire vers les zones régionales.",
    "Skilled Employer Sponsored Regional (494)":"Travail qualifié régional parrainé par un employeur (494)",
    "Regional employer sponsorship.":"Parrainage par un employeur en zone régionale.",
    "Permanent Residence Skilled Regional (191)":"Résidence permanente qualifiée régionale (191)",
    "Permanent residence for eligible regional provisional visa holders.":"Résidence permanente pour les titulaires admissibles d’un visa régional provisoire.",
    "Temporary Work Short Stay Specialist (400)":"Travail temporaire de spécialiste de courte durée (400)",
    "Short-term highly specialised work.":"Travail hautement spécialisé de courte durée.",
    "Temporary Activity (408)":"Activité temporaire (408)",
    "Specified temporary activities.":"Activités temporaires déterminées.",
    "International Relations (403)":"Relations internationales (403)",
    "Work connected to international arrangements.":"Travail lié à des accords internationaux.",
    "National Innovation (858)":"Innovation nationale (858)",
    "Invitation-based permanent visa for exceptional achievement.":"Visa permanent sur invitation pour des réalisations exceptionnelles.",
    "Study & Training":"Études et formation",
    "Student (500)":"Étudiant (500)",
    "Full-time study with an eligible provider.":"Études à temps plein auprès d’un établissement admissible.",
    "Student Guardian (590)":"Tuteur d’étudiant (590)",
    "Guardian for an eligible international student.":"Tuteur d’un étudiant international admissible.",
    "Training (407)":"Formation (407)",
    "Occupational training and professional development.":"Formation professionnelle et développement des compétences.",
    "Family":"Famille",
    "Partner visas (820/801, 309/100)":"Visas de partenaire (820/801, 309/100)",
    "Partner migration onshore or offshore.":"Migration de partenaire depuis l’Australie ou l’étranger.",
    "Prospective Marriage (300)":"Mariage prévu (300)",
    "Fiancé(e) pathway.":"Voie pour fiancé(e).",
    "Parent visas":"Visas pour parents",
    "Parent migration categories, including contributory routes.":"Catégories de migration pour parents, y compris les voies contributives.",
    "Child visas":"Visas pour enfants",
    "Eligible dependent, adoption and orphan-relative child categories.":"Catégories admissibles pour enfants à charge, adoptés ou parents orphelins.",
    "Other family visas":"Autres visas familiaux",
    "Remaining relative and carer family categories.":"Autres catégories familiales pour proches et aidants.",
    "Visit & Working Holiday":"Visite et vacances-travail",
    "Visitor (600)":"Visiteur (600)",
    "Tourism, family and eligible business visitor activity.":"Tourisme, visites familiales et activités professionnelles autorisées pour les visiteurs.",
    "Electronic Travel Authority (601)":"Autorisation électronique de voyage (601)",
    "ETA for eligible passport holders.":"ETA pour les titulaires de passeports admissibles.",
    "eVisitor (651)":"eVisitor (651)",
    "Visitor permission for eligible passport holders.":"Autorisation de visite pour les titulaires de passeports admissibles.",
    "Working Holiday (417)":"Vacances-travail (417)",
    "Work and holiday for eligible young adults.":"Travail et vacances pour les jeunes adultes admissibles.",
    "Work and Holiday (462)":"Work and Holiday (462)",
    "Work and holiday for eligible partner-country citizens.":"Travail et vacances pour les citoyens admissibles de pays partenaires.",
    "Transit (771)":"Transit (771)",
    "Transit through Australia.":"Transit par l’Australie.",
    "Medical Treatment (602)":"Traitement médical (602)",
    "Travel for medical treatment or support.":"Voyage pour recevoir des soins médicaux ou accompagner une personne.",
    "Business, Residence & Humanitarian":"Affaires, résidence et humanitaire",
    "Business Innovation and Investment Permanent (888)":"Innovation et investissement d’affaires – permanent (888)",
    "Permanent stage for eligible legacy business/investment holders.":"Étape permanente pour les titulaires admissibles d’anciens visas d’affaires/investissement.",
    "Resident Return (155/157)":"Retour de résident (155/157)",
    "Travel facility for eligible permanent residents.":"Facilité de voyage pour les résidents permanents admissibles.",
    "Refugee and Humanitarian visas":"Visas de réfugié et humanitaires",
    "Offshore and onshore humanitarian/protection categories.":"Catégories humanitaires et de protection depuis l’étranger ou en Australie.",
    "Bridging visas":"Visas transitoires",
    "Temporary lawful status while immigration matters are resolved.":"Statut légal temporaire pendant le règlement d’une situation migratoire."
  },
  de: {
    "Skilled & Employer Work":"Fachkräfte- und arbeitgebergesponserte Beschäftigung",
    "Skills in Demand (subclass 482)":"Skills in Demand (Unterklasse 482)",
    "Employer-sponsored temporary skilled work.":"Vorübergehende Fachkräftebeschäftigung mit Arbeitgebersponsoring.",
    "Employer Nomination Scheme (186)":"Employer Nomination Scheme (186)",
    "Employer-sponsored permanent residence.":"Daueraufenthalt mit Arbeitgebersponsoring.",
    "Skilled Independent (189)":"Skilled Independent (189)",
    "Points-tested independent skilled migration.":"Unabhängige Fachkräfteeinwanderung nach Punktesystem.",
    "Skilled Nominated (190)":"Skilled Nominated (190)",
    "State or territory nominated skilled migration.":"Fachkräfteeinwanderung mit Nominierung durch einen Bundesstaat oder ein Territorium.",
    "Skilled Work Regional (491)":"Skilled Work Regional (491)",
    "Regional provisional skilled migration.":"Vorläufige Fachkräfteeinwanderung in regionale Gebiete.",
    "Skilled Employer Sponsored Regional (494)":"Skilled Employer Sponsored Regional (494)",
    "Regional employer sponsorship.":"Arbeitgebersponsoring in einer regionalen Region.",
    "Permanent Residence Skilled Regional (191)":"Permanent Residence Skilled Regional (191)",
    "Permanent residence for eligible regional provisional visa holders.":"Daueraufenthalt für berechtigte Inhaber regionaler vorläufiger Visa.",
    "Temporary Work Short Stay Specialist (400)":"Temporary Work Short Stay Specialist (400)",
    "Short-term highly specialised work.":"Kurzfristige hochspezialisierte Beschäftigung.",
    "Temporary Activity (408)":"Temporary Activity (408)",
    "Specified temporary activities.":"Bestimmte vorübergehende Tätigkeiten.",
    "International Relations (403)":"International Relations (403)",
    "Work connected to international arrangements.":"Beschäftigung im Zusammenhang mit internationalen Vereinbarungen.",
    "National Innovation (858)":"National Innovation (858)",
    "Invitation-based permanent visa for exceptional achievement.":"Daueraufenthaltsvisum auf Einladung für außergewöhnliche Leistungen.",
    "Study & Training":"Studium und Ausbildung",
    "Student (500)":"Student (500)",
    "Full-time study with an eligible provider.":"Vollzeitstudium bei einem berechtigten Bildungsanbieter.",
    "Student Guardian (590)":"Student Guardian (590)",
    "Guardian for an eligible international student.":"Erziehungsberechtigter bzw. Begleiter eines berechtigten internationalen Studierenden.",
    "Training (407)":"Training (407)",
    "Occupational training and professional development.":"Berufliche Ausbildung und berufliche Weiterbildung.",
    "Family":"Familie",
    "Partner visas (820/801, 309/100)":"Partnervisa (820/801, 309/100)",
    "Partner migration onshore or offshore.":"Partnermigration aus Australien oder aus dem Ausland.",
    "Prospective Marriage (300)":"Prospective Marriage (300)",
    "Fiancé(e) pathway.":"Visumweg für Verlobte.",
    "Parent visas":"Elternvisa",
    "Parent migration categories, including contributory routes.":"Einwanderungskategorien für Eltern, einschließlich beitragsfinanzierter Wege.",
    "Child visas":"Kindervisa",
    "Eligible dependent, adoption and orphan-relative child categories.":"Berechtigte Kategorien für unterhaltsberechtigte, adoptierte und verwaiste verwandte Kinder.",
    "Other family visas":"Weitere Familienvisa",
    "Remaining relative and carer family categories.":"Weitere Familienkategorien für Verwandte und Betreuungspersonen.",
    "Visit & Working Holiday":"Besuch und Working Holiday",
    "Visitor (600)":"Visitor (600)",
    "Tourism, family and eligible business visitor activity.":"Tourismus, Familienbesuche und zulässige Geschäftsbesuchstätigkeiten.",
    "Electronic Travel Authority (601)":"Electronic Travel Authority (601)",
    "ETA for eligible passport holders.":"ETA für berechtigte Passinhaber.",
    "eVisitor (651)":"eVisitor (651)",
    "Visitor permission for eligible passport holders.":"Besuchserlaubnis für berechtigte Passinhaber.",
    "Working Holiday (417)":"Working Holiday (417)",
    "Work and holiday for eligible young adults.":"Arbeit und Urlaub für berechtigte junge Erwachsene.",
    "Work and Holiday (462)":"Work and Holiday (462)",
    "Work and holiday for eligible partner-country citizens.":"Arbeit und Urlaub für berechtigte Staatsangehörige von Partnerländern.",
    "Transit (771)":"Transit (771)",
    "Transit through Australia.":"Transit durch Australien.",
    "Medical Treatment (602)":"Medical Treatment (602)",
    "Travel for medical treatment or support.":"Reise zur medizinischen Behandlung oder Unterstützung.",
    "Business, Residence & Humanitarian":"Unternehmen, Aufenthalt und humanitäre Wege",
    "Business Innovation and Investment Permanent (888)":"Business Innovation and Investment Permanent (888)",
    "Permanent stage for eligible legacy business/investment holders.":"Daueraufenthaltsstufe für berechtigte Inhaber früherer Geschäfts-/Investitionsvisa.",
    "Resident Return (155/157)":"Resident Return (155/157)",
    "Travel facility for eligible permanent residents.":"Reiseerlaubnis für berechtigte Daueraufenthaltsberechtigte.",
    "Refugee and Humanitarian visas":"Flüchtlings- und humanitäre Visa",
    "Offshore and onshore humanitarian/protection categories.":"Humanitäre und Schutzkategorien für Anträge aus dem Ausland oder in Australien.",
    "Bridging visas":"Bridging Visa",
    "Temporary lawful status while immigration matters are resolved.":"Vorübergehender rechtmäßiger Status, während Einwanderungsangelegenheiten geklärt werden."
  },
  zh: {
    "Skilled & Employer Work":"技术移民与雇主担保工作",
    "Skills in Demand (subclass 482)":"紧缺技能签证（482 子类）",
    "Employer-sponsored temporary skilled work.":"由雇主担保的临时技术工作。",
    "Employer Nomination Scheme (186)":"雇主提名计划（186）",
    "Employer-sponsored permanent residence.":"由雇主担保的永久居留。",
    "Skilled Independent (189)":"独立技术移民（189）",
    "Points-tested independent skilled migration.":"通过积分评估的独立技术移民。",
    "Skilled Nominated (190)":"州担保技术移民（190）",
    "State or territory nominated skilled migration.":"由州或领地提名的技术移民。",
    "Skilled Work Regional (491)":"偏远地区技术工作（491）",
    "Regional provisional skilled migration.":"面向偏远地区的临时技术移民途径。",
    "Skilled Employer Sponsored Regional (494)":"偏远地区雇主担保技术签证（494）",
    "Regional employer sponsorship.":"由偏远地区雇主提供担保。",
    "Permanent Residence Skilled Regional (191)":"偏远地区技术移民永久居留（191）",
    "Permanent residence for eligible regional provisional visa holders.":"面向符合条件的偏远地区临时签证持有人的永久居留途径。",
    "Temporary Work Short Stay Specialist (400)":"临时工作短期专家签证（400）",
    "Short-term highly specialised work.":"短期高度专业化工作。",
    "Temporary Activity (408)":"临时活动签证（408）",
    "Specified temporary activities.":"指定的临时活动。",
    "International Relations (403)":"国际关系签证（403）",
    "Work connected to international arrangements.":"与国际安排相关的工作。",
    "National Innovation (858)":"国家创新签证（858）",
    "Invitation-based permanent visa for exceptional achievement.":"面向具有杰出成就人士、通过邀请申请的永久签证。",
    "Study & Training":"学习与培训",
    "Student (500)":"学生签证（500）",
    "Full-time study with an eligible provider.":"在符合条件的教育机构进行全日制学习。",
    "Student Guardian (590)":"学生监护人签证（590）",
    "Guardian for an eligible international student.":"符合条件国际学生的监护人。",
    "Training (407)":"培训签证（407）",
    "Occupational training and professional development.":"职业培训和专业发展。",
    "Family":"家庭",
    "Partner visas (820/801, 309/100)":"伴侣签证（820/801、309/100）",
    "Partner migration onshore or offshore.":"可从澳大利亚境内或境外申请的伴侣移民途径。",
    "Prospective Marriage (300)":"未婚夫妻签证（300）",
    "Fiancé(e) pathway.":"面向未婚夫/妻的途径。",
    "Parent visas":"父母签证",
    "Parent migration categories, including contributory routes.":"父母移民类别，包括缴费类途径。",
    "Child visas":"子女签证",
    "Eligible dependent, adoption and orphan-relative child categories.":"面向符合条件的受抚养子女、收养子女及孤儿亲属的类别。",
    "Other family visas":"其他家庭签证",
    "Remaining relative and carer family categories.":"其他亲属及照护者家庭类别。",
    "Visit & Working Holiday":"访问与打工度假",
    "Visitor (600)":"访客签证（600）",
    "Tourism, family and eligible business visitor activity.":"旅游、探亲及符合条件的商务访问活动。",
    "Electronic Travel Authority (601)":"电子旅行许可（601）",
    "ETA for eligible passport holders.":"面向符合条件护照持有人的 ETA。",
    "eVisitor (651)":"电子访客签证（651）",
    "Visitor permission for eligible passport holders.":"面向符合条件护照持有人的访客许可。",
    "Working Holiday (417)":"打工度假签证（417）",
    "Work and holiday for eligible young adults.":"面向符合条件年轻人的工作与度假途径。",
    "Work and Holiday (462)":"工作与度假签证（462）",
    "Work and holiday for eligible partner-country citizens.":"面向符合条件伙伴国家公民的工作与度假途径。",
    "Transit (771)":"过境签证（771）",
    "Transit through Australia.":"经澳大利亚过境。",
    "Medical Treatment (602)":"医疗签证（602）",
    "Travel for medical treatment or support.":"因医疗治疗或陪护支持而旅行。",
    "Business, Residence & Humanitarian":"商业、居留与人道主义",
    "Business Innovation and Investment Permanent (888)":"商业创新与投资永久签证（888）",
    "Permanent stage for eligible legacy business/investment holders.":"面向符合条件的旧有商业/投资签证持有人的永久阶段。",
    "Resident Return (155/157)":"居民返程签证（155/157）",
    "Travel facility for eligible permanent residents.":"供符合条件永久居民使用的出入境旅行许可。",
    "Refugee and Humanitarian visas":"难民与人道主义签证",
    "Offshore and onshore humanitarian/protection categories.":"境外和境内的人道主义/保护类别。",
    "Bridging visas":"过桥签证",
    "Temporary lawful status while immigration matters are resolved.":"在移民事项处理期间提供临时合法身份。"
  },
  ar: {
    "Skilled & Employer Work":"العمل الماهر وبرعاية صاحب العمل",
    "Skills in Demand (subclass 482)":"تأشيرة المهارات المطلوبة (الفئة الفرعية 482)",
    "Employer-sponsored temporary skilled work.":"عمل ماهر مؤقت برعاية صاحب عمل.",
    "Employer Nomination Scheme (186)":"برنامج ترشيح صاحب العمل (186)",
    "Employer-sponsored permanent residence.":"إقامة دائمة برعاية صاحب عمل.",
    "Skilled Independent (189)":"المهارات المستقلة (189)",
    "Points-tested independent skilled migration.":"هجرة مهارية مستقلة وفق نظام النقاط.",
    "Skilled Nominated (190)":"المهارات المرشحة (190)",
    "State or territory nominated skilled migration.":"هجرة مهارية بترشيح ولاية أو إقليم.",
    "Skilled Work Regional (491)":"العمل الماهر الإقليمي (491)",
    "Regional provisional skilled migration.":"هجرة مهارية إقليمية مؤقتة.",
    "Skilled Employer Sponsored Regional (494)":"العمل الماهر الإقليمي برعاية صاحب عمل (494)",
    "Regional employer sponsorship.":"رعاية صاحب عمل في منطقة إقليمية.",
    "Permanent Residence Skilled Regional (191)":"الإقامة الدائمة للمهارات الإقليمية (191)",
    "Permanent residence for eligible regional provisional visa holders.":"إقامة دائمة لحاملي التأشيرات الإقليمية المؤقتة المستوفين للشروط.",
    "Temporary Work Short Stay Specialist (400)":"عمل مؤقت لتخصص قصير الإقامة (400)",
    "Short-term highly specialised work.":"عمل عالي التخصص لفترة قصيرة.",
    "Temporary Activity (408)":"نشاط مؤقت (408)",
    "Specified temporary activities.":"أنشطة مؤقتة محددة.",
    "International Relations (403)":"العلاقات الدولية (403)",
    "Work connected to international arrangements.":"عمل مرتبط بترتيبات دولية.",
    "National Innovation (858)":"الابتكار الوطني (858)",
    "Invitation-based permanent visa for exceptional achievement.":"تأشيرة دائمة قائمة على الدعوة لأصحاب الإنجازات الاستثنائية.",
    "Study & Training":"الدراسة والتدريب",
    "Student (500)":"طالب (500)",
    "Full-time study with an eligible provider.":"دراسة بدوام كامل لدى مؤسسة مؤهلة.",
    "Student Guardian (590)":"ولي أمر طالب (590)",
    "Guardian for an eligible international student.":"ولي أمر لطالب دولي مؤهل.",
    "Training (407)":"تدريب (407)",
    "Occupational training and professional development.":"تدريب مهني وتطوير احترافي.",
    "Family":"الأسرة",
    "Partner visas (820/801, 309/100)":"تأشيرات الشريك (820/801، 309/100)",
    "Partner migration onshore or offshore.":"هجرة الشريك من داخل أستراليا أو خارجها.",
    "Prospective Marriage (300)":"الزواج المرتقب (300)",
    "Fiancé(e) pathway.":"مسار الخطيب/الخطيبة.",
    "Parent visas":"تأشيرات الوالدين",
    "Parent migration categories, including contributory routes.":"فئات هجرة الوالدين، بما في ذلك المسارات القائمة على المساهمة.",
    "Child visas":"تأشيرات الأطفال",
    "Eligible dependent, adoption and orphan-relative child categories.":"فئات الأطفال المعالين والمتبنين والأقارب الأيتام المستوفين للشروط.",
    "Other family visas":"تأشيرات عائلية أخرى",
    "Remaining relative and carer family categories.":"الفئات العائلية الأخرى للأقارب ومقدمي الرعاية.",
    "Visit & Working Holiday":"الزيارة وعطلة العمل",
    "Visitor (600)":"زائر (600)",
    "Tourism, family and eligible business visitor activity.":"السياحة والزيارات العائلية وأنشطة زيارة الأعمال المؤهلة.",
    "Electronic Travel Authority (601)":"تصريح السفر الإلكتروني (601)",
    "ETA for eligible passport holders.":"تصريح ETA لحاملي جوازات السفر المؤهلين.",
    "eVisitor (651)":"eVisitor (651)",
    "Visitor permission for eligible passport holders.":"إذن زيارة لحاملي جوازات السفر المؤهلين.",
    "Working Holiday (417)":"عطلة العمل (417)",
    "Work and holiday for eligible young adults.":"العمل والعطلة للشباب البالغين المؤهلين.",
    "Work and Holiday (462)":"العمل والعطلة (462)",
    "Work and holiday for eligible partner-country citizens.":"العمل والعطلة لمواطني الدول الشريكة المؤهلين.",
    "Transit (771)":"العبور (771)",
    "Transit through Australia.":"العبور عبر أستراليا.",
    "Medical Treatment (602)":"العلاج الطبي (602)",
    "Travel for medical treatment or support.":"السفر للعلاج الطبي أو لتقديم الدعم.",
    "Business, Residence & Humanitarian":"الأعمال والإقامة والمسارات الإنسانية",
    "Business Innovation and Investment Permanent (888)":"الابتكار والاستثمار التجاري الدائم (888)",
    "Permanent stage for eligible legacy business/investment holders.":"المرحلة الدائمة لحاملي فئات الأعمال/الاستثمار القديمة المستوفين للشروط.",
    "Resident Return (155/157)":"عودة المقيم (155/157)",
    "Travel facility for eligible permanent residents.":"تسهيل سفر للمقيمين الدائمين المؤهلين.",
    "Refugee and Humanitarian visas":"تأشيرات اللاجئين والإنسانية",
    "Offshore and onshore humanitarian/protection categories.":"فئات إنسانية وحماية من خارج أستراليا وداخلها.",
    "Bridging visas":"تأشيرات الجسر",
    "Temporary lawful status while immigration matters are resolved.":"وضع قانوني مؤقت أثناء تسوية مسائل الهجرة."
  },
  pt: {
    "Skilled & Employer Work":"Trabalho qualificado e patrocinado por empregador",
    "Skills in Demand (subclass 482)":"Skills in Demand (subclasse 482)",
    "Employer-sponsored temporary skilled work.":"Trabalho qualificado temporário patrocinado por empregador.",
    "Employer Nomination Scheme (186)":"Employer Nomination Scheme (186)",
    "Employer-sponsored permanent residence.":"Residência permanente patrocinada por empregador.",
    "Skilled Independent (189)":"Profissional Qualificado Independente (189)",
    "Points-tested independent skilled migration.":"Migração qualificada independente avaliada por pontos.",
    "Skilled Nominated (190)":"Profissional Qualificado Nomeado (190)",
    "State or territory nominated skilled migration.":"Migração qualificada nomeada por estado ou território.",
    "Skilled Work Regional (491)":"Trabalho Qualificado Regional (491)",
    "Regional provisional skilled migration.":"Migração qualificada provisória para regiões.",
    "Skilled Employer Sponsored Regional (494)":"Trabalho Qualificado Regional Patrocinado por Empregador (494)",
    "Regional employer sponsorship.":"Patrocínio por empregador numa região.",
    "Permanent Residence Skilled Regional (191)":"Residência Permanente Qualificada Regional (191)",
    "Permanent residence for eligible regional provisional visa holders.":"Residência permanente para titulares elegíveis de vistos regionais provisórios.",
    "Temporary Work Short Stay Specialist (400)":"Trabalho Temporário de Especialista de Curta Duração (400)",
    "Short-term highly specialised work.":"Trabalho altamente especializado de curta duração.",
    "Temporary Activity (408)":"Atividade Temporária (408)",
    "Specified temporary activities.":"Atividades temporárias específicas.",
    "International Relations (403)":"Relações Internacionais (403)",
    "Work connected to international arrangements.":"Trabalho ligado a acordos internacionais.",
    "National Innovation (858)":"Inovação Nacional (858)",
    "Invitation-based permanent visa for exceptional achievement.":"Visto permanente por convite para pessoas com realizações excecionais.",
    "Study & Training":"Estudo e formação",
    "Student (500)":"Estudante (500)",
    "Full-time study with an eligible provider.":"Estudo a tempo inteiro com uma instituição elegível.",
    "Student Guardian (590)":"Tutor de Estudante (590)",
    "Guardian for an eligible international student.":"Tutor de um estudante internacional elegível.",
    "Training (407)":"Formação (407)",
    "Occupational training and professional development.":"Formação profissional e desenvolvimento de carreira.",
    "Family":"Família",
    "Partner visas (820/801, 309/100)":"Vistos de parceiro (820/801, 309/100)",
    "Partner migration onshore or offshore.":"Migração de parceiro dentro ou fora da Austrália.",
    "Prospective Marriage (300)":"Casamento Futuro (300)",
    "Fiancé(e) pathway.":"Via para noivo/a.",
    "Parent visas":"Vistos para pais",
    "Parent migration categories, including contributory routes.":"Categorias de migração para pais, incluindo vias contributivas.",
    "Child visas":"Vistos para filhos",
    "Eligible dependent, adoption and orphan-relative child categories.":"Categorias elegíveis para filhos dependentes, adotados e parentes órfãos.",
    "Other family visas":"Outros vistos familiares",
    "Remaining relative and carer family categories.":"Restantes categorias familiares para parentes e cuidadores.",
    "Visit & Working Holiday":"Visita e Working Holiday",
    "Visitor (600)":"Visitante (600)",
    "Tourism, family and eligible business visitor activity.":"Turismo, visitas familiares e atividades de negócios permitidas a visitantes.",
    "Electronic Travel Authority (601)":"Autorização Eletrónica de Viagem (601)",
    "ETA for eligible passport holders.":"ETA para titulares de passaporte elegíveis.",
    "eVisitor (651)":"eVisitor (651)",
    "Visitor permission for eligible passport holders.":"Autorização de visitante para titulares de passaporte elegíveis.",
    "Working Holiday (417)":"Working Holiday (417)",
    "Work and holiday for eligible young adults.":"Trabalho e férias para jovens adultos elegíveis.",
    "Work and Holiday (462)":"Work and Holiday (462)",
    "Work and holiday for eligible partner-country citizens.":"Trabalho e férias para cidadãos elegíveis de países parceiros.",
    "Transit (771)":"Trânsito (771)",
    "Transit through Australia.":"Trânsito pela Austrália.",
    "Medical Treatment (602)":"Tratamento Médico (602)",
    "Travel for medical treatment or support.":"Viagem para tratamento médico ou apoio.",
    "Business, Residence & Humanitarian":"Negócios, residência e proteção humanitária",
    "Business Innovation and Investment Permanent (888)":"Inovação Empresarial e Investimento Permanente (888)",
    "Permanent stage for eligible legacy business/investment holders.":"Etapa permanente para titulares elegíveis de categorias antigas de negócios/investimento.",
    "Resident Return (155/157)":"Retorno de Residente (155/157)",
    "Travel facility for eligible permanent residents.":"Facilidade de viagem para residentes permanentes elegíveis.",
    "Refugee and Humanitarian visas":"Vistos de refugiado e humanitários",
    "Offshore and onshore humanitarian/protection categories.":"Categorias humanitárias e de proteção dentro e fora da Austrália.",
    "Bridging visas":"Vistos de transição",
    "Temporary lawful status while immigration matters are resolved.":"Estatuto legal temporário enquanto questões de imigração são resolvidas."
  },
  ja: {
    "Skilled & Employer Work":"技能・雇用主スポンサー就労",
    "Skills in Demand (subclass 482)":"Skills in Demand（サブクラス482）",
    "Employer-sponsored temporary skilled work.":"雇用主スポンサーによる一時的な技能職就労。",
    "Employer Nomination Scheme (186)":"雇用主指名制度（186）",
    "Employer-sponsored permanent residence.":"雇用主スポンサーによる永住。",
    "Skilled Independent (189)":"独立技能移民（189）",
    "Points-tested independent skilled migration.":"ポイント審査による独立技能移民。",
    "Skilled Nominated (190)":"州指名技能移民（190）",
    "State or territory nominated skilled migration.":"州または準州の指名による技能移民。",
    "Skilled Work Regional (491)":"地方技能就労（491）",
    "Regional provisional skilled migration.":"地方地域向けの暫定技能移民。",
    "Skilled Employer Sponsored Regional (494)":"地方雇用主スポンサー技能就労（494）",
    "Regional employer sponsorship.":"地方地域の雇用主によるスポンサー。",
    "Permanent Residence Skilled Regional (191)":"地方技能永住（191）",
    "Permanent residence for eligible regional provisional visa holders.":"要件を満たす地方暫定ビザ保持者向けの永住ルート。",
    "Temporary Work Short Stay Specialist (400)":"短期専門就労（400）",
    "Short-term highly specialised work.":"短期間の高度専門業務。",
    "Temporary Activity (408)":"一時活動（408）",
    "Specified temporary activities.":"指定された一時的活動。",
    "International Relations (403)":"国際関係（403）",
    "Work connected to international arrangements.":"国際的な取り決めに関連する就労。",
    "National Innovation (858)":"国家イノベーション（858）",
    "Invitation-based permanent visa for exceptional achievement.":"卓越した実績を持つ人を対象とする招待制の永住ビザ。",
    "Study & Training":"留学・研修",
    "Student (500)":"学生（500）",
    "Full-time study with an eligible provider.":"要件を満たす教育機関でのフルタイム学習。",
    "Student Guardian (590)":"学生保護者（590）",
    "Guardian for an eligible international student.":"要件を満たす留学生の保護者。",
    "Training (407)":"研修（407）",
    "Occupational training and professional development.":"職業訓練および専門能力開発。",
    "Family":"家族",
    "Partner visas (820/801, 309/100)":"パートナービザ（820/801、309/100）",
    "Partner migration onshore or offshore.":"オーストラリア国内または国外からのパートナー移民。",
    "Prospective Marriage (300)":"婚約者ビザ（300）",
    "Fiancé(e) pathway.":"婚約者向けのルート。",
    "Parent visas":"親ビザ",
    "Parent migration categories, including contributory routes.":"拠出型を含む親向け移民カテゴリー。",
    "Child visas":"子どもビザ",
    "Eligible dependent, adoption and orphan-relative child categories.":"要件を満たす扶養子、養子、孤児の親族に関するカテゴリー。",
    "Other family visas":"その他の家族ビザ",
    "Remaining relative and carer family categories.":"その他の親族・介護者向け家族カテゴリー。",
    "Visit & Working Holiday":"訪問・ワーキングホリデー",
    "Visitor (600)":"訪問者（600）",
    "Tourism, family and eligible business visitor activity.":"観光、家族訪問、要件を満たす商用訪問活動。",
    "Electronic Travel Authority (601)":"電子渡航許可（601）",
    "ETA for eligible passport holders.":"対象パスポート保持者向けの ETA。",
    "eVisitor (651)":"eVisitor（651）",
    "Visitor permission for eligible passport holders.":"対象パスポート保持者向けの訪問許可。",
    "Working Holiday (417)":"ワーキングホリデー（417）",
    "Work and holiday for eligible young adults.":"要件を満たす若年成人向けの就労・休暇制度。",
    "Work and Holiday (462)":"ワーク・アンド・ホリデー（462）",
    "Work and holiday for eligible partner-country citizens.":"対象パートナー国の市民向けの就労・休暇制度。",
    "Transit (771)":"乗り継ぎ（771）",
    "Transit through Australia.":"オーストラリアを経由するための乗り継ぎ。",
    "Medical Treatment (602)":"医療（602）",
    "Travel for medical treatment or support.":"医療を受ける、または支援するための渡航。",
    "Business, Residence & Humanitarian":"ビジネス・居住・人道",
    "Business Innovation and Investment Permanent (888)":"ビジネス・イノベーション／投資永住（888）",
    "Permanent stage for eligible legacy business/investment holders.":"旧制度のビジネス／投資ビザ保持者のうち、要件を満たす人向けの永住段階。",
    "Resident Return (155/157)":"居住者帰国（155/157）",
    "Travel facility for eligible permanent residents.":"要件を満たす永住者向けの渡航権。",
    "Refugee and Humanitarian visas":"難民・人道ビザ",
    "Offshore and onshore humanitarian/protection categories.":"国外・国内の人道／保護カテゴリー。",
    "Bridging visas":"ブリッジング・ビザ",
    "Temporary lawful status while immigration matters are resolved.":"移民手続が解決されるまでの一時的な合法滞在資格。"
  }
};
export default translations;
