const translations: Record<string, Record<string, string>> = {
  es: {
    "Permanent Residence & Economic": "Residencia permanente e inmigración económica",
    "Express Entry – Federal Skilled Worker": "Entrada Exprés – Trabajador Calificado Federal",
    "Economic immigration for eligible skilled workers.": "Inmigración económica para trabajadores calificados que cumplan los requisitos.",
    "Express Entry – Canadian Experience Class": "Entrada Exprés – Clase de Experiencia Canadiense",
    "For eligible applicants with Canadian skilled work experience.": "Para solicitantes elegibles con experiencia laboral calificada en Canadá.",
    "Express Entry – Federal Skilled Trades": "Entrada Exprés – Oficios Calificados Federales",
    "For eligible skilled tradespeople.": "Para trabajadores de oficios calificados que cumplan los requisitos.",
    "Provincial Nominee Program": "Programa de Nominación Provincial",
    "Province or territory nomination pathways.": "Vías de nominación por una provincia o territorio.",
    "Atlantic Immigration Program": "Programa de Inmigración del Atlántico",
    "Employer-led permanent residence in Atlantic Canada.": "Residencia permanente impulsada por un empleador en el Canadá Atlántico.",
    "Rural Community Immigration Pilot": "Programa Piloto de Inmigración de Comunidades Rurales",
    "Community-based permanent residence pathway.": "Vía de residencia permanente basada en la comunidad.",
    "Francophone Community Immigration Pilot": "Programa Piloto de Inmigración de Comunidades Francófonas",
    "Francophone community pathway.": "Vía de inmigración para comunidades francófonas.",
    "Quebec-selected skilled workers": "Trabajadores calificados seleccionados por Quebec",
    "Quebec-selected economic immigration.": "Inmigración económica para personas seleccionadas por Quebec.",
    "Caregiver pathways": "Vías para cuidadores",
    "Eligible home-care worker permanent residence pathways.": "Vías de residencia permanente para trabajadores elegibles de atención domiciliaria.",
    "Start-up Visa": "Visa para Empresas Emergentes",
    "Entrepreneur permanent residence programme, subject to current programme rules.": "Programa de residencia permanente para emprendedores, sujeto a las normas vigentes del programa.",
    "Work": "Trabajo",
    "Employer-specific work permit": "Permiso de trabajo específico para un empleador",
    "Work for the employer and under the conditions stated on the permit.": "Trabajar para el empleador y bajo las condiciones indicadas en el permiso.",
    "Open work permit": "Permiso de trabajo abierto",
    "Open employment permission for eligible circumstances.": "Autorización de trabajo abierto en circunstancias elegibles.",
    "Post-Graduation Work Permit": "Permiso de Trabajo Posterior a la Graduación",
    "Eligible graduates of designated learning institutions.": "Para graduados elegibles de instituciones de aprendizaje designadas.",
    "International Experience Canada – Working Holiday": "Experiencia Internacional Canadá – Working Holiday",
    "Youth mobility open work permit for eligible nationalities.": "Permiso de trabajo abierto de movilidad juvenil para nacionalidades elegibles.",
    "IEC – Young Professionals": "IEC – Jóvenes Profesionales",
    "Employer-specific youth mobility category.": "Categoría de movilidad juvenil vinculada a un empleador específico.",
    "IEC – International Co-op": "IEC – Cooperación Internacional",
    "Internship category for eligible students.": "Categoría de prácticas para estudiantes elegibles.",
    "International Mobility Program": "Programa de Movilidad Internacional",
    "LMIA-exempt work permit streams where eligible.": "Vías de permiso de trabajo exentas de LMIA cuando se cumplan los requisitos.",
    "Temporary Foreign Worker Program": "Programa de Trabajadores Extranjeros Temporales",
    "LMIA-supported temporary work.": "Trabajo temporal respaldado por una LMIA.",
    "Study": "Estudios",
    "Study Permit": "Permiso de estudios",
    "Study at a designated learning institution.": "Estudiar en una institución de aprendizaje designada.",
    "Student Direct Stream / related processing": "Student Direct Stream / tramitación relacionada",
    "Where a current facilitated processing route applies; verify current availability.": "Cuando exista una vía vigente de tramitación facilitada; verifique su disponibilidad actual.",
    "Family": "Familia",
    "Spouse or partner sponsorship": "Patrocinio de cónyuge o pareja",
    "Permanent residence family sponsorship.": "Patrocinio familiar para residencia permanente.",
    "Dependent child sponsorship": "Patrocinio de hijo dependiente",
    "Eligible dependent children.": "Hijos dependientes que cumplan los requisitos.",
    "Parents and Grandparents Program": "Programa de Padres y Abuelos",
    "Family sponsorship when intake is available.": "Patrocinio familiar cuando el programa admita solicitudes.",
    "Super Visa": "Super Visa",
    "Longer family visits for eligible parents and grandparents.": "Visitas familiares de mayor duración para padres y abuelos elegibles.",
    "Visit, Transit & Protection": "Visita, tránsito y protección",
    "Visitor Visa (TRV)": "Visa de visitante (TRV)",
    "Temporary resident visa for eligible visitors.": "Visa de residente temporal para visitantes elegibles.",
    "Electronic Travel Authorization (eTA)": "Autorización Electrónica de Viaje (eTA)",
    "Travel authorisation for eligible visa-exempt travellers.": "Autorización de viaje para viajeros elegibles exentos de visa.",
    "Transit Visa": "Visa de tránsito",
    "Transit through Canada where required.": "Tránsito por Canadá cuando sea obligatorio.",
    "Temporary Resident Permit": "Permiso de Residente Temporal",
    "For certain otherwise inadmissible travellers.": "Para determinados viajeros que de otro modo serían inadmisibles.",
    "Refugee / asylum protection": "Protección para refugiados / asilo",
    "Protection pathways for qualifying applicants.": "Vías de protección para solicitantes que cumplan los requisitos."
  },
  fr: {
    "Permanent Residence & Economic": "Résidence permanente et immigration économique",
    "Express Entry – Federal Skilled Worker": "Entrée express – Travailleurs qualifiés (fédéral)",
    "Economic immigration for eligible skilled workers.": "Immigration économique destinée aux travailleurs qualifiés admissibles.",
    "Express Entry – Canadian Experience Class": "Entrée express – Catégorie de l’expérience canadienne",
    "For eligible applicants with Canadian skilled work experience.": "Pour les demandeurs admissibles ayant une expérience de travail qualifié au Canada.",
    "Express Entry – Federal Skilled Trades": "Entrée express – Métiers spécialisés (fédéral)",
    "For eligible skilled tradespeople.": "Pour les travailleurs de métiers spécialisés admissibles.",
    "Provincial Nominee Program": "Programme des candidats des provinces",
    "Province or territory nomination pathways.": "Voies de désignation par une province ou un territoire.",
    "Atlantic Immigration Program": "Programme d’immigration au Canada atlantique",
    "Employer-led permanent residence in Atlantic Canada.": "Voie de résidence permanente au Canada atlantique appuyée par un employeur.",
    "Rural Community Immigration Pilot": "Programme pilote d’immigration dans les communautés rurales",
    "Community-based permanent residence pathway.": "Voie de résidence permanente fondée sur une communauté.",
    "Francophone Community Immigration Pilot": "Programme pilote d’immigration dans les communautés francophones",
    "Francophone community pathway.": "Voie d’immigration destinée aux communautés francophones.",
    "Quebec-selected skilled workers": "Travailleurs qualifiés sélectionnés par le Québec",
    "Quebec-selected economic immigration.": "Immigration économique pour les personnes sélectionnées par le Québec.",
    "Caregiver pathways": "Voies pour les aides familiaux",
    "Eligible home-care worker permanent residence pathways.": "Voies de résidence permanente pour les travailleurs admissibles des soins à domicile.",
    "Start-up Visa": "Visa pour démarrage d’entreprise",
    "Entrepreneur permanent residence programme, subject to current programme rules.": "Programme de résidence permanente pour entrepreneurs, sous réserve des règles en vigueur du programme.",
    "Work": "Travail",
    "Employer-specific work permit": "Permis de travail lié à un employeur donné",
    "Work for the employer and under the conditions stated on the permit.": "Travailler pour l’employeur et selon les conditions indiquées sur le permis.",
    "Open work permit": "Permis de travail ouvert",
    "Open employment permission for eligible circumstances.": "Autorisation de travail ouverte dans les situations admissibles.",
    "Post-Graduation Work Permit": "Permis de travail postdiplôme",
    "Eligible graduates of designated learning institutions.": "Pour les diplômés admissibles d’établissements d’enseignement désignés.",
    "International Experience Canada – Working Holiday": "Expérience internationale Canada – Vacances-travail",
    "Youth mobility open work permit for eligible nationalities.": "Permis de travail ouvert de mobilité des jeunes pour les nationalités admissibles.",
    "IEC – Young Professionals": "EIC – Jeunes professionnels",
    "Employer-specific youth mobility category.": "Catégorie de mobilité des jeunes liée à un employeur précis.",
    "IEC – International Co-op": "EIC – Stage coop international",
    "Internship category for eligible students.": "Catégorie de stage destinée aux étudiants admissibles.",
    "International Mobility Program": "Programme de mobilité internationale",
    "LMIA-exempt work permit streams where eligible.": "Voies de permis de travail dispensées d’EIMT lorsque les conditions sont remplies.",
    "Temporary Foreign Worker Program": "Programme des travailleurs étrangers temporaires",
    "LMIA-supported temporary work.": "Travail temporaire appuyé par une EIMT.",
    "Study": "Études",
    "Study Permit": "Permis d’études",
    "Study at a designated learning institution.": "Étudier dans un établissement d’enseignement désigné.",
    "Student Direct Stream / related processing": "Volet direct pour les études / traitement connexe",
    "Where a current facilitated processing route applies; verify current availability.": "Lorsqu’une voie de traitement facilité est actuellement applicable; vérifiez sa disponibilité.",
    "Family": "Famille",
    "Spouse or partner sponsorship": "Parrainage d’un époux ou conjoint",
    "Permanent residence family sponsorship.": "Parrainage familial en vue de la résidence permanente.",
    "Dependent child sponsorship": "Parrainage d’un enfant à charge",
    "Eligible dependent children.": "Enfants à charge admissibles.",
    "Parents and Grandparents Program": "Programme des parents et grands-parents",
    "Family sponsorship when intake is available.": "Parrainage familial lorsque la réception des demandes est ouverte.",
    "Super Visa": "Super visa",
    "Longer family visits for eligible parents and grandparents.": "Séjours familiaux prolongés pour les parents et grands-parents admissibles.",
    "Visit, Transit & Protection": "Visite, transit et protection",
    "Visitor Visa (TRV)": "Visa de visiteur (VRT)",
    "Temporary resident visa for eligible visitors.": "Visa de résident temporaire pour les visiteurs admissibles.",
    "Electronic Travel Authorization (eTA)": "Autorisation de voyage électronique (AVE)",
    "Travel authorisation for eligible visa-exempt travellers.": "Autorisation de voyage pour les voyageurs admissibles dispensés de visa.",
    "Transit Visa": "Visa de transit",
    "Transit through Canada where required.": "Transit par le Canada lorsqu’un visa est requis.",
    "Temporary Resident Permit": "Permis de séjour temporaire",
    "For certain otherwise inadmissible travellers.": "Pour certains voyageurs qui seraient autrement interdits de territoire.",
    "Refugee / asylum protection": "Protection des réfugiés / asile",
    "Protection pathways for qualifying applicants.": "Voies de protection pour les demandeurs admissibles."
  },
  de: {
    "Permanent Residence & Economic": "Daueraufenthalt und wirtschaftliche Einwanderung",
    "Express Entry – Federal Skilled Worker": "Express Entry – Bundesprogramm für qualifizierte Fachkräfte",
    "Economic immigration for eligible skilled workers.": "Wirtschaftliche Einwanderung für berechtigte qualifizierte Fachkräfte.",
    "Express Entry – Canadian Experience Class": "Express Entry – Canadian Experience Class",
    "For eligible applicants with Canadian skilled work experience.": "Für berechtigte Antragstellende mit qualifizierter Berufserfahrung in Kanada.",
    "Express Entry – Federal Skilled Trades": "Express Entry – Bundesprogramm für qualifizierte Handwerksberufe",
    "For eligible skilled tradespeople.": "Für berechtigte qualifizierte Fachkräfte in Handwerksberufen.",
    "Provincial Nominee Program": "Programm für Provinznominierungen",
    "Province or territory nomination pathways.": "Einwanderungswege über die Nominierung durch eine Provinz oder ein Territorium.",
    "Atlantic Immigration Program": "Atlantisches Einwanderungsprogramm",
    "Employer-led permanent residence in Atlantic Canada.": "Arbeitgebergestützter Weg zum Daueraufenthalt im atlantischen Kanada.",
    "Rural Community Immigration Pilot": "Pilotprogramm für die Einwanderung in ländliche Gemeinden",
    "Community-based permanent residence pathway.": "Gemeindebasierter Weg zum Daueraufenthalt.",
    "Francophone Community Immigration Pilot": "Pilotprogramm für die Einwanderung in frankophone Gemeinden",
    "Francophone community pathway.": "Einwanderungsweg für frankophone Gemeinden.",
    "Quebec-selected skilled workers": "Von Québec ausgewählte Fachkräfte",
    "Quebec-selected economic immigration.": "Wirtschaftliche Einwanderung für von Québec ausgewählte Personen.",
    "Caregiver pathways": "Einwanderungswege für Betreuungskräfte",
    "Eligible home-care worker permanent residence pathways.": "Wege zum Daueraufenthalt für berechtigte häusliche Betreuungskräfte.",
    "Start-up Visa": "Start-up-Visum",
    "Entrepreneur permanent residence programme, subject to current programme rules.": "Daueraufenthaltsprogramm für Unternehmer, vorbehaltlich der jeweils geltenden Programmregeln.",
    "Work": "Arbeit",
    "Employer-specific work permit": "Arbeitgebergebundene Arbeitserlaubnis",
    "Work for the employer and under the conditions stated on the permit.": "Arbeit für den angegebenen Arbeitgeber unter den im Permit genannten Bedingungen.",
    "Open work permit": "Offene Arbeitserlaubnis",
    "Open employment permission for eligible circumstances.": "Offene Arbeitserlaubnis für berechtigte Situationen.",
    "Post-Graduation Work Permit": "Post-Graduation Work Permit",
    "Eligible graduates of designated learning institutions.": "Für berechtigte Absolventinnen und Absolventen ausgewiesener Bildungseinrichtungen.",
    "International Experience Canada – Working Holiday": "International Experience Canada – Working Holiday",
    "Youth mobility open work permit for eligible nationalities.": "Offene Arbeitserlaubnis im Rahmen der Jugendmobilität für berechtigte Staatsangehörigkeiten.",
    "IEC – Young Professionals": "IEC – Young Professionals",
    "Employer-specific youth mobility category.": "Arbeitgebergebundene Kategorie der Jugendmobilität.",
    "IEC – International Co-op": "IEC – International Co-op",
    "Internship category for eligible students.": "Praktikumskategorie für berechtigte Studierende.",
    "International Mobility Program": "International Mobility Program",
    "LMIA-exempt work permit streams where eligible.": "Arbeitserlaubniswege ohne LMIA, sofern die Voraussetzungen erfüllt sind.",
    "Temporary Foreign Worker Program": "Programm für vorübergehend beschäftigte ausländische Arbeitskräfte",
    "LMIA-supported temporary work.": "Vorübergehende Beschäftigung auf Grundlage einer LMIA.",
    "Study": "Studium",
    "Study Permit": "Studienerlaubnis",
    "Study at a designated learning institution.": "Studium an einer ausgewiesenen Bildungseinrichtung.",
    "Student Direct Stream / related processing": "Student Direct Stream / entsprechende Bearbeitung",
    "Where a current facilitated processing route applies; verify current availability.": "Sofern aktuell ein beschleunigtes Bearbeitungsverfahren gilt; prüfen Sie die derzeitige Verfügbarkeit.",
    "Family": "Familie",
    "Spouse or partner sponsorship": "Familiennachzug für Ehe- oder Lebenspartner",
    "Permanent residence family sponsorship.": "Familiensponsoring für den Daueraufenthalt.",
    "Dependent child sponsorship": "Sponsoring für unterhaltsberechtigte Kinder",
    "Eligible dependent children.": "Berechtigte unterhaltsberechtigte Kinder.",
    "Parents and Grandparents Program": "Programm für Eltern und Großeltern",
    "Family sponsorship when intake is available.": "Familiensponsoring, wenn Bewerbungen angenommen werden.",
    "Super Visa": "Super Visa",
    "Longer family visits for eligible parents and grandparents.": "Längere Familienbesuche für berechtigte Eltern und Großeltern.",
    "Visit, Transit & Protection": "Besuch, Transit und Schutz",
    "Visitor Visa (TRV)": "Besuchervisum (TRV)",
    "Temporary resident visa for eligible visitors.": "Visum für vorübergehenden Aufenthalt für berechtigte Besucher.",
    "Electronic Travel Authorization (eTA)": "Elektronische Reisegenehmigung (eTA)",
    "Travel authorisation for eligible visa-exempt travellers.": "Reisegenehmigung für berechtigte visumbefreite Reisende.",
    "Transit Visa": "Transitvisum",
    "Transit through Canada where required.": "Transit durch Kanada, sofern erforderlich.",
    "Temporary Resident Permit": "Temporary Resident Permit",
    "For certain otherwise inadmissible travellers.": "Für bestimmte Reisende, die andernfalls nicht einreiseberechtigt wären.",
    "Refugee / asylum protection": "Flüchtlings- / Asylschutz",
    "Protection pathways for qualifying applicants.": "Schutzwege für Antragstellende, die die Voraussetzungen erfüllen."
  },
  zh: {
    "Permanent Residence & Economic": "永久居留与经济类移民",
    "Express Entry – Federal Skilled Worker": "快速通道 – 联邦技术工人计划",
    "Economic immigration for eligible skilled workers.": "面向符合条件的技术工人的经济类移民途径。",
    "Express Entry – Canadian Experience Class": "快速通道 – 加拿大经验类",
    "For eligible applicants with Canadian skilled work experience.": "适用于拥有加拿大技术工作经验且符合条件的申请人。",
    "Express Entry – Federal Skilled Trades": "快速通道 – 联邦技工类",
    "For eligible skilled tradespeople.": "适用于符合条件的技术工种从业人员。",
    "Provincial Nominee Program": "省提名计划",
    "Province or territory nomination pathways.": "通过省或地区提名获得移民资格的途径。",
    "Atlantic Immigration Program": "大西洋移民计划",
    "Employer-led permanent residence in Atlantic Canada.": "由雇主支持、通往加拿大大西洋地区永久居留的途径。",
    "Rural Community Immigration Pilot": "农村社区移民试点计划",
    "Community-based permanent residence pathway.": "以社区为基础的永久居留途径。",
    "Francophone Community Immigration Pilot": "法语社区移民试点计划",
    "Francophone community pathway.": "面向法语社区的移民途径。",
    "Quebec-selected skilled workers": "魁北克甄选技术工人",
    "Quebec-selected economic immigration.": "由魁北克甄选的经济类移民途径。",
    "Caregiver pathways": "护理人员移民途径",
    "Eligible home-care worker permanent residence pathways.": "面向符合条件的居家护理工作者的永久居留途径。",
    "Start-up Visa": "初创企业签证",
    "Entrepreneur permanent residence programme, subject to current programme rules.": "面向创业者的永久居留计划，具体以现行计划规则为准。",
    "Work": "工作",
    "Employer-specific work permit": "指定雇主工作许可",
    "Work for the employer and under the conditions stated on the permit.": "只能为许可中指定的雇主工作，并遵守许可所列条件。",
    "Open work permit": "开放式工作许可",
    "Open employment permission for eligible circumstances.": "在符合条件的情况下可获得不限定雇主的工作许可。",
    "Post-Graduation Work Permit": "毕业后工作许可",
    "Eligible graduates of designated learning institutions.": "适用于指定学习机构的符合条件毕业生。",
    "International Experience Canada – Working Holiday": "加拿大国际体验计划 – 打工度假",
    "Youth mobility open work permit for eligible nationalities.": "面向符合条件国籍青年流动人员的开放式工作许可。",
    "IEC – Young Professionals": "IEC – 青年专业人士",
    "Employer-specific youth mobility category.": "与特定雇主绑定的青年流动类别。",
    "IEC – International Co-op": "IEC – 国际合作实习",
    "Internship category for eligible students.": "面向符合条件学生的实习类别。",
    "International Mobility Program": "国际流动计划",
    "LMIA-exempt work permit streams where eligible.": "在符合条件时可使用免 LMIA 的工作许可类别。",
    "Temporary Foreign Worker Program": "临时外国工人计划",
    "LMIA-supported temporary work.": "基于 LMIA 支持的临时工作。",
    "Study": "学习",
    "Study Permit": "学习许可",
    "Study at a designated learning institution.": "在指定学习机构就读。",
    "Student Direct Stream / related processing": "学生直入计划 / 相关审理",
    "Where a current facilitated processing route applies; verify current availability.": "如目前存在便利化审理途径，请核实其当前是否开放。",
    "Family": "家庭",
    "Spouse or partner sponsorship": "配偶或伴侣担保",
    "Permanent residence family sponsorship.": "通过家庭担保申请永久居留。",
    "Dependent child sponsorship": "受抚养子女担保",
    "Eligible dependent children.": "符合条件的受抚养子女。",
    "Parents and Grandparents Program": "父母和祖父母计划",
    "Family sponsorship when intake is available.": "在开放接收申请期间可使用的家庭担保途径。",
    "Super Visa": "超级签证",
    "Longer family visits for eligible parents and grandparents.": "供符合条件的父母和祖父母进行较长期家庭探访。",
    "Visit, Transit & Protection": "访问、过境与保护",
    "Visitor Visa (TRV)": "访客签证（TRV）",
    "Temporary resident visa for eligible visitors.": "面向符合条件访客的临时居民签证。",
    "Electronic Travel Authorization (eTA)": "电子旅行授权（eTA）",
    "Travel authorisation for eligible visa-exempt travellers.": "面向符合条件免签旅客的旅行授权。",
    "Transit Visa": "过境签证",
    "Transit through Canada where required.": "在需要签证的情况下经加拿大过境。",
    "Temporary Resident Permit": "临时居民许可",
    "For certain otherwise inadmissible travellers.": "适用于某些原本可能不获准入境的旅客。",
    "Refugee / asylum protection": "难民 / 庇护保护",
    "Protection pathways for qualifying applicants.": "面向符合条件申请人的保护途径。"
  },
  ar: {
    "Permanent Residence & Economic": "الإقامة الدائمة والهجرة الاقتصادية",
    "Express Entry – Federal Skilled Worker": "الدخول السريع – برنامج العمال المهرة الفيدرالي",
    "Economic immigration for eligible skilled workers.": "مسار هجرة اقتصادية للعمال المهرة المستوفين للشروط.",
    "Express Entry – Canadian Experience Class": "الدخول السريع – فئة الخبرة الكندية",
    "For eligible applicants with Canadian skilled work experience.": "للمتقدمين المؤهلين ممن لديهم خبرة عمل ماهرة في كندا.",
    "Express Entry – Federal Skilled Trades": "الدخول السريع – برنامج الحرف الماهرة الفيدرالي",
    "For eligible skilled tradespeople.": "لأصحاب الحرف الماهرة المستوفين للشروط.",
    "Provincial Nominee Program": "برنامج المرشحين الإقليميين",
    "Province or territory nomination pathways.": "مسارات الترشيح من المقاطعات أو الأقاليم.",
    "Atlantic Immigration Program": "برنامج الهجرة الأطلسي",
    "Employer-led permanent residence in Atlantic Canada.": "مسار إقامة دائمة بدعم صاحب عمل في كندا الأطلسية.",
    "Rural Community Immigration Pilot": "البرنامج التجريبي للهجرة إلى المجتمعات الريفية",
    "Community-based permanent residence pathway.": "مسار إقامة دائمة قائم على المجتمع المحلي.",
    "Francophone Community Immigration Pilot": "البرنامج التجريبي للهجرة إلى المجتمعات الناطقة بالفرنسية",
    "Francophone community pathway.": "مسار هجرة للمجتمعات الناطقة بالفرنسية.",
    "Quebec-selected skilled workers": "العمال المهرة المختارون من كيبيك",
    "Quebec-selected economic immigration.": "هجرة اقتصادية للأشخاص الذين تختارهم كيبيك.",
    "Caregiver pathways": "مسارات مقدمي الرعاية",
    "Eligible home-care worker permanent residence pathways.": "مسارات إقامة دائمة لعمال الرعاية المنزلية المستوفين للشروط.",
    "Start-up Visa": "تأشيرة الشركات الناشئة",
    "Entrepreneur permanent residence programme, subject to current programme rules.": "برنامج إقامة دائمة لرواد الأعمال، وفقاً لقواعد البرنامج الحالية.",
    "Work": "العمل",
    "Employer-specific work permit": "تصريح عمل مرتبط بصاحب عمل محدد",
    "Work for the employer and under the conditions stated on the permit.": "العمل لدى صاحب العمل ووفق الشروط المذكورة في التصريح.",
    "Open work permit": "تصريح عمل مفتوح",
    "Open employment permission for eligible circumstances.": "إذن عمل مفتوح في الحالات المستوفية للشروط.",
    "Post-Graduation Work Permit": "تصريح العمل بعد التخرج",
    "Eligible graduates of designated learning institutions.": "للخريجين المؤهلين من مؤسسات تعليمية معتمدة.",
    "International Experience Canada – Working Holiday": "التجربة الدولية في كندا – عطلة العمل",
    "Youth mobility open work permit for eligible nationalities.": "تصريح عمل مفتوح ضمن تنقل الشباب للجنسيات المؤهلة.",
    "IEC – Young Professionals": "IEC – المهنيون الشباب",
    "Employer-specific youth mobility category.": "فئة لتنقل الشباب مرتبطة بصاحب عمل محدد.",
    "IEC – International Co-op": "IEC – التدريب التعاوني الدولي",
    "Internship category for eligible students.": "فئة تدريب عملي للطلاب المؤهلين.",
    "International Mobility Program": "برنامج التنقل الدولي",
    "LMIA-exempt work permit streams where eligible.": "مسارات تصاريح عمل معفاة من LMIA حيثما تنطبق الأهلية.",
    "Temporary Foreign Worker Program": "برنامج العمال الأجانب المؤقتين",
    "LMIA-supported temporary work.": "عمل مؤقت مدعوم بتقييم LMIA.",
    "Study": "الدراسة",
    "Study Permit": "تصريح الدراسة",
    "Study at a designated learning institution.": "الدراسة في مؤسسة تعليمية معتمدة.",
    "Student Direct Stream / related processing": "مسار الطالب المباشر / المعالجة ذات الصلة",
    "Where a current facilitated processing route applies; verify current availability.": "عندما يتوفر حالياً مسار معالجة ميسّر، تحقق من مدى توفره الآن.",
    "Family": "الأسرة",
    "Spouse or partner sponsorship": "كفالة الزوج أو الشريك",
    "Permanent residence family sponsorship.": "كفالة أسرية للحصول على الإقامة الدائمة.",
    "Dependent child sponsorship": "كفالة الطفل المعال",
    "Eligible dependent children.": "الأطفال المعالون المستوفون للشروط.",
    "Parents and Grandparents Program": "برنامج الآباء والأجداد",
    "Family sponsorship when intake is available.": "كفالة أسرية عندما يكون استقبال الطلبات مفتوحاً.",
    "Super Visa": "التأشيرة الفائقة",
    "Longer family visits for eligible parents and grandparents.": "زيارات عائلية أطول للآباء والأجداد المؤهلين.",
    "Visit, Transit & Protection": "الزيارة والعبور والحماية",
    "Visitor Visa (TRV)": "تأشيرة زائر (TRV)",
    "Temporary resident visa for eligible visitors.": "تأشيرة إقامة مؤقتة للزوار المؤهلين.",
    "Electronic Travel Authorization (eTA)": "تصريح السفر الإلكتروني (eTA)",
    "Travel authorisation for eligible visa-exempt travellers.": "تصريح سفر للمسافرين المؤهلين المعفيين من التأشيرة.",
    "Transit Visa": "تأشيرة عبور",
    "Transit through Canada where required.": "العبور عبر كندا عندما تكون التأشيرة مطلوبة.",
    "Temporary Resident Permit": "تصريح إقامة مؤقتة",
    "For certain otherwise inadmissible travellers.": "لبعض المسافرين الذين قد يكونون غير مقبولين للدخول لولا هذا التصريح.",
    "Refugee / asylum protection": "حماية اللاجئين / اللجوء",
    "Protection pathways for qualifying applicants.": "مسارات حماية للمتقدمين المستوفين للشروط."
  },
  pt: {
    "Permanent Residence & Economic": "Residência permanente e imigração económica",
    "Express Entry – Federal Skilled Worker": "Entrada Expressa – Trabalhador Qualificado Federal",
    "Economic immigration for eligible skilled workers.": "Imigração económica para trabalhadores qualificados elegíveis.",
    "Express Entry – Canadian Experience Class": "Entrada Expressa – Classe de Experiência Canadiana",
    "For eligible applicants with Canadian skilled work experience.": "Para candidatos elegíveis com experiência de trabalho qualificado no Canadá.",
    "Express Entry – Federal Skilled Trades": "Entrada Expressa – Ofícios Qualificados Federais",
    "For eligible skilled tradespeople.": "Para profissionais elegíveis de ofícios qualificados.",
    "Provincial Nominee Program": "Programa de Nomeação Provincial",
    "Province or territory nomination pathways.": "Vias de nomeação por uma província ou território.",
    "Atlantic Immigration Program": "Programa de Imigração do Atlântico",
    "Employer-led permanent residence in Atlantic Canada.": "Residência permanente no Canadá Atlântico com apoio de empregador.",
    "Rural Community Immigration Pilot": "Programa Piloto de Imigração para Comunidades Rurais",
    "Community-based permanent residence pathway.": "Via de residência permanente baseada na comunidade.",
    "Francophone Community Immigration Pilot": "Programa Piloto de Imigração para Comunidades Francófonas",
    "Francophone community pathway.": "Via de imigração para comunidades francófonas.",
    "Quebec-selected skilled workers": "Trabalhadores qualificados selecionados pelo Quebec",
    "Quebec-selected economic immigration.": "Imigração económica para pessoas selecionadas pelo Quebec.",
    "Caregiver pathways": "Vias para cuidadores",
    "Eligible home-care worker permanent residence pathways.": "Vias de residência permanente para trabalhadores elegíveis de cuidados ao domicílio.",
    "Start-up Visa": "Visto para Startups",
    "Entrepreneur permanent residence programme, subject to current programme rules.": "Programa de residência permanente para empreendedores, sujeito às regras atuais do programa.",
    "Work": "Trabalho",
    "Employer-specific work permit": "Autorização de trabalho específica para um empregador",
    "Work for the employer and under the conditions stated on the permit.": "Trabalhar para o empregador e nas condições indicadas na autorização.",
    "Open work permit": "Autorização de trabalho aberta",
    "Open employment permission for eligible circumstances.": "Autorização de trabalho aberta em circunstâncias elegíveis.",
    "Post-Graduation Work Permit": "Autorização de Trabalho Pós-Graduação",
    "Eligible graduates of designated learning institutions.": "Para diplomados elegíveis de instituições de ensino designadas.",
    "International Experience Canada – Working Holiday": "Experiência Internacional Canadá – Working Holiday",
    "Youth mobility open work permit for eligible nationalities.": "Autorização de trabalho aberta de mobilidade jovem para nacionalidades elegíveis.",
    "IEC – Young Professionals": "IEC – Jovens Profissionais",
    "Employer-specific youth mobility category.": "Categoria de mobilidade jovem vinculada a um empregador específico.",
    "IEC – International Co-op": "IEC – Cooperação Internacional",
    "Internship category for eligible students.": "Categoria de estágio para estudantes elegíveis.",
    "International Mobility Program": "Programa de Mobilidade Internacional",
    "LMIA-exempt work permit streams where eligible.": "Vias de autorização de trabalho isentas de LMIA quando elegíveis.",
    "Temporary Foreign Worker Program": "Programa de Trabalhadores Estrangeiros Temporários",
    "LMIA-supported temporary work.": "Trabalho temporário apoiado por LMIA.",
    "Study": "Estudo",
    "Study Permit": "Autorização de estudo",
    "Study at a designated learning institution.": "Estudar numa instituição de ensino designada.",
    "Student Direct Stream / related processing": "Student Direct Stream / processamento relacionado",
    "Where a current facilitated processing route applies; verify current availability.": "Quando exista uma via atual de processamento facilitado; confirme a disponibilidade atual.",
    "Family": "Família",
    "Spouse or partner sponsorship": "Patrocínio de cônjuge ou parceiro",
    "Permanent residence family sponsorship.": "Patrocínio familiar para residência permanente.",
    "Dependent child sponsorship": "Patrocínio de filho dependente",
    "Eligible dependent children.": "Filhos dependentes elegíveis.",
    "Parents and Grandparents Program": "Programa de Pais e Avós",
    "Family sponsorship when intake is available.": "Patrocínio familiar quando a receção de candidaturas estiver aberta.",
    "Super Visa": "Super Visa",
    "Longer family visits for eligible parents and grandparents.": "Visitas familiares mais longas para pais e avós elegíveis.",
    "Visit, Transit & Protection": "Visita, trânsito e proteção",
    "Visitor Visa (TRV)": "Visto de visitante (TRV)",
    "Temporary resident visa for eligible visitors.": "Visto de residente temporário para visitantes elegíveis.",
    "Electronic Travel Authorization (eTA)": "Autorização Eletrónica de Viagem (eTA)",
    "Travel authorisation for eligible visa-exempt travellers.": "Autorização de viagem para viajantes elegíveis isentos de visto.",
    "Transit Visa": "Visto de trânsito",
    "Transit through Canada where required.": "Trânsito pelo Canadá quando exigido.",
    "Temporary Resident Permit": "Autorização de Residente Temporário",
    "For certain otherwise inadmissible travellers.": "Para determinados viajantes que, de outro modo, seriam inadmissíveis.",
    "Refugee / asylum protection": "Proteção de refugiados / asilo",
    "Protection pathways for qualifying applicants.": "Vias de proteção para candidatos que cumpram os requisitos."
  },
  ja: {
    "Permanent Residence & Economic": "永住・経済移民",
    "Express Entry – Federal Skilled Worker": "エクスプレス・エントリー – 連邦技能労働者プログラム",
    "Economic immigration for eligible skilled workers.": "要件を満たす技能労働者向けの経済移民ルートです。",
    "Express Entry – Canadian Experience Class": "エクスプレス・エントリー – カナダ経験クラス",
    "For eligible applicants with Canadian skilled work experience.": "カナダでの技能職経験を持つ、要件を満たす申請者向けです。",
    "Express Entry – Federal Skilled Trades": "エクスプレス・エントリー – 連邦技能職プログラム",
    "For eligible skilled tradespeople.": "要件を満たす技能職従事者向けです。",
    "Provincial Nominee Program": "州推薦プログラム",
    "Province or territory nomination pathways.": "州または準州による推薦を通じた移民ルートです。",
    "Atlantic Immigration Program": "大西洋移民プログラム",
    "Employer-led permanent residence in Atlantic Canada.": "カナダ大西洋地域で、雇用主の支援を受けて永住を目指すルートです。",
    "Rural Community Immigration Pilot": "農村コミュニティ移民パイロット",
    "Community-based permanent residence pathway.": "地域コミュニティを基盤とした永住ルートです。",
    "Francophone Community Immigration Pilot": "フランス語圏コミュニティ移民パイロット",
    "Francophone community pathway.": "フランス語圏コミュニティを対象とした移民ルートです。",
    "Quebec-selected skilled workers": "ケベック州選定技能労働者",
    "Quebec-selected economic immigration.": "ケベック州が選定する経済移民ルートです。",
    "Caregiver pathways": "介護・ケアワーカー向けルート",
    "Eligible home-care worker permanent residence pathways.": "要件を満たす在宅ケア労働者向けの永住ルートです。",
    "Start-up Visa": "スタートアップ・ビザ",
    "Entrepreneur permanent residence programme, subject to current programme rules.": "起業家向けの永住プログラムです。適用には現行のプログラム規則が適用されます。",
    "Work": "就労",
    "Employer-specific work permit": "雇用主限定就労許可",
    "Work for the employer and under the conditions stated on the permit.": "許可証に記載された雇用主のもとで、記載条件に従って就労します。",
    "Open work permit": "オープン就労許可",
    "Open employment permission for eligible circumstances.": "要件を満たす場合に利用できる、雇用主を限定しない就労許可です。",
    "Post-Graduation Work Permit": "卒業後就労許可",
    "Eligible graduates of designated learning institutions.": "指定教育機関の要件を満たす卒業生向けです。",
    "International Experience Canada – Working Holiday": "インターナショナル・エクスペリエンス・カナダ – ワーキングホリデー",
    "Youth mobility open work permit for eligible nationalities.": "対象国籍の若者向けのオープン就労許可です。",
    "IEC – Young Professionals": "IEC – ヤング・プロフェッショナル",
    "Employer-specific youth mobility category.": "特定の雇用主に紐づく若者向けモビリティ区分です。",
    "IEC – International Co-op": "IEC – インターナショナル・コープ",
    "Internship category for eligible students.": "要件を満たす学生向けのインターンシップ区分です。",
    "International Mobility Program": "国際モビリティ・プログラム",
    "LMIA-exempt work permit streams where eligible.": "要件を満たす場合に利用できる、LMIA免除の就労許可区分です。",
    "Temporary Foreign Worker Program": "一時外国人労働者プログラム",
    "LMIA-supported temporary work.": "LMIAに基づく一時就労です。",
    "Study": "留学",
    "Study Permit": "就学許可",
    "Study at a designated learning institution.": "指定教育機関で学ぶための許可です。",
    "Student Direct Stream / related processing": "Student Direct Stream / 関連審査",
    "Where a current facilitated processing route applies; verify current availability.": "現在利用可能な簡易・迅速審査ルートがある場合に適用されます。最新の利用可否を確認してください。",
    "Family": "家族",
    "Spouse or partner sponsorship": "配偶者・パートナーのスポンサーシップ",
    "Permanent residence family sponsorship.": "家族スポンサーによる永住ルートです。",
    "Dependent child sponsorship": "扶養する子どものスポンサーシップ",
    "Eligible dependent children.": "要件を満たす扶養子どもが対象です。",
    "Parents and Grandparents Program": "両親・祖父母プログラム",
    "Family sponsorship when intake is available.": "申請受付期間中に利用できる家族スポンサー制度です。",
    "Super Visa": "スーパー・ビザ",
    "Longer family visits for eligible parents and grandparents.": "要件を満たす両親・祖父母向けの長期家族訪問制度です。",
    "Visit, Transit & Protection": "訪問・乗り継ぎ・保護",
    "Visitor Visa (TRV)": "訪問ビザ（TRV）",
    "Temporary resident visa for eligible visitors.": "要件を満たす訪問者向けの一時滞在ビザです。",
    "Electronic Travel Authorization (eTA)": "電子渡航認証（eTA）",
    "Travel authorisation for eligible visa-exempt travellers.": "対象となるビザ免除旅行者向けの渡航認証です。",
    "Transit Visa": "通過ビザ",
    "Transit through Canada where required.": "必要な場合にカナダを経由するためのビザです。",
    "Temporary Resident Permit": "一時滞在許可",
    "For certain otherwise inadmissible travellers.": "通常は入国不許可となる一部の旅行者向けです。",
    "Refugee / asylum protection": "難民・庇護保護",
    "Protection pathways for qualifying applicants.": "要件を満たす申請者向けの保護ルートです。"
  }
};

export default translations;
