type Row = [string,string,string,string,string,string,string,string];
const rows: Row[] = [
["Entry Visas","Visados de entrada","Visas d’entrée","Einreisevisa","入境签证","تأشيرات الدخول","Vistos de entrada","入国ビザ"],
["Work & Residence","Trabajo y residencia","Travail et résidence","Arbeit & Aufenthalt","工作与居留","العمل والإقامة","Trabalho e residência","就労・居住"],
["Study & Family","Estudios y familia","Études et famille","Studium & Familie","学习与家庭","الدراسة والأسرة","Estudos e família","留学・家族"],
["Schengen Visa Type C","Visado Schengen tipo C","Visa Schengen de type C","Schengen-Visum Typ C","申根C类签证","تأشيرة شنغن نوع C","Visto Schengen Tipo C","シェンゲンビザ（タイプC）"],
["Short stays up to 90 days in a 180-day period.","Estancias cortas de hasta 90 días en un periodo de 180 días.","Courts séjours jusqu’à 90 jours sur une période de 180 jours.","Kurzaufenthalte bis zu 90 Tagen innerhalb eines Zeitraums von 180 Tagen.","在180天期间内最多停留90天。","إقامات قصيرة تصل إلى 90 يوماً خلال فترة 180 يوماً.","Estadias curtas até 90 dias num período de 180 dias.","180日間のうち最長90日までの短期滞在。"],
["National Visa Type D","Visado nacional tipo D","Visa national de type D","Nationales Visum Typ D","国家D类签证","تأشيرة وطنية نوع D","Visto Nacional Tipo D","国民ビザ（タイプD）"],
["Long-term stays over 90 days, subject to cantonal authorisation.","Estancias de larga duración superiores a 90 días, sujetas a autorización cantonal.","Séjours de longue durée de plus de 90 jours, sous réserve d’une autorisation cantonale.","Langzeitaufenthalte von mehr als 90 Tagen, vorbehaltlich kantonaler Bewilligung.","超过90天的长期停留，须获得州级许可。","إقامات طويلة تتجاوز 90 يوماً، رهناً بموافقة الكانتون.","Estadias de longa duração superiores a 90 dias, sujeitas a autorização cantonal.","90日を超える長期滞在。州の許可が必要です。"],
["Airport Transit Visa","Visado de tránsito aeroportuario","Visa de transit aéroportuaire","Flughafentransitvisum","机场过境签证","تأشيرة عبور المطار","Visto de trânsito aeroportuário","空港通過ビザ"],
["Airport transit for nationalities that require it.","Tránsito aeroportuario para nacionalidades que lo requieren.","Transit aéroportuaire pour les nationalités qui y sont soumises.","Flughafentransit für Staatsangehörigkeiten, für die dies erforderlich ist.","适用于需要机场过境签证的国籍人士。","عبور المطار للجنسيات التي تتطلب ذلك.","Trânsito aeroportuário para nacionalidades sujeitas a essa exigência.","必要な国籍の人の空港通過。"],
["Short-term Residence Permit L","Permiso de residencia de corta duración L","Permis de séjour de courte durée L","Kurzaufenthaltsbewilligung L","短期居留许可L","تصريح إقامة قصيرة L","Autorização de residência de curta duração L","短期滞在許可L"],
["Short-term residence, including qualifying employment.","Residencia de corta duración, incluido el empleo que cumple los requisitos.","Séjour de courte durée, y compris un emploi admissible.","Kurzfristiger Aufenthalt einschließlich qualifizierender Beschäftigung.","短期居留，包括符合条件的就业。","إقامة قصيرة، بما في ذلك العمل المستوفي للشروط.","Residência de curta duração, incluindo emprego elegível.","対象となる雇用を含む短期居住。"],
["Residence Permit B","Permiso de residencia B","Permis de séjour B","Aufenthaltsbewilligung B","居留许可B","تصريح إقامة B","Autorização de residência B","居住許可B"],
["Longer residence for an approved purpose, including qualifying employment.","Residencia de mayor duración para un fin autorizado, incluido el empleo que cumple los requisitos.","Séjour plus long pour un motif approuvé, y compris un emploi admissible.","Längerer Aufenthalt für einen genehmigten Zweck einschließlich qualifizierender Beschäftigung.","因获批准的目的进行较长期居留，包括符合条件的就业。","إقامة أطول لغرض معتمد، بما في ذلك العمل المستوفي للشروط.","Residência mais longa para uma finalidade aprovada, incluindo emprego elegível.","承認された目的でのより長期の居住。対象雇用を含みます。"],
["Settlement Permit C","Permiso de establecimiento C","Permis d’établissement C","Niederlassungsbewilligung C","定居许可C","تصريح استقرار C","Autorização de estabelecimento C","定住許可C"],
["Permanent/settled residence for eligible long-term residents.","Residencia permanente o estable para residentes de larga duración que cumplen los requisitos.","Résidence permanente/établie pour les résidents de longue durée admissibles.","Dauerhafte/Niederlassungsbewilligung für berechtigte Langzeitaufenthalter.","适用于符合条件长期居民的永久／定居居留。","إقامة دائمة/مستقرة للمقيمين طويلي الأجل المستوفين للشروط.","Residência permanente/estabelecida para residentes de longa duração elegíveis.","要件を満たす長期居住者の永住・定住。"],
["Cross-border Commuter Permit G","Permiso G para trabajadores fronterizos","Permis G pour frontalier","Grenzgängerbewilligung G","跨境通勤许可G","تصريح عابر للحدود G","Autorização G para trabalhador transfronteiriço","国境通勤者許可G"],
["Qualifying cross-border employment.","Empleo transfronterizo que cumple los requisitos.","Emploi transfrontalier admissible.","Qualifizierende grenzüberschreitende Beschäftigung.","符合条件的跨境就业。","عمل عابر للحدود مستوفٍ للشروط.","Emprego transfronteiriço elegível.","要件を満たす越境雇用。"],
["Work authorisation for third-country nationals","Autorización de trabajo para nacionales de terceros países","Autorisation de travail pour ressortissants de pays tiers","Arbeitsbewilligung für Drittstaatsangehörige","第三国国民工作许可","تصريح عمل لمواطني الدول الثالثة","Autorização de trabalho para nacionais de países terceiros","第三国国籍者の就労許可"],
["Employer-led authorisation for highly qualified workers, subject to quotas and labour-market rules.","Autorización promovida por el empleador para trabajadores altamente cualificados, sujeta a cupos y normas del mercado laboral.","Autorisation à l’initiative de l’employeur pour les travailleurs hautement qualifiés, soumise aux contingents et aux règles du marché du travail.","Arbeitgebergestützte Bewilligung für hochqualifizierte Arbeitskräfte, vorbehaltlich von Kontingenten und Arbeitsmarktregeln.","由雇主发起的高技能工作者许可，受配额及劳动力市场规定限制。","تصريح يقوده صاحب العمل للعمال ذوي المهارات العالية، خاضع للحصص وقواعد سوق العمل.","Autorização promovida pelo empregador para trabalhadores altamente qualificados, sujeita a quotas e regras do mercado de trabalho.","雇用主主導による高度専門人材の許可。割当枠および労働市場規則の対象です。"],
["EU/EFTA work residence","Residencia laboral UE/AELC","Résidence de travail UE/AELE","EU-/EFTA-Arbeitsaufenthalt","欧盟／欧洲自由贸易联盟工作居留","إقامة عمل لمواطني الاتحاد الأوروبي/الرابطة الأوروبية للتجارة الحرة","Residência de trabalho UE/EFTA","EU・EFTA就労居住"],
["Residence/work permissions under free-movement rules for eligible EU/EFTA citizens.","Permisos de residencia y trabajo conforme a las normas de libre circulación para ciudadanos elegibles de la UE/AELC.","Autorisations de séjour/travail au titre de la libre circulation pour les citoyens UE/AELE admissibles.","Aufenthalts-/Arbeitsbewilligungen nach Freizügigkeitsregeln für berechtigte EU-/EFTA-Bürger.","依据自由流动规定向符合条件的欧盟／欧洲自由贸易联盟公民提供居留／工作许可。","تصاريح إقامة/عمل بموجب قواعد حرية التنقل لمواطني الاتحاد الأوروبي/الرابطة الأوروبية للتجارة الحرة المؤهلين.","Autorizações de residência/trabalho ao abrigo das regras de livre circulação para cidadãos UE/EFTA elegíveis.","対象となるEU・EFTA市民の自由移動規則に基づく居住・就労許可。"],
["Self-employment residence","Residencia por trabajo por cuenta propia","Résidence pour activité indépendante","Aufenthalt für Selbständige","自雇居留","إقامة للعمل المستقل","Residência para trabalho por conta própria","自営業居住"],
["Business/self-employment permission subject to nationality and cantonal/federal rules.","Permiso para actividad empresarial o por cuenta propia sujeto a la nacionalidad y a las normas cantonales/federales.","Autorisation d’activité entrepreneuriale/indépendante selon la nationalité et les règles cantonales/fédérales.","Bewilligung für unternehmerische/selbständige Tätigkeit abhängig von Staatsangehörigkeit sowie kantonalen und Bundesregeln.","商业／自雇许可取决于国籍以及州和联邦规定。","إذن للأعمال/العمل المستقل خاضع للجنسية والقواعد الكانتونية/الفيدرالية.","Autorização para atividade empresarial/trabalho independente sujeita à nacionalidade e às regras cantonais/federais.","国籍および州・連邦規則に応じた事業・自営業許可。"],
["Student National Visa / Residence","Visado nacional / residencia para estudiantes","Visa national / séjour étudiant","Nationales Studentenvisum / Aufenthalt","学生国家签证／居留","تأشيرة وطنية / إقامة للطلاب","Visto nacional / residência para estudantes","学生向け国民ビザ／居住"],
["Long-term study with cantonal residence authorisation.","Estudios de larga duración con autorización cantonal de residencia.","Études de longue durée avec autorisation cantonale de séjour.","Langzeitstudium mit kantonaler Aufenthaltsbewilligung.","获得州级居留许可的长期学习。","دراسة طويلة الأجل مع تصريح إقامة من الكانتون.","Estudos de longa duração com autorização cantonal de residência.","州の居住許可を伴う長期就学。"],
["Family Reunification","Reagrupación familiar","Regroupement familial","Familiennachzug","家庭团聚","لمّ شمل الأسرة","Reagrupamento familiar","家族再統合"],
["Qualifying spouse/partner and family residence.","Residencia para cónyuge, pareja y familiares que cumplen los requisitos.","Résidence pour conjoint/partenaire et famille admissibles.","Aufenthalt für berechtigte Ehegatten/Partner und Familienangehörige.","适用于符合条件的配偶／伴侣及家属的居留。","إقامة للزوج/الشريك وأفراد الأسرة المستوفين للشروط.","Residência para cônjuge/parceiro e familiares elegíveis.","要件を満たす配偶者・パートナーおよび家族の居住。"],
["Marriage in Switzerland","Matrimonio en Suiza","Mariage en Suisse","Eheschließung in der Schweiz","在瑞士结婚","الزواج في سويسرا","Casamento na Suíça","スイスでの婚姻"],
["National visa/residence process where applicable.","Proceso de visado nacional o residencia cuando corresponda.","Procédure de visa national/séjour lorsque applicable.","Verfahren für nationales Visum/Aufenthalt, soweit anwendbar.","适用时办理国家签证／居留程序。","إجراءات التأشيرة الوطنية/الإقامة حيثما ينطبق.","Processo de visto nacional/residência quando aplicável.","該当する場合の国民ビザ・居住手続。"],
["Residence without gainful employment","Residencia sin actividad lucrativa","Résidence sans activité lucrative","Aufenthalt ohne Erwerbstätigkeit","非就业居留","إقامة دون عمل مدر للدخل","Residência sem atividade remunerada","非就労居住"],
["Residence for eligible financially self-sufficient applicants, subject to applicable rules.","Residencia para solicitantes económicamente autosuficientes que cumplen los requisitos, sujeta a las normas aplicables.","Résidence pour les demandeurs financièrement autonomes admissibles, sous réserve des règles applicables.","Aufenthalt für berechtigte finanziell selbständige Antragsteller, vorbehaltlich der geltenden Regeln.","适用于符合条件、经济自足申请人的居留，并受相关规定约束。","إقامة للمتقدمين المؤهلين القادرين على إعالة أنفسهم مالياً، وفقاً للقواعد المعمول بها.","Residência para candidatos financeiramente autossuficientes elegíveis, sujeita às regras aplicáveis.","適用規則に従い、要件を満たす経済的に自立した申請者のための居住。"]
];
const langs=["es","fr","de","zh","ar","pt","ja"];
const translations: Record<string,Record<string,string>> = Object.fromEntries(
  langs.map((lang,i)=>[lang,Object.fromEntries(rows.map(row=>[row[0],row[i+1]]))])
);
export default translations;
