const translations: Record<string, Record<string, string>> = {
  es: {
    "Work & Talent":"Trabajo y talento",
    "EU Blue Card":"Tarjeta Azul de la UE",
    "Highly qualified employment meeting the applicable requirements.":"Empleo altamente cualificado que cumple los requisitos aplicables.",
    "Work visa for qualified professionals":"Visa de trabajo para profesionales cualificados",
    "Qualified employment with recognised/comparable qualifications.":"Empleo cualificado con titulaciones reconocidas o comparables.",
    "Visa for professionally experienced workers":"Visa para trabajadores con experiencia profesional",
    "Employment route based on qualifying professional experience.":"Vía de empleo basada en experiencia profesional que cumpla los requisitos.",
    "Opportunity Card (Chancenkarte)":"Tarjeta de Oportunidades (Chancenkarte)",
    "Job-search route for eligible applicants.":"Vía de búsqueda de empleo para solicitantes elegibles.",
    "Visa for IT professionals":"Visa para profesionales de TI",
    "Employment options for qualifying IT specialists.":"Opciones de empleo para especialistas de TI que cumplan los requisitos.",
    "Visa for research":"Visa para investigación",
    "Research activity in Germany.":"Actividad de investigación en Alemania.",
    "Intra-corporate transfer (ICT Card)":"Traslado intraempresarial (Tarjeta ICT)",
    "Qualifying company transfers.":"Traslados empresariales que cumplan los requisitos.",
    "Recognition partnership":"Asociación para el reconocimiento",
    "Work while completing qualification recognition where eligible.":"Trabajar mientras se completa el reconocimiento de cualificaciones cuando se cumplan los requisitos.",
    "Business":"Negocios",
    "Self-employment – business":"Trabajo por cuenta propia – actividad empresarial",
    "Residence for qualifying commercial self-employment.":"Residencia para actividad empresarial por cuenta propia que cumpla los requisitos.",
    "Self-employment – freelance":"Trabajo por cuenta propia – profesión freelance",
    "Residence for qualifying freelance professions.":"Residencia para profesiones freelance que cumplan los requisitos.",
    "Study & Training":"Estudios y formación",
    "Study visa":"Visa de estudios",
    "University study and qualifying preparatory measures.":"Estudios universitarios y medidas preparatorias que cumplan los requisitos.",
    "Seeking a place in higher education":"Búsqueda de plaza en educación superior",
    "Search for a study place where eligible.":"Búsqueda de una plaza de estudios cuando se cumplan los requisitos.",
    "Vocational training visa":"Visa de formación profesional",
    "Company or school-based vocational training.":"Formación profesional en empresa o centro educativo.",
    "Seeking vocational training place":"Búsqueda de plaza de formación profesional",
    "Search for eligible vocational training.":"Búsqueda de formación profesional que cumpla los requisitos.",
    "Language course visa":"Visa para curso de idiomas",
    "Qualifying intensive language study.":"Curso intensivo de idiomas que cumpla los requisitos.",
    "Family & Other":"Familia y otros",
    "Family reunification":"Reagrupación familiar",
    "Eligible spouses, children and other qualifying family circumstances.":"Cónyuges, hijos y otras circunstancias familiares que cumplan los requisitos.",
    "Visa for marriage / joining spouse":"Visa para matrimonio / reunirse con el cónyuge",
    "Family formation or reunification route.":"Vía para formación o reagrupación familiar.",
    "Schengen short-stay visa":"Visa Schengen de corta estancia",
    "Visits up to 90 days where a visa is required.":"Visitas de hasta 90 días cuando se requiere visa.",
    "Airport transit visa":"Visa de tránsito aeroportuario",
    "Airport transit where required.":"Tránsito aeroportuario cuando sea obligatorio."
  },
  fr: {
    "Work & Talent":"Travail et talents",
    "EU Blue Card":"Carte bleue européenne",
    "Highly qualified employment meeting the applicable requirements.":"Emploi hautement qualifié répondant aux exigences applicables.",
    "Work visa for qualified professionals":"Visa de travail pour professionnels qualifiés",
    "Qualified employment with recognised/comparable qualifications.":"Emploi qualifié avec des qualifications reconnues ou comparables.",
    "Visa for professionally experienced workers":"Visa pour travailleurs ayant une expérience professionnelle",
    "Employment route based on qualifying professional experience.":"Voie d’emploi fondée sur une expérience professionnelle admissible.",
    "Opportunity Card (Chancenkarte)":"Carte des opportunités (Chancenkarte)",
    "Job-search route for eligible applicants.":"Voie de recherche d’emploi pour les demandeurs admissibles.",
    "Visa for IT professionals":"Visa pour professionnels de l’informatique",
    "Employment options for qualifying IT specialists.":"Options d’emploi pour les spécialistes informatiques admissibles.",
    "Visa for research":"Visa pour la recherche",
    "Research activity in Germany.":"Activité de recherche en Allemagne.",
    "Intra-corporate transfer (ICT Card)":"Transfert intra-entreprise (carte ICT)",
    "Qualifying company transfers.":"Transferts d’entreprise admissibles.",
    "Recognition partnership":"Partenariat de reconnaissance",
    "Work while completing qualification recognition where eligible.":"Travailler pendant l’achèvement de la reconnaissance des qualifications lorsque les conditions sont remplies.",
    "Business":"Activité professionnelle indépendante",
    "Self-employment – business":"Travail indépendant – activité commerciale",
    "Residence for qualifying commercial self-employment.":"Résidence pour une activité commerciale indépendante admissible.",
    "Self-employment – freelance":"Travail indépendant – profession libérale",
    "Residence for qualifying freelance professions.":"Résidence pour les professions libérales admissibles.",
    "Study & Training":"Études et formation",
    "Study visa":"Visa d’études",
    "University study and qualifying preparatory measures.":"Études universitaires et mesures préparatoires admissibles.",
    "Seeking a place in higher education":"Recherche d’une place dans l’enseignement supérieur",
    "Search for a study place where eligible.":"Recherche d’une place d’études lorsque les conditions sont remplies.",
    "Vocational training visa":"Visa de formation professionnelle",
    "Company or school-based vocational training.":"Formation professionnelle en entreprise ou en établissement scolaire.",
    "Seeking vocational training place":"Recherche d’une place de formation professionnelle",
    "Search for eligible vocational training.":"Recherche d’une formation professionnelle admissible.",
    "Language course visa":"Visa pour cours de langue",
    "Qualifying intensive language study.":"Étude intensive de langue répondant aux conditions.",
    "Family & Other":"Famille et autres",
    "Family reunification":"Regroupement familial",
    "Eligible spouses, children and other qualifying family circumstances.":"Conjoints, enfants et autres situations familiales admissibles.",
    "Visa for marriage / joining spouse":"Visa pour mariage / rejoindre son conjoint",
    "Family formation or reunification route.":"Voie de formation de famille ou de regroupement familial.",
    "Schengen short-stay visa":"Visa Schengen de court séjour",
    "Visits up to 90 days where a visa is required.":"Séjours jusqu’à 90 jours lorsqu’un visa est requis.",
    "Airport transit visa":"Visa de transit aéroportuaire",
    "Airport transit where required.":"Transit aéroportuaire lorsqu’il est requis."
  },
  de: {
    "Work & Talent":"Arbeit und Fachkräfte",
    "EU Blue Card":"EU Blue Card",
    "Highly qualified employment meeting the applicable requirements.":"Hochqualifizierte Beschäftigung, die die geltenden Voraussetzungen erfüllt.",
    "Work visa for qualified professionals":"Arbeitsvisum für qualifizierte Fachkräfte",
    "Qualified employment with recognised/comparable qualifications.":"Qualifizierte Beschäftigung mit anerkannten oder vergleichbaren Qualifikationen.",
    "Visa for professionally experienced workers":"Visum für berufserfahrene Arbeitskräfte",
    "Employment route based on qualifying professional experience.":"Beschäftigungsweg auf Grundlage einschlägiger Berufserfahrung.",
    "Opportunity Card (Chancenkarte)":"Chancenkarte",
    "Job-search route for eligible applicants.":"Weg zur Arbeitssuche für berechtigte Antragstellende.",
    "Visa for IT professionals":"Visum für IT-Fachkräfte",
    "Employment options for qualifying IT specialists.":"Beschäftigungsmöglichkeiten für berechtigte IT-Spezialisten.",
    "Visa for research":"Visum für Forschung",
    "Research activity in Germany.":"Forschungstätigkeit in Deutschland.",
    "Intra-corporate transfer (ICT Card)":"Unternehmensinterner Transfer (ICT-Karte)",
    "Qualifying company transfers.":"Berechtigte unternehmensinterne Versetzungen.",
    "Recognition partnership":"Anerkennungspartnerschaft",
    "Work while completing qualification recognition where eligible.":"Arbeiten während der Qualifikationsanerkennung, sofern die Voraussetzungen erfüllt sind.",
    "Business":"Selbstständigkeit",
    "Self-employment – business":"Selbstständigkeit – Gewerbe",
    "Residence for qualifying commercial self-employment.":"Aufenthalt für berechtigte gewerbliche Selbstständigkeit.",
    "Self-employment – freelance":"Selbstständigkeit – freiberuflich",
    "Residence for qualifying freelance professions.":"Aufenthalt für berechtigte freiberufliche Tätigkeiten.",
    "Study & Training":"Studium und Ausbildung",
    "Study visa":"Visum zum Studium",
    "University study and qualifying preparatory measures.":"Hochschulstudium und berechtigte studienvorbereitende Maßnahmen.",
    "Seeking a place in higher education":"Suche nach einem Studienplatz",
    "Search for a study place where eligible.":"Suche nach einem Studienplatz, sofern die Voraussetzungen erfüllt sind.",
    "Vocational training visa":"Visum zur Berufsausbildung",
    "Company or school-based vocational training.":"Betriebliche oder schulische Berufsausbildung.",
    "Seeking vocational training place":"Suche nach einem Ausbildungsplatz",
    "Search for eligible vocational training.":"Suche nach einer geeigneten Berufsausbildung.",
    "Language course visa":"Visum für einen Sprachkurs",
    "Qualifying intensive language study.":"Berechtigter intensiver Sprachkurs.",
    "Family & Other":"Familie und Sonstiges",
    "Family reunification":"Familiennachzug",
    "Eligible spouses, children and other qualifying family circumstances.":"Berechtigte Ehepartner, Kinder und andere berücksichtigungsfähige familiäre Umstände.",
    "Visa for marriage / joining spouse":"Visum zur Eheschließung / zum Ehegattennachzug",
    "Family formation or reunification route.":"Weg zur Familiengründung oder Familienzusammenführung.",
    "Schengen short-stay visa":"Schengen-Visum für Kurzaufenthalte",
    "Visits up to 90 days where a visa is required.":"Besuche bis zu 90 Tagen, sofern ein Visum erforderlich ist.",
    "Airport transit visa":"Flughafentransitvisum",
    "Airport transit where required.":"Flughafentransit, sofern erforderlich."
  },
  zh: {
    "Work & Talent":"工作与人才",
    "EU Blue Card":"欧盟蓝卡",
    "Highly qualified employment meeting the applicable requirements.":"符合适用要求的高技能就业。",
    "Work visa for qualified professionals":"合格专业人士工作签证",
    "Qualified employment with recognised/comparable qualifications.":"凭认可或可比学历/资质从事合格工作。",
    "Visa for professionally experienced workers":"具备职业经验人员签证",
    "Employment route based on qualifying professional experience.":"基于符合条件的职业经验获得就业的途径。",
    "Opportunity Card (Chancenkarte)":"机会卡（Chancenkarte）",
    "Job-search route for eligible applicants.":"面向符合条件申请人的求职途径。",
    "Visa for IT professionals":"IT 专业人士签证",
    "Employment options for qualifying IT specialists.":"面向符合条件 IT 专家的就业选择。",
    "Visa for research":"研究签证",
    "Research activity in Germany.":"在德国开展研究活动。",
    "Intra-corporate transfer (ICT Card)":"公司内部调动（ICT 卡）",
    "Qualifying company transfers.":"符合条件的公司内部调动。",
    "Recognition partnership":"资格认可伙伴关系",
    "Work while completing qualification recognition where eligible.":"在符合条件的情况下，可在完成资格认可期间工作。",
    "Business":"商业与自雇",
    "Self-employment – business":"自雇 – 商业经营",
    "Residence for qualifying commercial self-employment.":"面向符合条件商业自雇活动的居留途径。",
    "Self-employment – freelance":"自雇 – 自由职业",
    "Residence for qualifying freelance professions.":"面向符合条件自由职业的居留途径。",
    "Study & Training":"学习与培训",
    "Study visa":"学习签证",
    "University study and qualifying preparatory measures.":"大学学习及符合条件的预备措施。",
    "Seeking a place in higher education":"寻找高等教育学习名额",
    "Search for a study place where eligible.":"在符合条件的情况下寻找学习名额。",
    "Vocational training visa":"职业培训签证",
    "Company or school-based vocational training.":"企业或学校形式的职业培训。",
    "Seeking vocational training place":"寻找职业培训名额",
    "Search for eligible vocational training.":"寻找符合条件的职业培训机会。",
    "Language course visa":"语言课程签证",
    "Qualifying intensive language study.":"符合条件的密集语言学习。",
    "Family & Other":"家庭及其他",
    "Family reunification":"家庭团聚",
    "Eligible spouses, children and other qualifying family circumstances.":"符合条件的配偶、子女及其他家庭情形。",
    "Visa for marriage / joining spouse":"结婚 / 与配偶团聚签证",
    "Family formation or reunification route.":"家庭建立或团聚途径。",
    "Schengen short-stay visa":"申根短期签证",
    "Visits up to 90 days where a visa is required.":"在需要签证时，可用于最长 90 天的访问。",
    "Airport transit visa":"机场过境签证",
    "Airport transit where required.":"在需要时用于机场过境。"
  },
  ar: {
    "Work & Talent":"العمل والمواهب",
    "EU Blue Card":"البطاقة الزرقاء للاتحاد الأوروبي",
    "Highly qualified employment meeting the applicable requirements.":"عمل عالي التأهيل يستوفي المتطلبات المعمول بها.",
    "Work visa for qualified professionals":"تأشيرة عمل للمهنيين المؤهلين",
    "Qualified employment with recognised/comparable qualifications.":"عمل مؤهل بمؤهلات معترف بها أو قابلة للمقارنة.",
    "Visa for professionally experienced workers":"تأشيرة للعمال ذوي الخبرة المهنية",
    "Employment route based on qualifying professional experience.":"مسار عمل قائم على خبرة مهنية مستوفية للشروط.",
    "Opportunity Card (Chancenkarte)":"بطاقة الفرص (Chancenkarte)",
    "Job-search route for eligible applicants.":"مسار للبحث عن عمل للمتقدمين المؤهلين.",
    "Visa for IT professionals":"تأشيرة لمتخصصي تقنية المعلومات",
    "Employment options for qualifying IT specialists.":"خيارات عمل لمتخصصي تقنية المعلومات المستوفين للشروط.",
    "Visa for research":"تأشيرة للبحث",
    "Research activity in Germany.":"نشاط بحثي في ألمانيا.",
    "Intra-corporate transfer (ICT Card)":"نقل داخل الشركة (بطاقة ICT)",
    "Qualifying company transfers.":"عمليات نقل داخل الشركات مستوفية للشروط.",
    "Recognition partnership":"شراكة الاعتراف بالمؤهلات",
    "Work while completing qualification recognition where eligible.":"العمل أثناء استكمال الاعتراف بالمؤهلات حيثما تتوافر الأهلية.",
    "Business":"الأعمال والعمل الحر",
    "Self-employment – business":"العمل الحر – نشاط تجاري",
    "Residence for qualifying commercial self-employment.":"إقامة لنشاط تجاري مستقل مستوفٍ للشروط.",
    "Self-employment – freelance":"العمل الحر – مهنة حرة",
    "Residence for qualifying freelance professions.":"إقامة للمهن الحرة المستوفية للشروط.",
    "Study & Training":"الدراسة والتدريب",
    "Study visa":"تأشيرة دراسة",
    "University study and qualifying preparatory measures.":"دراسة جامعية وإجراءات تحضيرية مستوفية للشروط.",
    "Seeking a place in higher education":"البحث عن مقعد في التعليم العالي",
    "Search for a study place where eligible.":"البحث عن مقعد دراسي حيثما تتوافر الأهلية.",
    "Vocational training visa":"تأشيرة تدريب مهني",
    "Company or school-based vocational training.":"تدريب مهني في شركة أو مؤسسة تعليمية.",
    "Seeking vocational training place":"البحث عن مكان للتدريب المهني",
    "Search for eligible vocational training.":"البحث عن تدريب مهني مستوفٍ للشروط.",
    "Language course visa":"تأشيرة دورة لغة",
    "Qualifying intensive language study.":"دراسة مكثفة للغة مستوفية للشروط.",
    "Family & Other":"الأسرة وفئات أخرى",
    "Family reunification":"لمّ شمل الأسرة",
    "Eligible spouses, children and other qualifying family circumstances.":"الأزواج والأطفال والحالات العائلية الأخرى المستوفية للشروط.",
    "Visa for marriage / joining spouse":"تأشيرة للزواج / الالتحاق بالزوج أو الزوجة",
    "Family formation or reunification route.":"مسار لتكوين الأسرة أو لمّ شملها.",
    "Schengen short-stay visa":"تأشيرة شنغن قصيرة الإقامة",
    "Visits up to 90 days where a visa is required.":"زيارات تصل إلى 90 يوماً عندما تكون التأشيرة مطلوبة.",
    "Airport transit visa":"تأشيرة عبور المطار",
    "Airport transit where required.":"عبور المطار عند الحاجة."
  },
  pt: {
    "Work & Talent":"Trabalho e talento",
    "EU Blue Card":"Cartão Azul da UE",
    "Highly qualified employment meeting the applicable requirements.":"Emprego altamente qualificado que cumpra os requisitos aplicáveis.",
    "Work visa for qualified professionals":"Visto de trabalho para profissionais qualificados",
    "Qualified employment with recognised/comparable qualifications.":"Emprego qualificado com qualificações reconhecidas ou comparáveis.",
    "Visa for professionally experienced workers":"Visto para trabalhadores com experiência profissional",
    "Employment route based on qualifying professional experience.":"Via de emprego baseada em experiência profissional elegível.",
    "Opportunity Card (Chancenkarte)":"Cartão de Oportunidades (Chancenkarte)",
    "Job-search route for eligible applicants.":"Via de procura de emprego para candidatos elegíveis.",
    "Visa for IT professionals":"Visto para profissionais de TI",
    "Employment options for qualifying IT specialists.":"Opções de emprego para especialistas de TI elegíveis.",
    "Visa for research":"Visto para investigação",
    "Research activity in Germany.":"Atividade de investigação na Alemanha.",
    "Intra-corporate transfer (ICT Card)":"Transferência intraempresa (Cartão ICT)",
    "Qualifying company transfers.":"Transferências empresariais elegíveis.",
    "Recognition partnership":"Parceria de reconhecimento",
    "Work while completing qualification recognition where eligible.":"Trabalhar enquanto conclui o reconhecimento de qualificações quando elegível.",
    "Business":"Negócios e trabalho independente",
    "Self-employment – business":"Trabalho independente – atividade empresarial",
    "Residence for qualifying commercial self-employment.":"Residência para atividade empresarial por conta própria elegível.",
    "Self-employment – freelance":"Trabalho independente – profissão freelance",
    "Residence for qualifying freelance professions.":"Residência para profissões freelance elegíveis.",
    "Study & Training":"Estudo e formação",
    "Study visa":"Visto de estudo",
    "University study and qualifying preparatory measures.":"Estudo universitário e medidas preparatórias elegíveis.",
    "Seeking a place in higher education":"Procura de vaga no ensino superior",
    "Search for a study place where eligible.":"Procura de uma vaga de estudo quando elegível.",
    "Vocational training visa":"Visto de formação profissional",
    "Company or school-based vocational training.":"Formação profissional em empresa ou escola.",
    "Seeking vocational training place":"Procura de vaga de formação profissional",
    "Search for eligible vocational training.":"Procura de formação profissional elegível.",
    "Language course visa":"Visto para curso de língua",
    "Qualifying intensive language study.":"Estudo intensivo de língua elegível.",
    "Family & Other":"Família e outros",
    "Family reunification":"Reagrupamento familiar",
    "Eligible spouses, children and other qualifying family circumstances.":"Cônjuges, filhos e outras situações familiares elegíveis.",
    "Visa for marriage / joining spouse":"Visto para casamento / juntar-se ao cônjuge",
    "Family formation or reunification route.":"Via para formação ou reagrupamento familiar.",
    "Schengen short-stay visa":"Visto Schengen de curta duração",
    "Visits up to 90 days where a visa is required.":"Visitas até 90 dias quando é necessário visto.",
    "Airport transit visa":"Visto de trânsito aeroportuário",
    "Airport transit where required.":"Trânsito aeroportuário quando exigido."
  },
  ja: {
    "Work & Talent":"就労・人材",
    "EU Blue Card":"EUブルーカード",
    "Highly qualified employment meeting the applicable requirements.":"適用要件を満たす高度技能就労。",
    "Work visa for qualified professionals":"資格を有する専門職向け就労ビザ",
    "Qualified employment with recognised/comparable qualifications.":"認定済みまたは同等と認められる資格を用いた専門的就労。",
    "Visa for professionally experienced workers":"実務経験者向けビザ",
    "Employment route based on qualifying professional experience.":"要件を満たす職業経験に基づく就労ルート。",
    "Opportunity Card (Chancenkarte)":"チャンスカード（Chancenkarte）",
    "Job-search route for eligible applicants.":"要件を満たす申請者向けの求職ルート。",
    "Visa for IT professionals":"IT専門職向けビザ",
    "Employment options for qualifying IT specialists.":"要件を満たすIT専門家向けの就労選択肢。",
    "Visa for research":"研究ビザ",
    "Research activity in Germany.":"ドイツでの研究活動。",
    "Intra-corporate transfer (ICT Card)":"企業内転勤（ICTカード）",
    "Qualifying company transfers.":"要件を満たす企業内転勤。",
    "Recognition partnership":"資格認定パートナーシップ",
    "Work while completing qualification recognition where eligible.":"要件を満たす場合、資格認定手続を進めながら就労できます。",
    "Business":"ビジネス・自営業",
    "Self-employment – business":"自営業 – 事業",
    "Residence for qualifying commercial self-employment.":"要件を満たす商業的自営業向けの滞在ルート。",
    "Self-employment – freelance":"自営業 – フリーランス",
    "Residence for qualifying freelance professions.":"要件を満たすフリーランス職向けの滞在ルート。",
    "Study & Training":"留学・職業訓練",
    "Study visa":"留学ビザ",
    "University study and qualifying preparatory measures.":"大学での学習および要件を満たす準備課程。",
    "Seeking a place in higher education":"大学等の入学先を探す",
    "Search for a study place where eligible.":"要件を満たす場合に学習先を探すためのルート。",
    "Vocational training visa":"職業訓練ビザ",
    "Company or school-based vocational training.":"企業または学校で行う職業訓練。",
    "Seeking vocational training place":"職業訓練先を探す",
    "Search for eligible vocational training.":"要件を満たす職業訓練先を探すためのルート。",
    "Language course visa":"語学コースビザ",
    "Qualifying intensive language study.":"要件を満たす集中語学学習。",
    "Family & Other":"家族・その他",
    "Family reunification":"家族再統合",
    "Eligible spouses, children and other qualifying family circumstances.":"要件を満たす配偶者、子ども、その他の家族事情。",
    "Visa for marriage / joining spouse":"結婚 / 配偶者合流ビザ",
    "Family formation or reunification route.":"家族形成または家族再統合のためのルート。",
    "Schengen short-stay visa":"シェンゲン短期滞在ビザ",
    "Visits up to 90 days where a visa is required.":"ビザが必要な場合の90日以内の訪問。",
    "Airport transit visa":"空港通過ビザ",
    "Airport transit where required.":"必要な場合の空港乗り継ぎ。"
  }
};
export default translations;
