type Row = [string,string,string,string,string,string,string,string];
const rows: Row[] = [
["Work & Business","Trabajo y negocios","Travail et affaires","Arbeit & Geschäft","工作与商业","العمل والأعمال","Trabalho e negócios","就労・ビジネス"],
["Residence, Study & Family","Residencia, estudios y familia","Résidence, études et famille","Aufenthalt, Studium & Familie","居留、学习与家庭","الإقامة والدراسة والأسرة","Residência, estudos e família","居住・留学・家族"],
["Short Stay","Estancia corta","Court séjour","Kurzaufenthalt","短期停留","إقامة قصيرة","Estadia de curta duração","短期滞在"],
["Employee Work Visa","Visado de trabajo por cuenta ajena","Visa de travail salarié","Arbeitsvisum für Beschäftigte","受雇工作签证","تأشيرة عمل للموظفين","Visto de trabalho por conta de outrem","雇用就労ビザ"],
["Residence and employment under the general scheme.","Residencia y empleo conforme al régimen general.","Résidence et emploi dans le cadre du régime général.","Aufenthalt und Beschäftigung nach dem allgemeinen System.","依据一般制度进行居留和就业。","إقامة وعمل بموجب النظام العام.","Residência e emprego ao abrigo do regime geral.","一般制度に基づく居住・雇用。"],
["Self-employed Work Visa","Visado de trabajo por cuenta propia","Visa de travail indépendant","Arbeitsvisum für Selbständige","自雇工作签证","تأشيرة عمل مستقل","Visto de trabalho por conta própria","自営業ビザ"],
["Residence to carry out self-employed activity.","Residencia para realizar una actividad por cuenta propia.","Résidence pour exercer une activité indépendante.","Aufenthalt zur Ausübung einer selbständigen Tätigkeit.","用于开展自雇活动的居留。","إقامة لمزاولة نشاط مستقل.","Residência para exercer atividade por conta própria.","自営業を行うための居住。"],
["Highly Qualified Worker Visa","Visado para trabajadores altamente cualificados","Visa pour travailleur hautement qualifié","Visum für hochqualifizierte Arbeitnehmer","高技能工作者签证","تأشيرة العامل عالي التأهيل","Visto para trabalhador altamente qualificado","高度専門職ビザ"],
["Residence for qualifying highly skilled professionals.","Residencia para profesionales altamente cualificados que cumplen los requisitos.","Résidence pour les professionnels hautement qualifiés admissibles.","Aufenthalt für qualifizierende hochqualifizierte Fachkräfte.","适用于符合条件的高技能专业人士的居留。","إقامة للمهنيين ذوي المهارات العالية المستوفين للشروط.","Residência para profissionais altamente qualificados elegíveis.","要件を満たす高度専門職のための居住。"],
["Intra-company Transfer Visa","Visado de traslado intraempresarial","Visa de transfert intra-entreprise","Visum für unternehmensinternen Transfer","企业内部调动签证","تأشيرة النقل داخل الشركة","Visto de transferência intraempresa","企業内転勤ビザ"],
["Qualifying company transfers.","Traslados de empresa que cumplen los requisitos.","Transferts d’entreprise admissibles.","Qualifizierende Unternehmensversetzungen.","符合条件的公司内部调动。","عمليات نقل مؤهلة داخل الشركة.","Transferências empresariais elegíveis.","要件を満たす企業内転勤。"],
["Entrepreneur Visa","Visado para emprendedores","Visa entrepreneur","Unternehmervisum","企业家签证","تأشيرة رائد الأعمال","Visto para empreendedores","起業家ビザ"],
["Innovative entrepreneurial activity of particular economic interest.","Actividad emprendedora innovadora de especial interés económico.","Activité entrepreneuriale innovante présentant un intérêt économique particulier.","Innovative unternehmerische Tätigkeit von besonderem wirtschaftlichem Interesse.","具有特殊经济利益的创新创业活动。","نشاط ريادي مبتكر ذي أهمية اقتصادية خاصة.","Atividade empreendedora inovadora de especial interesse económico.","特に経済的利益が認められる革新的な起業活動。"],
["Digital Nomad Visa","Visado para nómadas digitales","Visa nomade numérique","Visum für digitale Nomaden","数字游民签证","تأشيرة الرحّل الرقميين","Visto para nómadas digitais","デジタルノマドビザ"],
["Residence for qualifying international remote workers.","Residencia para trabajadores remotos internacionales que cumplen los requisitos.","Résidence pour les travailleurs à distance internationaux admissibles.","Aufenthalt für qualifizierende internationale Remote-Arbeitnehmer.","适用于符合条件的国际远程工作者的居留。","إقامة للعاملين الدوليين عن بُعد المستوفين للشروط.","Residência para trabalhadores remotos internacionais elegíveis.","要件を満たす国際リモートワーカーのための居住。"],
["Researcher Visa","Visado para investigadores","Visa chercheur","Forschervisum","研究人员签证","تأشيرة الباحث","Visto para investigadores","研究者ビザ"],
["Research, development and innovation activity.","Actividad de investigación, desarrollo e innovación.","Activité de recherche, développement et innovation.","Forschungs-, Entwicklungs- und Innovationstätigkeit.","研究、开发与创新活动。","نشاط البحث والتطوير والابتكار.","Atividade de investigação, desenvolvimento e inovação.","研究・開発・イノベーション活動。"],
["Audiovisual Sector Professional Visa","Visado para profesionales del sector audiovisual","Visa pour professionnels du secteur audiovisuel","Visum für Fachkräfte im audiovisuellen Sektor","视听行业专业人士签证","تأشيرة مهنيي قطاع السمعي البصري","Visto para profissionais do setor audiovisual","映像・音響分野専門職ビザ"],
["Qualifying audiovisual professionals.","Profesionales audiovisuales que cumplen los requisitos.","Professionnels de l’audiovisuel admissibles.","Qualifizierende Fachkräfte im audiovisuellen Bereich.","符合条件的视听行业专业人士。","المهنيون المؤهلون في قطاع السمعي البصري.","Profissionais do setor audiovisual elegíveis.","対象となる映像・音響分野の専門職。"],
["Work Visa with Permit Exemption","Visado de trabajo con exención de autorización","Visa de travail avec dispense d’autorisation","Arbeitsvisum mit Befreiung von der Arbeitserlaubnis","免工作许可签证","تأشيرة عمل مع إعفاء من التصريح","Visto de trabalho com isenção de autorização","就労許可免除付き就労ビザ"],
["Specified work categories exempt from ordinary work authorisation.","Categorías de trabajo específicas exentas de la autorización de trabajo ordinaria.","Catégories de travail déterminées dispensées de l’autorisation de travail ordinaire.","Bestimmte Arbeitskategorien, die von der regulären Arbeitserlaubnis befreit sind.","免于一般工作许可的指定工作类别。","فئات عمل محددة معفاة من تصريح العمل العادي.","Categorias de trabalho específicas isentas da autorização de trabalho normal.","通常の就労許可が免除される指定就労カテゴリー。"],
["Non-lucrative Residence Visa","Visado de residencia no lucrativa","Visa de résidence non lucrative","Visum für nicht-erwerbstätigen Aufenthalt","非营利居留签证","تأشيرة إقامة غير ربحية","Visto de residência não lucrativa","非就労居住ビザ"],
["Residence without gainful activity.","Residencia sin actividad lucrativa.","Résidence sans activité rémunérée.","Aufenthalt ohne Erwerbstätigkeit.","不从事有报酬活动的居留。","إقامة دون نشاط مدر للدخل.","Residência sem atividade remunerada.","就労を伴わない居住。"],
["Study Visa","Visado de estudios","Visa d’études","Studienvisum","学习签证","تأشيرة دراسة","Visto de estudos","留学ビザ"],
["Long-term study, training and related eligible activities.","Estudios de larga duración, formación y actividades relacionadas que cumplen los requisitos.","Études de longue durée, formation et activités connexes admissibles.","Langzeitstudium, Ausbildung und damit verbundene qualifizierende Tätigkeiten.","长期学习、培训及相关符合条件的活动。","الدراسة طويلة الأجل والتدريب والأنشطة ذات الصلة المستوفية للشروط.","Estudos de longa duração, formação e atividades relacionadas elegíveis.","長期就学、研修および関連する対象活動。"],
["Internship Visa","Visado de prácticas","Visa de stage","Praktikumsvisum","实习签证","تأشيرة تدريب عملي","Visto de estágio","インターンシップビザ"],
["Qualifying internship.","Prácticas que cumplen los requisitos.","Stage admissible.","Qualifizierendes Praktikum.","符合条件的实习。","تدريب عملي مستوفٍ للشروط.","Estágio elegível.","対象となるインターンシップ。"],
["Family Reunification Visa","Visado de reagrupación familiar","Visa de regroupement familial","Visum zum Familiennachzug","家庭团聚签证","تأشيرة لمّ شمل الأسرة","Visto de reagrupamento familiar","家族再統合ビザ"],
["Join qualifying non-EU resident family.","Reunirse con un familiar residente no perteneciente a la UE que cumpla los requisitos.","Rejoindre un membre de la famille résident hors UE admissible.","Nachzug zu einem berechtigten, nicht der EU angehörenden Familienmitglied mit Aufenthalt.","与符合条件的非欧盟居民家庭成员团聚。","الانضمام إلى فرد أسرة مقيم من خارج الاتحاد الأوروبي ومستوفٍ للشروط.","Juntar-se a um familiar residente não UE elegível.","要件を満たす非EU居住家族との合流。"],
["Family of Spanish Citizen Visa","Visado para familiares de ciudadanos españoles","Visa pour famille d’un citoyen espagnol","Visum für Familienangehörige spanischer Staatsbürger","西班牙公民家属签证","تأشيرة أسرة المواطن الإسباني","Visto para familiares de cidadão espanhol","スペイン国民の家族ビザ"],
["Residence for qualifying family of Spanish citizens.","Residencia para familiares de ciudadanos españoles que cumplen los requisitos.","Résidence pour les membres de famille admissibles de citoyens espagnols.","Aufenthalt für berechtigte Familienangehörige spanischer Staatsbürger.","适用于符合条件的西班牙公民家属的居留。","إقامة لأفراد أسرة المواطنين الإسبان المستوفين للشروط.","Residência para familiares elegíveis de cidadãos espanhóis.","要件を満たすスペイン国民の家族のための居住。"],
["Family of EU Citizen Visa","Visado para familiares de ciudadanos de la UE","Visa pour famille d’un citoyen de l’UE","Visum für Familienangehörige von EU-Bürgern","欧盟公民家属签证","تأشيرة أسرة مواطن الاتحاد الأوروبي","Visto para familiares de cidadão da UE","EU市民の家族ビザ"],
["Qualifying family under EU free-movement rules.","Familiares que cumplen los requisitos conforme a las normas de libre circulación de la UE.","Famille admissible au titre des règles de libre circulation de l’UE.","Berechtigte Familienangehörige nach EU-Freizügigkeitsregeln.","符合欧盟自由流动规定的家属。","أفراد الأسرة المؤهلون بموجب قواعد حرية التنقل في الاتحاد الأوروبي.","Familiares elegíveis ao abrigo das regras de livre circulação da UE.","EU自由移動規則に基づく対象家族。"],
["Long-term / EU Long-term Residence Recovery Visa","Visado de recuperación de residencia de larga duración / larga duración UE","Visa de récupération du statut de résident longue durée / longue durée UE","Visum zur Wiedererlangung des Daueraufenthalts / EU-Daueraufenthalts","长期／欧盟长期居留恢复签证","تأشيرة استعادة الإقامة طويلة الأجل / طويلة الأجل في الاتحاد الأوروبي","Visto de recuperação de residência de longa duração / longa duração UE","長期居住／EU長期居住回復ビザ"],
["Recover qualifying long-term residence status.","Recuperar un estatus de residencia de larga duración que cumpla los requisitos.","Rétablir un statut de résident de longue durée admissible.","Wiedererlangung eines qualifizierenden Daueraufenthaltsstatus.","恢复符合条件的长期居留身份。","استعادة وضع إقامة طويلة الأجل مستوفٍ للشروط.","Recuperar um estatuto de residência de longa duração elegível.","要件を満たす長期居住資格の回復。"],
["Schengen Visa","Visado Schengen","Visa Schengen","Schengen-Visum","申根签证","تأشيرة شنغن","Visto Schengen","シェンゲンビザ"],
["Short tourism, business, family and other permitted stays.","Estancias cortas por turismo, negocios, familia y otros fines permitidos.","Courts séjours pour tourisme, affaires, famille et autres motifs autorisés.","Kurze Aufenthalte für Tourismus, Geschäft, Familie und andere zulässige Zwecke.","旅游、商务、探亲及其他允许目的的短期停留。","إقامات قصيرة للسياحة والأعمال والأسرة وغيرها من الأغراض المسموح بها.","Estadias curtas para turismo, negócios, família e outros fins permitidos.","観光、商用、家族訪問その他認められた目的の短期滞在。"],
["Airport Transit Visa","Visado de tránsito aeroportuario","Visa de transit aéroportuaire","Flughafentransitvisum","机场过境签证","تأشيرة عبور المطار","Visto de trânsito aeroportuário","空港通過ビザ"],
["Airport transit where required.","Tránsito aeroportuario cuando sea obligatorio.","Transit aéroportuaire lorsque requis.","Flughafentransit, sofern erforderlich.","需要时用于机场过境。","عبور المطار عند الحاجة.","Trânsito aeroportuário quando exigido.","必要な場合の空港通過。"]
];
const langs=["es","fr","de","zh","ar","pt","ja"];
const translations: Record<string,Record<string,string>> = Object.fromEntries(
  langs.map((lang,i)=>[lang,Object.fromEntries(rows.map(row=>[row[0],row[i+1]]))])
);
export default translations;
