const translations: Record<string, Record<string, string>> = {
  es: {
    "Professional & Talent":"Profesionales y talento",
    "Talent Passport / Talent residence routes":"Pasaporte Talento / vías de residencia para talento",
    "Qualifying highly skilled, innovative, artistic, research and investment profiles.":"Perfiles altamente cualificados, innovadores, artísticos, de investigación e inversión que cumplan los requisitos.",
    "Employee / salaried worker":"Empleado / trabajador asalariado",
    "Long-stay employment route.":"Vía de empleo de larga estancia.",
    "Temporary worker":"Trabajador temporal",
    "Temporary salaried employment.":"Empleo asalariado temporal.",
    "Entrepreneur / self-employed":"Emprendedor / trabajador por cuenta propia",
    "Business creation or self-employed professional activity.":"Creación de empresa o actividad profesional por cuenta propia.",
    "Intra-company mobility":"Movilidad intraempresarial",
    "Qualifying assignments within international groups.":"Asignaciones que cumplan los requisitos dentro de grupos internacionales.",
    "Researcher":"Investigador",
    "Research and academic mobility.":"Investigación y movilidad académica.",
    "Artist / cultural profession":"Artista / profesión cultural",
    "Qualifying artistic and cultural professional activity.":"Actividad profesional artística y cultural que cumpla los requisitos.",
    "Working Holiday":"Working Holiday",
    "Youth mobility for eligible nationalities.":"Movilidad juvenil para nacionalidades elegibles.",
    "Study & Training":"Estudios y formación",
    "Student":"Estudiante",
    "Long-stay study.":"Estudios de larga estancia.",
    "Student – entrance examination":"Estudiante – examen de ingreso",
    "Short-stay student examination route.":"Vía de corta estancia para realizar un examen de ingreso.",
    "School-going minor":"Menor escolarizado",
    "Long-stay schooling for eligible minors.":"Escolarización de larga estancia para menores elegibles.",
    "Intern / trainee":"Prácticas / formación",
    "Qualifying internship or professional training.":"Prácticas o formación profesional que cumplan los requisitos.",
    "Au pair":"Au pair",
    "Eligible au-pair stay.":"Estancia au pair que cumpla los requisitos.",
    "Family":"Familia",
    "Family of French national":"Familia de ciudadano francés",
    "Spouse, child, parent and other qualifying relationships.":"Cónyuge, hijo, progenitor y otras relaciones que cumplan los requisitos.",
    "Family reunification":"Reagrupación familiar",
    "Join an eligible foreign resident in France.":"Reunirse con un residente extranjero elegible en Francia.",
    "Family of EU/EEA/Swiss citizen":"Familia de ciudadano de la UE/EEE/Suiza",
    "Qualifying family-member route.":"Vía para familiares que cumplan los requisitos.",
    "Visit & Other":"Visita y otros",
    "Schengen short-stay visa":"Visa Schengen de corta estancia",
    "Tourism, business, family visits and other stays up to 90 days.":"Turismo, negocios, visitas familiares y otras estancias de hasta 90 días.",
    "Airport transit visa":"Visa de tránsito aeroportuario",
    "Transit through the international zone where required.":"Tránsito por la zona internacional cuando sea obligatorio.",
    "Long-stay visitor":"Visitante de larga estancia",
    "Residence without professional activity.":"Residencia sin actividad profesional.",
    "Medical stay":"Estancia médica",
    "Travel connected with medical treatment.":"Viaje relacionado con tratamiento médico.",
    "Overseas territories visa":"Visa para territorios de ultramar",
    "Visas applicable to French overseas territories where required.":"Visas aplicables a los territorios franceses de ultramar cuando sean necesarias."
  },
  fr: {
    "Professional & Talent":"Professionnels et talents",
    "Talent Passport / Talent residence routes":"Passeport talent / titres de séjour talent",
    "Qualifying highly skilled, innovative, artistic, research and investment profiles.":"Profils admissibles hautement qualifiés, innovants, artistiques, de recherche ou d’investissement.",
    "Employee / salaried worker":"Salarié",
    "Long-stay employment route.":"Voie de long séjour pour emploi.",
    "Temporary worker":"Travailleur temporaire",
    "Temporary salaried employment.":"Emploi salarié temporaire.",
    "Entrepreneur / self-employed":"Entrepreneur / indépendant",
    "Business creation or self-employed professional activity.":"Création d’entreprise ou activité professionnelle indépendante.",
    "Intra-company mobility":"Mobilité intra-groupe",
    "Qualifying assignments within international groups.":"Missions admissibles au sein de groupes internationaux.",
    "Researcher":"Chercheur",
    "Research and academic mobility.":"Recherche et mobilité académique.",
    "Artist / cultural profession":"Artiste / profession culturelle",
    "Qualifying artistic and cultural professional activity.":"Activité professionnelle artistique et culturelle admissible.",
    "Working Holiday":"Vacances-travail",
    "Youth mobility for eligible nationalities.":"Mobilité des jeunes pour les nationalités admissibles.",
    "Study & Training":"Études et formation",
    "Student":"Étudiant",
    "Long-stay study.":"Études de long séjour.",
    "Student – entrance examination":"Étudiant – concours ou examen d’entrée",
    "Short-stay student examination route.":"Voie de court séjour pour passer un examen d’entrée.",
    "School-going minor":"Mineur scolarisé",
    "Long-stay schooling for eligible minors.":"Scolarité de long séjour pour les mineurs admissibles.",
    "Intern / trainee":"Stagiaire",
    "Qualifying internship or professional training.":"Stage ou formation professionnelle admissible.",
    "Au pair":"Au pair",
    "Eligible au-pair stay.":"Séjour au pair admissible.",
    "Family":"Famille",
    "Family of French national":"Famille d’un ressortissant français",
    "Spouse, child, parent and other qualifying relationships.":"Conjoint, enfant, parent et autres liens familiaux admissibles.",
    "Family reunification":"Regroupement familial",
    "Join an eligible foreign resident in France.":"Rejoindre un résident étranger admissible en France.",
    "Family of EU/EEA/Swiss citizen":"Famille d’un citoyen UE/EEE/Suisse",
    "Qualifying family-member route.":"Voie pour membre de famille admissible.",
    "Visit & Other":"Visite et autres",
    "Schengen short-stay visa":"Visa Schengen de court séjour",
    "Tourism, business, family visits and other stays up to 90 days.":"Tourisme, affaires, visites familiales et autres séjours jusqu’à 90 jours.",
    "Airport transit visa":"Visa de transit aéroportuaire",
    "Transit through the international zone where required.":"Transit par la zone internationale lorsqu’il est requis.",
    "Long-stay visitor":"Visiteur de long séjour",
    "Residence without professional activity.":"Résidence sans activité professionnelle.",
    "Medical stay":"Séjour pour soins médicaux",
    "Travel connected with medical treatment.":"Voyage lié à un traitement médical.",
    "Overseas territories visa":"Visa pour les territoires d’outre-mer",
    "Visas applicable to French overseas territories where required.":"Visas applicables aux territoires français d’outre-mer lorsqu’ils sont requis."
  },
  de: {
    "Professional & Talent":"Beruf und Talente",
    "Talent Passport / Talent residence routes":"Talent Passport / Aufenthaltswege für Talente",
    "Qualifying highly skilled, innovative, artistic, research and investment profiles.":"Berechtigte hochqualifizierte, innovative, künstlerische, Forschungs- und Investitionsprofile.",
    "Employee / salaried worker":"Arbeitnehmer / Beschäftigte",
    "Long-stay employment route.":"Langfristiger Aufenthaltsweg für Beschäftigung.",
    "Temporary worker":"Vorübergehender Arbeitnehmer",
    "Temporary salaried employment.":"Vorübergehende abhängige Beschäftigung.",
    "Entrepreneur / self-employed":"Unternehmer / Selbstständige",
    "Business creation or self-employed professional activity.":"Unternehmensgründung oder selbstständige berufliche Tätigkeit.",
    "Intra-company mobility":"Unternehmensinterne Mobilität",
    "Qualifying assignments within international groups.":"Berechtigte Einsätze innerhalb internationaler Unternehmensgruppen.",
    "Researcher":"Forscher",
    "Research and academic mobility.":"Forschung und akademische Mobilität.",
    "Artist / cultural profession":"Künstler / Kulturberuf",
    "Qualifying artistic and cultural professional activity.":"Berechtigte künstlerische und kulturelle Berufstätigkeit.",
    "Working Holiday":"Working Holiday",
    "Youth mobility for eligible nationalities.":"Jugendmobilität für berechtigte Staatsangehörigkeiten.",
    "Study & Training":"Studium und Ausbildung",
    "Student":"Studierende",
    "Long-stay study.":"Langfristiges Studium.",
    "Student – entrance examination":"Studierende – Aufnahmeprüfung",
    "Short-stay student examination route.":"Kurzaufenthaltsweg für eine Aufnahmeprüfung.",
    "School-going minor":"Schulpflichtiger Minderjähriger",
    "Long-stay schooling for eligible minors.":"Langfristiger Schulbesuch für berechtigte Minderjährige.",
    "Intern / trainee":"Praktikant / Auszubildender",
    "Qualifying internship or professional training.":"Berechtigtes Praktikum oder berufliche Ausbildung.",
    "Au pair":"Au-pair",
    "Eligible au-pair stay.":"Berechtigter Au-pair-Aufenthalt.",
    "Family":"Familie",
    "Family of French national":"Familie eines französischen Staatsangehörigen",
    "Spouse, child, parent and other qualifying relationships.":"Ehepartner, Kinder, Eltern und andere berechtigte Beziehungen.",
    "Family reunification":"Familiennachzug",
    "Join an eligible foreign resident in France.":"Nachzug zu einem berechtigten ausländischen Einwohner in Frankreich.",
    "Family of EU/EEA/Swiss citizen":"Familie eines EU-/EWR-/Schweizer Bürgers",
    "Qualifying family-member route.":"Weg für berechtigte Familienangehörige.",
    "Visit & Other":"Besuch und Sonstiges",
    "Schengen short-stay visa":"Schengen-Visum für Kurzaufenthalte",
    "Tourism, business, family visits and other stays up to 90 days.":"Tourismus, Geschäftsreisen, Familienbesuche und andere Aufenthalte bis zu 90 Tagen.",
    "Airport transit visa":"Flughafentransitvisum",
    "Transit through the international zone where required.":"Transit durch den internationalen Bereich, sofern erforderlich.",
    "Long-stay visitor":"Besucher für Langzeitaufenthalt",
    "Residence without professional activity.":"Aufenthalt ohne berufliche Tätigkeit.",
    "Medical stay":"Medizinischer Aufenthalt",
    "Travel connected with medical treatment.":"Reise im Zusammenhang mit medizinischer Behandlung.",
    "Overseas territories visa":"Visum für Überseegebiete",
    "Visas applicable to French overseas territories where required.":"Visa für französische Überseegebiete, sofern erforderlich."
  },
  zh: {
    "Professional & Talent":"专业人士与人才",
    "Talent Passport / Talent residence routes":"人才护照 / 人才居留途径",
    "Qualifying highly skilled, innovative, artistic, research and investment profiles.":"面向符合条件的高技能、创新、艺术、科研及投资类人士。",
    "Employee / salaried worker":"雇员 / 受薪工作者",
    "Long-stay employment route.":"长期就业居留途径。",
    "Temporary worker":"临时工作者",
    "Temporary salaried employment.":"临时受薪就业。",
    "Entrepreneur / self-employed":"企业家 / 自雇人士",
    "Business creation or self-employed professional activity.":"创办企业或开展自雇专业活动。",
    "Intra-company mobility":"公司内部流动",
    "Qualifying assignments within international groups.":"国际企业集团内符合条件的派遣任务。",
    "Researcher":"研究人员",
    "Research and academic mobility.":"科研与学术流动。",
    "Artist / cultural profession":"艺术家 / 文化专业人士",
    "Qualifying artistic and cultural professional activity.":"符合条件的艺术和文化专业活动。",
    "Working Holiday":"打工度假",
    "Youth mobility for eligible nationalities.":"面向符合条件国籍青年人士的流动途径。",
    "Study & Training":"学习与培训",
    "Student":"学生",
    "Long-stay study.":"长期学习。",
    "Student – entrance examination":"学生 – 入学考试",
    "Short-stay student examination route.":"为参加入学考试而设置的短期停留途径。",
    "School-going minor":"就学未成年人",
    "Long-stay schooling for eligible minors.":"面向符合条件未成年人的长期就学途径。",
    "Intern / trainee":"实习生 / 培训人员",
    "Qualifying internship or professional training.":"符合条件的实习或职业培训。",
    "Au pair":"互惠生",
    "Eligible au-pair stay.":"符合条件的互惠生停留。",
    "Family":"家庭",
    "Family of French national":"法国公民家庭成员",
    "Spouse, child, parent and other qualifying relationships.":"配偶、子女、父母及其他符合条件的亲属关系。",
    "Family reunification":"家庭团聚",
    "Join an eligible foreign resident in France.":"与在法国居住且符合条件的外国居民团聚。",
    "Family of EU/EEA/Swiss citizen":"欧盟/欧洲经济区/瑞士公民家庭成员",
    "Qualifying family-member route.":"面向符合条件家庭成员的途径。",
    "Visit & Other":"访问及其他",
    "Schengen short-stay visa":"申根短期签证",
    "Tourism, business, family visits and other stays up to 90 days.":"旅游、商务、探亲及其他最长 90 天的停留。",
    "Airport transit visa":"机场过境签证",
    "Transit through the international zone where required.":"在需要时通过机场国际区过境。",
    "Long-stay visitor":"长期访客",
    "Residence without professional activity.":"不从事职业活动的居留。",
    "Medical stay":"医疗停留",
    "Travel connected with medical treatment.":"与医疗治疗相关的旅行。",
    "Overseas territories visa":"海外领地签证",
    "Visas applicable to French overseas territories where required.":"在需要时适用于法国海外领地的签证。"
  },
  ar: {
    "Professional & Talent":"المهنيون والمواهب",
    "Talent Passport / Talent residence routes":"جواز المواهب / مسارات إقامة المواهب",
    "Qualifying highly skilled, innovative, artistic, research and investment profiles.":"لفئات مؤهلة من ذوي المهارات العالية والمبتكرين والفنانين والباحثين والمستثمرين.",
    "Employee / salaried worker":"موظف / عامل بأجر",
    "Long-stay employment route.":"مسار إقامة طويلة للعمل.",
    "Temporary worker":"عامل مؤقت",
    "Temporary salaried employment.":"عمل مؤقت بأجر.",
    "Entrepreneur / self-employed":"رائد أعمال / عامل مستقل",
    "Business creation or self-employed professional activity.":"إنشاء مشروع أو ممارسة نشاط مهني مستقل.",
    "Intra-company mobility":"التنقل داخل الشركة",
    "Qualifying assignments within international groups.":"مهام مستوفية للشروط داخل مجموعات دولية.",
    "Researcher":"باحث",
    "Research and academic mobility.":"البحث والتنقل الأكاديمي.",
    "Artist / cultural profession":"فنان / مهنة ثقافية",
    "Qualifying artistic and cultural professional activity.":"نشاط مهني فني وثقافي مستوفٍ للشروط.",
    "Working Holiday":"عطلة العمل",
    "Youth mobility for eligible nationalities.":"تنقل الشباب للجنسيات المؤهلة.",
    "Study & Training":"الدراسة والتدريب",
    "Student":"طالب",
    "Long-stay study.":"دراسة بإقامة طويلة.",
    "Student – entrance examination":"طالب – امتحان دخول",
    "Short-stay student examination route.":"مسار إقامة قصيرة لأداء امتحان دخول.",
    "School-going minor":"قاصر ملتحق بالمدرسة",
    "Long-stay schooling for eligible minors.":"دراسة مدرسية طويلة الإقامة للقاصرين المؤهلين.",
    "Intern / trainee":"متدرب",
    "Qualifying internship or professional training.":"تدريب عملي أو مهني مستوفٍ للشروط.",
    "Au pair":"أو بير",
    "Eligible au-pair stay.":"إقامة أو بير مستوفية للشروط.",
    "Family":"الأسرة",
    "Family of French national":"أسرة مواطن فرنسي",
    "Spouse, child, parent and other qualifying relationships.":"الزوج أو الطفل أو الوالد وعلاقات أخرى مستوفية للشروط.",
    "Family reunification":"لمّ شمل الأسرة",
    "Join an eligible foreign resident in France.":"الالتحاق بمقيم أجنبي مؤهل في فرنسا.",
    "Family of EU/EEA/Swiss citizen":"أسرة مواطن من الاتحاد الأوروبي/المنطقة الاقتصادية الأوروبية/سويسرا",
    "Qualifying family-member route.":"مسار لأفراد الأسرة المستوفين للشروط.",
    "Visit & Other":"الزيارة وفئات أخرى",
    "Schengen short-stay visa":"تأشيرة شنغن قصيرة الإقامة",
    "Tourism, business, family visits and other stays up to 90 days.":"السياحة والأعمال والزيارات العائلية وإقامات أخرى تصل إلى 90 يوماً.",
    "Airport transit visa":"تأشيرة عبور المطار",
    "Transit through the international zone where required.":"العبور عبر المنطقة الدولية عند الحاجة.",
    "Long-stay visitor":"زائر بإقامة طويلة",
    "Residence without professional activity.":"إقامة دون نشاط مهني.",
    "Medical stay":"إقامة طبية",
    "Travel connected with medical treatment.":"سفر مرتبط بعلاج طبي.",
    "Overseas territories visa":"تأشيرة الأقاليم ما وراء البحار",
    "Visas applicable to French overseas territories where required.":"تأشيرات تنطبق على الأقاليم الفرنسية ما وراء البحار عند الحاجة."
  },
  pt: {
    "Professional & Talent":"Profissionais e talento",
    "Talent Passport / Talent residence routes":"Passaporte Talento / vias de residência para talento",
    "Qualifying highly skilled, innovative, artistic, research and investment profiles.":"Perfis elegíveis altamente qualificados, inovadores, artísticos, de investigação e investimento.",
    "Employee / salaried worker":"Empregado / trabalhador assalariado",
    "Long-stay employment route.":"Via de emprego de longa duração.",
    "Temporary worker":"Trabalhador temporário",
    "Temporary salaried employment.":"Emprego assalariado temporário.",
    "Entrepreneur / self-employed":"Empreendedor / trabalhador independente",
    "Business creation or self-employed professional activity.":"Criação de empresa ou atividade profissional por conta própria.",
    "Intra-company mobility":"Mobilidade intraempresa",
    "Qualifying assignments within international groups.":"Missões elegíveis dentro de grupos internacionais.",
    "Researcher":"Investigador",
    "Research and academic mobility.":"Investigação e mobilidade académica.",
    "Artist / cultural profession":"Artista / profissão cultural",
    "Qualifying artistic and cultural professional activity.":"Atividade profissional artística e cultural elegível.",
    "Working Holiday":"Working Holiday",
    "Youth mobility for eligible nationalities.":"Mobilidade jovem para nacionalidades elegíveis.",
    "Study & Training":"Estudo e formação",
    "Student":"Estudante",
    "Long-stay study.":"Estudo de longa duração.",
    "Student – entrance examination":"Estudante – exame de admissão",
    "Short-stay student examination route.":"Via de curta duração para realizar exame de admissão.",
    "School-going minor":"Menor em idade escolar",
    "Long-stay schooling for eligible minors.":"Escolaridade de longa duração para menores elegíveis.",
    "Intern / trainee":"Estagiário",
    "Qualifying internship or professional training.":"Estágio ou formação profissional elegível.",
    "Au pair":"Au pair",
    "Eligible au-pair stay.":"Estadia au pair elegível.",
    "Family":"Família",
    "Family of French national":"Família de cidadão francês",
    "Spouse, child, parent and other qualifying relationships.":"Cônjuge, filho, progenitor e outras relações elegíveis.",
    "Family reunification":"Reagrupamento familiar",
    "Join an eligible foreign resident in France.":"Juntar-se a um residente estrangeiro elegível em França.",
    "Family of EU/EEA/Swiss citizen":"Família de cidadão da UE/EEE/Suíça",
    "Qualifying family-member route.":"Via para familiar elegível.",
    "Visit & Other":"Visita e outros",
    "Schengen short-stay visa":"Visto Schengen de curta duração",
    "Tourism, business, family visits and other stays up to 90 days.":"Turismo, negócios, visitas familiares e outras estadias até 90 dias.",
    "Airport transit visa":"Visto de trânsito aeroportuário",
    "Transit through the international zone where required.":"Trânsito pela zona internacional quando exigido.",
    "Long-stay visitor":"Visitante de longa duração",
    "Residence without professional activity.":"Residência sem atividade profissional.",
    "Medical stay":"Estadia médica",
    "Travel connected with medical treatment.":"Viagem relacionada com tratamento médico.",
    "Overseas territories visa":"Visto para territórios ultramarinos",
    "Visas applicable to French overseas territories where required.":"Vistos aplicáveis aos territórios ultramarinos franceses quando exigidos."
  },
  ja: {
    "Professional & Talent":"専門職・人材",
    "Talent Passport / Talent residence routes":"タレント・パスポート / 人材向け滞在ルート",
    "Qualifying highly skilled, innovative, artistic, research and investment profiles.":"要件を満たす高度技能、イノベーション、芸術、研究、投資分野の人材向けです。",
    "Employee / salaried worker":"雇用者 / 給与所得者",
    "Long-stay employment route.":"長期滞在を伴う就労ルート。",
    "Temporary worker":"一時就労者",
    "Temporary salaried employment.":"一時的な給与所得による就労。",
    "Entrepreneur / self-employed":"起業家 / 自営業",
    "Business creation or self-employed professional activity.":"事業設立または自営業としての専門活動。",
    "Intra-company mobility":"企業内移動",
    "Qualifying assignments within international groups.":"国際企業グループ内の要件を満たす派遣。",
    "Researcher":"研究者",
    "Research and academic mobility.":"研究および学術的な移動。",
    "Artist / cultural profession":"芸術家 / 文化専門職",
    "Qualifying artistic and cultural professional activity.":"要件を満たす芸術・文化分野の専門活動。",
    "Working Holiday":"ワーキングホリデー",
    "Youth mobility for eligible nationalities.":"対象国籍の若者向けモビリティ制度。",
    "Study & Training":"留学・研修",
    "Student":"学生",
    "Long-stay study.":"長期留学。",
    "Student – entrance examination":"学生 – 入学試験",
    "Short-stay student examination route.":"入学試験を受けるための短期滞在ルート。",
    "School-going minor":"就学する未成年者",
    "Long-stay schooling for eligible minors.":"要件を満たす未成年者向けの長期就学。",
    "Intern / trainee":"インターン / 研修生",
    "Qualifying internship or professional training.":"要件を満たすインターンシップまたは職業訓練。",
    "Au pair":"オペア",
    "Eligible au-pair stay.":"要件を満たすオペア滞在。",
    "Family":"家族",
    "Family of French national":"フランス国民の家族",
    "Spouse, child, parent and other qualifying relationships.":"配偶者、子ども、親、その他の要件を満たす家族関係。",
    "Family reunification":"家族再統合",
    "Join an eligible foreign resident in France.":"フランスに居住する要件を満たす外国人との合流。",
    "Family of EU/EEA/Swiss citizen":"EU/EEA/スイス市民の家族",
    "Qualifying family-member route.":"要件を満たす家族向けのルート。",
    "Visit & Other":"訪問・その他",
    "Schengen short-stay visa":"シェンゲン短期滞在ビザ",
    "Tourism, business, family visits and other stays up to 90 days.":"観光、商用、家族訪問、その他90日以内の滞在。",
    "Airport transit visa":"空港通過ビザ",
    "Transit through the international zone where required.":"必要な場合に国際区域を通過するためのビザ。",
    "Long-stay visitor":"長期訪問者",
    "Residence without professional activity.":"職業活動を行わない滞在。",
    "Medical stay":"医療滞在",
    "Travel connected with medical treatment.":"医療を受けることに関連する渡航。",
    "Overseas territories visa":"海外領土ビザ",
    "Visas applicable to French overseas territories where required.":"必要に応じてフランス海外領土に適用されるビザ。"
  }
};
export default translations;
