const translations: Record<string, Record<string, string>> = {
  es: {
    "Work & Talent":"Trabajo y talento",
    "Highly skilled migrant":"Migrante altamente cualificado",
    "Employment with an IND-recognised sponsor.":"Empleo con un patrocinador reconocido por el IND.",
    "EU Blue Card":"Tarjeta Azul de la UE",
    "Highly qualified employment route.":"Vía de empleo altamente cualificado.",
    "Paid employment / single permit (GVVA)":"Empleo remunerado / permiso único (GVVA)",
    "Employment requiring combined residence and work authorisation.":"Empleo que requiere una autorización combinada de residencia y trabajo.",
    "Intra-corporate transferee":"Traslado intraempresarial",
    "Manager, specialist or trainee transfer.":"Traslado de directivo, especialista o trabajador en formación.",
    "Researcher":"Investigador",
    "Scientific research under the relevant directive.":"Investigación científica conforme a la directiva aplicable.",
    "Orientation year":"Año de orientación",
    "Post-study/research job-search year for eligible graduates and researchers.":"Año posterior a estudios o investigación para buscar empleo, destinado a graduados e investigadores elegibles.",
    "Essential start-up personnel":"Personal esencial de start-up",
    "Pilot residence route for qualifying start-up employees.":"Vía piloto de residencia para empleados de start-ups que cumplan los requisitos.",
    "Seasonal work":"Trabajo estacional",
    "Qualifying seasonal employment.":"Empleo estacional que cumpla los requisitos.",
    "Working holiday":"Working Holiday",
    "Youth exchange/work holiday where eligible.":"Intercambio juvenil y trabajo durante vacaciones cuando se cumplan los requisitos.",
    "Business":"Negocios",
    "Start-up":"Start-up",
    "Innovative business with a recognised facilitator.":"Empresa innovadora con un facilitador reconocido.",
    "Self-employed person":"Trabajador por cuenta propia",
    "Entrepreneur or self-employed professional route.":"Vía para emprendedores o profesionales por cuenta propia.",
    "Foreign investor / business routes":"Inversor extranjero / vías empresariales",
    "Applicable business residence permissions under current IND rules.":"Permisos de residencia empresarial aplicables conforme a las normas vigentes del IND.",
    "Study":"Estudios",
    "Study at university or higher professional education":"Estudios universitarios o educación profesional superior",
    "Residence for recognised higher education.":"Residencia para cursar educación superior reconocida.",
    "Secondary or vocational education":"Educación secundaria o profesional",
    "Qualifying secondary/MBO study.":"Estudios secundarios o MBO que cumplan los requisitos.",
    "Exchange":"Intercambio",
    "Recognised exchange programmes.":"Programas de intercambio reconocidos.",
    "Family & Other":"Familia y otros",
    "Partner / spouse":"Pareja / cónyuge",
    "Residence with a qualifying partner.":"Residencia con una pareja que cumpla los requisitos.",
    "Minor child":"Hijo menor",
    "Family residence for qualifying children.":"Residencia familiar para hijos que cumplan los requisitos.",
    "Parent / family under EU law":"Progenitor / familia conforme al derecho de la UE",
    "Applicable family and EU-law routes.":"Vías familiares y de derecho de la UE aplicables.",
    "Short-stay Schengen visa":"Visa Schengen de corta estancia",
    "Visits up to 90 days where required.":"Visitas de hasta 90 días cuando sea necesario.",
    "MVV long-stay entry visa":"Visa de entrada de larga estancia MVV",
    "Provisional residence visa where required.":"Visa provisional de residencia cuando sea necesaria.",
    "Asylum":"Asilo",
    "Protection for qualifying applicants.":"Protección para solicitantes que cumplan los requisitos."
  },
  fr: {
    "Work & Talent":"Travail et talents",
    "Highly skilled migrant":"Migrant hautement qualifié",
    "Employment with an IND-recognised sponsor.":"Emploi auprès d’un sponsor reconnu par l’IND.",
    "EU Blue Card":"Carte bleue européenne",
    "Highly qualified employment route.":"Voie d’emploi hautement qualifié.",
    "Paid employment / single permit (GVVA)":"Emploi salarié / permis unique (GVVA)",
    "Employment requiring combined residence and work authorisation.":"Emploi nécessitant une autorisation combinée de séjour et de travail.",
    "Intra-corporate transferee":"Transfert intra-entreprise",
    "Manager, specialist or trainee transfer.":"Transfert de cadre, spécialiste ou stagiaire.",
    "Researcher":"Chercheur",
    "Scientific research under the relevant directive.":"Recherche scientifique dans le cadre de la directive applicable.",
    "Orientation year":"Année d’orientation",
    "Post-study/research job-search year for eligible graduates and researchers.":"Année de recherche d’emploi après études ou recherche pour les diplômés et chercheurs admissibles.",
    "Essential start-up personnel":"Personnel essentiel de start-up",
    "Pilot residence route for qualifying start-up employees.":"Voie pilote de résidence pour les employés admissibles de start-ups.",
    "Seasonal work":"Travail saisonnier",
    "Qualifying seasonal employment.":"Emploi saisonnier admissible.",
    "Working holiday":"Vacances-travail",
    "Youth exchange/work holiday where eligible.":"Échange de jeunes et vacances-travail lorsque les conditions sont remplies.",
    "Business":"Affaires",
    "Start-up":"Start-up",
    "Innovative business with a recognised facilitator.":"Entreprise innovante avec un facilitateur reconnu.",
    "Self-employed person":"Travailleur indépendant",
    "Entrepreneur or self-employed professional route.":"Voie pour entrepreneur ou professionnel indépendant.",
    "Foreign investor / business routes":"Investisseur étranger / voies d’affaires",
    "Applicable business residence permissions under current IND rules.":"Autorisations de séjour d’affaires applicables selon les règles actuelles de l’IND.",
    "Study":"Études",
    "Study at university or higher professional education":"Études universitaires ou supérieures professionnelles",
    "Residence for recognised higher education.":"Séjour pour suivre un enseignement supérieur reconnu.",
    "Secondary or vocational education":"Enseignement secondaire ou professionnel",
    "Qualifying secondary/MBO study.":"Études secondaires ou MBO admissibles.",
    "Exchange":"Échange",
    "Recognised exchange programmes.":"Programmes d’échange reconnus.",
    "Family & Other":"Famille et autres",
    "Partner / spouse":"Partenaire / conjoint",
    "Residence with a qualifying partner.":"Séjour avec un partenaire admissible.",
    "Minor child":"Enfant mineur",
    "Family residence for qualifying children.":"Séjour familial pour les enfants admissibles.",
    "Parent / family under EU law":"Parent / famille au titre du droit de l’UE",
    "Applicable family and EU-law routes.":"Voies familiales et de droit de l’UE applicables.",
    "Short-stay Schengen visa":"Visa Schengen de court séjour",
    "Visits up to 90 days where required.":"Séjours jusqu’à 90 jours lorsqu’un visa est requis.",
    "MVV long-stay entry visa":"Visa d’entrée long séjour MVV",
    "Provisional residence visa where required.":"Visa provisoire de séjour lorsqu’il est requis.",
    "Asylum":"Asile",
    "Protection for qualifying applicants.":"Protection pour les demandeurs admissibles."
  },
  de: {
    "Work & Talent":"Arbeit und Talente",
    "Highly skilled migrant":"Hochqualifizierter Migrant",
    "Employment with an IND-recognised sponsor.":"Beschäftigung bei einem vom IND anerkannten Sponsor.",
    "EU Blue Card":"EU Blue Card",
    "Highly qualified employment route.":"Aufenthaltsweg für hochqualifizierte Beschäftigung.",
    "Paid employment / single permit (GVVA)":"Bezahlte Beschäftigung / kombinierte Genehmigung (GVVA)",
    "Employment requiring combined residence and work authorisation.":"Beschäftigung, die eine kombinierte Aufenthalts- und Arbeitserlaubnis erfordert.",
    "Intra-corporate transferee":"Unternehmensintern Versetzte",
    "Manager, specialist or trainee transfer.":"Versetzung als Führungskraft, Spezialist oder Trainee.",
    "Researcher":"Forscher",
    "Scientific research under the relevant directive.":"Wissenschaftliche Forschung nach der einschlägigen Richtlinie.",
    "Orientation year":"Orientierungsjahr",
    "Post-study/research job-search year for eligible graduates and researchers.":"Jahr zur Arbeitssuche nach Studium oder Forschung für berechtigte Absolventen und Forschende.",
    "Essential start-up personnel":"Unverzichtbares Start-up-Personal",
    "Pilot residence route for qualifying start-up employees.":"Pilot-Aufenthaltsweg für berechtigte Start-up-Beschäftigte.",
    "Seasonal work":"Saisonarbeit",
    "Qualifying seasonal employment.":"Berechtigte saisonale Beschäftigung.",
    "Working holiday":"Working Holiday",
    "Youth exchange/work holiday where eligible.":"Jugendaustausch bzw. Working Holiday, sofern berechtigt.",
    "Business":"Unternehmen",
    "Start-up":"Start-up",
    "Innovative business with a recognised facilitator.":"Innovatives Unternehmen mit einem anerkannten Facilitator.",
    "Self-employed person":"Selbstständige Person",
    "Entrepreneur or self-employed professional route.":"Weg für Unternehmer oder selbstständige Berufstätige.",
    "Foreign investor / business routes":"Ausländische Investoren / Geschäftswege",
    "Applicable business residence permissions under current IND rules.":"Anwendbare geschäftliche Aufenthaltserlaubnisse nach den aktuellen IND-Regeln.",
    "Study":"Studium",
    "Study at university or higher professional education":"Studium an Universität oder Hochschule für angewandte Wissenschaften",
    "Residence for recognised higher education.":"Aufenthalt für anerkannte Hochschulbildung.",
    "Secondary or vocational education":"Sekundar- oder Berufsausbildung",
    "Qualifying secondary/MBO study.":"Berechtigte Sekundar- oder MBO-Ausbildung.",
    "Exchange":"Austausch",
    "Recognised exchange programmes.":"Anerkannte Austauschprogramme.",
    "Family & Other":"Familie und Sonstiges",
    "Partner / spouse":"Partner / Ehepartner",
    "Residence with a qualifying partner.":"Aufenthalt mit einem berechtigten Partner.",
    "Minor child":"Minderjähriges Kind",
    "Family residence for qualifying children.":"Familienaufenthalt für berechtigte Kinder.",
    "Parent / family under EU law":"Elternteil / Familie nach EU-Recht",
    "Applicable family and EU-law routes.":"Anwendbare Familien- und EU-rechtliche Wege.",
    "Short-stay Schengen visa":"Schengen-Visum für Kurzaufenthalte",
    "Visits up to 90 days where required.":"Besuche bis zu 90 Tagen, sofern erforderlich.",
    "MVV long-stay entry visa":"MVV-Einreisevisum für Langzeitaufenthalt",
    "Provisional residence visa where required.":"Vorläufiges Aufenthaltsvisum, sofern erforderlich.",
    "Asylum":"Asyl",
    "Protection for qualifying applicants.":"Schutz für berechtigte Antragstellende."
  },
  zh: {
    "Work & Talent":"工作与人才",
    "Highly skilled migrant":"高技能移民",
    "Employment with an IND-recognised sponsor.":"受雇于 IND 认可的担保雇主。",
    "EU Blue Card":"欧盟蓝卡",
    "Highly qualified employment route.":"高技能就业途径。",
    "Paid employment / single permit (GVVA)":"受薪就业 / 单一许可（GVVA）",
    "Employment requiring combined residence and work authorisation.":"需要合并居留和工作授权的就业。",
    "Intra-corporate transferee":"公司内部调派",
    "Manager, specialist or trainee transfer.":"经理、专家或培训人员的公司内部调动。",
    "Researcher":"研究人员",
    "Scientific research under the relevant directive.":"依据相关指令开展科学研究。",
    "Orientation year":"求职导向年",
    "Post-study/research job-search year for eligible graduates and researchers.":"面向符合条件毕业生和研究人员的毕业/研究后一年求职期。",
    "Essential start-up personnel":"初创企业核心人员",
    "Pilot residence route for qualifying start-up employees.":"面向符合条件初创企业员工的试点居留途径。",
    "Seasonal work":"季节性工作",
    "Qualifying seasonal employment.":"符合条件的季节性就业。",
    "Working holiday":"打工度假",
    "Youth exchange/work holiday where eligible.":"在符合条件时可使用的青年交流/打工度假途径。",
    "Business":"商业",
    "Start-up":"初创企业",
    "Innovative business with a recognised facilitator.":"与获认可辅导机构合作的创新企业。",
    "Self-employed person":"自雇人士",
    "Entrepreneur or self-employed professional route.":"企业家或自雇专业人士途径。",
    "Foreign investor / business routes":"外国投资者 / 商业途径",
    "Applicable business residence permissions under current IND rules.":"依据现行 IND 规则适用的商业居留许可。",
    "Study":"学习",
    "Study at university or higher professional education":"大学或高等职业教育学习",
    "Residence for recognised higher education.":"用于就读获认可高等教育的居留。",
    "Secondary or vocational education":"中等或职业教育",
    "Qualifying secondary/MBO study.":"符合条件的中等教育/MBO 学习。",
    "Exchange":"交流",
    "Recognised exchange programmes.":"获认可的交流项目。",
    "Family & Other":"家庭及其他",
    "Partner / spouse":"伴侣 / 配偶",
    "Residence with a qualifying partner.":"与符合条件的伴侣共同居留。",
    "Minor child":"未成年子女",
    "Family residence for qualifying children.":"面向符合条件子女的家庭居留。",
    "Parent / family under EU law":"欧盟法下的父母 / 家庭成员",
    "Applicable family and EU-law routes.":"适用的家庭及欧盟法律途径。",
    "Short-stay Schengen visa":"申根短期签证",
    "Visits up to 90 days where required.":"在需要时可用于最长 90 天的访问。",
    "MVV long-stay entry visa":"MVV 长期入境签证",
    "Provisional residence visa where required.":"在需要时使用的临时居留入境签证。",
    "Asylum":"庇护",
    "Protection for qualifying applicants.":"面向符合条件申请人的保护。"
  },
  ar: {
    "Work & Talent":"العمل والمواهب",
    "Highly skilled migrant":"مهاجر عالي المهارة",
    "Employment with an IND-recognised sponsor.":"العمل لدى جهة راعية معترف بها من IND.",
    "EU Blue Card":"البطاقة الزرقاء للاتحاد الأوروبي",
    "Highly qualified employment route.":"مسار عمل عالي التأهيل.",
    "Paid employment / single permit (GVVA)":"عمل مأجور / تصريح موحد (GVVA)",
    "Employment requiring combined residence and work authorisation.":"عمل يتطلب تصريحاً موحداً للإقامة والعمل.",
    "Intra-corporate transferee":"منقول داخل الشركة",
    "Manager, specialist or trainee transfer.":"نقل مدير أو متخصص أو متدرب.",
    "Researcher":"باحث",
    "Scientific research under the relevant directive.":"بحث علمي بموجب التوجيه ذي الصلة.",
    "Orientation year":"سنة التوجيه",
    "Post-study/research job-search year for eligible graduates and researchers.":"سنة للبحث عن عمل بعد الدراسة أو البحث للخريجين والباحثين المؤهلين.",
    "Essential start-up personnel":"الموظفون الأساسيون في الشركات الناشئة",
    "Pilot residence route for qualifying start-up employees.":"مسار إقامة تجريبي لموظفي الشركات الناشئة المستوفين للشروط.",
    "Seasonal work":"عمل موسمي",
    "Qualifying seasonal employment.":"عمل موسمي مستوفٍ للشروط.",
    "Working holiday":"عطلة العمل",
    "Youth exchange/work holiday where eligible.":"تبادل شبابي/عطلة عمل عند استيفاء الشروط.",
    "Business":"الأعمال",
    "Start-up":"شركة ناشئة",
    "Innovative business with a recognised facilitator.":"مشروع مبتكر مع جهة تيسير معترف بها.",
    "Self-employed person":"عامل مستقل",
    "Entrepreneur or self-employed professional route.":"مسار لرائد أعمال أو مهني يعمل لحسابه الخاص.",
    "Foreign investor / business routes":"مستثمر أجنبي / مسارات الأعمال",
    "Applicable business residence permissions under current IND rules.":"تصاريح الإقامة التجارية المطبقة وفق قواعد IND الحالية.",
    "Study":"الدراسة",
    "Study at university or higher professional education":"الدراسة الجامعية أو التعليم المهني العالي",
    "Residence for recognised higher education.":"إقامة للدراسة في تعليم عالٍ معترف به.",
    "Secondary or vocational education":"التعليم الثانوي أو المهني",
    "Qualifying secondary/MBO study.":"دراسة ثانوية أو MBO مستوفية للشروط.",
    "Exchange":"التبادل",
    "Recognised exchange programmes.":"برامج تبادل معترف بها.",
    "Family & Other":"الأسرة وفئات أخرى",
    "Partner / spouse":"الشريك / الزوج",
    "Residence with a qualifying partner.":"إقامة مع شريك مستوفٍ للشروط.",
    "Minor child":"طفل قاصر",
    "Family residence for qualifying children.":"إقامة أسرية للأطفال المستوفين للشروط.",
    "Parent / family under EU law":"الوالد / الأسرة بموجب قانون الاتحاد الأوروبي",
    "Applicable family and EU-law routes.":"مسارات الأسرة وقانون الاتحاد الأوروبي ذات الصلة.",
    "Short-stay Schengen visa":"تأشيرة شنغن قصيرة الإقامة",
    "Visits up to 90 days where required.":"زيارات تصل إلى 90 يوماً عند الحاجة.",
    "MVV long-stay entry visa":"تأشيرة دخول طويلة الإقامة MVV",
    "Provisional residence visa where required.":"تأشيرة إقامة مؤقتة عند الحاجة.",
    "Asylum":"اللجوء",
    "Protection for qualifying applicants.":"حماية للمتقدمين المستوفين للشروط."
  },
  pt: {
    "Work & Talent":"Trabalho e talento",
    "Highly skilled migrant":"Migrante altamente qualificado",
    "Employment with an IND-recognised sponsor.":"Emprego com um patrocinador reconhecido pelo IND.",
    "EU Blue Card":"Cartão Azul da UE",
    "Highly qualified employment route.":"Via de emprego altamente qualificado.",
    "Paid employment / single permit (GVVA)":"Emprego remunerado / autorização única (GVVA)",
    "Employment requiring combined residence and work authorisation.":"Emprego que exige autorização combinada de residência e trabalho.",
    "Intra-corporate transferee":"Transferência intraempresa",
    "Manager, specialist or trainee transfer.":"Transferência de gestor, especialista ou estagiário.",
    "Researcher":"Investigador",
    "Scientific research under the relevant directive.":"Investigação científica ao abrigo da diretiva relevante.",
    "Orientation year":"Ano de orientação",
    "Post-study/research job-search year for eligible graduates and researchers.":"Ano de procura de emprego após estudos ou investigação para diplomados e investigadores elegíveis.",
    "Essential start-up personnel":"Pessoal essencial de start-up",
    "Pilot residence route for qualifying start-up employees.":"Via piloto de residência para funcionários elegíveis de start-ups.",
    "Seasonal work":"Trabalho sazonal",
    "Qualifying seasonal employment.":"Emprego sazonal elegível.",
    "Working holiday":"Working Holiday",
    "Youth exchange/work holiday where eligible.":"Intercâmbio jovem / trabalho em férias quando elegível.",
    "Business":"Negócios",
    "Start-up":"Start-up",
    "Innovative business with a recognised facilitator.":"Empresa inovadora com um facilitador reconhecido.",
    "Self-employed person":"Trabalhador independente",
    "Entrepreneur or self-employed professional route.":"Via para empreendedor ou profissional por conta própria.",
    "Foreign investor / business routes":"Investidor estrangeiro / vias empresariais",
    "Applicable business residence permissions under current IND rules.":"Autorizações de residência empresarial aplicáveis segundo as regras atuais do IND.",
    "Study":"Estudo",
    "Study at university or higher professional education":"Estudo universitário ou ensino profissional superior",
    "Residence for recognised higher education.":"Residência para ensino superior reconhecido.",
    "Secondary or vocational education":"Ensino secundário ou profissional",
    "Qualifying secondary/MBO study.":"Estudo secundário ou MBO elegível.",
    "Exchange":"Intercâmbio",
    "Recognised exchange programmes.":"Programas de intercâmbio reconhecidos.",
    "Family & Other":"Família e outros",
    "Partner / spouse":"Parceiro / cônjuge",
    "Residence with a qualifying partner.":"Residência com um parceiro elegível.",
    "Minor child":"Filho menor",
    "Family residence for qualifying children.":"Residência familiar para filhos elegíveis.",
    "Parent / family under EU law":"Progenitor / família ao abrigo do direito da UE",
    "Applicable family and EU-law routes.":"Vias familiares e de direito da UE aplicáveis.",
    "Short-stay Schengen visa":"Visto Schengen de curta duração",
    "Visits up to 90 days where required.":"Visitas até 90 dias quando exigido.",
    "MVV long-stay entry visa":"Visto de entrada de longa duração MVV",
    "Provisional residence visa where required.":"Visto provisório de residência quando exigido.",
    "Asylum":"Asilo",
    "Protection for qualifying applicants.":"Proteção para candidatos elegíveis."
  },
  ja: {
    "Work & Talent":"就労・人材",
    "Highly skilled migrant":"高度技能移民",
    "Employment with an IND-recognised sponsor.":"IND 認定スポンサーのもとでの雇用。",
    "EU Blue Card":"EUブルーカード",
    "Highly qualified employment route.":"高度資格就労ルート。",
    "Paid employment / single permit (GVVA)":"有給雇用 / 単一許可（GVVA）",
    "Employment requiring combined residence and work authorisation.":"居住と就労を組み合わせた許可が必要な雇用。",
    "Intra-corporate transferee":"企業内転勤者",
    "Manager, specialist or trainee transfer.":"管理職、専門家、研修生としての転勤。",
    "Researcher":"研究者",
    "Scientific research under the relevant directive.":"関連指令に基づく科学研究。",
    "Orientation year":"オリエンテーション・イヤー",
    "Post-study/research job-search year for eligible graduates and researchers.":"要件を満たす卒業生・研究者向けの、卒業・研究後の1年間の求職期間。",
    "Essential start-up personnel":"スタートアップの中核人材",
    "Pilot residence route for qualifying start-up employees.":"要件を満たすスタートアップ従業員向けの試験的居住ルート。",
    "Seasonal work":"季節労働",
    "Qualifying seasonal employment.":"要件を満たす季節雇用。",
    "Working holiday":"ワーキングホリデー",
    "Youth exchange/work holiday where eligible.":"要件を満たす場合の青年交流・ワーキングホリデー。",
    "Business":"ビジネス",
    "Start-up":"スタートアップ",
    "Innovative business with a recognised facilitator.":"認定ファシリテーターの支援を受ける革新的な事業。",
    "Self-employed person":"自営業者",
    "Entrepreneur or self-employed professional route.":"起業家または自営業の専門職向けルート。",
    "Foreign investor / business routes":"外国人投資家 / ビジネスルート",
    "Applicable business residence permissions under current IND rules.":"現行の IND 規則に基づく該当するビジネス滞在許可。",
    "Study":"留学",
    "Study at university or higher professional education":"大学または高等職業教育での学習",
    "Residence for recognised higher education.":"認定された高等教育のための滞在。",
    "Secondary or vocational education":"中等教育または職業教育",
    "Qualifying secondary/MBO study.":"要件を満たす中等教育または MBO 課程。",
    "Exchange":"交流",
    "Recognised exchange programmes.":"認定された交流プログラム。",
    "Family & Other":"家族・その他",
    "Partner / spouse":"パートナー / 配偶者",
    "Residence with a qualifying partner.":"要件を満たすパートナーとの滞在。",
    "Minor child":"未成年の子ども",
    "Family residence for qualifying children.":"要件を満たす子どもの家族滞在。",
    "Parent / family under EU law":"EU法に基づく親 / 家族",
    "Applicable family and EU-law routes.":"該当する家族およびEU法上のルート。",
    "Short-stay Schengen visa":"シェンゲン短期滞在ビザ",
    "Visits up to 90 days where required.":"必要な場合の90日以内の訪問。",
    "MVV long-stay entry visa":"MVV 長期滞在入国ビザ",
    "Provisional residence visa where required.":"必要な場合の暫定居住ビザ。",
    "Asylum":"庇護",
    "Protection for qualifying applicants.":"要件を満たす申請者向けの保護。"
  }
};
export default translations;
