const translations: Record<string, Record<string, string>> = {
  es: {
    "Work":"Trabajo",
    "Accredited Employer Work Visa":"Visa de Trabajo con Empleador Acreditado",
    "Work for an accredited employer in an approved job.":"Trabajar para un empleador acreditado en un puesto aprobado.",
    "Post Study Work Visa":"Visa de Trabajo Posterior a los Estudios",
    "Work after eligible New Zealand study.":"Trabajar después de estudios elegibles en Nueva Zelanda.",
    "Working Holiday Visas":"Visas Working Holiday",
    "Country-specific youth working holiday schemes.":"Programas de trabajo y vacaciones para jóvenes según el país.",
    "Specific Purpose Work Visa":"Visa de Trabajo para Propósito Específico",
    "Work for an approved specific purpose or event.":"Trabajar para un propósito o evento específico aprobado.",
    "Partner of a Worker Work Visa":"Visa de Trabajo para Pareja de un Trabajador",
    "Work based on an eligible partner's status.":"Trabajar en función del estatus elegible de la pareja.",
    "Partner of a Student Work Visa":"Visa de Trabajo para Pareja de un Estudiante",
    "Work based on an eligible student's status.":"Trabajar en función del estatus de un estudiante elegible.",
    "Religious Worker Work Visa":"Visa de Trabajo para Trabajador Religioso",
    "Qualifying religious work.":"Trabajo religioso que cumpla los requisitos.",
    "Recognised Seasonal Employer Limited Visa":"Visa Limitada para Empleador Estacional Reconocido",
    "Seasonal horticulture/viticulture work.":"Trabajo estacional en horticultura o viticultura.",
    "Business Investor Work Visa":"Visa de Trabajo para Inversor Empresarial",
    "Invest in and actively run an established business.":"Invertir en una empresa establecida y participar activamente en su gestión.",
    "Entrepreneur Work Visa":"Visa de Trabajo para Emprendedores",
    "Legacy/eligible self-employment business route subject to current availability.":"Vía empresarial de trabajo por cuenta propia anterior o elegible, sujeta a disponibilidad actual.",
    "Residence":"Residencia",
    "Skilled Migrant Category Resident Visa":"Visa de Residente de la Categoría de Migrante Cualificado",
    "Points/skills-based residence.":"Residencia basada en puntos y competencias.",
    "Straight to Residence Visa":"Visa Straight to Residence",
    "Eligible Green List Tier 1 employment.":"Empleo elegible de nivel 1 de la Green List.",
    "Work to Residence Visa":"Visa Work to Residence",
    "Eligible work-to-residence pathway.":"Vía elegible de trabajo hacia la residencia.",
    "Care Workforce Work to Residence":"Trabajo a Residencia para Personal de Cuidados",
    "Eligible care workforce residence.":"Residencia para personal de cuidados que cumpla los requisitos.",
    "Transport Work to Residence":"Trabajo a Residencia para el Sector del Transporte",
    "Eligible transport workforce residence.":"Residencia para personal del transporte que cumpla los requisitos.",
    "Active Investor Plus Visa":"Visa Active Investor Plus",
    "Residence through qualifying investment.":"Residencia mediante una inversión que cumpla los requisitos.",
    "Business Investor Resident Visa":"Visa de Residente para Inversor Empresarial",
    "Residence after qualifying business-investor activity.":"Residencia tras una actividad de inversión empresarial que cumpla los requisitos.",
    "Permanent Resident Visa":"Visa de Residente Permanente",
    "Permanent residence for eligible resident visa holders.":"Residencia permanente para titulares elegibles de una visa de residente.",
    "Pacific Access Category":"Categoría Pacific Access",
    "Residence for eligible Pacific nationals selected under the scheme.":"Residencia para nacionales del Pacífico elegibles seleccionados mediante el programa.",
    "Samoan Quota Resident Visa":"Visa de Residente por Cuota de Samoa",
    "Residence under the Samoa quota.":"Residencia conforme a la cuota de Samoa.",
    "Religious Workers Resident Visa":"Visa de Residente para Trabajadores Religiosos",
    "Residence for qualifying religious workers.":"Residencia para trabajadores religiosos que cumplan los requisitos.",
    "Study":"Estudios",
    "Fee Paying Student Visa":"Visa de Estudiante de Pago",
    "Full-time fee-paying study.":"Estudios a tiempo completo con pago de matrícula.",
    "Pathway Student Visa":"Visa de Estudiante Pathway",
    "Up to three approved programmes in sequence.":"Hasta tres programas aprobados de forma consecutiva.",
    "English Language Student Visa":"Visa de Estudiante de Inglés",
    "Full-time English-language study.":"Estudios de inglés a tiempo completo.",
    "Dependent Child Student Visa":"Visa de Estudiante para Hijo Dependiente",
    "School study for eligible dependent children.":"Escolarización para hijos dependientes que cumplan los requisitos.",
    "Exchange Student Visa":"Visa de Estudiante de Intercambio",
    "Approved exchange study.":"Estudios de intercambio aprobados.",
    "Foreign Government Supported Student Visa":"Visa de Estudiante con Apoyo de Gobierno Extranjero",
    "Study supported by a foreign government.":"Estudios financiados o apoyados por un gobierno extranjero.",
    "Family & Visit":"Familia y visita",
    "Partner visas":"Visas de pareja",
    "Visitor, work and residence routes for eligible partners.":"Vías de visita, trabajo y residencia para parejas elegibles.",
    "Dependent Child visas":"Visas para hijos dependientes",
    "Visitor, student and resident routes for eligible children.":"Vías de visita, estudios y residencia para hijos elegibles.",
    "Parent Resident Visa":"Visa de Residente para Padres",
    "Residence for eligible parents.":"Residencia para padres elegibles.",
    "Parent Boost Visitor Visa":"Visa de Visitante Parent Boost",
    "Longer visits for eligible parents.":"Visitas más largas para padres elegibles.",
    "Visitor Visa":"Visa de Visitante",
    "Tourism and family visits.":"Turismo y visitas familiares.",
    "Business Visitor Visa":"Visa de Visitante de Negocios",
    "Short business visits.":"Visitas de negocios de corta duración.",
    "NZeTA":"NZeTA",
    "Travel authority for eligible visa-waiver travellers.":"Autorización de viaje para viajeros elegibles exentos de visa.",
    "Transit Visa":"Visa de Tránsito",
    "Transit through New Zealand where required.":"Tránsito por Nueva Zelanda cuando sea necesario."
  },
  fr: {
    "Work":"Travail",
    "Accredited Employer Work Visa":"Visa de travail auprès d’un employeur accrédité",
    "Work for an accredited employer in an approved job.":"Travailler pour un employeur accrédité dans un emploi approuvé.",
    "Post Study Work Visa":"Visa de travail post-études",
    "Work after eligible New Zealand study.":"Travailler après des études admissibles en Nouvelle-Zélande.",
    "Working Holiday Visas":"Visas vacances-travail",
    "Country-specific youth working holiday schemes.":"Programmes vacances-travail pour jeunes selon le pays.",
    "Specific Purpose Work Visa":"Visa de travail pour objectif spécifique",
    "Work for an approved specific purpose or event.":"Travailler pour un objectif ou événement spécifique approuvé.",
    "Partner of a Worker Work Visa":"Visa de travail pour partenaire d’un travailleur",
    "Work based on an eligible partner's status.":"Travailler sur la base du statut admissible de son partenaire.",
    "Partner of a Student Work Visa":"Visa de travail pour partenaire d’un étudiant",
    "Work based on an eligible student's status.":"Travailler sur la base du statut d’un étudiant admissible.",
    "Religious Worker Work Visa":"Visa de travail pour travailleur religieux",
    "Qualifying religious work.":"Travail religieux admissible.",
    "Recognised Seasonal Employer Limited Visa":"Visa limité pour employeur saisonnier reconnu",
    "Seasonal horticulture/viticulture work.":"Travail saisonnier en horticulture ou viticulture.",
    "Business Investor Work Visa":"Visa de travail pour investisseur d’entreprise",
    "Invest in and actively run an established business.":"Investir dans une entreprise établie et participer activement à sa gestion.",
    "Entrepreneur Work Visa":"Visa de travail pour entrepreneur",
    "Legacy/eligible self-employment business route subject to current availability.":"Ancienne voie ou voie admissible d’activité indépendante, sous réserve de sa disponibilité actuelle.",
    "Residence":"Résidence",
    "Skilled Migrant Category Resident Visa":"Visa de résident – catégorie migrant qualifié",
    "Points/skills-based residence.":"Résidence fondée sur les points et compétences.",
    "Straight to Residence Visa":"Visa Straight to Residence",
    "Eligible Green List Tier 1 employment.":"Emploi admissible de niveau 1 de la Green List.",
    "Work to Residence Visa":"Visa Work to Residence",
    "Eligible work-to-residence pathway.":"Voie admissible du travail vers la résidence.",
    "Care Workforce Work to Residence":"Work to Residence – personnel de soins",
    "Eligible care workforce residence.":"Résidence pour le personnel de soins admissible.",
    "Transport Work to Residence":"Work to Residence – transport",
    "Eligible transport workforce residence.":"Résidence pour le personnel du transport admissible.",
    "Active Investor Plus Visa":"Visa Active Investor Plus",
    "Residence through qualifying investment.":"Résidence au moyen d’un investissement admissible.",
    "Business Investor Resident Visa":"Visa de résident pour investisseur d’entreprise",
    "Residence after qualifying business-investor activity.":"Résidence après une activité d’investissement d’entreprise admissible.",
    "Permanent Resident Visa":"Visa de résident permanent",
    "Permanent residence for eligible resident visa holders.":"Résidence permanente pour les titulaires admissibles d’un visa de résident.",
    "Pacific Access Category":"Catégorie Pacific Access",
    "Residence for eligible Pacific nationals selected under the scheme.":"Résidence pour les ressortissants admissibles du Pacifique sélectionnés dans le cadre du programme.",
    "Samoan Quota Resident Visa":"Visa de résident – quota samoan",
    "Residence under the Samoa quota.":"Résidence dans le cadre du quota des Samoa.",
    "Religious Workers Resident Visa":"Visa de résident pour travailleurs religieux",
    "Residence for qualifying religious workers.":"Résidence pour les travailleurs religieux admissibles.",
    "Study":"Études",
    "Fee Paying Student Visa":"Visa étudiant payant",
    "Full-time fee-paying study.":"Études à temps plein avec frais de scolarité.",
    "Pathway Student Visa":"Visa étudiant Pathway",
    "Up to three approved programmes in sequence.":"Jusqu’à trois programmes approuvés successifs.",
    "English Language Student Visa":"Visa étudiant en langue anglaise",
    "Full-time English-language study.":"Études d’anglais à temps plein.",
    "Dependent Child Student Visa":"Visa étudiant pour enfant à charge",
    "School study for eligible dependent children.":"Scolarité pour les enfants à charge admissibles.",
    "Exchange Student Visa":"Visa étudiant d’échange",
    "Approved exchange study.":"Études dans le cadre d’un échange approuvé.",
    "Foreign Government Supported Student Visa":"Visa étudiant soutenu par un gouvernement étranger",
    "Study supported by a foreign government.":"Études soutenues par un gouvernement étranger.",
    "Family & Visit":"Famille et visite",
    "Partner visas":"Visas de partenaire",
    "Visitor, work and residence routes for eligible partners.":"Voies de visite, de travail et de résidence pour les partenaires admissibles.",
    "Dependent Child visas":"Visas pour enfants à charge",
    "Visitor, student and resident routes for eligible children.":"Voies de visite, d’études et de résidence pour les enfants admissibles.",
    "Parent Resident Visa":"Visa de résident pour parents",
    "Residence for eligible parents.":"Résidence pour les parents admissibles.",
    "Parent Boost Visitor Visa":"Visa visiteur Parent Boost",
    "Longer visits for eligible parents.":"Visites plus longues pour les parents admissibles.",
    "Visitor Visa":"Visa de visiteur",
    "Tourism and family visits.":"Tourisme et visites familiales.",
    "Business Visitor Visa":"Visa de visiteur d’affaires",
    "Short business visits.":"Courtes visites d’affaires.",
    "NZeTA":"NZeTA",
    "Travel authority for eligible visa-waiver travellers.":"Autorisation de voyage pour les voyageurs admissibles dispensés de visa.",
    "Transit Visa":"Visa de transit",
    "Transit through New Zealand where required.":"Transit par la Nouvelle-Zélande lorsqu’il est requis."
  },
  de: {
    "Work":"Arbeit",
    "Accredited Employer Work Visa":"Arbeitsvisum bei einem akkreditierten Arbeitgeber",
    "Work for an accredited employer in an approved job.":"Arbeit bei einem akkreditierten Arbeitgeber in einer genehmigten Stelle.",
    "Post Study Work Visa":"Arbeitsvisum nach dem Studium",
    "Work after eligible New Zealand study.":"Arbeit nach einem berechtigten Studium in Neuseeland.",
    "Working Holiday Visas":"Working-Holiday-Visa",
    "Country-specific youth working holiday schemes.":"Länderspezifische Working-Holiday-Programme für junge Menschen.",
    "Specific Purpose Work Visa":"Arbeitsvisum für einen bestimmten Zweck",
    "Work for an approved specific purpose or event.":"Arbeit für einen genehmigten bestimmten Zweck oder eine Veranstaltung.",
    "Partner of a Worker Work Visa":"Arbeitsvisum für Partner eines Arbeitnehmers",
    "Work based on an eligible partner's status.":"Arbeit auf Grundlage des berechtigten Status eines Partners.",
    "Partner of a Student Work Visa":"Arbeitsvisum für Partner eines Studierenden",
    "Work based on an eligible student's status.":"Arbeit auf Grundlage des Status eines berechtigten Studierenden.",
    "Religious Worker Work Visa":"Arbeitsvisum für religiöse Beschäftigte",
    "Qualifying religious work.":"Berechtigte religiöse Tätigkeit.",
    "Recognised Seasonal Employer Limited Visa":"Begrenztes Visum für anerkannte Saisonarbeitgeber",
    "Seasonal horticulture/viticulture work.":"Saisonarbeit im Garten- oder Weinbau.",
    "Business Investor Work Visa":"Arbeitsvisum für Unternehmensinvestoren",
    "Invest in and actively run an established business.":"In ein bestehendes Unternehmen investieren und es aktiv führen.",
    "Entrepreneur Work Visa":"Arbeitsvisum für Unternehmer",
    "Legacy/eligible self-employment business route subject to current availability.":"Frühere bzw. berechtigte Geschäftsroute zur Selbstständigkeit, abhängig von der aktuellen Verfügbarkeit.",
    "Residence":"Aufenthalt",
    "Skilled Migrant Category Resident Visa":"Aufenthaltsvisum der Kategorie Skilled Migrant",
    "Points/skills-based residence.":"Aufenthalt auf Grundlage von Punkten und Qualifikationen.",
    "Straight to Residence Visa":"Straight-to-Residence-Visum",
    "Eligible Green List Tier 1 employment.":"Berechtigte Beschäftigung der Green List Tier 1.",
    "Work to Residence Visa":"Work-to-Residence-Visum",
    "Eligible work-to-residence pathway.":"Berechtigter Weg von Arbeit zum Aufenthalt.",
    "Care Workforce Work to Residence":"Work to Residence für Pflegekräfte",
    "Eligible care workforce residence.":"Aufenthalt für berechtigte Pflegekräfte.",
    "Transport Work to Residence":"Work to Residence für Transportbeschäftigte",
    "Eligible transport workforce residence.":"Aufenthalt für berechtigte Beschäftigte im Transportsektor.",
    "Active Investor Plus Visa":"Active Investor Plus Visa",
    "Residence through qualifying investment.":"Aufenthalt durch eine berechtigte Investition.",
    "Business Investor Resident Visa":"Aufenthaltsvisum für Unternehmensinvestoren",
    "Residence after qualifying business-investor activity.":"Aufenthalt nach einer berechtigten Unternehmensinvestition.",
    "Permanent Resident Visa":"Daueraufenthaltsvisum",
    "Permanent residence for eligible resident visa holders.":"Daueraufenthalt für berechtigte Inhaber eines Aufenthaltsvisums.",
    "Pacific Access Category":"Pacific Access Category",
    "Residence for eligible Pacific nationals selected under the scheme.":"Aufenthalt für berechtigte Staatsangehörige pazifischer Staaten, die im Rahmen des Programms ausgewählt wurden.",
    "Samoan Quota Resident Visa":"Aufenthaltsvisum im Samoa-Kontingent",
    "Residence under the Samoa quota.":"Aufenthalt im Rahmen des Samoa-Kontingents.",
    "Religious Workers Resident Visa":"Aufenthaltsvisum für religiöse Beschäftigte",
    "Residence for qualifying religious workers.":"Aufenthalt für berechtigte religiöse Beschäftigte.",
    "Study":"Studium",
    "Fee Paying Student Visa":"Visum für gebührenpflichtige Studierende",
    "Full-time fee-paying study.":"Gebührenpflichtiges Vollzeitstudium.",
    "Pathway Student Visa":"Pathway Student Visa",
    "Up to three approved programmes in sequence.":"Bis zu drei genehmigte Programme nacheinander.",
    "English Language Student Visa":"Visum für Englischsprachstudierende",
    "Full-time English-language study.":"Vollzeit-Englischsprachstudium.",
    "Dependent Child Student Visa":"Studentenvisum für unterhaltsberechtigte Kinder",
    "School study for eligible dependent children.":"Schulbesuch für berechtigte unterhaltsberechtigte Kinder.",
    "Exchange Student Visa":"Austauschstudentenvisum",
    "Approved exchange study.":"Genehmigtes Austauschstudium.",
    "Foreign Government Supported Student Visa":"Visum für von einer ausländischen Regierung geförderte Studierende",
    "Study supported by a foreign government.":"Studium mit Unterstützung einer ausländischen Regierung.",
    "Family & Visit":"Familie und Besuch",
    "Partner visas":"Partnervisa",
    "Visitor, work and residence routes for eligible partners.":"Besuchs-, Arbeits- und Aufenthaltswege für berechtigte Partner.",
    "Dependent Child visas":"Visa für unterhaltsberechtigte Kinder",
    "Visitor, student and resident routes for eligible children.":"Besuchs-, Studien- und Aufenthaltswege für berechtigte Kinder.",
    "Parent Resident Visa":"Aufenthaltsvisum für Eltern",
    "Residence for eligible parents.":"Aufenthalt für berechtigte Eltern.",
    "Parent Boost Visitor Visa":"Parent Boost Visitor Visa",
    "Longer visits for eligible parents.":"Längere Besuche für berechtigte Eltern.",
    "Visitor Visa":"Besuchervisum",
    "Tourism and family visits.":"Tourismus und Familienbesuche.",
    "Business Visitor Visa":"Geschäftsbesuchervisum",
    "Short business visits.":"Kurze Geschäftsbesuche.",
    "NZeTA":"NZeTA",
    "Travel authority for eligible visa-waiver travellers.":"Reisegenehmigung für berechtigte visumbefreite Reisende.",
    "Transit Visa":"Transitvisum",
    "Transit through New Zealand where required.":"Transit durch Neuseeland, sofern erforderlich."
  },
  zh: {
    "Work":"工作",
    "Accredited Employer Work Visa":"认可雇主工作签证",
    "Work for an accredited employer in an approved job.":"在认可雇主处从事获批准的工作。",
    "Post Study Work Visa":"毕业后工作签证",
    "Work after eligible New Zealand study.":"在完成符合条件的新西兰学习后工作。",
    "Working Holiday Visas":"打工度假签证",
    "Country-specific youth working holiday schemes.":"按国家设置的青年打工度假计划。",
    "Specific Purpose Work Visa":"特定目的工作签证",
    "Work for an approved specific purpose or event.":"为获批准的特定目的或活动工作。",
    "Partner of a Worker Work Visa":"工人伴侣工作签证",
    "Work based on an eligible partner's status.":"基于符合条件伴侣的身份获得工作权利。",
    "Partner of a Student Work Visa":"学生伴侣工作签证",
    "Work based on an eligible student's status.":"基于符合条件学生伴侣的身份获得工作权利。",
    "Religious Worker Work Visa":"宗教工作者工作签证",
    "Qualifying religious work.":"符合条件的宗教工作。",
    "Recognised Seasonal Employer Limited Visa":"认可季节性雇主限制签证",
    "Seasonal horticulture/viticulture work.":"季节性园艺或葡萄栽培工作。",
    "Business Investor Work Visa":"商业投资者工作签证",
    "Invest in and actively run an established business.":"投资并积极经营一家已建立的企业。",
    "Entrepreneur Work Visa":"企业家工作签证",
    "Legacy/eligible self-employment business route subject to current availability.":"旧有或符合条件的自雇商业途径，具体以当前是否开放为准。",
    "Residence":"居留",
    "Skilled Migrant Category Resident Visa":"技术移民类别居民签证",
    "Points/skills-based residence.":"基于积分或技能的居留途径。",
    "Straight to Residence Visa":"直接居留签证",
    "Eligible Green List Tier 1 employment.":"符合条件的绿色清单一级职业就业。",
    "Work to Residence Visa":"工作转居留签证",
    "Eligible work-to-residence pathway.":"符合条件的工作转居留途径。",
    "Care Workforce Work to Residence":"护理人员工作转居留",
    "Eligible care workforce residence.":"面向符合条件护理人员的居留途径。",
    "Transport Work to Residence":"运输行业工作转居留",
    "Eligible transport workforce residence.":"面向符合条件运输行业人员的居留途径。",
    "Active Investor Plus Visa":"Active Investor Plus 投资者签证",
    "Residence through qualifying investment.":"通过符合条件的投资获得居留。",
    "Business Investor Resident Visa":"商业投资者居民签证",
    "Residence after qualifying business-investor activity.":"在完成符合条件的商业投资活动后获得居留。",
    "Permanent Resident Visa":"永久居民签证",
    "Permanent residence for eligible resident visa holders.":"面向符合条件居民签证持有人的永久居留。",
    "Pacific Access Category":"太平洋准入类别",
    "Residence for eligible Pacific nationals selected under the scheme.":"面向通过该计划选中的符合条件太平洋国家公民的居留。",
    "Samoan Quota Resident Visa":"萨摩亚配额居民签证",
    "Residence under the Samoa quota.":"通过萨摩亚配额获得居留。",
    "Religious Workers Resident Visa":"宗教工作者居民签证",
    "Residence for qualifying religious workers.":"面向符合条件宗教工作者的居留。",
    "Study":"学习",
    "Fee Paying Student Visa":"付费学生签证",
    "Full-time fee-paying study.":"需支付学费的全日制学习。",
    "Pathway Student Visa":"学习路径学生签证",
    "Up to three approved programmes in sequence.":"可连续就读最多三个获批准的课程。",
    "English Language Student Visa":"英语语言学生签证",
    "Full-time English-language study.":"全日制英语语言学习。",
    "Dependent Child Student Visa":"受抚养子女学生签证",
    "School study for eligible dependent children.":"面向符合条件受抚养子女的学校学习。",
    "Exchange Student Visa":"交换学生签证",
    "Approved exchange study.":"获批准的交换学习。",
    "Foreign Government Supported Student Visa":"外国政府资助学生签证",
    "Study supported by a foreign government.":"由外国政府支持的学习。",
    "Family & Visit":"家庭与访问",
    "Partner visas":"伴侣签证",
    "Visitor, work and residence routes for eligible partners.":"面向符合条件伴侣的访问、工作和居留途径。",
    "Dependent Child visas":"受抚养子女签证",
    "Visitor, student and resident routes for eligible children.":"面向符合条件子女的访问、学生及居民途径。",
    "Parent Resident Visa":"父母居民签证",
    "Residence for eligible parents.":"面向符合条件父母的居留。",
    "Parent Boost Visitor Visa":"Parent Boost 父母访问签证",
    "Longer visits for eligible parents.":"面向符合条件父母的较长期访问。",
    "Visitor Visa":"访客签证",
    "Tourism and family visits.":"旅游及探亲访问。",
    "Business Visitor Visa":"商务访客签证",
    "Short business visits.":"短期商务访问。",
    "NZeTA":"NZeTA",
    "Travel authority for eligible visa-waiver travellers.":"面向符合条件免签旅客的旅行授权。",
    "Transit Visa":"过境签证",
    "Transit through New Zealand where required.":"在需要时经新西兰过境。"
  },
  ar: {
    "Work":"العمل",
    "Accredited Employer Work Visa":"تأشيرة عمل لدى صاحب عمل معتمد",
    "Work for an accredited employer in an approved job.":"العمل لدى صاحب عمل معتمد في وظيفة مصرح بها.",
    "Post Study Work Visa":"تأشيرة العمل بعد الدراسة",
    "Work after eligible New Zealand study.":"العمل بعد دراسة مؤهلة في نيوزيلندا.",
    "Working Holiday Visas":"تأشيرات عطلة العمل",
    "Country-specific youth working holiday schemes.":"برامج عطلة العمل للشباب بحسب الدولة.",
    "Specific Purpose Work Visa":"تأشيرة عمل لغرض محدد",
    "Work for an approved specific purpose or event.":"العمل لغرض أو حدث محدد معتمد.",
    "Partner of a Worker Work Visa":"تأشيرة عمل لشريك عامل",
    "Work based on an eligible partner's status.":"العمل استناداً إلى وضع شريك مؤهل.",
    "Partner of a Student Work Visa":"تأشيرة عمل لشريك طالب",
    "Work based on an eligible student's status.":"العمل استناداً إلى وضع طالب مؤهل.",
    "Religious Worker Work Visa":"تأشيرة عمل للعامل الديني",
    "Qualifying religious work.":"عمل ديني مستوفٍ للشروط.",
    "Recognised Seasonal Employer Limited Visa":"تأشيرة محدودة لصاحب عمل موسمي معترف به",
    "Seasonal horticulture/viticulture work.":"عمل موسمي في البستنة أو زراعة العنب.",
    "Business Investor Work Visa":"تأشيرة عمل لمستثمر أعمال",
    "Invest in and actively run an established business.":"الاستثمار في مشروع قائم وإدارته بصورة نشطة.",
    "Entrepreneur Work Visa":"تأشيرة عمل لرائد أعمال",
    "Legacy/eligible self-employment business route subject to current availability.":"مسار أعمال قديم أو مؤهل للعمل الحر، رهناً بتوفره الحالي.",
    "Residence":"الإقامة",
    "Skilled Migrant Category Resident Visa":"تأشيرة إقامة فئة المهاجر الماهر",
    "Points/skills-based residence.":"إقامة قائمة على النقاط والمهارات.",
    "Straight to Residence Visa":"تأشيرة الإقامة المباشرة",
    "Eligible Green List Tier 1 employment.":"عمل مؤهل ضمن المستوى الأول من القائمة الخضراء.",
    "Work to Residence Visa":"تأشيرة العمل إلى الإقامة",
    "Eligible work-to-residence pathway.":"مسار مؤهل من العمل إلى الإقامة.",
    "Care Workforce Work to Residence":"العمل إلى الإقامة لقطاع الرعاية",
    "Eligible care workforce residence.":"إقامة للعاملين المؤهلين في قطاع الرعاية.",
    "Transport Work to Residence":"العمل إلى الإقامة لقطاع النقل",
    "Eligible transport workforce residence.":"إقامة للعاملين المؤهلين في قطاع النقل.",
    "Active Investor Plus Visa":"تأشيرة Active Investor Plus",
    "Residence through qualifying investment.":"إقامة من خلال استثمار مستوفٍ للشروط.",
    "Business Investor Resident Visa":"تأشيرة إقامة لمستثمر أعمال",
    "Residence after qualifying business-investor activity.":"إقامة بعد نشاط استثماري تجاري مستوفٍ للشروط.",
    "Permanent Resident Visa":"تأشيرة إقامة دائمة",
    "Permanent residence for eligible resident visa holders.":"إقامة دائمة لحاملي تأشيرات الإقامة المؤهلين.",
    "Pacific Access Category":"فئة Pacific Access",
    "Residence for eligible Pacific nationals selected under the scheme.":"إقامة لمواطني دول المحيط الهادئ المؤهلين الذين يتم اختيارهم ضمن البرنامج.",
    "Samoan Quota Resident Visa":"تأشيرة إقامة حصة ساموا",
    "Residence under the Samoa quota.":"إقامة ضمن حصة ساموا.",
    "Religious Workers Resident Visa":"تأشيرة إقامة للعاملين الدينيين",
    "Residence for qualifying religious workers.":"إقامة للعاملين الدينيين المستوفين للشروط.",
    "Study":"الدراسة",
    "Fee Paying Student Visa":"تأشيرة طالب دافع للرسوم",
    "Full-time fee-paying study.":"دراسة بدوام كامل مع دفع الرسوم.",
    "Pathway Student Visa":"تأشيرة طالب للمسار الدراسي",
    "Up to three approved programmes in sequence.":"حتى ثلاثة برامج معتمدة متتالية.",
    "English Language Student Visa":"تأشيرة طالب لغة إنجليزية",
    "Full-time English-language study.":"دراسة اللغة الإنجليزية بدوام كامل.",
    "Dependent Child Student Visa":"تأشيرة طالب لطفل معال",
    "School study for eligible dependent children.":"دراسة مدرسية للأطفال المعالين المؤهلين.",
    "Exchange Student Visa":"تأشيرة طالب تبادل",
    "Approved exchange study.":"دراسة تبادل معتمدة.",
    "Foreign Government Supported Student Visa":"تأشيرة طالب مدعوم من حكومة أجنبية",
    "Study supported by a foreign government.":"دراسة بدعم من حكومة أجنبية.",
    "Family & Visit":"الأسرة والزيارة",
    "Partner visas":"تأشيرات الشريك",
    "Visitor, work and residence routes for eligible partners.":"مسارات زيارة وعمل وإقامة للشركاء المؤهلين.",
    "Dependent Child visas":"تأشيرات الأطفال المعالين",
    "Visitor, student and resident routes for eligible children.":"مسارات زيارة ودراسة وإقامة للأطفال المؤهلين.",
    "Parent Resident Visa":"تأشيرة إقامة للوالدين",
    "Residence for eligible parents.":"إقامة للوالدين المؤهلين.",
    "Parent Boost Visitor Visa":"تأشيرة زيارة Parent Boost",
    "Longer visits for eligible parents.":"زيارات أطول للوالدين المؤهلين.",
    "Visitor Visa":"تأشيرة زائر",
    "Tourism and family visits.":"السياحة والزيارات العائلية.",
    "Business Visitor Visa":"تأشيرة زائر أعمال",
    "Short business visits.":"زيارات أعمال قصيرة.",
    "NZeTA":"NZeTA",
    "Travel authority for eligible visa-waiver travellers.":"تصريح سفر للمسافرين المؤهلين المعفيين من التأشيرة.",
    "Transit Visa":"تأشيرة عبور",
    "Transit through New Zealand where required.":"العبور عبر نيوزيلندا عند الحاجة."
  },
  pt: {
    "Work":"Trabalho",
    "Accredited Employer Work Visa":"Visto de Trabalho com Empregador Acreditado",
    "Work for an accredited employer in an approved job.":"Trabalhar para um empregador acreditado numa função aprovada.",
    "Post Study Work Visa":"Visto de Trabalho Pós-Estudos",
    "Work after eligible New Zealand study.":"Trabalhar após estudos elegíveis na Nova Zelândia.",
    "Working Holiday Visas":"Vistos Working Holiday",
    "Country-specific youth working holiday schemes.":"Programas de trabalho e férias para jovens específicos por país.",
    "Specific Purpose Work Visa":"Visto de Trabalho para Finalidade Específica",
    "Work for an approved specific purpose or event.":"Trabalhar para uma finalidade ou evento específico aprovado.",
    "Partner of a Worker Work Visa":"Visto de Trabalho para Parceiro de Trabalhador",
    "Work based on an eligible partner's status.":"Trabalhar com base no estatuto elegível do parceiro.",
    "Partner of a Student Work Visa":"Visto de Trabalho para Parceiro de Estudante",
    "Work based on an eligible student's status.":"Trabalhar com base no estatuto de um estudante elegível.",
    "Religious Worker Work Visa":"Visto de Trabalho para Trabalhador Religioso",
    "Qualifying religious work.":"Trabalho religioso elegível.",
    "Recognised Seasonal Employer Limited Visa":"Visto Limitado para Empregador Sazonal Reconhecido",
    "Seasonal horticulture/viticulture work.":"Trabalho sazonal em horticultura ou viticultura.",
    "Business Investor Work Visa":"Visto de Trabalho para Investidor Empresarial",
    "Invest in and actively run an established business.":"Investir e gerir ativamente uma empresa estabelecida.",
    "Entrepreneur Work Visa":"Visto de Trabalho para Empreendedor",
    "Legacy/eligible self-employment business route subject to current availability.":"Via empresarial antiga ou elegível de trabalho independente, sujeita à disponibilidade atual.",
    "Residence":"Residência",
    "Skilled Migrant Category Resident Visa":"Visto de Residente da Categoria Migrante Qualificado",
    "Points/skills-based residence.":"Residência baseada em pontos e competências.",
    "Straight to Residence Visa":"Visto Straight to Residence",
    "Eligible Green List Tier 1 employment.":"Emprego elegível de nível 1 da Green List.",
    "Work to Residence Visa":"Visto Work to Residence",
    "Eligible work-to-residence pathway.":"Via elegível de trabalho para residência.",
    "Care Workforce Work to Residence":"Work to Residence para Setor de Cuidados",
    "Eligible care workforce residence.":"Residência para trabalhadores elegíveis do setor de cuidados.",
    "Transport Work to Residence":"Work to Residence para Setor de Transportes",
    "Eligible transport workforce residence.":"Residência para trabalhadores elegíveis do setor de transportes.",
    "Active Investor Plus Visa":"Visto Active Investor Plus",
    "Residence through qualifying investment.":"Residência através de investimento elegível.",
    "Business Investor Resident Visa":"Visto de Residente para Investidor Empresarial",
    "Residence after qualifying business-investor activity.":"Residência após atividade de investimento empresarial elegível.",
    "Permanent Resident Visa":"Visto de Residente Permanente",
    "Permanent residence for eligible resident visa holders.":"Residência permanente para titulares elegíveis de visto de residente.",
    "Pacific Access Category":"Categoria Pacific Access",
    "Residence for eligible Pacific nationals selected under the scheme.":"Residência para nacionais elegíveis do Pacífico selecionados pelo programa.",
    "Samoan Quota Resident Visa":"Visto de Residente da Quota de Samoa",
    "Residence under the Samoa quota.":"Residência ao abrigo da quota de Samoa.",
    "Religious Workers Resident Visa":"Visto de Residente para Trabalhadores Religiosos",
    "Residence for qualifying religious workers.":"Residência para trabalhadores religiosos elegíveis.",
    "Study":"Estudo",
    "Fee Paying Student Visa":"Visto de Estudante Pagante",
    "Full-time fee-paying study.":"Estudo a tempo inteiro com pagamento de propinas.",
    "Pathway Student Visa":"Visto de Estudante Pathway",
    "Up to three approved programmes in sequence.":"Até três programas aprovados em sequência.",
    "English Language Student Visa":"Visto de Estudante de Língua Inglesa",
    "Full-time English-language study.":"Estudo de inglês a tempo inteiro.",
    "Dependent Child Student Visa":"Visto de Estudante para Filho Dependente",
    "School study for eligible dependent children.":"Estudo escolar para filhos dependentes elegíveis.",
    "Exchange Student Visa":"Visto de Estudante de Intercâmbio",
    "Approved exchange study.":"Estudo de intercâmbio aprovado.",
    "Foreign Government Supported Student Visa":"Visto de Estudante Apoiado por Governo Estrangeiro",
    "Study supported by a foreign government.":"Estudo apoiado por um governo estrangeiro.",
    "Family & Visit":"Família e visita",
    "Partner visas":"Vistos de parceiro",
    "Visitor, work and residence routes for eligible partners.":"Vias de visita, trabalho e residência para parceiros elegíveis.",
    "Dependent Child visas":"Vistos para filhos dependentes",
    "Visitor, student and resident routes for eligible children.":"Vias de visita, estudo e residência para filhos elegíveis.",
    "Parent Resident Visa":"Visto de Residente para Pais",
    "Residence for eligible parents.":"Residência para pais elegíveis.",
    "Parent Boost Visitor Visa":"Visto de Visitante Parent Boost",
    "Longer visits for eligible parents.":"Visitas mais longas para pais elegíveis.",
    "Visitor Visa":"Visto de Visitante",
    "Tourism and family visits.":"Turismo e visitas familiares.",
    "Business Visitor Visa":"Visto de Visitante de Negócios",
    "Short business visits.":"Visitas de negócios de curta duração.",
    "NZeTA":"NZeTA",
    "Travel authority for eligible visa-waiver travellers.":"Autorização de viagem para viajantes elegíveis isentos de visto.",
    "Transit Visa":"Visto de Trânsito",
    "Transit through New Zealand where required.":"Trânsito pela Nova Zelândia quando exigido."
  },
  ja: {
    "Work":"就労",
    "Accredited Employer Work Visa":"認定雇用主就労ビザ",
    "Work for an accredited employer in an approved job.":"認定雇用主のもとで承認された職務に従事するためのビザ。",
    "Post Study Work Visa":"卒業後就労ビザ",
    "Work after eligible New Zealand study.":"要件を満たすニュージーランドでの学習後に就労するための制度。",
    "Working Holiday Visas":"ワーキングホリデービザ",
    "Country-specific youth working holiday schemes.":"国ごとに設けられた若者向けワーキングホリデー制度。",
    "Specific Purpose Work Visa":"特定目的就労ビザ",
    "Work for an approved specific purpose or event.":"承認された特定の目的またはイベントのために就労する制度。",
    "Partner of a Worker Work Visa":"就労者のパートナー向け就労ビザ",
    "Work based on an eligible partner's status.":"要件を満たすパートナーの在留資格に基づいて就労する制度。",
    "Partner of a Student Work Visa":"学生のパートナー向け就労ビザ",
    "Work based on an eligible student's status.":"要件を満たす学生のパートナーとして就労する制度。",
    "Religious Worker Work Visa":"宗教労働者就労ビザ",
    "Qualifying religious work.":"要件を満たす宗教活動に従事するための制度。",
    "Recognised Seasonal Employer Limited Visa":"認定季節雇用主限定ビザ",
    "Seasonal horticulture/viticulture work.":"園芸またはブドウ栽培分野の季節労働。",
    "Business Investor Work Visa":"事業投資家就労ビザ",
    "Invest in and actively run an established business.":"既存事業に投資し、積極的に経営するための制度。",
    "Entrepreneur Work Visa":"起業家就労ビザ",
    "Legacy/eligible self-employment business route subject to current availability.":"旧制度または対象となる自営業ビジネスルートで、現在の利用可否に従います。",
    "Residence":"居住",
    "Skilled Migrant Category Resident Visa":"技能移民カテゴリー居住ビザ",
    "Points/skills-based residence.":"ポイントや技能に基づく居住ルート。",
    "Straight to Residence Visa":"直接居住ビザ",
    "Eligible Green List Tier 1 employment.":"要件を満たす Green List Tier 1 の雇用。",
    "Work to Residence Visa":"就労から居住へのビザ",
    "Eligible work-to-residence pathway.":"要件を満たす就労から居住へのルート。",
    "Care Workforce Work to Residence":"ケア人材向け就労から居住への制度",
    "Eligible care workforce residence.":"要件を満たすケア人材向けの居住ルート。",
    "Transport Work to Residence":"運輸人材向け就労から居住への制度",
    "Eligible transport workforce residence.":"要件を満たす運輸人材向けの居住ルート。",
    "Active Investor Plus Visa":"Active Investor Plus ビザ",
    "Residence through qualifying investment.":"要件を満たす投資による居住。",
    "Business Investor Resident Visa":"事業投資家居住ビザ",
    "Residence after qualifying business-investor activity.":"要件を満たす事業投資活動後の居住。",
    "Permanent Resident Visa":"永住者ビザ",
    "Permanent residence for eligible resident visa holders.":"要件を満たす居住ビザ保持者向けの永住。",
    "Pacific Access Category":"Pacific Access カテゴリー",
    "Residence for eligible Pacific nationals selected under the scheme.":"制度により選ばれた、要件を満たす太平洋諸国の国民向け居住。",
    "Samoan Quota Resident Visa":"サモア・クオータ居住ビザ",
    "Residence under the Samoa quota.":"サモア枠に基づく居住。",
    "Religious Workers Resident Visa":"宗教労働者居住ビザ",
    "Residence for qualifying religious workers.":"要件を満たす宗教労働者向けの居住。",
    "Study":"留学",
    "Fee Paying Student Visa":"授業料支払学生ビザ",
    "Full-time fee-paying study.":"授業料を支払うフルタイム学習。",
    "Pathway Student Visa":"Pathway 学生ビザ",
    "Up to three approved programmes in sequence.":"承認された最大3つのプログラムを連続して履修できます。",
    "English Language Student Visa":"英語学習学生ビザ",
    "Full-time English-language study.":"フルタイムの英語学習。",
    "Dependent Child Student Visa":"扶養子女学生ビザ",
    "School study for eligible dependent children.":"要件を満たす扶養子女の学校教育。",
    "Exchange Student Visa":"交換留学生ビザ",
    "Approved exchange study.":"承認された交換留学。",
    "Foreign Government Supported Student Visa":"外国政府支援学生ビザ",
    "Study supported by a foreign government.":"外国政府の支援を受けた学習。",
    "Family & Visit":"家族・訪問",
    "Partner visas":"パートナービザ",
    "Visitor, work and residence routes for eligible partners.":"要件を満たすパートナー向けの訪問・就労・居住ルート。",
    "Dependent Child visas":"扶養子女ビザ",
    "Visitor, student and resident routes for eligible children.":"要件を満たす子ども向けの訪問・学生・居住ルート。",
    "Parent Resident Visa":"親向け居住ビザ",
    "Residence for eligible parents.":"要件を満たす親向けの居住。",
    "Parent Boost Visitor Visa":"Parent Boost 訪問ビザ",
    "Longer visits for eligible parents.":"要件を満たす親向けの長期訪問。",
    "Visitor Visa":"訪問ビザ",
    "Tourism and family visits.":"観光および家族訪問。",
    "Business Visitor Visa":"商用訪問ビザ",
    "Short business visits.":"短期間の商用訪問。",
    "NZeTA":"NZeTA",
    "Travel authority for eligible visa-waiver travellers.":"要件を満たすビザ免除旅行者向けの渡航認証。",
    "Transit Visa":"通過ビザ",
    "Transit through New Zealand where required.":"必要な場合にニュージーランドを経由するためのビザ。"
  }
};
export default translations;
