const translations: Record<string, Record<string, string>> = {
  es: {
    "Professional Work":"Trabajo profesional",
    "Employment Pass":"Employment Pass",
    "Foreign professionals, managers and executives.":"Profesionales extranjeros, directivos y ejecutivos.",
    "S Pass":"S Pass",
    "Skilled workers meeting current eligibility requirements.":"Trabajadores cualificados que cumplen los requisitos de elegibilidad vigentes.",
    "Overseas Networks & Expertise Pass":"Overseas Networks & Expertise Pass",
    "Top talent across qualifying fields.":"Talento de alto nivel en campos que cumplan los requisitos.",
    "Personalised Employment Pass":"Personalised Employment Pass",
    "Eligible high-earning professionals.":"Profesionales con ingresos elevados que cumplan los requisitos.",
    "EntrePass":"EntrePass",
    "Eligible founders of venture-backed or innovative businesses.":"Fundadores elegibles de empresas innovadoras o respaldadas por capital de riesgo.",
    "Tech.Pass / successor arrangements":"Tech.Pass / acuerdos sucesores",
    "Technology talent route subject to current programme status.":"Vía para talento tecnológico sujeta al estado actual del programa.",
    "Work Permit":"Permiso de trabajo",
    "Approved sector-specific semi-skilled work.":"Trabajo semicalificado aprobado en sectores específicos.",
    "Miscellaneous Work Pass":"Permiso de Trabajo Misceláneo",
    "Certain short-term assignments.":"Determinadas asignaciones de corta duración.",
    "Training Employment Pass":"Permiso de Empleo para Formación",
    "Practical training for eligible foreign professionals.":"Formación práctica para profesionales extranjeros elegibles.",
    "Training Work Permit":"Permiso de Trabajo para Formación",
    "Practical training for eligible semi-skilled trainees.":"Formación práctica para aprendices semicalificados elegibles.",
    "Work Holiday Pass":"Permiso de Working Holiday",
    "Eligible students and graduates under participating programmes.":"Estudiantes y graduados elegibles bajo programas participantes.",
    "Study & Family":"Estudios y familia",
    "Student's Pass":"Student's Pass",
    "Full-time study at an approved institution.":"Estudios a tiempo completo en una institución aprobada.",
    "Dependant's Pass":"Dependant's Pass",
    "Eligible spouses and children of qualifying work-pass holders.":"Cónyuges e hijos elegibles de titulares de permisos de trabajo que cumplan los requisitos.",
    "Long-Term Visit Pass":"Permiso de Visita de Larga Duración",
    "Eligible family members under MOM or ICA rules.":"Familiares elegibles según las normas de MOM o ICA.",
    "Long-Term Visit Pass Plus":"Long-Term Visit Pass Plus",
    "Longer-term family permission in qualifying ICA cases.":"Permiso familiar de mayor duración en casos ICA que cumplan los requisitos.",
    "Visit & Residence":"Visita y residencia",
    "Short-Term Visit Pass":"Permiso de Visita de Corta Duración",
    "Short visits for tourism, social or business purposes.":"Visitas cortas por turismo, motivos sociales o negocios.",
    "Singapore entry visa":"Visa de entrada a Singapur",
    "Entry visa for visa-required nationalities.":"Visa de entrada para nacionalidades que requieren visa.",
    "Permanent Residence":"Residencia permanente",
    "PR schemes for eligible professionals, investors and family members.":"Programas de residencia permanente para profesionales, inversores y familiares elegibles."
  },
  fr: {
    "Professional Work":"Travail professionnel",
    "Employment Pass":"Employment Pass",
    "Foreign professionals, managers and executives.":"Professionnels étrangers, cadres et dirigeants.",
    "S Pass":"S Pass",
    "Skilled workers meeting current eligibility requirements.":"Travailleurs qualifiés répondant aux critères d’éligibilité en vigueur.",
    "Overseas Networks & Expertise Pass":"Overseas Networks & Expertise Pass",
    "Top talent across qualifying fields.":"Talents de haut niveau dans les domaines admissibles.",
    "Personalised Employment Pass":"Personalised Employment Pass",
    "Eligible high-earning professionals.":"Professionnels à hauts revenus admissibles.",
    "EntrePass":"EntrePass",
    "Eligible founders of venture-backed or innovative businesses.":"Fondateurs admissibles d’entreprises innovantes ou financées par capital-risque.",
    "Tech.Pass / successor arrangements":"Tech.Pass / dispositifs successeurs",
    "Technology talent route subject to current programme status.":"Voie pour talents technologiques sous réserve du statut actuel du programme.",
    "Work Permit":"Permis de travail",
    "Approved sector-specific semi-skilled work.":"Travail semi-qualifié approuvé dans des secteurs déterminés.",
    "Miscellaneous Work Pass":"Miscellaneous Work Pass",
    "Certain short-term assignments.":"Certaines missions de courte durée.",
    "Training Employment Pass":"Training Employment Pass",
    "Practical training for eligible foreign professionals.":"Formation pratique pour professionnels étrangers admissibles.",
    "Training Work Permit":"Training Work Permit",
    "Practical training for eligible semi-skilled trainees.":"Formation pratique pour stagiaires semi-qualifiés admissibles.",
    "Work Holiday Pass":"Work Holiday Pass",
    "Eligible students and graduates under participating programmes.":"Étudiants et diplômés admissibles dans le cadre de programmes participants.",
    "Study & Family":"Études et famille",
    "Student's Pass":"Student's Pass",
    "Full-time study at an approved institution.":"Études à temps plein dans un établissement approuvé.",
    "Dependant's Pass":"Dependant's Pass",
    "Eligible spouses and children of qualifying work-pass holders.":"Conjoints et enfants admissibles de titulaires de permis de travail répondant aux critères.",
    "Long-Term Visit Pass":"Long-Term Visit Pass",
    "Eligible family members under MOM or ICA rules.":"Membres de famille admissibles selon les règles du MOM ou de l’ICA.",
    "Long-Term Visit Pass Plus":"Long-Term Visit Pass Plus",
    "Longer-term family permission in qualifying ICA cases.":"Autorisation familiale de plus longue durée dans certains cas admissibles de l’ICA.",
    "Visit & Residence":"Visite et résidence",
    "Short-Term Visit Pass":"Short-Term Visit Pass",
    "Short visits for tourism, social or business purposes.":"Courtes visites pour tourisme, motifs sociaux ou affaires.",
    "Singapore entry visa":"Visa d’entrée à Singapour",
    "Entry visa for visa-required nationalities.":"Visa d’entrée pour les nationalités soumises à visa.",
    "Permanent Residence":"Résidence permanente",
    "PR schemes for eligible professionals, investors and family members.":"Dispositifs de résidence permanente pour professionnels, investisseurs et membres de famille admissibles."
  },
  de: {
    "Professional Work":"Berufliche Beschäftigung",
    "Employment Pass":"Employment Pass",
    "Foreign professionals, managers and executives.":"Ausländische Fachkräfte, Führungskräfte und leitende Angestellte.",
    "S Pass":"S Pass",
    "Skilled workers meeting current eligibility requirements.":"Qualifizierte Arbeitskräfte, die die aktuellen Voraussetzungen erfüllen.",
    "Overseas Networks & Expertise Pass":"Overseas Networks & Expertise Pass",
    "Top talent across qualifying fields.":"Spitzentalente in berechtigten Fachgebieten.",
    "Personalised Employment Pass":"Personalised Employment Pass",
    "Eligible high-earning professionals.":"Berechtigte hochverdienende Fachkräfte.",
    "EntrePass":"EntrePass",
    "Eligible founders of venture-backed or innovative businesses.":"Berechtigte Gründer von risikokapitalfinanzierten oder innovativen Unternehmen.",
    "Tech.Pass / successor arrangements":"Tech.Pass / Nachfolgeregelungen",
    "Technology talent route subject to current programme status.":"Weg für Technologietalente abhängig vom aktuellen Programmstatus.",
    "Work Permit":"Arbeitserlaubnis",
    "Approved sector-specific semi-skilled work.":"Genehmigte angelernte Beschäftigung in bestimmten Branchen.",
    "Miscellaneous Work Pass":"Miscellaneous Work Pass",
    "Certain short-term assignments.":"Bestimmte kurzfristige Einsätze.",
    "Training Employment Pass":"Training Employment Pass",
    "Practical training for eligible foreign professionals.":"Praktische Ausbildung für berechtigte ausländische Fachkräfte.",
    "Training Work Permit":"Training Work Permit",
    "Practical training for eligible semi-skilled trainees.":"Praktische Ausbildung für berechtigte angelernte Auszubildende.",
    "Work Holiday Pass":"Work Holiday Pass",
    "Eligible students and graduates under participating programmes.":"Berechtigte Studierende und Absolventen im Rahmen teilnehmender Programme.",
    "Study & Family":"Studium und Familie",
    "Student's Pass":"Student's Pass",
    "Full-time study at an approved institution.":"Vollzeitstudium an einer zugelassenen Einrichtung.",
    "Dependant's Pass":"Dependant's Pass",
    "Eligible spouses and children of qualifying work-pass holders.":"Berechtigte Ehepartner und Kinder qualifizierter Arbeitspassinhaber.",
    "Long-Term Visit Pass":"Long-Term Visit Pass",
    "Eligible family members under MOM or ICA rules.":"Berechtigte Familienangehörige nach MOM- oder ICA-Regeln.",
    "Long-Term Visit Pass Plus":"Long-Term Visit Pass Plus",
    "Longer-term family permission in qualifying ICA cases.":"Längerfristige Familienerlaubnis in berechtigten ICA-Fällen.",
    "Visit & Residence":"Besuch und Aufenthalt",
    "Short-Term Visit Pass":"Short-Term Visit Pass",
    "Short visits for tourism, social or business purposes.":"Kurzaufenthalte für Tourismus, soziale oder geschäftliche Zwecke.",
    "Singapore entry visa":"Einreisevisum für Singapur",
    "Entry visa for visa-required nationalities.":"Einreisevisum für visumpflichtige Staatsangehörigkeiten.",
    "Permanent Residence":"Daueraufenthalt",
    "PR schemes for eligible professionals, investors and family members.":"Daueraufenthaltsprogramme für berechtigte Fachkräfte, Investoren und Familienangehörige."
  },
  zh: {
    "Professional Work":"专业就业",
    "Employment Pass":"就业准证",
    "Foreign professionals, managers and executives.":"面向外国专业人士、经理和高管。",
    "S Pass":"S 准证",
    "Skilled workers meeting current eligibility requirements.":"面向符合现行资格要求的技能工人。",
    "Overseas Networks & Expertise Pass":"海外网络与专业人才准证",
    "Top talent across qualifying fields.":"面向符合条件领域的顶尖人才。",
    "Personalised Employment Pass":"个人化就业准证",
    "Eligible high-earning professionals.":"面向符合条件的高收入专业人士。",
    "EntrePass":"创业准证",
    "Eligible founders of venture-backed or innovative businesses.":"面向符合条件的风投支持或创新企业创始人。",
    "Tech.Pass / successor arrangements":"Tech.Pass / 后续安排",
    "Technology talent route subject to current programme status.":"科技人才途径，具体以当前计划状态为准。",
    "Work Permit":"工作准证",
    "Approved sector-specific semi-skilled work.":"获批准特定行业的半技能工作。",
    "Miscellaneous Work Pass":"其他工作准证",
    "Certain short-term assignments.":"部分短期工作任务。",
    "Training Employment Pass":"培训就业准证",
    "Practical training for eligible foreign professionals.":"面向符合条件外国专业人士的实践培训。",
    "Training Work Permit":"培训工作准证",
    "Practical training for eligible semi-skilled trainees.":"面向符合条件半技能培训人员的实践培训。",
    "Work Holiday Pass":"打工度假准证",
    "Eligible students and graduates under participating programmes.":"面向参与计划中符合条件的学生和毕业生。",
    "Study & Family":"学习与家庭",
    "Student's Pass":"学生准证",
    "Full-time study at an approved institution.":"在获批准机构进行全日制学习。",
    "Dependant's Pass":"家属准证",
    "Eligible spouses and children of qualifying work-pass holders.":"符合条件工作准证持有人的配偶和子女。",
    "Long-Term Visit Pass":"长期探访准证",
    "Eligible family members under MOM or ICA rules.":"符合 MOM 或 ICA 规则的家庭成员。",
    "Long-Term Visit Pass Plus":"长期探访准证 Plus",
    "Longer-term family permission in qualifying ICA cases.":"在符合条件的 ICA 案件中提供较长期家庭居留许可。",
    "Visit & Residence":"访问与居留",
    "Short-Term Visit Pass":"短期探访准证",
    "Short visits for tourism, social or business purposes.":"用于旅游、社交或商务目的的短期访问。",
    "Singapore entry visa":"新加坡入境签证",
    "Entry visa for visa-required nationalities.":"面向需要签证国籍人士的入境签证。",
    "Permanent Residence":"永久居民",
    "PR schemes for eligible professionals, investors and family members.":"面向符合条件专业人士、投资者及家庭成员的永久居民计划。"
  },
  ar: {
    "Professional Work":"العمل المهني",
    "Employment Pass":"تصريح التوظيف",
    "Foreign professionals, managers and executives.":"للمهنيين والمديرين والتنفيذيين الأجانب.",
    "S Pass":"تصريح S",
    "Skilled workers meeting current eligibility requirements.":"للعمال المهرة المستوفين لمتطلبات الأهلية الحالية.",
    "Overseas Networks & Expertise Pass":"تصريح الشبكات والخبرات الخارجية",
    "Top talent across qualifying fields.":"للمواهب البارزة في المجالات المؤهلة.",
    "Personalised Employment Pass":"تصريح التوظيف الشخصي",
    "Eligible high-earning professionals.":"للمهنيين ذوي الدخل المرتفع المستوفين للشروط.",
    "EntrePass":"EntrePass",
    "Eligible founders of venture-backed or innovative businesses.":"لمؤسسي الشركات المبتكرة أو المدعومة برأس المال الجريء المستوفين للشروط.",
    "Tech.Pass / successor arrangements":"Tech.Pass / الترتيبات اللاحقة",
    "Technology talent route subject to current programme status.":"مسار لمواهب التكنولوجيا وفق الحالة الحالية للبرنامج.",
    "Work Permit":"تصريح عمل",
    "Approved sector-specific semi-skilled work.":"عمل شبه ماهر معتمد في قطاعات محددة.",
    "Miscellaneous Work Pass":"تصريح عمل متنوع",
    "Certain short-term assignments.":"بعض المهام قصيرة الأجل.",
    "Training Employment Pass":"تصريح توظيف للتدريب",
    "Practical training for eligible foreign professionals.":"تدريب عملي للمهنيين الأجانب المؤهلين.",
    "Training Work Permit":"تصريح عمل للتدريب",
    "Practical training for eligible semi-skilled trainees.":"تدريب عملي للمتدربين شبه المهرة المؤهلين.",
    "Work Holiday Pass":"تصريح عطلة العمل",
    "Eligible students and graduates under participating programmes.":"للطلاب والخريجين المؤهلين ضمن البرامج المشاركة.",
    "Study & Family":"الدراسة والأسرة",
    "Student's Pass":"تصريح الطالب",
    "Full-time study at an approved institution.":"دراسة بدوام كامل في مؤسسة معتمدة.",
    "Dependant's Pass":"تصريح المعال",
    "Eligible spouses and children of qualifying work-pass holders.":"الأزواج والأطفال المؤهلون لحاملي تصاريح العمل المستوفين للشروط.",
    "Long-Term Visit Pass":"تصريح زيارة طويلة الأجل",
    "Eligible family members under MOM or ICA rules.":"أفراد الأسرة المؤهلون وفق قواعد MOM أو ICA.",
    "Long-Term Visit Pass Plus":"تصريح زيارة طويلة الأجل Plus",
    "Longer-term family permission in qualifying ICA cases.":"إذن عائلي أطول أمداً في حالات ICA المؤهلة.",
    "Visit & Residence":"الزيارة والإقامة",
    "Short-Term Visit Pass":"تصريح زيارة قصيرة الأجل",
    "Short visits for tourism, social or business purposes.":"زيارات قصيرة للسياحة أو الأغراض الاجتماعية أو التجارية.",
    "Singapore entry visa":"تأشيرة دخول سنغافورة",
    "Entry visa for visa-required nationalities.":"تأشيرة دخول للجنسيات التي تتطلب تأشيرة.",
    "Permanent Residence":"الإقامة الدائمة",
    "PR schemes for eligible professionals, investors and family members.":"برامج إقامة دائمة للمهنيين والمستثمرين وأفراد الأسرة المؤهلين."
  },
  pt: {
    "Professional Work":"Trabalho profissional",
    "Employment Pass":"Employment Pass",
    "Foreign professionals, managers and executives.":"Profissionais estrangeiros, gestores e executivos.",
    "S Pass":"S Pass",
    "Skilled workers meeting current eligibility requirements.":"Trabalhadores qualificados que cumprem os requisitos atuais de elegibilidade.",
    "Overseas Networks & Expertise Pass":"Overseas Networks & Expertise Pass",
    "Top talent across qualifying fields.":"Talento de topo em áreas elegíveis.",
    "Personalised Employment Pass":"Personalised Employment Pass",
    "Eligible high-earning professionals.":"Profissionais de rendimento elevado elegíveis.",
    "EntrePass":"EntrePass",
    "Eligible founders of venture-backed or innovative businesses.":"Fundadores elegíveis de empresas inovadoras ou apoiadas por capital de risco.",
    "Tech.Pass / successor arrangements":"Tech.Pass / regimes sucessores",
    "Technology talent route subject to current programme status.":"Via para talento tecnológico sujeita ao estado atual do programa.",
    "Work Permit":"Autorização de trabalho",
    "Approved sector-specific semi-skilled work.":"Trabalho semiespecializado aprovado em setores específicos.",
    "Miscellaneous Work Pass":"Miscellaneous Work Pass",
    "Certain short-term assignments.":"Determinadas missões de curta duração.",
    "Training Employment Pass":"Training Employment Pass",
    "Practical training for eligible foreign professionals.":"Formação prática para profissionais estrangeiros elegíveis.",
    "Training Work Permit":"Training Work Permit",
    "Practical training for eligible semi-skilled trainees.":"Formação prática para formandos semiespecializados elegíveis.",
    "Work Holiday Pass":"Work Holiday Pass",
    "Eligible students and graduates under participating programmes.":"Estudantes e diplomados elegíveis ao abrigo de programas participantes.",
    "Study & Family":"Estudo e família",
    "Student's Pass":"Student's Pass",
    "Full-time study at an approved institution.":"Estudo a tempo inteiro numa instituição aprovada.",
    "Dependant's Pass":"Dependant's Pass",
    "Eligible spouses and children of qualifying work-pass holders.":"Cônjuges e filhos elegíveis de titulares de autorizações de trabalho que cumpram os requisitos.",
    "Long-Term Visit Pass":"Long-Term Visit Pass",
    "Eligible family members under MOM or ICA rules.":"Familiares elegíveis ao abrigo das regras do MOM ou ICA.",
    "Long-Term Visit Pass Plus":"Long-Term Visit Pass Plus",
    "Longer-term family permission in qualifying ICA cases.":"Autorização familiar de maior duração em casos ICA elegíveis.",
    "Visit & Residence":"Visita e residência",
    "Short-Term Visit Pass":"Short-Term Visit Pass",
    "Short visits for tourism, social or business purposes.":"Visitas curtas para turismo, fins sociais ou negócios.",
    "Singapore entry visa":"Visto de entrada em Singapura",
    "Entry visa for visa-required nationalities.":"Visto de entrada para nacionalidades sujeitas a visto.",
    "Permanent Residence":"Residência permanente",
    "PR schemes for eligible professionals, investors and family members.":"Regimes de residência permanente para profissionais, investidores e familiares elegíveis."
  },
  ja: {
    "Professional Work":"専門就労",
    "Employment Pass":"Employment Pass",
    "Foreign professionals, managers and executives.":"外国人専門職、管理職、経営幹部向け。",
    "S Pass":"S Pass",
    "Skilled workers meeting current eligibility requirements.":"現行の要件を満たす技能労働者向け。",
    "Overseas Networks & Expertise Pass":"Overseas Networks & Expertise Pass",
    "Top talent across qualifying fields.":"対象分野のトップ人材向け。",
    "Personalised Employment Pass":"Personalised Employment Pass",
    "Eligible high-earning professionals.":"要件を満たす高所得専門職向け。",
    "EntrePass":"EntrePass",
    "Eligible founders of venture-backed or innovative businesses.":"ベンチャー投資を受ける企業や革新的企業の要件を満たす創業者向け。",
    "Tech.Pass / successor arrangements":"Tech.Pass / 後継制度",
    "Technology talent route subject to current programme status.":"現在の制度状況に応じたテクノロジー人材向けルート。",
    "Work Permit":"就労許可",
    "Approved sector-specific semi-skilled work.":"承認された特定業種の半熟練就労。",
    "Miscellaneous Work Pass":"その他の就労パス",
    "Certain short-term assignments.":"特定の短期業務。",
    "Training Employment Pass":"研修用 Employment Pass",
    "Practical training for eligible foreign professionals.":"要件を満たす外国人専門職向けの実務研修。",
    "Training Work Permit":"研修用 Work Permit",
    "Practical training for eligible semi-skilled trainees.":"要件を満たす半熟練研修生向けの実務研修。",
    "Work Holiday Pass":"ワークホリデー・パス",
    "Eligible students and graduates under participating programmes.":"参加プログラムの要件を満たす学生・卒業生向け。",
    "Study & Family":"留学・家族",
    "Student's Pass":"Student's Pass",
    "Full-time study at an approved institution.":"認可された教育機関でのフルタイム学習。",
    "Dependant's Pass":"Dependant's Pass",
    "Eligible spouses and children of qualifying work-pass holders.":"要件を満たす就労パス保持者の配偶者・子ども向け。",
    "Long-Term Visit Pass":"長期訪問パス",
    "Eligible family members under MOM or ICA rules.":"MOM または ICA の規則に基づく要件を満たす家族向け。",
    "Long-Term Visit Pass Plus":"長期訪問パス Plus",
    "Longer-term family permission in qualifying ICA cases.":"要件を満たす ICA ケースにおける、より長期の家族滞在許可。",
    "Visit & Residence":"訪問・居住",
    "Short-Term Visit Pass":"短期訪問パス",
    "Short visits for tourism, social or business purposes.":"観光、社交、商用目的の短期訪問。",
    "Singapore entry visa":"シンガポール入国ビザ",
    "Entry visa for visa-required nationalities.":"ビザが必要な国籍向けの入国ビザ。",
    "Permanent Residence":"永住権",
    "PR schemes for eligible professionals, investors and family members.":"要件を満たす専門職、投資家、家族向けの永住制度。"
  }
};
export default translations;
