const translations: Record<string, Record<string, string>> = {
  es: {
    "Employment & Talent":"Empleo y talento",
    "EB-1":"EB-1",
    "Priority workers: extraordinary ability, outstanding professors/researchers and certain multinational executives.":"Trabajadores prioritarios: personas con capacidad extraordinaria, profesores/investigadores destacados y determinados ejecutivos de multinacionales.",
    "EB-2 / National Interest Waiver":"EB-2 / Exención por Interés Nacional",
    "Advanced-degree or exceptional-ability permanent residence, including eligible NIW cases.":"Residencia permanente para personas con titulación avanzada o capacidad excepcional, incluidos los casos NIW elegibles.",
    "EB-3":"EB-3",
    "Skilled workers, professionals and other workers.":"Trabajadores cualificados, profesionales y otros trabajadores.",
    "O-1":"O-1",
    "Extraordinary ability or achievement.":"Capacidad o logros extraordinarios.",
    "H-1B":"H-1B",
    "Specialty occupation and qualifying professional employment.":"Ocupaciones especializadas y empleo profesional que cumpla los requisitos.",
    "L-1":"L-1",
    "Intracompany transferee.":"Traslado dentro de la misma empresa.",
    "E-1 Treaty Trader":"E-1 Comerciante por Tratado",
    "Treaty-based trade activity.":"Actividad comercial basada en un tratado.",
    "E-2 Treaty Investor":"E-2 Inversor por Tratado",
    "Treaty-based investment activity.":"Actividad de inversión basada en un tratado.",
    "TN":"TN",
    "Qualifying Canadian and Mexican professionals.":"Profesionales canadienses y mexicanos que cumplan los requisitos.",
    "P visas":"Visas P",
    "Athletes, artists and entertainers.":"Deportistas, artistas y profesionales del entretenimiento.",
    "R-1":"R-1",
    "Religious workers.":"Trabajadores religiosos.",
    "H-2A":"H-2A",
    "Temporary agricultural workers.":"Trabajadores agrícolas temporales.",
    "H-2B":"H-2B",
    "Temporary non-agricultural workers.":"Trabajadores temporales no agrícolas.",
    "J-1":"J-1",
    "Exchange visitors.":"Visitantes de intercambio.",
    "Q-1":"Q-1",
    "International cultural exchange.":"Intercambio cultural internacional.",
    "Study & Exchange":"Estudios e intercambio",
    "F-1":"F-1",
    "Academic student.":"Estudiante académico.",
    "M-1":"M-1",
    "Vocational student.":"Estudiante de formación profesional.",
    "J-1 Exchange Visitor":"J-1 Visitante de Intercambio",
    "Approved exchange programmes.":"Programas de intercambio aprobados.",
    "Family & Permanent Residence":"Familia y residencia permanente",
    "Immediate Relative immigrant visas":"Visas de inmigrante para familiares inmediatos",
    "Spouse, child or parent categories for qualifying U.S. citizens.":"Categorías para cónyuge, hijo o progenitor de ciudadanos estadounidenses que cumplan los requisitos.",
    "Family Preference immigrant visas":"Visas de inmigrante por preferencia familiar",
    "Family-sponsored preference categories.":"Categorías de preferencia patrocinadas por familiares.",
    "K-1":"K-1",
    "Fiancé(e) of a U.S. citizen.":"Prometido/a de un ciudadano estadounidense.",
    "K-3":"K-3",
    "Spouse of a U.S. citizen in qualifying circumstances.":"Cónyuge de un ciudadano estadounidense en circunstancias que cumplan los requisitos.",
    "Diversity Visa":"Visa de Diversidad",
    "Diversity immigrant visa programme where eligible.":"Programa de visas de inmigrante por diversidad cuando se cumplan los requisitos.",
    "Visit & Transit":"Visita y tránsito",
    "B-1":"B-1",
    "Temporary business visitor.":"Visitante temporal por negocios.",
    "B-2":"B-2",
    "Tourism, visits and certain medical travel.":"Turismo, visitas y determinados viajes por motivos médicos.",
    "C":"C",
    "Transit.":"Tránsito.",
    "D":"D",
    "Crewmember.":"Miembro de tripulación.",
    "ESTA / Visa Waiver Programme":"ESTA / Programa de Exención de Visa",
    "Travel authorisation for eligible visa-waiver travellers.":"Autorización de viaje para viajeros elegibles bajo el programa de exención de visa.",
    "Humanitarian & Other":"Humanitario y otros",
    "Refugee":"Refugiado",
    "Refugee admission programme.":"Programa de admisión de refugiados.",
    "Asylum":"Asilo",
    "Protection for qualifying applicants.":"Protección para solicitantes que cumplan los requisitos.",
    "U visa":"Visa U",
    "Certain victims of qualifying criminal activity.":"Determinadas víctimas de actividades delictivas que cumplan los requisitos.",
    "T visa":"Visa T",
    "Certain victims of human trafficking.":"Determinadas víctimas de trata de personas.",
    "S visa":"Visa S",
    "Certain witnesses or informants.":"Determinados testigos o informantes.",
    "Humanitarian parole":"Parole humanitario",
    "Temporary parole in qualifying urgent circumstances.":"Permiso temporal de entrada en circunstancias urgentes que cumplan los requisitos."
  },
  fr: {
    "Employment & Talent":"Emploi et talents",
    "EB-1":"EB-1",
    "Priority workers: extraordinary ability, outstanding professors/researchers and certain multinational executives.":"Travailleurs prioritaires : personnes aux capacités extraordinaires, professeurs/chercheurs éminents et certains cadres de multinationales.",
    "EB-2 / National Interest Waiver":"EB-2 / Dérogation pour intérêt national",
    "Advanced-degree or exceptional-ability permanent residence, including eligible NIW cases.":"Résidence permanente pour titulaires d’un diplôme supérieur ou personnes aux capacités exceptionnelles, y compris certains cas NIW admissibles.",
    "EB-3":"EB-3",
    "Skilled workers, professionals and other workers.":"Travailleurs qualifiés, professionnels et autres travailleurs.",
    "O-1":"O-1",
    "Extraordinary ability or achievement.":"Capacité ou réalisation extraordinaire.",
    "H-1B":"H-1B",
    "Specialty occupation and qualifying professional employment.":"Emploi dans une profession spécialisée et activité professionnelle admissible.",
    "L-1":"L-1",
    "Intracompany transferee.":"Salarié transféré au sein d’une même entreprise.",
    "E-1 Treaty Trader":"E-1 Commerçant sous traité",
    "Treaty-based trade activity.":"Activité commerciale fondée sur un traité.",
    "E-2 Treaty Investor":"E-2 Investisseur sous traité",
    "Treaty-based investment activity.":"Activité d’investissement fondée sur un traité.",
    "TN":"TN",
    "Qualifying Canadian and Mexican professionals.":"Professionnels canadiens et mexicains admissibles.",
    "P visas":"Visas P",
    "Athletes, artists and entertainers.":"Athlètes, artistes et professionnels du spectacle.",
    "R-1":"R-1",
    "Religious workers.":"Travailleurs religieux.",
    "H-2A":"H-2A",
    "Temporary agricultural workers.":"Travailleurs agricoles temporaires.",
    "H-2B":"H-2B",
    "Temporary non-agricultural workers.":"Travailleurs temporaires non agricoles.",
    "J-1":"J-1",
    "Exchange visitors.":"Visiteurs d’échange.",
    "Q-1":"Q-1",
    "International cultural exchange.":"Échange culturel international.",
    "Study & Exchange":"Études et échanges",
    "F-1":"F-1",
    "Academic student.":"Étudiant dans un programme académique.",
    "M-1":"M-1",
    "Vocational student.":"Étudiant en formation professionnelle.",
    "J-1 Exchange Visitor":"J-1 Visiteur d’échange",
    "Approved exchange programmes.":"Programmes d’échange approuvés.",
    "Family & Permanent Residence":"Famille et résidence permanente",
    "Immediate Relative immigrant visas":"Visas d’immigrant pour parents proches",
    "Spouse, child or parent categories for qualifying U.S. citizens.":"Catégories pour conjoint, enfant ou parent de citoyens américains admissibles.",
    "Family Preference immigrant visas":"Visas d’immigrant de préférence familiale",
    "Family-sponsored preference categories.":"Catégories de préférence parrainées par la famille.",
    "K-1":"K-1",
    "Fiancé(e) of a U.S. citizen.":"Fiancé(e) d’un citoyen américain.",
    "K-3":"K-3",
    "Spouse of a U.S. citizen in qualifying circumstances.":"Conjoint d’un citoyen américain dans les situations admissibles.",
    "Diversity Visa":"Visa de diversité",
    "Diversity immigrant visa programme where eligible.":"Programme de visas d’immigrant de diversité lorsqu’il est applicable.",
    "Visit & Transit":"Visite et transit",
    "B-1":"B-1",
    "Temporary business visitor.":"Visiteur temporaire pour affaires.",
    "B-2":"B-2",
    "Tourism, visits and certain medical travel.":"Tourisme, visites et certains déplacements pour soins médicaux.",
    "C":"C",
    "Transit.":"Transit.",
    "D":"D",
    "Crewmember.":"Membre d’équipage.",
    "ESTA / Visa Waiver Programme":"ESTA / Programme d’exemption de visa",
    "Travel authorisation for eligible visa-waiver travellers.":"Autorisation de voyage pour les voyageurs admissibles au programme d’exemption de visa.",
    "Humanitarian & Other":"Humanitaire et autres",
    "Refugee":"Réfugié",
    "Refugee admission programme.":"Programme d’admission des réfugiés.",
    "Asylum":"Asile",
    "Protection for qualifying applicants.":"Protection pour les demandeurs admissibles.",
    "U visa":"Visa U",
    "Certain victims of qualifying criminal activity.":"Certaines victimes d’activités criminelles admissibles.",
    "T visa":"Visa T",
    "Certain victims of human trafficking.":"Certaines victimes de traite des êtres humains.",
    "S visa":"Visa S",
    "Certain witnesses or informants.":"Certains témoins ou informateurs.",
    "Humanitarian parole":"Parole humanitaire",
    "Temporary parole in qualifying urgent circumstances.":"Autorisation temporaire d’entrée dans certaines situations urgentes admissibles."
  },
  de: {
    "Employment & Talent":"Beschäftigung und Talente",
    "EB-1":"EB-1",
    "Priority workers: extraordinary ability, outstanding professors/researchers and certain multinational executives.":"Prioritäre Arbeitskräfte: Personen mit außergewöhnlichen Fähigkeiten, herausragende Professoren/Forschende und bestimmte Führungskräfte multinationaler Unternehmen.",
    "EB-2 / National Interest Waiver":"EB-2 / National Interest Waiver",
    "Advanced-degree or exceptional-ability permanent residence, including eligible NIW cases.":"Daueraufenthalt für Personen mit höherem Abschluss oder außergewöhnlicher Befähigung, einschließlich berechtigter NIW-Fälle.",
    "EB-3":"EB-3",
    "Skilled workers, professionals and other workers.":"Fachkräfte, Akademiker und andere Arbeitnehmer.",
    "O-1":"O-1",
    "Extraordinary ability or achievement.":"Außergewöhnliche Fähigkeiten oder Leistungen.",
    "H-1B":"H-1B",
    "Specialty occupation and qualifying professional employment.":"Spezialisierte Berufe und qualifizierte professionelle Beschäftigung.",
    "L-1":"L-1",
    "Intracompany transferee.":"Unternehmensinterner Versetzter.",
    "E-1 Treaty Trader":"E-1 Treaty Trader",
    "Treaty-based trade activity.":"Handelstätigkeit auf Grundlage eines Vertrags.",
    "E-2 Treaty Investor":"E-2 Treaty Investor",
    "Treaty-based investment activity.":"Investitionstätigkeit auf Grundlage eines Vertrags.",
    "TN":"TN",
    "Qualifying Canadian and Mexican professionals.":"Berechtigte kanadische und mexikanische Fachkräfte.",
    "P visas":"P-Visa",
    "Athletes, artists and entertainers.":"Sportler, Künstler und Unterhaltungsschaffende.",
    "R-1":"R-1",
    "Religious workers.":"Religiöse Beschäftigte.",
    "H-2A":"H-2A",
    "Temporary agricultural workers.":"Vorübergehende landwirtschaftliche Arbeitskräfte.",
    "H-2B":"H-2B",
    "Temporary non-agricultural workers.":"Vorübergehende nichtlandwirtschaftliche Arbeitskräfte.",
    "J-1":"J-1",
    "Exchange visitors.":"Austauschbesucher.",
    "Q-1":"Q-1",
    "International cultural exchange.":"Internationaler Kulturaustausch.",
    "Study & Exchange":"Studium und Austausch",
    "F-1":"F-1",
    "Academic student.":"Studierender in einem akademischen Programm.",
    "M-1":"M-1",
    "Vocational student.":"Berufsschüler bzw. Teilnehmer an einer Berufsausbildung.",
    "J-1 Exchange Visitor":"J-1 Austauschbesucher",
    "Approved exchange programmes.":"Genehmigte Austauschprogramme.",
    "Family & Permanent Residence":"Familie und Daueraufenthalt",
    "Immediate Relative immigrant visas":"Einwanderungsvisa für unmittelbare Angehörige",
    "Spouse, child or parent categories for qualifying U.S. citizens.":"Kategorien für Ehepartner, Kinder oder Eltern berechtigter US-Bürger.",
    "Family Preference immigrant visas":"Einwanderungsvisa nach Familienpräferenz",
    "Family-sponsored preference categories.":"Familiengesponserte Präferenzkategorien.",
    "K-1":"K-1",
    "Fiancé(e) of a U.S. citizen.":"Verlobte(r) eines US-Bürgers.",
    "K-3":"K-3",
    "Spouse of a U.S. citizen in qualifying circumstances.":"Ehepartner eines US-Bürgers in berechtigten Fällen.",
    "Diversity Visa":"Diversity Visa",
    "Diversity immigrant visa programme where eligible.":"Diversity-Einwanderungsvisumprogramm, sofern die Voraussetzungen erfüllt sind.",
    "Visit & Transit":"Besuch und Transit",
    "B-1":"B-1",
    "Temporary business visitor.":"Vorübergehender Geschäftsbesucher.",
    "B-2":"B-2",
    "Tourism, visits and certain medical travel.":"Tourismus, Besuche und bestimmte medizinische Reisen.",
    "C":"C",
    "Transit.":"Transit.",
    "D":"D",
    "Crewmember.":"Besatzungsmitglied.",
    "ESTA / Visa Waiver Programme":"ESTA / Visa-Waiver-Programm",
    "Travel authorisation for eligible visa-waiver travellers.":"Reisegenehmigung für berechtigte Reisende im Visa-Waiver-Programm.",
    "Humanitarian & Other":"Humanitär und Sonstiges",
    "Refugee":"Flüchtling",
    "Refugee admission programme.":"Programm zur Aufnahme von Flüchtlingen.",
    "Asylum":"Asyl",
    "Protection for qualifying applicants.":"Schutz für berechtigte Antragstellende.",
    "U visa":"U-Visum",
    "Certain victims of qualifying criminal activity.":"Bestimmte Opfer einschlägiger Straftaten.",
    "T visa":"T-Visum",
    "Certain victims of human trafficking.":"Bestimmte Opfer von Menschenhandel.",
    "S visa":"S-Visum",
    "Certain witnesses or informants.":"Bestimmte Zeugen oder Informanten.",
    "Humanitarian parole":"Humanitäre Parole",
    "Temporary parole in qualifying urgent circumstances.":"Vorübergehende Einreiseerlaubnis in bestimmten dringenden Fällen."
  },
  zh: {
    "Employment & Talent":"就业与人才",
    "EB-1":"EB-1",
    "Priority workers: extraordinary ability, outstanding professors/researchers and certain multinational executives.":"优先类别工作者：具有杰出能力的人士、杰出教授/研究人员以及部分跨国公司高管。",
    "EB-2 / National Interest Waiver":"EB-2 / 国家利益豁免",
    "Advanced-degree or exceptional-ability permanent residence, including eligible NIW cases.":"面向具有高等学位或杰出能力人士的永久居留类别，包括符合条件的 NIW 案件。",
    "EB-3":"EB-3",
    "Skilled workers, professionals and other workers.":"技术工人、专业人士及其他工人。",
    "O-1":"O-1",
    "Extraordinary ability or achievement.":"杰出能力或成就。",
    "H-1B":"H-1B",
    "Specialty occupation and qualifying professional employment.":"专业性职业及符合条件的专业工作。",
    "L-1":"L-1",
    "Intracompany transferee.":"跨国公司内部调派人员。",
    "E-1 Treaty Trader":"E-1 条约贸易商",
    "Treaty-based trade activity.":"基于条约开展的贸易活动。",
    "E-2 Treaty Investor":"E-2 条约投资者",
    "Treaty-based investment activity.":"基于条约开展的投资活动。",
    "TN":"TN",
    "Qualifying Canadian and Mexican professionals.":"符合条件的加拿大和墨西哥专业人士。",
    "P visas":"P 类签证",
    "Athletes, artists and entertainers.":"运动员、艺术家及演艺人员。",
    "R-1":"R-1",
    "Religious workers.":"宗教工作者。",
    "H-2A":"H-2A",
    "Temporary agricultural workers.":"临时农业工人。",
    "H-2B":"H-2B",
    "Temporary non-agricultural workers.":"临时非农业工人。",
    "J-1":"J-1",
    "Exchange visitors.":"交流访问人员。",
    "Q-1":"Q-1",
    "International cultural exchange.":"国际文化交流。",
    "Study & Exchange":"学习与交流",
    "F-1":"F-1",
    "Academic student.":"学术课程学生。",
    "M-1":"M-1",
    "Vocational student.":"职业教育学生。",
    "J-1 Exchange Visitor":"J-1 交流访问人员",
    "Approved exchange programmes.":"获批准的交流项目。",
    "Family & Permanent Residence":"家庭与永久居留",
    "Immediate Relative immigrant visas":"直系亲属移民签证",
    "Spouse, child or parent categories for qualifying U.S. citizens.":"适用于符合条件的美国公民之配偶、子女或父母类别。",
    "Family Preference immigrant visas":"家庭优先类移民签证",
    "Family-sponsored preference categories.":"由家庭成员担保的优先类别。",
    "K-1":"K-1",
    "Fiancé(e) of a U.S. citizen.":"美国公民的未婚夫/妻。",
    "K-3":"K-3",
    "Spouse of a U.S. citizen in qualifying circumstances.":"在符合条件的情况下适用于美国公民的配偶。",
    "Diversity Visa":"多元化移民签证",
    "Diversity immigrant visa programme where eligible.":"符合条件时可申请的多元化移民签证计划。",
    "Visit & Transit":"访问与过境",
    "B-1":"B-1",
    "Temporary business visitor.":"临时商务访问。",
    "B-2":"B-2",
    "Tourism, visits and certain medical travel.":"旅游、探亲访友及部分医疗旅行。",
    "C":"C",
    "Transit.":"过境。",
    "D":"D",
    "Crewmember.":"机组或船员。",
    "ESTA / Visa Waiver Programme":"ESTA / 免签证计划",
    "Travel authorisation for eligible visa-waiver travellers.":"面向符合免签计划条件旅客的旅行授权。",
    "Humanitarian & Other":"人道主义及其他",
    "Refugee":"难民",
    "Refugee admission programme.":"难民接收计划。",
    "Asylum":"庇护",
    "Protection for qualifying applicants.":"面向符合条件申请人的保护途径。",
    "U visa":"U 类签证",
    "Certain victims of qualifying criminal activity.":"特定符合条件犯罪活动的受害者。",
    "T visa":"T 类签证",
    "Certain victims of human trafficking.":"特定人口贩运受害者。",
    "S visa":"S 类签证",
    "Certain witnesses or informants.":"特定证人或线人。",
    "Humanitarian parole":"人道主义假释入境",
    "Temporary parole in qualifying urgent circumstances.":"在符合条件的紧急情况下给予的临时假释入境许可。"
  },
  ar: {
    "Employment & Talent":"العمل والمواهب",
    "EB-1":"EB-1",
    "Priority workers: extraordinary ability, outstanding professors/researchers and certain multinational executives.":"عمال ذو أولوية: أصحاب القدرات الاستثنائية، والأساتذة/الباحثون البارزون، وبعض المديرين التنفيذيين في الشركات متعددة الجنسيات.",
    "EB-2 / National Interest Waiver":"EB-2 / إعفاء المصلحة الوطنية",
    "Advanced-degree or exceptional-ability permanent residence, including eligible NIW cases.":"إقامة دائمة لأصحاب الدرجات العلمية المتقدمة أو القدرات الاستثنائية، بما في ذلك حالات NIW المؤهلة.",
    "EB-3":"EB-3",
    "Skilled workers, professionals and other workers.":"العمال المهرة والمهنيون وغيرهم من العمال.",
    "O-1":"O-1",
    "Extraordinary ability or achievement.":"قدرة أو إنجاز استثنائي.",
    "H-1B":"H-1B",
    "Specialty occupation and qualifying professional employment.":"وظيفة في مهنة تخصصية وعمل مهني مستوفٍ للشروط.",
    "L-1":"L-1",
    "Intracompany transferee.":"موظف منقول داخل الشركة.",
    "E-1 Treaty Trader":"E-1 تاجر بموجب معاهدة",
    "Treaty-based trade activity.":"نشاط تجاري قائم على معاهدة.",
    "E-2 Treaty Investor":"E-2 مستثمر بموجب معاهدة",
    "Treaty-based investment activity.":"نشاط استثماري قائم على معاهدة.",
    "TN":"TN",
    "Qualifying Canadian and Mexican professionals.":"مهنيون كنديون ومكسيكيون مستوفون للشروط.",
    "P visas":"تأشيرات P",
    "Athletes, artists and entertainers.":"الرياضيون والفنانون والعاملون في مجال الترفيه.",
    "R-1":"R-1",
    "Religious workers.":"العاملون الدينيون.",
    "H-2A":"H-2A",
    "Temporary agricultural workers.":"عمال زراعيون مؤقتون.",
    "H-2B":"H-2B",
    "Temporary non-agricultural workers.":"عمال مؤقتون في قطاعات غير زراعية.",
    "J-1":"J-1",
    "Exchange visitors.":"زوار برامج التبادل.",
    "Q-1":"Q-1",
    "International cultural exchange.":"تبادل ثقافي دولي.",
    "Study & Exchange":"الدراسة والتبادل",
    "F-1":"F-1",
    "Academic student.":"طالب أكاديمي.",
    "M-1":"M-1",
    "Vocational student.":"طالب في تعليم مهني.",
    "J-1 Exchange Visitor":"J-1 زائر تبادل",
    "Approved exchange programmes.":"برامج تبادل معتمدة.",
    "Family & Permanent Residence":"الأسرة والإقامة الدائمة",
    "Immediate Relative immigrant visas":"تأشيرات هجرة للأقارب المباشرين",
    "Spouse, child or parent categories for qualifying U.S. citizens.":"فئات للزوج أو الطفل أو الوالد لمواطني الولايات المتحدة المستوفين للشروط.",
    "Family Preference immigrant visas":"تأشيرات هجرة ضمن الأفضلية العائلية",
    "Family-sponsored preference categories.":"فئات أفضلية برعاية أفراد الأسرة.",
    "K-1":"K-1",
    "Fiancé(e) of a U.S. citizen.":"خطيب/خطيبة مواطن أمريكي.",
    "K-3":"K-3",
    "Spouse of a U.S. citizen in qualifying circumstances.":"زوج/زوجة مواطن أمريكي في الحالات المستوفية للشروط.",
    "Diversity Visa":"تأشيرة التنوع",
    "Diversity immigrant visa programme where eligible.":"برنامج تأشيرة هجرة التنوع حيثما تنطبق الأهلية.",
    "Visit & Transit":"الزيارة والعبور",
    "B-1":"B-1",
    "Temporary business visitor.":"زائر أعمال مؤقت.",
    "B-2":"B-2",
    "Tourism, visits and certain medical travel.":"السياحة والزيارات وبعض الرحلات الطبية.",
    "C":"C",
    "Transit.":"عبور.",
    "D":"D",
    "Crewmember.":"عضو طاقم.",
    "ESTA / Visa Waiver Programme":"ESTA / برنامج الإعفاء من التأشيرة",
    "Travel authorisation for eligible visa-waiver travellers.":"تصريح سفر للمسافرين المؤهلين ضمن برنامج الإعفاء من التأشيرة.",
    "Humanitarian & Other":"إنساني وفئات أخرى",
    "Refugee":"لاجئ",
    "Refugee admission programme.":"برنامج قبول اللاجئين.",
    "Asylum":"اللجوء",
    "Protection for qualifying applicants.":"حماية للمتقدمين المستوفين للشروط.",
    "U visa":"تأشيرة U",
    "Certain victims of qualifying criminal activity.":"بعض ضحايا الأنشطة الإجرامية المؤهلة.",
    "T visa":"تأشيرة T",
    "Certain victims of human trafficking.":"بعض ضحايا الاتجار بالبشر.",
    "S visa":"تأشيرة S",
    "Certain witnesses or informants.":"بعض الشهود أو المخبرين.",
    "Humanitarian parole":"الإفراج الإنساني المشروط",
    "Temporary parole in qualifying urgent circumstances.":"إذن دخول مؤقت في ظروف عاجلة مستوفية للشروط."
  },
  pt: {
    "Employment & Talent":"Emprego e talento",
    "EB-1":"EB-1",
    "Priority workers: extraordinary ability, outstanding professors/researchers and certain multinational executives.":"Trabalhadores prioritários: pessoas com capacidade extraordinária, professores/investigadores de destaque e determinados executivos de multinacionais.",
    "EB-2 / National Interest Waiver":"EB-2 / Dispensa por Interesse Nacional",
    "Advanced-degree or exceptional-ability permanent residence, including eligible NIW cases.":"Residência permanente para pessoas com grau académico avançado ou capacidade excecional, incluindo casos NIW elegíveis.",
    "EB-3":"EB-3",
    "Skilled workers, professionals and other workers.":"Trabalhadores qualificados, profissionais e outros trabalhadores.",
    "O-1":"O-1",
    "Extraordinary ability or achievement.":"Capacidade ou realização extraordinária.",
    "H-1B":"H-1B",
    "Specialty occupation and qualifying professional employment.":"Ocupação especializada e emprego profissional que cumpra os requisitos.",
    "L-1":"L-1",
    "Intracompany transferee.":"Transferência dentro da mesma empresa.",
    "E-1 Treaty Trader":"E-1 Comerciante ao abrigo de tratado",
    "Treaty-based trade activity.":"Atividade comercial baseada em tratado.",
    "E-2 Treaty Investor":"E-2 Investidor ao abrigo de tratado",
    "Treaty-based investment activity.":"Atividade de investimento baseada em tratado.",
    "TN":"TN",
    "Qualifying Canadian and Mexican professionals.":"Profissionais canadianos e mexicanos elegíveis.",
    "P visas":"Vistos P",
    "Athletes, artists and entertainers.":"Atletas, artistas e profissionais do entretenimento.",
    "R-1":"R-1",
    "Religious workers.":"Trabalhadores religiosos.",
    "H-2A":"H-2A",
    "Temporary agricultural workers.":"Trabalhadores agrícolas temporários.",
    "H-2B":"H-2B",
    "Temporary non-agricultural workers.":"Trabalhadores temporários não agrícolas.",
    "J-1":"J-1",
    "Exchange visitors.":"Visitantes de intercâmbio.",
    "Q-1":"Q-1",
    "International cultural exchange.":"Intercâmbio cultural internacional.",
    "Study & Exchange":"Estudo e intercâmbio",
    "F-1":"F-1",
    "Academic student.":"Estudante académico.",
    "M-1":"M-1",
    "Vocational student.":"Estudante de formação profissional.",
    "J-1 Exchange Visitor":"J-1 Visitante de Intercâmbio",
    "Approved exchange programmes.":"Programas de intercâmbio aprovados.",
    "Family & Permanent Residence":"Família e residência permanente",
    "Immediate Relative immigrant visas":"Vistos de imigrante para familiares imediatos",
    "Spouse, child or parent categories for qualifying U.S. citizens.":"Categorias para cônjuge, filho ou progenitor de cidadãos dos EUA elegíveis.",
    "Family Preference immigrant visas":"Vistos de imigrante por preferência familiar",
    "Family-sponsored preference categories.":"Categorias de preferência patrocinadas pela família.",
    "K-1":"K-1",
    "Fiancé(e) of a U.S. citizen.":"Noivo/a de cidadão dos EUA.",
    "K-3":"K-3",
    "Spouse of a U.S. citizen in qualifying circumstances.":"Cônjuge de cidadão dos EUA em circunstâncias elegíveis.",
    "Diversity Visa":"Visto de Diversidade",
    "Diversity immigrant visa programme where eligible.":"Programa de vistos de imigrante por diversidade quando elegível.",
    "Visit & Transit":"Visita e trânsito",
    "B-1":"B-1",
    "Temporary business visitor.":"Visitante temporário de negócios.",
    "B-2":"B-2",
    "Tourism, visits and certain medical travel.":"Turismo, visitas e determinadas viagens médicas.",
    "C":"C",
    "Transit.":"Trânsito.",
    "D":"D",
    "Crewmember.":"Membro da tripulação.",
    "ESTA / Visa Waiver Programme":"ESTA / Programa de Isenção de Visto",
    "Travel authorisation for eligible visa-waiver travellers.":"Autorização de viagem para viajantes elegíveis ao programa de isenção de visto.",
    "Humanitarian & Other":"Humanitário e outros",
    "Refugee":"Refugiado",
    "Refugee admission programme.":"Programa de admissão de refugiados.",
    "Asylum":"Asilo",
    "Protection for qualifying applicants.":"Proteção para candidatos elegíveis.",
    "U visa":"Visto U",
    "Certain victims of qualifying criminal activity.":"Determinadas vítimas de atividade criminosa elegível.",
    "T visa":"Visto T",
    "Certain victims of human trafficking.":"Determinadas vítimas de tráfico de pessoas.",
    "S visa":"Visto S",
    "Certain witnesses or informants.":"Determinadas testemunhas ou informadores.",
    "Humanitarian parole":"Parole humanitário",
    "Temporary parole in qualifying urgent circumstances.":"Autorização temporária de entrada em circunstâncias urgentes elegíveis."
  },
  ja: {
    "Employment & Talent":"雇用・人材",
    "EB-1":"EB-1",
    "Priority workers: extraordinary ability, outstanding professors/researchers and certain multinational executives.":"優先労働者：卓越した能力を持つ人、著名な教授・研究者、および一部の多国籍企業幹部。",
    "EB-2 / National Interest Waiver":"EB-2 / 国益免除（NIW）",
    "Advanced-degree or exceptional-ability permanent residence, including eligible NIW cases.":"上級学位または卓越した能力を持つ人向けの永住カテゴリーで、要件を満たす NIW 案件を含みます。",
    "EB-3":"EB-3",
    "Skilled workers, professionals and other workers.":"技能労働者、専門職、その他の労働者。",
    "O-1":"O-1",
    "Extraordinary ability or achievement.":"卓越した能力または実績。",
    "H-1B":"H-1B",
    "Specialty occupation and qualifying professional employment.":"専門職および要件を満たす専門的雇用。",
    "L-1":"L-1",
    "Intracompany transferee.":"企業内転勤者。",
    "E-1 Treaty Trader":"E-1 条約貿易家",
    "Treaty-based trade activity.":"条約に基づく貿易活動。",
    "E-2 Treaty Investor":"E-2 条約投資家",
    "Treaty-based investment activity.":"条約に基づく投資活動。",
    "TN":"TN",
    "Qualifying Canadian and Mexican professionals.":"要件を満たすカナダおよびメキシコの専門職。",
    "P visas":"P ビザ",
    "Athletes, artists and entertainers.":"スポーツ選手、芸術家、エンターテイナー。",
    "R-1":"R-1",
    "Religious workers.":"宗教関係の労働者。",
    "H-2A":"H-2A",
    "Temporary agricultural workers.":"一時的な農業労働者。",
    "H-2B":"H-2B",
    "Temporary non-agricultural workers.":"一時的な非農業労働者。",
    "J-1":"J-1",
    "Exchange visitors.":"交流訪問者。",
    "Q-1":"Q-1",
    "International cultural exchange.":"国際文化交流。",
    "Study & Exchange":"留学・交流",
    "F-1":"F-1",
    "Academic student.":"学術課程の学生。",
    "M-1":"M-1",
    "Vocational student.":"職業訓練課程の学生。",
    "J-1 Exchange Visitor":"J-1 交流訪問者",
    "Approved exchange programmes.":"承認された交流プログラム。",
    "Family & Permanent Residence":"家族・永住",
    "Immediate Relative immigrant visas":"近親者向け移民ビザ",
    "Spouse, child or parent categories for qualifying U.S. citizens.":"要件を満たす米国市民の配偶者、子ども、親を対象とするカテゴリー。",
    "Family Preference immigrant visas":"家族優先移民ビザ",
    "Family-sponsored preference categories.":"家族スポンサーによる優先カテゴリー。",
    "K-1":"K-1",
    "Fiancé(e) of a U.S. citizen.":"米国市民の婚約者。",
    "K-3":"K-3",
    "Spouse of a U.S. citizen in qualifying circumstances.":"要件を満たす場合の米国市民の配偶者。",
    "Diversity Visa":"多様性移民ビザ",
    "Diversity immigrant visa programme where eligible.":"要件を満たす場合に利用できる多様性移民ビザ・プログラム。",
    "Visit & Transit":"訪問・乗り継ぎ",
    "B-1":"B-1",
    "Temporary business visitor.":"短期商用訪問者。",
    "B-2":"B-2",
    "Tourism, visits and certain medical travel.":"観光、訪問、一部の医療目的の渡航。",
    "C":"C",
    "Transit.":"乗り継ぎ。",
    "D":"D",
    "Crewmember.":"乗務員・船員。",
    "ESTA / Visa Waiver Programme":"ESTA / ビザ免除プログラム",
    "Travel authorisation for eligible visa-waiver travellers.":"ビザ免除プログラムの対象となる旅行者向けの渡航認証。",
    "Humanitarian & Other":"人道・その他",
    "Refugee":"難民",
    "Refugee admission programme.":"難民受入プログラム。",
    "Asylum":"庇護",
    "Protection for qualifying applicants.":"要件を満たす申請者向けの保護。",
    "U visa":"U ビザ",
    "Certain victims of qualifying criminal activity.":"対象となる犯罪行為の一部被害者。",
    "T visa":"T ビザ",
    "Certain victims of human trafficking.":"人身取引の一部被害者。",
    "S visa":"S ビザ",
    "Certain witnesses or informants.":"一部の証人または情報提供者。",
    "Humanitarian parole":"人道的パロール",
    "Temporary parole in qualifying urgent circumstances.":"要件を満たす緊急事情における一時的な入国許可。"
  }
};
export default translations;
