import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription } from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";
import { FileText, FileIcon, FileType2 } from "lucide-react";
import { jsPDF } from "jspdf";
import "jspdf-autotable";
import { Document, Packer, Paragraph, TextRun, HeadingLevel, AlignmentType } from "docx";
import { saveAs } from "file-saver";
import { useToast } from "@/hooks/use-toast";

declare module 'jspdf' {
  interface jsPDF {
    autoTable: (options: any) => jsPDF;
    lastAutoTable: { finalY: number };
  }
}

interface ExportSection {
  title: string;
  content: string;
  score?: number;
}

interface ExportFormatDialogProps {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  title: string;
  subtitle?: string;
  filename: string;
  sections: ExportSection[];
}

export function ExportFormatDialog({
  open,
  onOpenChange,
  title,
  subtitle,
  filename,
  sections
}: ExportFormatDialogProps) {
  const { toast } = useToast();
  const timestamp = new Date().toLocaleString('en-GB');
  const safeFilename = filename.replace(/[^a-z0-9]/gi, '-').toLowerCase();

  const handleDownloadTXT = () => {
    let content = `${title.toUpperCase()}\n`;
    content += "=".repeat(60) + "\n\n";
    if (subtitle) content += `${subtitle}\n\n`;
    content += `Generated: ${timestamp}\n\n`;

    sections.forEach((section, index) => {
      content += `\n${"=".repeat(60)}\n`;
      content += `SECTION ${index + 1}: ${section.title.toUpperCase()}\n`;
      content += `${"=".repeat(60)}\n\n`;
      content += section.content || "No content available";
      if (section.score !== undefined) {
        content += `\n\nScore: ${section.score}/100`;
      }
      content += "\n\n";
    });

    content += "\n" + "=".repeat(60) + "\n";
    content += "DISCLAIMER\n";
    content += "=".repeat(60) + "\n";
    content += "This document is for guidance only and does not constitute legal advice.\n";
    content += "Please consult a qualified immigration advisor for your specific situation.\n";
    content += "\nGenerated by UK Innovator Founder Visa Assistant\n";

    const blob = new Blob([content], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${safeFilename}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);

    onOpenChange(false);
    toast({
      title: "TXT Downloaded",
      description: "Your report has been saved as a text file.",
    });
  };

  const handleDownloadPDF = () => {
    const doc = new jsPDF();
    const pageWidth = doc.internal.pageSize.getWidth();
    const pageHeight = doc.internal.pageSize.getHeight();
    const margin = 20;
    const maxWidth = pageWidth - margin * 2;
    let yPos = 20;

    doc.setFillColor(26, 26, 46);
    doc.rect(0, 0, pageWidth, 40, 'F');

    doc.setTextColor(255, 255, 255);
    doc.setFontSize(14);
    doc.setFont("helvetica", "bold");
    doc.text("UK Innovator Founder Visa Assistant", pageWidth / 2, 18, { align: "center" });
    doc.setFontSize(10);
    doc.setFont("helvetica", "normal");
    doc.text("UK's #1 Visa AI Assistant", pageWidth / 2, 28, { align: "center" });

    yPos = 55;

    doc.setTextColor(26, 26, 46);
    doc.setFontSize(20);
    doc.setFont("helvetica", "bold");
    doc.text(title, pageWidth / 2, yPos, { align: "center" });
    yPos += 8;

    if (subtitle) {
      doc.setFontSize(12);
      doc.setFont("helvetica", "normal");
      doc.setTextColor(100, 100, 100);
      doc.text(subtitle, pageWidth / 2, yPos, { align: "center" });
      yPos += 8;
    }

    doc.setFontSize(10);
    doc.setTextColor(100, 100, 100);
    doc.text(`Generated: ${timestamp}`, pageWidth / 2, yPos, { align: "center" });
    yPos += 15;

    sections.forEach((section, index) => {
      if (yPos > pageHeight - 50) {
        doc.addPage();
        yPos = 20;
      }

      doc.setFontSize(14);
      doc.setFont("helvetica", "bold");
      doc.setTextColor(26, 26, 46);
      doc.text(`${index + 1}. ${section.title}`, margin, yPos);
      yPos += 8;

      if (section.score !== undefined) {
        doc.setFontSize(10);
        doc.setFont("helvetica", "italic");
        const scoreColor = section.score >= 70 ? [34, 197, 94] : section.score >= 40 ? [234, 179, 8] : [239, 68, 68];
        doc.setTextColor(scoreColor[0], scoreColor[1], scoreColor[2]);
        doc.text(`Score: ${section.score}/100`, margin, yPos);
        yPos += 8;
      }

      doc.setFontSize(10);
      doc.setFont("helvetica", "normal");
      doc.setTextColor(51, 51, 51);
      const lines = doc.splitTextToSize(section.content || "No content available", maxWidth);
      
      lines.forEach((line: string) => {
        if (yPos > pageHeight - 30) {
          doc.addPage();
          yPos = 20;
        }
        doc.text(line, margin, yPos);
        yPos += 5;
      });
      yPos += 10;
    });

    if (yPos > pageHeight - 60) {
      doc.addPage();
      yPos = 20;
    }

    doc.setDrawColor(180, 83, 9);
    doc.line(margin, yPos, pageWidth - margin, yPos);
    yPos += 8;
    
    doc.setFontSize(10);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(180, 83, 9);
    doc.text("IMPORTANT LEGAL NOTICE", margin, yPos);
    yPos += 6;
    
    doc.setFontSize(8);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(100, 100, 100);
    const disclaimer = "This document was generated by the UK Innovator Founder Visa Assistant and provides general guidance only. It does NOT constitute regulated immigration advice under the Immigration and Asylum Act 1999.";
    const disclaimerLines = doc.splitTextToSize(disclaimer, maxWidth);
    doc.text(disclaimerLines, margin, yPos);

    doc.save(`${safeFilename}.pdf`);
    onOpenChange(false);
    toast({
      title: "PDF Downloaded",
      description: "Your report has been saved as a PDF.",
    });
  };

  const handleDownloadDOCX = async () => {
    const children: Paragraph[] = [
      new Paragraph({
        children: [
          new TextRun({ text: "UK Innovator Founder Visa Assistant", bold: true, size: 24, color: "1a1a2e" }),
        ],
        alignment: AlignmentType.CENTER,
        spacing: { after: 100 },
      }),
      new Paragraph({
        children: [
          new TextRun({ text: title, bold: true, size: 48, color: "1a1a2e" }),
        ],
        heading: HeadingLevel.TITLE,
        alignment: AlignmentType.CENTER,
        spacing: { after: 200 },
      }),
    ];

    if (subtitle) {
      children.push(
        new Paragraph({
          children: [
            new TextRun({ text: subtitle, size: 28, color: "666666" }),
          ],
          alignment: AlignmentType.CENTER,
          spacing: { after: 200 },
        })
      );
    }

    children.push(
      new Paragraph({
        children: [
          new TextRun({ text: `Generated: ${timestamp}`, italics: true, size: 20, color: "999999" }),
        ],
        alignment: AlignmentType.CENTER,
        spacing: { after: 400 },
      })
    );

    sections.forEach((section, index) => {
      children.push(
        new Paragraph({
          text: `${index + 1}. ${section.title}`,
          heading: HeadingLevel.HEADING_1,
          spacing: { before: 400, after: 200 },
        })
      );

      if (section.score !== undefined) {
        const scoreColor = section.score >= 70 ? "22c55e" : section.score >= 40 ? "f59e0b" : "ef4444";
        children.push(
          new Paragraph({
            children: [
              new TextRun({ text: `Score: ${section.score}/100`, italics: true, bold: true, color: scoreColor }),
            ],
            spacing: { after: 200 },
          })
        );
      }

      const paragraphs = (section.content || "No content available").split('\n\n');
      paragraphs.forEach(para => {
        if (para.trim()) {
          children.push(
            new Paragraph({
              text: para.trim(),
              spacing: { after: 200 },
            })
          );
        }
      });
    });

    children.push(
      new Paragraph({
        children: [
          new TextRun({ text: "────────────────────────────────────────", color: "CCCCCC" }),
        ],
        spacing: { before: 400, after: 200 },
      }),
      new Paragraph({
        children: [
          new TextRun({ text: "IMPORTANT LEGAL NOTICE", bold: true, size: 20, color: "B45309" }),
        ],
        spacing: { after: 100 },
      }),
      new Paragraph({
        children: [
          new TextRun({ 
            text: "This document was generated by the UK Innovator Founder Visa Assistant and provides general guidance only. It does NOT constitute regulated immigration advice under the Immigration and Asylum Act 1999.", 
            italics: true,
            size: 18,
            color: "666666"
          }),
        ],
        spacing: { after: 200 },
      })
    );

    const doc = new Document({
      creator: "UK Innovator Founder Visa Assistant",
      title: title,
      sections: [{
        properties: {},
        children,
      }],
    });

    const blob = await Packer.toBlob(doc);
    saveAs(blob, `${safeFilename}.docx`);
    onOpenChange(false);
    toast({
      title: "Word Document Downloaded",
      description: "Your report has been saved as a Word document.",
    });
  };

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="max-w-md">
        <DialogHeader>
          <DialogTitle>Choose Export Format</DialogTitle>
          <DialogDescription>
            Select the format for your report download
          </DialogDescription>
        </DialogHeader>
        <div className="grid gap-3 py-4">
          <Button 
            variant="outline" 
            className="h-16 justify-start gap-4 hover-elevate"
            onClick={handleDownloadDOCX}
            data-testid="button-export-docx"
          >
            <div className="h-10 w-10 rounded-lg bg-blue-500/10 flex items-center justify-center">
              <FileType2 className="h-5 w-5 text-blue-500" />
            </div>
            <div className="text-left">
              <div className="font-medium">Word Document (.docx)</div>
              <div className="text-sm text-muted-foreground">Best for editing and formatting</div>
            </div>
          </Button>
          <Button 
            variant="outline" 
            className="h-16 justify-start gap-4 hover-elevate"
            onClick={handleDownloadPDF}
            data-testid="button-export-pdf"
          >
            <div className="h-10 w-10 rounded-lg bg-red-500/10 flex items-center justify-center">
              <FileIcon className="h-5 w-5 text-red-500" />
            </div>
            <div className="text-left">
              <div className="font-medium">PDF Document (.pdf)</div>
              <div className="text-sm text-muted-foreground">Best for sharing and printing</div>
            </div>
          </Button>
          <Button 
            variant="outline" 
            className="h-16 justify-start gap-4 hover-elevate"
            onClick={handleDownloadTXT}
            data-testid="button-export-txt"
          >
            <div className="h-10 w-10 rounded-lg bg-gray-500/10 flex items-center justify-center">
              <FileText className="h-5 w-5 text-gray-500" />
            </div>
            <div className="text-left">
              <div className="font-medium">Plain Text (.txt)</div>
              <div className="text-sm text-muted-foreground">Simple text format</div>
            </div>
          </Button>
        </div>
      </DialogContent>
    </Dialog>
  );
}

export default ExportFormatDialog;
