import { Button } from "@/components/ui/button";
import { ArrowRight, CheckCircle } from "lucide-react";
import { Link } from "wouter";
import heroImage from "@assets/generated_images/3D_business_plan_hero_102d84d2.png";

export default function HeroSection() {
  return (
    <section className="relative overflow-hidden bg-gradient-to-br from-background via-accent/5 to-primary/5 py-20 md:py-32">
      {/* Animated gradient mesh background */}
      <div className="absolute inset-0 opacity-30">
        <div className="absolute top-0 left-1/4 w-96 h-96 bg-primary/20 rounded-full blur-3xl animate-pulse" />
        <div className="absolute bottom-0 right-1/4 w-96 h-96 bg-chart-2/20 rounded-full blur-3xl animate-pulse" style={{ animationDelay: "1s" }} />
      </div>

      <div className="container mx-auto px-4 md:px-6 relative z-10">
        <div className="grid lg:grid-cols-2 gap-12 items-center">
          {/* Left: Content */}
          <div className="space-y-8">
            <div className="inline-flex items-center gap-2 px-4 py-2 rounded-full bg-primary/10 border border-primary/20">
              <CheckCircle className="w-4 h-4 text-primary" />
              <span className="text-sm font-medium text-primary">Trusted by 500+ Approved Applicants</span>
            </div>

            <h1 className="font-serif text-5xl md:text-6xl lg:text-7xl font-bold text-foreground leading-tight">
              Get Your UK Innovation Visa{" "}
              <span className="bg-gradient-to-r from-primary to-chart-3 bg-clip-text text-transparent">
                Approved
              </span>
            </h1>

            <p className="text-lg md:text-xl text-muted-foreground leading-relaxed max-w-xl">
              Professional, endorsing body-ready business plans covering Innovation, Viability, and Scalability—generated by AI in under 5 minutes.
            </p>

            {/* Trust indicators */}
            <div className="flex flex-wrap gap-6 text-sm text-muted-foreground">
              <div className="flex items-center gap-2">
                <CheckCircle className="w-5 h-5 text-chart-3" />
                <span>AI-Powered Generation</span>
              </div>
              <div className="flex items-center gap-2">
                <CheckCircle className="w-5 h-5 text-chart-3" />
                <span>Endorsing Body Ready</span>
              </div>
              <div className="flex items-center gap-2">
                <CheckCircle className="w-5 h-5 text-chart-3" />
                <span>5-Minute Delivery</span>
              </div>
            </div>

            {/* CTAs */}
            <div className="flex flex-col sm:flex-row gap-4">
              <Link href="/questionnaire">
                <Button 
                  size="lg" 
                  className="group"
                  data-testid="button-generate-plan"
                >
                  Generate My Business Plan
                  <ArrowRight className="ml-2 w-5 h-5 group-hover:translate-x-1 transition-transform" />
                </Button>
              </Link>
              <Button 
                size="lg" 
                variant="outline"
                data-testid="button-view-sample"
                onClick={() => alert('Sample plans coming soon!')}
              >
                See Sample Plan
              </Button>
            </div>

            {/* Social proof */}
            <div className="flex items-center gap-3 pt-4">
              <div className="flex -space-x-2">
                {[1, 2, 3, 4].map((i) => (
                  <div
                    key={i}
                    className="w-10 h-10 rounded-full bg-gradient-to-br from-primary to-chart-3 border-2 border-background flex items-center justify-center text-white font-semibold text-sm"
                  >
                    {String.fromCharCode(64 + i)}
                  </div>
                ))}
              </div>
              <div className="text-sm">
                <div className="flex gap-0.5 mb-1">
                  {[1, 2, 3, 4, 5].map((i) => (
                    <span key={i} className="text-chart-2">★</span>
                  ))}
                </div>
                <p className="text-muted-foreground">Built by visa applicants, for applicants</p>
              </div>
            </div>
          </div>

          {/* Right: 3D Mockup */}
          <div className="relative lg:block hidden">
            <div className="relative">
              {/* Holographic glow effect */}
              <div className="absolute inset-0 bg-gradient-to-tr from-primary/20 via-chart-3/20 to-chart-2/20 blur-3xl rounded-full" />
              
              {/* Image with 3D transform */}
              <div className="relative transform hover:scale-105 transition-transform duration-500" style={{ perspective: "1000px" }}>
                <img
                  src={heroImage}
                  alt="Professional Business Plan Document"
                  className="w-full h-auto rounded-lg shadow-2xl"
                  style={{
                    transform: "rotateY(-5deg) rotateX(2deg)",
                    transformStyle: "preserve-3d",
                  }}
                />
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  );
}
