import { storage } from "../storage";

// Demo Plan 1: AI SaaS (already created via SQL)

// Demo Plan 2: Green Energy
const greenEnergyDemo = {
  id: 'demo-green-energy-2025',
  tier: 'enterprise' as const,
  businessName: 'SolarGrid UK - Community Solar Networks',
  industry: 'Renewable Energy / CleanTech',
  problem: 'UK has 29M homes suitable for solar but only 1.2M installed (4% penetration) due to high upfront costs (£6-8k average), unsuitable roofs (40% of properties), and complex planning permission (8-12 month delays). This creates £4.8B annual lost renewable energy opportunity.',
  uniqueness: 'World\'s first AI-optimized virtual power plant enabling neighborhoods to share solar generation through intelligent microgrid orchestration. Our patent-pending "GridFlow AI" predicts consumption patterns 96 hours ahead with 94% accuracy, automatically balancing supply/demand across 50-200 homes reducing grid dependence by 73%.',
  technology: 'Proprietary reinforcement learning algorithm managing distributed energy resources across community microgrids. Hardware: Smart inverters (Enphase IQ8+) with custom firmware, Tesla Powerwall integration, real-time IoT sensors. Software: Edge computing on Nvidia Jetson for <100ms latency control. Blockchain-based (Ethereum Layer 2) peer-to-peer energy trading.',
  experience: 'Founded by Michael Thompson (MEng Electrical Engineering, Imperial) - 15 years National Grid experience as Senior Grid Operations Engineer managing £2.4B substation network. Co-founder Dr. Aisha Patel (PhD Renewable Energy, Oxford) - Former Tesla Energy product manager, launched Powerwall 2 across UK/EU (18k units sold).',
  funding: 450000,
  revenue: 'B2B2C model: 1) Community solar subscriptions: £0 upfront, 25-35% electricity bill savings via monthly subscription (£68/mo avg). 2) Grid services revenue: Frequency response contracts with National Grid ESO (£180k annually per 100-home microgrid). 3) Carbon credit sales (REGOs). Revenue mix: 72% subscriptions, 18% grid services, 10% carbon credits. 68% gross margin.',
  jobCreation: 45,
  expansion: 'Phase 1: 12 microgrids Greater London/Southeast (600 homes). Phase 2: Birmingham, Manchester, Bristol (2,000 homes). Phase 3: National - 120 communities (6,000 homes) with ops centers in Edinburgh, Cardiff, Leeds. Phase 4: International - Ireland, Netherlands, Germany. Creates 45 direct + 120 indirect jobs by Year 5.',
  vision: 'Become UK\'s leading community renewable platform by 2030, powering 100,000+ homes through intelligent microgrids contributing 2.8% toward net-zero targets. Partner with councils to electrify 4.2M social housing homes. Exit via acquisition by National Grid or Octopus Energy at £250M+ valuation by 2031.',
  innovationStage: 'market-validation' as const,
  productStatus: 'Full production system operational across 3 pilot communities (Islington 52 homes, Camden 38 homes, Hackney 44 homes) - 134 total homes generating 890 MWh annually. Performance: 94% forecast accuracy, 73% grid independence, 31% average bill savings. Roadmap: Q2 2025 V2G integration, Q3 heat pump balancing, Q4 solar optimization AI.',
  existingCustomers: '134 paying customers (£68/mo avg subscription, 4.7/5 satisfaction). Case study: Islington Community Microgrid - 52 Victorian homes, £340k capex, 312 MWh generation, £38,400 annual savings (£738/household), 89 tonnes CO2 avoided, 7.2-year payback. Waitlist: 840 homes across 6 London boroughs.',
  betaTesters: '1,240 registered beta participants across 8 trial communities via mobile app. 68% weekly engagement, 847 completed energy audits. Beta-to-paid conversion: 11% signed binding contracts for Year 2 (840 homes, £6.8M contracted revenue). Gathering 2,400+ monthly data points on consumption patterns.',
  tractionEvidence: '£110k MRR (134% QoQ growth), 840 signed waitlist (£6.8M forward revenue), 890 MWh annual generation, 89 tonnes CO2 avoided. Winner Innovate UK Energy Game Changer (£250k grant March 2025), partnership with UK Power Networks, featured in FT "Future of Energy", COP29 speaker, partnership discussions with Octopus Energy.',
  techStack: 'Hardware: Enphase IQ8+ microinverters, Tesla Powerwall 2/3, Nvidia Jetson AGX Orin edge AI, Landis+Gyr SMETS2 meters, ABB switchgear. Software: Python 3.11, TensorFlow 2.14 RL models, FastAPI, React Native, PostgreSQL + TimescaleDB, InfluxDB. Cloud: AWS IoT Core, Lambda, S3, QuickSight. Blockchain: Ethereum Layer 2 (Polygon).',
  dataArchitecture: 'Event-driven IoT processing 2.4M sensor readings daily. Pipeline: Edge devices → AWS IoT Core (MQTT) → Kinesis → Lambda → TimescaleDB (90 days hot) → S3 Glacier (7 years regulatory). 847 features per home (consumption, weather, solar, grid, occupancy). Grafana dashboards + mobile app. UK-only AWS for GDPR.',
  aiMethodology: 'Deep Q-Network (DQN) optimizing: Maximize renewable utilization + Minimize cost + Maximize grid stability. State space: 847 features. Action space: Battery charge/discharge, EV charging, demand response. Training: 3 years National Grid data + 8 months operational. 94% consumption forecast accuracy 96h ahead. Nightly retraining.',
  complianceDesign: 'Multi-layer compliance: 1) Electrical Safety: G98/G99 grid compliance, annual NICEIC inspections. 2) GDPR: Pseudonymization, AES-256 encryption, UK-only storage. 3) Energy Trading: Ofgem license in application (6-month process), FCA appointed representative. 4) Building: Planning permission coordination. 5) Environmental: REGO verification.',
  patentStatus: 'Provisional patent filed (UK IPO: GB2598432.1, March 2025) for "GridFlow AI - Reinforcement learning-based distributed energy resource optimization for community microgrids". International PCT application planned August 2025 (UK, EU, US). Trade secret protection for training datasets and RL reward functions.',
  founderEducation: 'Michael Thompson: MEng Electrical Engineering (Imperial College London, First Class, 2005), Chartered Engineer (IET), AWS Certified Solutions Architect. Dr. Aisha Patel: PhD Renewable Energy Systems (University of Oxford, 2014) - Thesis on battery management for grid-scale storage, published in Nature Energy (IF 67.4), BSc Physics (Cambridge, First Class, 2010).',
  founderWorkHistory: 'Thompson: National Grid Senior Grid Operations Engineer (2010-2020) - Managed £2.4B substation network, led microgrid pilot at Western Power Distribution achieving 34% peak demand reduction. Consultant at Arup Energy (2020-2024) - Designed 8 community energy projects across UK. Patel: Tesla Energy Product Manager (2015-2023) - Launched Powerwall 2 in UK/EU (18k units), managed £12M product budget, led integration with Octopus Energy Time-of-Use tariffs.',
  founderAchievements: 'Thompson: Reduced National Grid peak demand by 34% via microgrid pilot (£2.1M annual savings), delivered 8 community energy projects at Arup (total £4.8M capex), chartered engineer designation (IET). Patel: Launched Tesla Powerwall 2 across 12 countries (18,000 units sold, £54M revenue), published in Nature Energy (140 citations), speaker at RE Global 2019/2021. Both: Bootstrapped SolarGrid to £110k MRR and 134 customers in 12 months.',
  relevantProjects: 'Western Power Distribution Microgrid Pilot (Thompson lead, 2018-2020) - 50-home trial in Bristol achieving 34% peak reduction, £340k capex, featured in IEEE Power & Energy Magazine. Tesla Powerwall 2 UK Launch (Patel lead, 2016-2017) - Go-to-market strategy, regulatory approval, 3,200 units year 1. Islington Community Solar (joint, 2024) - 52-home operational microgrid, £340k capex, 73% grid independence, 7.2-year payback, 89t CO2 avoided.',
  monthlyProjections: 'Month 1-6: £110k → £184k MRR (67% growth), deploy 2 new communities (100 homes). Month 7-12: £184k → £312k MRR (70%), 4 communities (200 homes), hire sales director. Month 13-18: £312k → £528k MRR (69%), expand Birmingham (4 communities). Month 19-24: £528k → £847k MRR (60%), Manchester/Bristol entry. Month 25-30: £847k → £1.31M MRR (55%), national expansion 12 communities. Month 31-36: £1.31M → £1.98M MRR (51%), 20 total communities (1,000 homes). Break-even Month 18 (£480k MRR). Assumes 8% churn, 65% gross margin, £340k capex per community amortized over 20 years.',
  customerAcquisitionCost: 680,
  lifetimeValue: 24480,
  paybackPeriod: 9,
  fundingSources: '£450k total: 1) Founder equity £150k (Thompson £80k from National Grid pension, Patel £70k Tesla stock). 2) Innovate UK Energy Game Changer grant £250k (non-dilutive, March 2025). 3) Angel investors £50k (2 angels: former Tesla Energy VP, Octopus Energy investment director at £3M pre-money). Planned Series A: £4.5M at Month 24 (£18M pre-money) from climate-focused VC (discussions with Breakthrough Energy Ventures, Energy Impact Partners).',
  detailedCosts: 'Year 1 costs (£892k): Capex: £1.36M (4 communities × £340k - solar arrays, batteries, inverters, installation) amortized over 20 years = £68k annual. Opex: Engineering £285k (3 engineers @ £95k), Operations £180k (ops manager £72k, 2 installers @ £54k), Sales/Marketing £145k (community engagement manager £62k, marketing £83k), Admin £214k (CEO £0, CTO £80k, legal/accounting £134k). Infrastructure: AWS IoT £42k, grid connection fees £38k. Total: £892k Year 1 opex + £1.36M capex.',
  competitors: '1) Ripple Energy - Passive community solar, no AI optimization, 40% grid dependence vs our 27%, £1,200 upfront fee. 2) Toucan Energy - Virtual PPA model, no physical infrastructure, 0% grid independence (100% reliant on grid). 3) Octopus Energy - Intelligent Octopus tariff, optimizes home batteries but no community sharing. 4) Centrica Local Energy - Enterprise-only (£2M+ contracts), 18-month deployment vs our 6 months. 5) Solar Together - Group buying scheme, no ongoing optimization, individual home systems not community shared. All lack our AI-optimized community coordination and peer-to-peer trading capability.',
  competitiveDifferentiation: 'Unique advantages: 1) 73% grid independence vs competitors 40-60% (validated by Carbon Trust audit). 2) £0 upfront vs £1,200-8,000 industry (democratizing access). 3) 94% forecast accuracy enabling superior battery dispatch vs 67% industry. 4) Peer-to-peer energy trading via blockchain (first in UK community solar). 5) 31% bill savings vs 18-22% competitors (validated across 134 homes). 6) Patent-pending GridFlow AI RL algorithm. 7) 6-month deployment vs 12-18 month industry average. Quantified ROI: Customers achieve 9-month payback on subscription vs savings (£68/mo cost, £92/mo savings = £24/mo net benefit).',
  customerInterviews: '287 customer discovery interviews (June 2024 - Feb 2025) with homeowners, housing association managers, and local councils. Key findings: 1) 82% interested in community solar if £0 upfront, 2) 76% willing to pay £60-80/mo for 30%+ bill savings, 3) 68% prefer neighborhood energy sharing over individual systems, 4) Trust barriers: Need council endorsement (64%) or existing customer testimonials (71%). Structured interview protocol validated via Mom Test methodology (Rob Fitzpatrick), focusing on past behavior vs hypothetical interest.',
  lettersOfIntent: '4 signed LOIs from London borough councils representing 2,400 social housing homes (£1.96M annual contract value). 1) Islington Council: 840 homes, £68/home/mo subscription (£686k ACV), pilot Q3 2025. 2) Hackney Council: 620 homes (£505k ACV), Q4 2025. 3) Tower Hamlets: 580 homes (£473k ACV), Q1 2026. 4) Camden Council: 360 homes (£294k ACV), Q2 2026. All LOIs include committed capital budgets, identified project sponsors, and council cabinet approval pathways.',
  willingnessToPay: 'Pricing validation via 3 methods: 1) Van Westendorp Price Sensitivity Meter (n=340 homeowners) - optimal price £68/mo (acceptable range £52-89/mo). 2) Conjoint analysis (n=180 participants) - £68/mo achieved highest purchase intent for 30% bill savings feature bundle. 3) Live market validation: 134 paying customers at £68/mo average with 94% retention (churn: 8% annually). Customer acquisition via £680 CAC (door-to-door canvassing £420, council partnership development £180, online advertising £80) achieving £24,480 LTV (lifetime customer value over 30-year solar system life).',
  marketSize: 'TAM: 29M UK homes suitable for solar × £816 annual profit potential (£68/mo subscription - £20/mo marginal costs) × 30-year system life = £710B lifetime value. SAM: 8.4M homes in urban areas suitable for community solar (multi-family buildings, terraced housing) × £816 annual = £6.9B annual market. SOM: Conservative 1.5% market share by 2030 = 126,000 homes = £103M annual revenue. Bottom-up validation: 840 signed waitlist + 1,240 beta registrations demonstrates strong demand. Comparable: Octopus Energy reached 3.4M UK customers in 7 years - our TAM well-supported by precedent.',
  regulatoryRequirements: 'Key requirements: 1) Electrical Safety: G98 (<16A) and G99 (>16A) grid connection approval from DNOs, compliance with Electricity Safety, Quality and Continuity Regulations 2002. Annual inspections by NICEIC certified engineers. 2) GDPR: Smart meter data is personal data requiring consent, pseudonymization, UK-only storage. 3) Ofgem Licensing: Electricity supply license required for community energy trading (6-month application process). 4) FCA Oversight: Peer-to-peer trading platform requires appointed representative status or full FCA authorization. 5) Planning: Building Regulations approval for roof-mounted solar, structural surveys. 6) Environmental: REGO certificate verification for carbon credit sales.',
  complianceTimeline: 'Compliance roadmap: Q1 2025 - Cyber Essentials Plus (completed Jan 2025, £8k cost). Q2 2025 - Ofgem electricity supply license application submitted (£45k legal fees, 6-month expected). Q3 2025 - ISO 14001 Environmental Management (in progress, completion July 2025, £24k). Q4 2025 - BSI Kitemark for microgrid safety (4-month process, £18k). 2026: Ofgem license approval (Jan), FCA appointed representative status (March), annual G99 compliance audits ongoing. Ongoing: Quarterly penetration testing (£15k/year), annual electrical safety inspections across all sites (£32k/year), GDPR DPIAs for new features (2/year).',
  complianceBudget: 78000,
  hiringPlan: 'Year 1 (6 roles, £382k): Lead Electrical Engineer £95k, 2× Solar Installation Engineers £68k each, Community Engagement Manager £62k, Grid Operations Specialist £74k, Customer Support £42k. Year 2 (9 additional, total 15): VP Operations £110k, 3× Installation Engineers £68k, 2× Energy Analysts £72k, Sales Director £98k + equity, Marketing Manager £65k. Year 3-5 (30 additional, total 45): Expand to Birmingham (4 roles), Manchester (3), Bristol (2), Edinburgh (5), Cardiff (3), Leeds (4). Priority: 60% local hiring in deployment communities, apprenticeships with renewable training providers, 45% women in technical roles target (Women in Renewable Energy partnership).',
  specificRegions: 'Deployment priority: 1) Greater London (38% UK population density, £0.34/kWh highest electricity costs) - 12 communities Year 1 targeting Islington, Camden, Hackney, Tower Hamlets, Southwark social housing. 2) Birmingham (1.1M population, strong council renewable commitment) - 8 communities Year 2. 3) Manchester (975k population, 1,100 kWh/kWp/year solar irradiance) - 6 communities Year 2. 4) Bristol (Green Capital award, progressive energy policies) - 4 communities Year 2. 5) Scotland (Edinburgh/Glasgow, hybrid solar-wind potential) - 6 communities Year 3. Focus criteria: High electricity costs, suitable irradiance, cooperative councils, social housing concentration.',
  internationalPlan: 'Year 4-5 expansion: Ireland (Dublin/Cork): £680M community energy market, EU 32% renewable mandate by 2030. Regulatory: Irish grid code (similar to UK G99), CRU electricity license. Dublin entity (€12k), 4 staff (sales, ops, engineering). Netherlands (Amsterdam/Rotterdam): 16.9M population, 73% homeownership, €1,200/home government subsidy. Partner with Eneco for customer acquisition. Amsterdam office (6 staff). Germany (Berlin/Munich): €2.4B TAM, "Energiegenossenschaften" cultural fit. Berlin office (8 staff), German localization. Target: 15% international revenue by Month 36 (€480k ARR).',
  targetEndorser: 'Target: UK Research and Innovation (UKRI) - Energy Systems Catapult pathway - optimal fit for hardware-enabled renewable innovation with sustainability impact. Rationale: 1) Energy/sustainability specialization directly aligned, 2) Track record endorsing CleanTech with social impact (12 precedents), 3) Existing relationship via Innovate UK Energy Game Changer £250k grant (March 2025), 4) Demonstrated job creation (45 direct + 120 indirect) and regional economic impact. Backup: TechNation if Energy Catapult full. Decision timeline: 8-10 weeks typical.',
  contactPointsStrategy: 'Contact strategy: 1) Warm intro via Innovate UK grant officer "David Clarke" who approved £250k - initial endorsement conversation scheduled June 2025. 2) Attend Energy Systems Catapult Innovation Forum (July 2025, Birmingham) - present Islington 73% grid independence case study. 3) Leverage UK Power Networks (London DNO) partnership for credibility letter. 4) Submit comprehensive package: 3 operational case studies, carbon impact report (89t CO2 avoided), job creation plan (45 direct roles), waitlist evidence (840 homes, £6.8M contracted). 5) Board advisor Prof. Sarah Lewis (Imperial College Renewable Energy) academic endorsement letter.',
  supportingEvidence: '1) 134 customer testimonials (video + written references from 3 communities), 2) UK Power Networks partnership letter + G99 approvals for 8 sites, 3) Independent Carbon Trust audit validating 73% grid independence and 31% cost savings, 4) Financial Times "Future of Energy" feature (April 2025), 5) Innovate UK Energy Game Changer award docs (£250k grant), 6) Octopus Energy partnership LOI for white-label distribution, 7) Patent filing acknowledgment GridFlow AI (UK IPO GB2598432.1), 8) Environmental impact: 89t CO2 avoided = 4,050 trees planted equivalent, 9) Waitlist contracts (840 homes, £6.8M forward revenue), 10) Cyber Essentials Plus + ISO 14001 certifications.',
  generatedContent: 'COMPREHENSIVE BUSINESS PLAN: SolarGrid UK deploys AI-optimized community solar microgrids achieving 73% renewable independence through intelligent grid balancing. Founded by Michael Thompson (ex-National Grid, 15 years grid ops) and Dr. Aisha Patel (ex-Tesla Energy, Powerwall 2 launch). TRACTION: 134 paying homes (£110k MRR), 840 waitlist (£6.8M contracted), 890 MWh generation, 89t CO2 avoided. 3 operational pilots: 94% forecast accuracy, 31% cost savings. MARKET: £4.8B UK opportunity (29M suitable homes), targeting 100k homes by 2030. DIFFERENTIATION: 94% AI accuracy vs 67% passive solar, 73% grid independence (2.7× better), £0 upfront vs £6-8k traditional, blockchain peer-to-peer trading. TEAM: National Grid + Tesla pedigree, £450k funding (Innovate UK £250k + £200k angels), Octopus Energy partnership discussions. COMPLIANCE: Cyber Essentials Plus, ISO 14001, Ofgem license in application, G99 grid approvals × 8 sites. JOBS: 45 direct + 120 indirect across London, Birmingham, Manchester, Bristol, Edinburgh, Cardiff, Leeds. SUSTAINABILITY: 2.8% UK net-zero contribution target by 2030, democratizing renewable access, reducing social housing fuel poverty. ENDORSEMENT: Warm intro to Energy Catapult via Innovate UK relationship, strong commercial + environmental evidence.',
  status: 'completed' as const,
  isDemoData: true,
  userId: null,
};

// Create the demo plan via storage interface
async function createDemoPlans() {
  try {
    console.log('Creating Green Energy demo plan...');
    await storage.createBusinessPlan(greenEnergyDemo);
    console.log('✓ Green Energy demo plan created successfully!');
    
    // We'll create the 3rd demo plan (FinTech) in the next script
    console.log('\nDemo Plan 1 (AI SaaS): ✓ Already created');
    console.log('Demo Plan 2 (Green Energy): ✓ Created');
    console.log('Demo Plan 3 (FinTech): Pending - will create next');
    
  } catch (error) {
    console.error('Error creating demo plans:', error);
  }
}

createDemoPlans();
